Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > Class Template Reference
gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > Class Template Reference
Chromosome bit crisp matrix.
#include <chromosome_crispmatrix.hpp>
Public Member Functions
ChromosomeCrispMatrix ()
ChromosomeCrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns)
ChromosomeCrispMatrix (const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > &aichrombitcrispmatrix_b)
ChromosomeCrispMatrix (ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > &&aichrombitcrispmatrix_b)
virtual ~ChromosomeCrispMatrix ()
ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > & operator= (const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > &aichrombitcrispmatrix_b)
ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > & operator= (ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > &&aichrombitcrispmatrix_b)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Public Member Functions inherited from mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >
CrispMatrix ()
CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns)
CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_BITSIZE *aiarrayT_data)
CrispMatrix (const CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aibitcrispmatrix_B)
CrispMatrix (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &&aibitcrispmatrix_B)
virtual ~CrispMatrix ()
mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & operator= (const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aibitcrispmatrix_B)
mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & operator= (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &&aibitcrispmatrix_B)
const T_CLUSTERIDX getMember (uintidx aiuintidx_instanceIdx) const
bool setMember (uintidx aiuintidx_instanceIdx, T_CLUSTERIDX aimgidxT_memberCluster)
Public Member Functions inherited from mat::BitMatrix< T_BITSIZE >
BitMatrix ()
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns)
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns, T_BITSIZE *aiarrayT_data)
BitMatrix (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
BitMatrix (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
~BitMatrix ()
void initialize ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
void setAll ()
void toggleAll ()
void clearBit (uintidx i, uintidx j)
void setBit (uintidx i, uintidx j)
const T_BITSIZE * getRow (const uintidx i) const
T_BITSIZE * getRow (const uintidx i)
bool operator() (uintidx i, uintidx j) const
void copyAligned (BitMatrix< T_BITSIZE > &aibitmatrix_source, const uintidx aiui_idxTarget, const uintidx aiui_length)
uintidx getRowNumBitOn (uintidx aiui_rowi)
uintidx maxNorm ()
void copyUnaligned (uintidx aiui_idxTarget, BitMatrix< T_BITSIZE > &aibitmatrix_source, uintidx aiui_idxSource, uintidx aiui_length)
void print_listAdj (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimVert=',', const char aic_delimAdj=';') const
void printByColumns (std::ostream &os=std::cout, const uintidx aiui_numRows=80, const char aic_delimRow='\n') const
void opXor (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
opXor
Friends
std::ostream & operator<< (std::ostream &os, const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > &aichrombitcrispmatrix_b)
Additional Inherited Members
Protected Member Functions inherited from mat::BitMatrix< T_BITSIZE >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Protected Attributes inherited from mat::BitMatrix< T_BITSIZE >
ds::BitContainer< T_BITSIZE > _bitContainer_data
uintidx _ui_numRows
uintidx _ui_numColumns
uintidx _st_numWordsRows
Detailed Description
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC>
class gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >
Chromosome bit crisp matrix.
Definition at line 39 of file chromosome_crispmatrix.hpp.
Constructor & Destructor Documentation
ChromosomeCrispMatrix() [1/4]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::ChromosomeCrispMatrix () inline
Definition at line 44 of file chromosome_crispmatrix.hpp.
ChromosomeCrispMatrix() [2/4]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::ChromosomeCrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns) inline
Definition at line 50 of file chromosome_crispmatrix.hpp.
ChromosomeCrispMatrix() [3/4]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::ChromosomeCrispMatrix (const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > & aichrombitcrispmatrix_b) inline
Definition at line 59 of file chromosome_crispmatrix.hpp.
ChromosomeCrispMatrix() [4/4]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::ChromosomeCrispMatrix (ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > && aichrombitcrispmatrix_b) inline
Definition at line 66 of file chromosome_crispmatrix.hpp.
~ChromosomeCrispMatrix()
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> virtual gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::~ChromosomeCrispMatrix () inline virtual
Definition at line 71 of file chromosome_crispmatrix.hpp.
Member Function Documentation
operator=() [1/2]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> ChromosomeCrispMatrix<T_BITSIZE,T_CLUSTERIDX,T_METRIC>& gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::operator= (const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > & aichrombitcrispmatrix_b) inline
Definition at line 77 of file chromosome_crispmatrix.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::operator=(), and gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::print().
operator=() [2/2]
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> ChromosomeCrispMatrix<T_BITSIZE,T_CLUSTERIDX,T_METRIC>& gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::operator= (ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > && aichrombitcrispmatrix_b) inline
Definition at line 116 of file chromosome_crispmatrix.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::operator=(), and gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::print().
print()
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> virtual void gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = '\n') const inline virtual
Reimplemented from gaencode::ChromosomeBase< T_METRIC >.
Definition at line 155 of file chromosome_crispmatrix.hpp.
References gaencode::ChromosomeBase< T_METRIC >::print(), and mat::BitMatrix< T_BITSIZE >::print().
Referenced by gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::operator=().
Friends And Related Function Documentation
operator<<
template<class T_BITSIZE, class T_CLUSTERIDX, class T_METRIC> std::ostream& operator<< (std::ostream & os, const ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC > & aichrombitcrispmatrix_b) friend
Definition at line 176 of file chromosome_crispmatrix.hpp.
The documentation for this class was generated from the following file:
include/chromosome_crispmatrix.hpp