Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromVariableLength< T_GENE, T_METRIC > Class Template Reference
gaencode::ChromVariableLength< T_GENE, T_METRIC > Class Template Reference
Chromosome with variable length string.
#include <chromosome_variablelength.hpp>
Public Member Functions
ChromVariableLength ()
ChromVariableLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromVariableLength (const uintidx aiuintidx_stringSize)
ChromVariableLength (ChromVariableLength< T_GENE, T_METRIC > &&aichromvarlength_b)
ChromVariableLength (const ChromVariableLength< T_GENE, T_METRIC > &aichromvarlength_b)
virtual ~ChromVariableLength ()
ChromVariableLength< T_GENE, T_METRIC > & operator= (const ChromVariableLength< T_GENE, T_METRIC > &aichromvarlength_b)
ChromVariableLength< T_GENE, T_METRIC > & operator= (ChromVariableLength< T_GENE, T_METRIC > &&aichromvarlength_b)
virtual const uintidx getStringSize () const
virtual void setString (T_GENE *aips_string)
virtual T_GENE * getString ()
virtual const T_GENE * getString () const
virtual const T_GENE getGene (const uintidx aiuintidx_idxGene) const
virtual void setGene (uintidx aiuintidx_idxGene, T_GENE ait_newGene)
T_GENE * begin ()
T_GENE * end ()
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromosomeString< T_GENE, T_METRIC >
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_GENE, T_METRIC > & operator= (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
ChromosomeString< T_GENE, T_METRIC > & operator= (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Protected Attributes
T_GENE * _pts_string
uintidx _uintidx_stringSize
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Detailed Description
template<class T_GENE, class T_METRIC>
class gaencode::ChromVariableLength< T_GENE, T_METRIC >
Chromosome with variable length string.
Definition at line 42 of file chromosome_variablelength.hpp.
Constructor & Destructor Documentation
ChromVariableLength() [1/5]
template<class T_GENE, class T_METRIC> gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength () inline
Definition at line 46 of file chromosome_variablelength.hpp.
ChromVariableLength() [2/5]
template<class T_GENE, class T_METRIC> gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness) inline
Definition at line 52 of file chromosome_variablelength.hpp.
ChromVariableLength() [3/5]
template<class T_GENE, class T_METRIC> gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength (const uintidx aiuintidx_stringSize) inline
Definition at line 58 of file chromosome_variablelength.hpp.
ChromVariableLength() [4/5]
template<class T_GENE, class T_METRIC> gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength (ChromVariableLength< T_GENE, T_METRIC > && aichromvarlength_b) inline
Definition at line 65 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::print().
ChromVariableLength() [5/5]
template<class T_GENE, class T_METRIC> gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength (const ChromVariableLength< T_GENE, T_METRIC > & aichromvarlength_b) inline
Definition at line 99 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, interfacesse::copy(), and gaencode::ChromVariableLength< T_GENE, T_METRIC >::print().
~ChromVariableLength()
template<class T_GENE, class T_METRIC> virtual gaencode::ChromVariableLength< T_GENE, T_METRIC >::~ChromVariableLength () inline virtual
Definition at line 136 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string.
Member Function Documentation
begin()
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromVariableLength< T_GENE, T_METRIC >::begin () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 252 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string.
end()
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromVariableLength< T_GENE, T_METRIC >::end () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 257 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, and gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize.
getGene()
template<class T_GENE, class T_METRIC> virtual const T_GENE gaencode::ChromVariableLength< T_GENE, T_METRIC >::getGene (const uintidx aiuintidx_idxGene) const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 240 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, and gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize.
getString() [1/2]
template<class T_GENE, class T_METRIC> virtual T_GENE* gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 230 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string.
Referenced by main(), gaclusteringop::newChromosome(), gagenericop::onePointCrossover(), and eac::tgca_vkcentroid().
getString() [2/2]
template<class T_GENE, class T_METRIC> virtual const T_GENE* gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString () const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 235 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string.
getStringSize()
template<class T_GENE, class T_METRIC> virtual const uintidx gaencode::ChromVariableLength< T_GENE, T_METRIC >::getStringSize () const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 216 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize.
Referenced by main(), gagenericop::onePointCrossover(), and eac::tgca_vkcentroid().
operator=() [1/2]
template<class T_GENE, class T_METRIC> ChromVariableLength<T_GENE,T_METRIC>& gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator= (const ChromVariableLength< T_GENE, T_METRIC > & aichromvarlength_b) inline
Definition at line 156 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize, interfacesse::copy(), gaencode::ChromosomeString< T_GENE, T_METRIC >::operator=(), and gaencode::ChromVariableLength< T_GENE, T_METRIC >::print().
operator=() [2/2]
template<class T_GENE, class T_METRIC> ChromVariableLength<T_GENE,T_METRIC>& gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator= (ChromVariableLength< T_GENE, T_METRIC > && aichromvarlength_b) inline
Definition at line 199 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize, and gaencode::ChromosomeString< T_GENE, T_METRIC >::operator=().
print()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromVariableLength< T_GENE, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromosomeBase< T_METRIC >.
Definition at line 263 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize, and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength(), gaclusteringop::newChromosome(), gagenericop::onePointCrossover(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator=(), and eac::tgca_vkcentroid().
setGene()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromVariableLength< T_GENE, T_METRIC >::setGene (uintidx aiuintidx_idxGene, T_GENE ait_newGene) inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 246 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, and gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize.
setString()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromVariableLength< T_GENE, T_METRIC >::setString (T_GENE * aips_string) inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 221 of file chromosome_variablelength.hpp.
References gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string, gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize, and interfacesse::copy().
Member Data Documentation
_pts_string
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromVariableLength< T_GENE, T_METRIC >::_pts_string protected
Definition at line 290 of file chromosome_variablelength.hpp.
Referenced by gaencode::ChromVariableLength< T_GENE, T_METRIC >::begin(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::end(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getGene(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator=(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::print(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::setGene(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::setString(), and gaencode::ChromVariableLength< T_GENE, T_METRIC >::~ChromVariableLength().
_uintidx_stringSize
template<class T_GENE, class T_METRIC> uintidx gaencode::ChromVariableLength< T_GENE, T_METRIC >::_uintidx_stringSize protected
Definition at line 291 of file chromosome_variablelength.hpp.
Referenced by gaencode::ChromVariableLength< T_GENE, T_METRIC >::end(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getGene(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getStringSize(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator=(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::print(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::setGene(), and gaencode::ChromVariableLength< T_GENE, T_METRIC >::setString().
The documentation for this class was generated from the following file:
include/chromosome_variablelength.hpp