Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamFk< T_CLUSTERIDX > Class Template Reference
inout::InParamFk< T_CLUSTERIDX > Class Template Reference
Input parameter for algorithms with Fixed K.
#include <inparam_fixedk.hpp>
Public Member Functions
InParamFk ()
~InParamFk ()
void setNumClusterK (T_CLUSTERIDX aiidxK_numClusterK)
const T_CLUSTERIDX getNumClusterK () const
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Protected Attributes
T_CLUSTERIDX _idxK_numClusterK
Detailed Description
template<class T_CLUSTERIDX>
class inout::InParamFk< T_CLUSTERIDX >
Input parameter for algorithms with Fixed K.
Definition at line 35 of file inparam_fixedk.hpp.
Constructor & Destructor Documentation
InParamFk()
template<class T_CLUSTERIDX > inout::InParamFk< T_CLUSTERIDX >::InParamFk () inline
Definition at line 37 of file inparam_fixedk.hpp.
~InParamFk()
template<class T_CLUSTERIDX > inout::InParamFk< T_CLUSTERIDX >::~InParamFk () inline
Definition at line 40 of file inparam_fixedk.hpp.
Member Function Documentation
getNumClusterK()
template<class T_CLUSTERIDX > const T_CLUSTERIDX inout::InParamFk< T_CLUSTERIDX >::getNumClusterK () const inline
Definition at line 47 of file inparam_fixedk.hpp.
References inout::InParamFk< T_CLUSTERIDX >::_idxK_numClusterK.
print()
template<class T_CLUSTERIDX > virtual void inout::InParamFk< T_CLUSTERIDX >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented in inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSlink< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, and inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >.
Definition at line 52 of file inparam_fixedk.hpp.
References inout::InParamFk< T_CLUSTERIDX >::_idxK_numClusterK.
Referenced by inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamSlink< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >::print().
setNumClusterK()
template<class T_CLUSTERIDX > void inout::InParamFk< T_CLUSTERIDX >::setNumClusterK (T_CLUSTERIDX aiidxK_numClusterK) inline
Definition at line 42 of file inparam_fixedk.hpp.
References inout::InParamFk< T_CLUSTERIDX >::_idxK_numClusterK.
Member Data Documentation
_idxK_numClusterK
template<class T_CLUSTERIDX > T_CLUSTERIDX inout::InParamFk< T_CLUSTERIDX >::_idxK_numClusterK protected
Definition at line 59 of file inparam_fixedk.hpp.
Referenced by inout::InParamFk< T_CLUSTERIDX >::getNumClusterK(), inout::InParamFk< T_CLUSTERIDX >::print(), and inout::InParamFk< T_CLUSTERIDX >::setNumClusterK().
The documentation for this class was generated from the following file:
include_inout/inparam_fixedk.hpp