Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
Input parameter for read instances.
#include <inparam_readinst.hpp>
Public Member Functions
InParamReadInst ()
InParamReadInst (const char *aips_fileNameInstance, EnumFormatInstanceFile aienum_formatInstanceFile, const char *ais_separatorAttributes, const char *aips_selectAttributes, bool aib_haveHeaderFile=false)
~InParamReadInst ()
void clearVectorFilesInstance ()
const std::vector< std::string > & getVectorFilesInstance () const
void setVectorFilesInstance (const std::vector< std::string > &aivectorstr_filesInstance)
uintidx getNumFilesInstance ()
void setVectorFilesInstanceTest (const std::vector< std::string > &aivectorstr_filesInstanceTest)
const std::vector< std::string > & getVectorFilesInstanceTest () const
uintidx getNumFilesInstanceTest ()
void setFileInstance (const char *aips_nameFile)
void setFileInstance (const std::string aistr_nameFile)
void setFileInstanceTest (const char *aips_nameFileTest)
void setFileInstanceTest (const std::string aistr_nameFileTest)
const std::string & getCurrentFileInstance () const
const std::string & getCurrentFileInstanceTest () const
void setCurrentFileInstance (uintidx aiui_i)
void setSelectAttributes (const char *aips_selectAttributes)
const std::string & getSelectAttributes ()
void setSeparateAttributes (const char *aipc_separateAttributes)
const std::string & getSeparateAttributes ()
char getSeparateAttributesChar ()
void setHaveHeaderFileInstance (bool aib_bool)
bool getHaveHeaderFileInstance ()
void setClassInstanceColumn (uintidx aiui_classInstanceColumn)
uintidx getClassInstanceColumn ()
void setClusterInstanceColumn (uintidx aiui_clusterInstanceColumn)
uintidx getClusterInstanceColumn ()
void setIDInstanceColumn (uintidx aiui_idInstanceColumn)
uintidx getIDInstanceColumn ()
void setInstanceFrequencyColumn (uintidx aiui_instancesFrequencyColumn)
uintidx getInstanceFrequencyColumn ()
void setFormatInstanceFile (EnumFormatInstanceFile aienum_formatInstanceFile)
EnumFormatInstanceFile getFormatInstanceFile ()
void setIDMultiInstanceColumn (uintidx aiui_idMultiInstanceColumn)
uintidx getIDMultiInstanceColumn ()
void setClassMultiInstColumn (uintidx aiui_classMultiInstColumn)
uintidx getClassMultiInstColumn ()
void setNumInstances (uintidx aiui_numInstances)
const uintidx getNumInstances () const
void setNumInstancesTest (uintidx aiui_numInstancesTest)
const uintidx getNumInstancesTest () const
void setNumDimensionsInstances (uintidx aiui_numDimensionsInstances)
const uintidx getNumDimensionsInstances () const
void setPrintMulLine (bool aib_printMulLine)
bool getPrintMulLine ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Protected Attributes
uintidx _ui_idxCurrentFileInstance
std::vector< std::string > _vectorstr_filesInstance
std::vector< std::string > _vectorstr_filesInstanceTest
EnumFormatInstanceFile _enum_formatInstanceFile
bool _b_haveHeaderFile
std::string _s_separatorAttributes
std::string _ps_selectAttributes
uintidx _ui_classInstanceColumn
uintidx _ui_clusterInstanceColumn
uintidx _ui_idInstanceColumn
uintidx _ui_instancesFrequencyColumn
uintidx _ui_idMultiInstanceColumn
uintidx _ui_classMultiInstColumn
uintidx _ui_numInstances
uintidx _ui_numDimensionsInstances
uintidx _ui_numInstancesTest
bool _b_printMulLine
Detailed Description
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX>
class inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
Input parameter for read instances.
Definition at line 48 of file inparam_readinst.hpp.
Constructor & Destructor Documentation
InParamReadInst() [1/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InParamReadInst () inline
Definition at line 50 of file inparam_readinst.hpp.
InParamReadInst() [2/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InParamReadInst (const char * aips_fileNameInstance, EnumFormatInstanceFile aienum_formatInstanceFile, const char * ais_separatorAttributes, const char * aips_selectAttributes, bool aib_haveHeaderFile = false) inline
Definition at line 70 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
~InParamReadInst()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::~InParamReadInst () inline
Definition at line 97 of file inparam_readinst.hpp.
Member Function Documentation
clearVectorFilesInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::clearVectorFilesInstance () inline
Definition at line 99 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance, and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
getClassInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn () inline
Definition at line 217 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classInstanceColumn.
Referenced by inout::dataSetRead(), inout::dataSetReadWithFreq(), inout::instancesReadDimName(), inout::instancesReadWithClass(), and inout::instancesReadWithFreqClass().
getClassMultiInstColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassMultiInstColumn () inline
Definition at line 280 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classMultiInstColumn.
getClusterInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClusterInstanceColumn () inline
Definition at line 228 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_clusterInstanceColumn.
Referenced by inout::instancesReadWithClass(), and inout::instancesReadWithFreqClass().
getCurrentFileInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::string& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance () const inline
Definition at line 162 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idxCurrentFileInstance, and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
Referenced by inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), inout::instancesReadWithFreqClass(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and inout::readNumInstances().
getCurrentFileInstanceTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::string& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest () const inline
Definition at line 167 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idxCurrentFileInstance, and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
Referenced by inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), inout::instancesReadWithFreqClass(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and inout::readNumInstances().
getFormatInstanceFile()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> EnumFormatInstanceFile inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getFormatInstanceFile () inline
Definition at line 260 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_enum_formatInstanceFile.
Referenced by inout::instancesReadDimName().
getHaveHeaderFileInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> bool inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance () inline
Definition at line 207 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_haveHeaderFile.
Referenced by inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), inout::instancesReadWithFreqClass(), and inout::readNumInstances().
getIDInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn () inline
Definition at line 239 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idInstanceColumn.
Referenced by inout::instancesRead(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), and inout::instancesReadWithFreqClass().
getIDMultiInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDMultiInstanceColumn () inline
Definition at line 270 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idMultiInstanceColumn.
getInstanceFrequencyColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getInstanceFrequencyColumn () inline
Definition at line 249 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_instancesFrequencyColumn.
Referenced by inout::instancesReadWithFreq(), and inout::instancesReadWithFreqClass().
getNumDimensionsInstances()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumDimensionsInstances () const inline
Definition at line 311 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numDimensionsInstances.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
getNumFilesInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstance () inline
Definition at line 119 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
getNumFilesInstanceTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstanceTest () inline
Definition at line 137 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
Referenced by inout::dataSetRead(), and inout::dataSetReadWithFreq().
getNumInstances()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstances () const inline
Definition at line 290 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstances.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
getNumInstancesTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstancesTest () const inline
Definition at line 301 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstancesTest.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
getPrintMulLine()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> bool inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getPrintMulLine () inline
Definition at line 321 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_printMulLine.
getSelectAttributes()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::string& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes () inline
Definition at line 182 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ps_selectAttributes.
Referenced by inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), inout::instancesReadWithFreqClass(), and inout::readNumInstances().
getSeparateAttributes()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::string& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes () inline
Definition at line 192 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_s_separatorAttributes.
Referenced by inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), inout::instancesReadWithFreqClass(), and inout::readNumInstances().
getSeparateAttributesChar()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> char inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributesChar () inline
Definition at line 197 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_s_separatorAttributes.
getVectorFilesInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::vector<std::string>& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getVectorFilesInstance () const inline
Definition at line 105 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
getVectorFilesInstanceTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> const std::vector<std::string>& inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getVectorFilesInstanceTest () const inline
Definition at line 132 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
print()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> virtual void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented in inout::InParamPlotClustering< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamDBSCAN< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamPCA< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >, inout::InParamTGCA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamStdVar< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSlink< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, and inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >.
Definition at line 326 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_enum_formatInstanceFile, inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ps_selectAttributes, inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classInstanceColumn, inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest, inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumDimensionsInstances(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstances(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstancesTest(), and INPARAMCLUSTERING_FORMATINSTANCEFILE.
Referenced by inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamSlink< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamStdVar< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >::print(), inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPCA< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamDBSCAN< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamPlotClustering< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
setClassInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClassInstanceColumn (uintidx aiui_classInstanceColumn) inline
Definition at line 212 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classInstanceColumn.
setClassMultiInstColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClassMultiInstColumn (uintidx aiui_classMultiInstColumn) inline
Definition at line 275 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classMultiInstColumn.
setClusterInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClusterInstanceColumn (uintidx aiui_clusterInstanceColumn) inline
Definition at line 223 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_clusterInstanceColumn.
setCurrentFileInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setCurrentFileInstance (uintidx aiui_i) inline
Definition at line 172 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idxCurrentFileInstance.
setFileInstance() [1/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstance (const char * aips_nameFile) inline
Definition at line 142 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
setFileInstance() [2/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstance (const std::string aistr_nameFile) inline
Definition at line 147 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
setFileInstanceTest() [1/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstanceTest (const char * aips_nameFileTest) inline
Definition at line 152 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
setFileInstanceTest() [2/2]
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstanceTest (const std::string aistr_nameFileTest) inline
Definition at line 157 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
setFormatInstanceFile()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFormatInstanceFile (EnumFormatInstanceFile aienum_formatInstanceFile) inline
Definition at line 255 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_enum_formatInstanceFile.
setHaveHeaderFileInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setHaveHeaderFileInstance (bool aib_bool) inline
Definition at line 202 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_haveHeaderFile.
setIDInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setIDInstanceColumn (uintidx aiui_idInstanceColumn) inline
Definition at line 234 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idInstanceColumn.
setIDMultiInstanceColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setIDMultiInstanceColumn (uintidx aiui_idMultiInstanceColumn) inline
Definition at line 265 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idMultiInstanceColumn.
setInstanceFrequencyColumn()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setInstanceFrequencyColumn (uintidx aiui_instancesFrequencyColumn) inline
Definition at line 244 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_instancesFrequencyColumn.
setNumDimensionsInstances()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumDimensionsInstances (uintidx aiui_numDimensionsInstances) inline
Definition at line 306 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numDimensionsInstances.
setNumInstances()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumInstances (uintidx aiui_numInstances) inline
Definition at line 285 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstances.
setNumInstancesTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumInstancesTest (uintidx aiui_numInstancesTest) inline
Definition at line 296 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstancesTest.
setPrintMulLine()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setPrintMulLine (bool aib_printMulLine) inline
Definition at line 316 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_printMulLine.
setSelectAttributes()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setSelectAttributes (const char * aips_selectAttributes) inline
Definition at line 177 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ps_selectAttributes.
setSeparateAttributes()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setSeparateAttributes (const char * aipc_separateAttributes) inline
Definition at line 187 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_s_separatorAttributes.
setVectorFilesInstance()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setVectorFilesInstance (const std::vector< std::string > & aivectorstr_filesInstance) inline
Definition at line 113 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance.
setVectorFilesInstanceTest()
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> void inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setVectorFilesInstanceTest (const std::vector< std::string > & aivectorstr_filesInstanceTest) inline
Definition at line 127 of file inparam_readinst.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest.
Member Data Documentation
_b_haveHeaderFile
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> bool inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_haveHeaderFile protected
Definition at line 359 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setHaveHeaderFileInstance().
_b_printMulLine
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> bool inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_b_printMulLine protected
Definition at line 372 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getPrintMulLine(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setPrintMulLine().
_enum_formatInstanceFile
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> EnumFormatInstanceFile inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_enum_formatInstanceFile protected
Definition at line 358 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getFormatInstanceFile(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFormatInstanceFile().
_ps_selectAttributes
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> std::string inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ps_selectAttributes protected
Definition at line 361 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setSelectAttributes().
_s_separatorAttributes
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> std::string inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_s_separatorAttributes protected
Definition at line 360 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributesChar(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setSeparateAttributes().
_ui_classInstanceColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classInstanceColumn protected
Definition at line 362 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClassInstanceColumn().
_ui_classMultiInstColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_classMultiInstColumn protected
Definition at line 367 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassMultiInstColumn(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClassMultiInstColumn().
_ui_clusterInstanceColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_clusterInstanceColumn protected
Definition at line 363 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClusterInstanceColumn(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setClusterInstanceColumn().
_ui_idInstanceColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idInstanceColumn protected
Definition at line 364 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setIDInstanceColumn().
_ui_idMultiInstanceColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idMultiInstanceColumn protected
Definition at line 366 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDMultiInstanceColumn(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setIDMultiInstanceColumn().
_ui_idxCurrentFileInstance
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_idxCurrentFileInstance protected
Definition at line 355 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setCurrentFileInstance().
_ui_instancesFrequencyColumn
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_instancesFrequencyColumn protected
Definition at line 365 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getInstanceFrequencyColumn(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setInstanceFrequencyColumn().
_ui_numDimensionsInstances
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numDimensionsInstances protected
Definition at line 369 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumDimensionsInstances(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumDimensionsInstances().
_ui_numInstances
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstances protected
Definition at line 368 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstances(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumInstances().
_ui_numInstancesTest
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> uintidx inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_ui_numInstancesTest protected
Definition at line 370 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumInstancesTest(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setNumInstancesTest().
_vectorstr_filesInstance
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> std::vector<std::string> inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstance protected
Definition at line 356 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::clearVectorFilesInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getVectorFilesInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InParamReadInst(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstance(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setVectorFilesInstance().
_vectorstr_filesInstanceTest
template<typename T_FEATURE, typename T_INSTANCES_CLUSTER_K, typename T_CLUSTERIDX> std::vector<std::string> inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_vectorstr_filesInstanceTest protected
Definition at line 357 of file inparam_readinst.hpp.
Referenced by inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::clearVectorFilesInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getVectorFilesInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setFileInstanceTest(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::setVectorFilesInstanceTest().
The documentation for this class was generated from the following file:
include_inout/inparam_readinst.hpp