Library Evolutionary Algorithms for Clustering (LEAC): partition::PartitionDisjSets< T_CLUSTERIDX > Class Template Reference
partition::PartitionDisjSets< T_CLUSTERIDX > Class Template Reference
Partition of instances in base DisjSets data structure.
#include <partition_disjsets.hpp>
Public Member Functions
PartitionDisjSets ()
PartitionDisjSets (ds::DisjSets &&aids_disjset)
PartitionDisjSets (ds::DisjSets &&aids_disjset, const std::vector< uintidx > &aivectoruintidx_idxToMap)
PartitionDisjSets (const PartitionDisjSets< T_CLUSTERIDX > &aimembclassdisjset_b)
PartitionDisjSets (PartitionDisjSets< T_CLUSTERIDX > &&aimembclassdisjset_b)
~PartitionDisjSets ()
void begin ()
const T_CLUSTERIDX next ()
bool end () const
PartitionDisjSets< T_CLUSTERIDX > & operator= (const PartitionDisjSets< T_CLUSTERIDX > &aimembclassdisjset_b)
PartitionDisjSets< T_CLUSTERIDX > & operator= (PartitionDisjSets< T_CLUSTERIDX > &&aimembclassdisjset_b)
const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const
const uintidx getNumInstances () const
const T_CLUSTERIDX getNumCluster () const
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from partition::Partition< T_CLUSTERIDX >
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
Public Member Functions inherited from ds::DisjSets
DisjSets ()
DisjSets (const uintidx ai_numObj)
DisjSets (DisjSets &&aids_disjset)
DisjSets (const DisjSets &aids_disjset)
~ DisjSets ()
DisjSets & operator= (DisjSets &&aids_disjset)
DisjSets & operator= (const DisjSets &aids_disjset)
void make_set (uintidx x)
uintidx find (uintidx x)
const uintidx constfind (uintidx x) const
void merge (uintidx x, uintidx y)
uintidx getNumSet ()
const uintidx size () const
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',') const
Protected Attributes
std::map< uintidx, T_CLUSTERIDX > _mapset_clusterk
uintidx _ui_iteratornext
Protected Attributes inherited from ds::DisjSets
uintidx _m
std::vector< uintidx > _vectorst_parent
std::vector< unsigned > _vectorui_rank
Detailed Description
template<class T_CLUSTERIDX>
class partition::PartitionDisjSets< T_CLUSTERIDX >
Partition of instances in base DisjSets data structure.
Definition at line 37 of file partition_disjsets.hpp.
Constructor & Destructor Documentation
PartitionDisjSets() [1/5]
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets () inline
Definition at line 43 of file partition_disjsets.hpp.
PartitionDisjSets() [2/5]
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets (ds::DisjSets && aids_disjset) inline
Definition at line 49 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk, and ds::DisjSets::_vectorst_parent.
PartitionDisjSets() [3/5]
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets (ds::DisjSets && aids_disjset, const std::vector< uintidx > & aivectoruintidx_idxToMap) inline
Definition at line 65 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk, and ds::DisjSets::constfind().
PartitionDisjSets() [4/5]
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets (const PartitionDisjSets< T_CLUSTERIDX > & aimembclassdisjset_b) inline
Definition at line 85 of file partition_disjsets.hpp.
PartitionDisjSets() [5/5]
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets (PartitionDisjSets< T_CLUSTERIDX > && aimembclassdisjset_b) inline
Definition at line 93 of file partition_disjsets.hpp.
~PartitionDisjSets()
template<class T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::~PartitionDisjSets () inline
Definition at line 100 of file partition_disjsets.hpp.
Member Function Documentation
begin()
template<class T_CLUSTERIDX> void partition::PartitionDisjSets< T_CLUSTERIDX >::begin () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 102 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_ui_iteratornext.
end()
template<class T_CLUSTERIDX> bool partition::PartitionDisjSets< T_CLUSTERIDX >::end () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 125 of file partition_disjsets.hpp.
References ds::DisjSets::_vectorst_parent.
getClusterIdx()
template<class T_CLUSTERIDX> const T_CLUSTERIDX partition::PartitionDisjSets< T_CLUSTERIDX >::getClusterIdx (uintidx aiuintidx_instanceIdx) const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 152 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk, ds::DisjSets::constfind(), and NEARESTCENTROID_UNKNOWN.
getNumCluster()
template<class T_CLUSTERIDX> const T_CLUSTERIDX partition::PartitionDisjSets< T_CLUSTERIDX >::getNumCluster () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 172 of file partition_disjsets.hpp.
References ds::DisjSets::_m.
Referenced by eac::clustering_vksubclusterbinary().
getNumInstances()
template<class T_CLUSTERIDX> const uintidx partition::PartitionDisjSets< T_CLUSTERIDX >::getNumInstances () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 167 of file partition_disjsets.hpp.
References ds::DisjSets::_vectorst_parent.
next()
template<class T_CLUSTERIDX> const T_CLUSTERIDX partition::PartitionDisjSets< T_CLUSTERIDX >::next () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 107 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk, partition::PartitionDisjSets< T_CLUSTERIDX >::_ui_iteratornext, ds::DisjSets::constfind(), and NEARESTCENTROID_UNKNOWN.
operator=() [1/2]
template<class T_CLUSTERIDX> PartitionDisjSets<T_CLUSTERIDX>& partition::PartitionDisjSets< T_CLUSTERIDX >::operator= (const PartitionDisjSets< T_CLUSTERIDX > & aimembclassdisjset_b) inline
Definition at line 131 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk.
operator=() [2/2]
template<class T_CLUSTERIDX> PartitionDisjSets<T_CLUSTERIDX>& partition::PartitionDisjSets< T_CLUSTERIDX >::operator= (PartitionDisjSets< T_CLUSTERIDX > && aimembclassdisjset_b) inline
Definition at line 142 of file partition_disjsets.hpp.
References partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk.
print()
template<class T_CLUSTERIDX> void partition::PartitionDisjSets< T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 178 of file partition_disjsets.hpp.
Referenced by eac::clustering_vksubclusterbinary(), and main().
Member Data Documentation
_mapset_clusterk
template<class T_CLUSTERIDX> std::map<uintidx,T_CLUSTERIDX> partition::PartitionDisjSets< T_CLUSTERIDX >::_mapset_clusterk protected
Definition at line 206 of file partition_disjsets.hpp.
Referenced by partition::PartitionDisjSets< T_CLUSTERIDX >::getClusterIdx(), partition::PartitionDisjSets< T_CLUSTERIDX >::next(), partition::PartitionDisjSets< T_CLUSTERIDX >::operator=(), and partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets().
_ui_iteratornext
template<class T_CLUSTERIDX> uintidx partition::PartitionDisjSets< T_CLUSTERIDX >::_ui_iteratornext protected
Definition at line 207 of file partition_disjsets.hpp.
Referenced by partition::PartitionDisjSets< T_CLUSTERIDX >::begin(), and partition::PartitionDisjSets< T_CLUSTERIDX >::next().
The documentation for this class was generated from the following file:
include/partition_disjsets.hpp