Library Evolutionary Algorithms for Clustering (LEAC): data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > Class Template Reference
data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > Class Template Reference
Patterns, usually vectors in a multidimensional space, with an attribute to store occurrences of instances.
#include <instance_frequency.hpp>
Public Member Functions
InstanceFreq ()
InstanceFreq (T_INSTANCE_FREQUENCY ait_frequency)
InstanceFreq (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
InstanceFreq (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
virtual ~InstanceFreq ()
InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & operator= (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & operator= (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &&aiinstfreq_b)
void setFrequency (T_INSTANCE_FREQUENCY ait_frequency)
const T_INSTANCE_FREQUENCY getFrequency () const
virtual void print (std::ostream &os=std::cout, const char aic_delim='\t') const
virtual std::string getToString (const char aic_delim='\t')
Public Member Functions inherited from data::Instance< T_FEATURE >
Instance ()
Instance (T_FEATURE *aiarrayt_feature)
Instance (const Instance< T_FEATURE > &aiinst_b)
Instance (Instance< T_FEATURE > &&aiinst_b)
virtual ~Instance ()
Instance< T_FEATURE > & operator= (const Instance< T_FEATURE > &aiinst_b)
Instance< T_FEATURE > & operator= (Instance< T_FEATURE > &&aiinst_b)
const T_FEATURE * getFeatures () const
T_FEATURE * getFeatures ()
const T_FEATURE getAttribute (uintidx aui_idxAttribute) const
void readFeature (inout::LineSplit &ails_linesplit)
void setId (const std::string &aistr_id)
const char * getId () const
Protected Attributes
T_INSTANCE_FREQUENCY _t_frequency
Protected Attributes inherited from data::Instance< T_FEATURE >
char * _ptc_id
T_FEATURE * _arrayt_feature
Additional Inherited Members
Static Public Member Functions inherited from data::Instance< T_FEATURE >
static void setNumDimensions (uintidx aiuintidx_numDimensions)
static uintidx getNumDimensions ()
static void setHomogeneousCoord (bool aib_homogeneousCoord)
static bool getHomogeneousCoord ()
static T_FEATURE type ()
static T_FEATURE getInfiniteFeature ()
static bool isInfiniteFeature (T_FEATURE aiT_feacture)
Static Protected Attributes inherited from data::Instance< T_FEATURE >
static uintidx _stcuintidx_numDimensions = 0
static bool _stcb_homogeneousCoord = false
Detailed Description
template<class T_FEATURE, class T_INSTANCE_FREQUENCY>
class data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >
Patterns, usually vectors in a multidimensional space, with an attribute to store occurrences of instances.
Definition at line 34 of file instance_frequency.hpp.
Constructor & Destructor Documentation
InstanceFreq() [1/4]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::InstanceFreq () inline
Definition at line 39 of file instance_frequency.hpp.
InstanceFreq() [2/4]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::InstanceFreq (T_INSTANCE_FREQUENCY ait_frequency) inline
Definition at line 46 of file instance_frequency.hpp.
InstanceFreq() [3/4]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::InstanceFreq (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & aiinstfreq_b) inline
Definition at line 54 of file instance_frequency.hpp.
InstanceFreq() [4/4]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::InstanceFreq (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & aiinstfreq_b) inline
Definition at line 62 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency.
~InstanceFreq()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> virtual data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::~InstanceFreq () inline virtual
Definition at line 69 of file instance_frequency.hpp.
Member Function Documentation
getFrequency()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> const T_INSTANCE_FREQUENCY data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getFrequency () const inline
Definition at line 100 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency.
Referenced by clusteringop::fillEmptyPartitions(), clusteringop::joinPartition(), and main().
getToString()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> virtual std::string data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getToString (const char aic_delim = '\t') inline virtual
Reimplemented from data::Instance< T_FEATURE >.
Reimplemented in data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >.
Definition at line 112 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency.
operator=() [1/2]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> InstanceFreq<T_FEATURE,T_INSTANCE_FREQUENCY>& data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator= (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & aiinstfreq_b) inline
Definition at line 72 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency, and data::Instance< T_FEATURE >::operator=().
Referenced by data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=().
operator=() [2/2]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> InstanceFreq<T_FEATURE,T_INSTANCE_FREQUENCY>& data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator= (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > && aiinstfreq_b) inline
Definition at line 83 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency, and data::Instance< T_FEATURE >::operator=().
print()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> virtual void data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::print (std::ostream & os = std::cout, const char aic_delim = '\t') const inline virtual
Reimplemented from data::Instance< T_FEATURE >.
Reimplemented in data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >.
Definition at line 105 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency, and data::Instance< T_FEATURE >::print().
Referenced by clusteringop::joinPartition(), and data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
setFrequency()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> void data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::setFrequency (T_INSTANCE_FREQUENCY ait_frequency) inline
Definition at line 95 of file instance_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency.
Member Data Documentation
_t_frequency
template<class T_FEATURE, class T_INSTANCE_FREQUENCY> T_INSTANCE_FREQUENCY data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::_t_frequency protected
Definition at line 124 of file instance_frequency.hpp.
Referenced by data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getFrequency(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getToString(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::InstanceFreq(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator=(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::print(), and data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::setFrequency().
The documentation for this class was generated from the following file:
include/instance_frequency.hpp