Library Evolutionary Algorithms for Clustering (LEAC): mat::MatrixBase< T_FEATURE > Class Template Reference
mat::MatrixBase< T_FEATURE > Class Template Reference abstract
MatrixBase.
#include <matrix_base.hpp>
Public Member Functions
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T_FEATURE > &&B)
MatrixBase (const MatrixBase< T_FEATURE > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
virtual const T_FEATURE * getRow (const uintidx i) const =0
virtual T_FEATURE * getRow (const uintidx i)=0
MatrixBase< T_FEATURE > & operator= (const MatrixBase< T_FEATURE > &B)
MatrixBase< T_FEATURE > & operator= (MatrixBase< T_FEATURE > &&B)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const =0
Protected Member Functions
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Protected Attributes
uintidx _ui_numRows
uintidx _ui_numColumns
Friends
std::ostream & operator<< (std::ostream &os, const MatrixBase< T_FEATURE > &aimatrix_a)
Detailed Description
template<class T_FEATURE>
class mat::MatrixBase< T_FEATURE >
MatrixBase.
Definition at line 42 of file matrix_base.hpp.
Constructor & Destructor Documentation
MatrixBase() [1/5]
template<class T_FEATURE> mat::MatrixBase< T_FEATURE >::MatrixBase () inline
Definition at line 44 of file matrix_base.hpp.
MatrixBase() [2/5]
template<class T_FEATURE> mat::MatrixBase< T_FEATURE >::MatrixBase (const uintidx aiui_numRows) inline
Definition at line 49 of file matrix_base.hpp.
MatrixBase() [3/5]
template<class T_FEATURE> mat::MatrixBase< T_FEATURE >::MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns) inline
Definition at line 54 of file matrix_base.hpp.
MatrixBase() [4/5]
template<class T_FEATURE> mat::MatrixBase< T_FEATURE >::MatrixBase (MatrixBase< T_FEATURE > && B) inline
Definition at line 60 of file matrix_base.hpp.
MatrixBase() [5/5]
template<class T_FEATURE> mat::MatrixBase< T_FEATURE >::MatrixBase (const MatrixBase< T_FEATURE > & B) inline
Definition at line 69 of file matrix_base.hpp.
~MatrixBase()
template<class T_FEATURE> virtual mat::MatrixBase< T_FEATURE >::~MatrixBase () inline virtual
Definition at line 74 of file matrix_base.hpp.
Member Function Documentation
_setNumColumns()
template<class T_FEATURE> void mat::MatrixBase< T_FEATURE >::_setNumColumns (uintidx aiui_numColumns) inline protected
Definition at line 142 of file matrix_base.hpp.
_setNumRows()
template<class T_FEATURE> void mat::MatrixBase< T_FEATURE >::_setNumRows (uintidx aiui_numRows) inline protected
Definition at line 137 of file matrix_base.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::decreaseRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::increasesRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize().
getNumColumns()
template<class T_FEATURE> const uintidx mat::MatrixBase< T_FEATURE >::getNumColumns () const inline
Definition at line 81 of file matrix_base.hpp.
Referenced by gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::checkChangedCodeVectors(), nearest::checkNullCentroidsNN(), mat::MatrixRow< T_METRIC >::copyRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRow(), mat::MatrixRow< T_METRIC >::cpyLoweToUpper(), mat::MatrixRow< T_METRIC >::cpyUpper(), um::dbindex(), nearest::dist(), um::entropy(), nearest::findTwoNearestCentroids(), eac::gaclustering_fkcrispmatrix(), interfacesse::gemm(), interfacesse::gemv(), clusteringop::getCentroids(), mat::MatrixRow< T_METRIC >::getMaximumElemIJ(), mat::MatrixBase< T_GENE >::getNumElems(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getNumElemsMaximum(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumInstances(), mat::MatrixRow< T_METRIC >::getRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getRow(), mat::getTranspose(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), mat::inverse(), mat::keepRows(), gaclusteringop::kmeansfeac(), mat::lange(), main(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::MatrixResizableRow(), um::maxDistCjCjp(), stats::meanRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), um::minDistCjCjp(), gaclusteringop::MO1(), mat::mulRowsIColumns0N(), gaintegerop::mutationgka(), nearest::NN(), mat::MatrixRow< T_METRIC >::operator()(), mat::MatrixRow< T_METRIC >::operator+=(), mat::MatrixRow< T_METRIC >::operator-=(), um::partitioncoefficient(), mat::point(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::print(), mat::MatrixRow< T_METRIC >::print(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), mat::MatrixRow< T_METRIC >::r8mat_print(), clusteringop::randomInitialize(), gaclusteringop::rearrangedCluster(), clusteringop::reassignCluster(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize(), um::ssb(), um::ssbreeval(), um::sumMinCjCjp(), mat::MatrixRow< T_METRIC >::swapRows(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::swapRows(), and mat::syevd().
getNumElems()
template<class T_FEATURE> const uintidx mat::MatrixBase< T_FEATURE >::getNumElems () const inline
Definition at line 86 of file matrix_base.hpp.
Referenced by um::entropy(), clusteringop::getCentroids(), mat::MatrixRow< T_METRIC >::initialize(), mat::lange(), mat::MatrixRow< T_METRIC >::MatrixRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), mat::MatrixRow< T_METRIC >::operator=(), um::partitioncoefficient(), mat::MatrixRow< T_METRIC >::print(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::print().
getNumRows()
template<class T_FEATURE> const uintidx mat::MatrixBase< T_FEATURE >::getNumRows () const inline
Definition at line 76 of file matrix_base.hpp.
Referenced by um::avgRadiusClusterK(), mat::bitgemm(), gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::checkChangedCodeVectors(), nearest::checkNullCentroidsNN(), eac::clustering_genetic(), mat::MatrixRow< T_METRIC >::copyRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRows(), mat::MatrixRow< T_METRIC >::cpyLoweToUpper(), mat::MatrixRow< T_METRIC >::cpyUpper(), um::D2(), um::dbindex(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::decreaseRow(), um::Dinter(), um::Dintra(), nearest::dist(), um::distortion(), nearest::findTwoNearestCentroids(), clusteringop::fuzzyPartition(), eac::gaclustering_fkcrispmatrix(), eac::gcuk_vkcentroid(), interfacesse::gemm(), interfacesse::gemv(), clusteringop::getCentroids(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx(), clusteringop::getClusters(), mat::getIdentity(), stats::getMatrixDiagonal(), mat::MatrixRow< T_METRIC >::getMaximumElemIJ(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumCluster(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumClusterK(), mat::MatrixBase< T_GENE >::getNumElems(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumPartitions(), clusteringop::getPartition(), mat::MatrixRow< T_METRIC >::getRow(), mat::getTranspose(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::increasesRow(), um::indexI(), um::indexIreeval(), clusteringop::initialize(), mat::inverse(), um::j1(), um::jm(), gaclusteringop::kmeansfeac(), clusteringop::kmeansoperator(), mat::lange(), mat::LUPdecompose(), mat::LUPinverse(), main(), um::maxDistCjCjp(), um::maxRadiusClusterK(), clusteringop::meanCentroids(), stats::meanRow(), gaclusteringop::merge(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), um::minDistCjCjp(), gaclusteringop::MO1(), gaclusteringop::MO2(), gaintegerop::mutationgka(), gaclusteringop::newChromosome(), nearest::NN(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::numClusterEmpty(), mat::MatrixRow< T_METRIC >::operator+=(), mat::MatrixRow< T_METRIC >::operator-=(), mat::MatrixRow< T_METRIC >::print(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), mat::MatrixRow< T_METRIC >::r8mat_print(), clusteringop::randomInitialize(), gaclusteringop::rearrangedCluster(), clusteringop::reassignCluster(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::removeRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize(), um::scoreFunction(), um::scoreFunctionreeval(), mat::MatrixWithRowNull< T_GENE >::setMatrix(), um::simplifiedSilhouette(), um::ssb(), um::ssbreeval(), um::SSE(), um::sumDistInstCentInK(), um::sumMinCjCjp(), mat::MatrixRow< T_METRIC >::swapRows(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::swapRows(), mat::syevd(), um::VRC(), um::VRCreeval(), um::WBIndex(), um::WBIndexreeval(), and um::xb().
getRow() [1/2]
template<class T_FEATURE> virtual const T_FEATURE* mat::MatrixBase< T_FEATURE >::getRow (const uintidx i) const pure virtual
Implemented in mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >, mat::MatrixResizableRow< T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >, mat::MatrixRow< T_FEATURE >, mat::MatrixRow< T_U >, mat::MatrixRow< T_FEATURE_SUM >, mat::MatrixRow< T_INSTANCES_CLUSTER_K >, mat::MatrixRow< T_DIST >, mat::MatrixRow< T_METRIC >, mat::MatrixWithRowNull< T >, mat::MatrixWithRowNull< T_FEATURE >, and mat::MatrixWithRowNull< T_GENE >.
Referenced by um::avgRadiusClusterK(), nearest::checkNullCentroidsNN(), um::dbindex(), nearest::dist(), nearest::findTwoNearestCentroids(), clusteringop::initialize(), clusteringop::meanCentroids(), um::minDistCjCjp(), nearest::NN(), clusteringop::randomInitialize(), clusteringop::reassignCluster(), um::simplifiedDunnIndex(), um::simplifiedSilhouette(), and um::sumDistInstCentInK().
getRow() [2/2]
template<class T_FEATURE> virtual T_FEATURE* mat::MatrixBase< T_FEATURE >::getRow (const uintidx i) pure virtual
Implemented in mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >, mat::MatrixResizableRow< T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >, mat::MatrixRow< T_FEATURE >, mat::MatrixRow< T_U >, mat::MatrixRow< T_FEATURE_SUM >, mat::MatrixRow< T_INSTANCES_CLUSTER_K >, mat::MatrixRow< T_DIST >, mat::MatrixRow< T_METRIC >, mat::MatrixWithRowNull< T >, mat::MatrixWithRowNull< T_FEATURE >, and mat::MatrixWithRowNull< T_GENE >.
operator=() [1/2]
template<class T_FEATURE> MatrixBase<T_FEATURE>& mat::MatrixBase< T_FEATURE >::operator= (const MatrixBase< T_FEATURE > & B) inline
Definition at line 96 of file matrix_base.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::operator=(), mat::MatrixRow< T_METRIC >::operator=(), and mat::MatrixWithRowNull< T_GENE >::operator=().
operator=() [2/2]
template<class T_FEATURE> MatrixBase<T_FEATURE>& mat::MatrixBase< T_FEATURE >::operator= (MatrixBase< T_FEATURE > && B) inline
Definition at line 105 of file matrix_base.hpp.
print()
template<class T_FEATURE> virtual void mat::MatrixBase< T_FEATURE >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = '\n') const pure virtual
Implemented in mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >, mat::MatrixResizableRow< T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >, mat::MatrixWithRowNull< T >, mat::MatrixWithRowNull< T_FEATURE >, mat::MatrixWithRowNull< T_GENE >, mat::MatrixRow< T_FEATURE >, mat::MatrixRow< T_U >, mat::MatrixRow< T_FEATURE_SUM >, mat::MatrixRow< T_INSTANCES_CLUSTER_K >, mat::MatrixRow< T_DIST >, mat::MatrixRow< T_METRIC >, sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >, and gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >.
Referenced by clusteringop::initialize(), clusteringop::meanCentroids(), and clusteringop::randomInitialize().
Friends And Related Function Documentation
operator<<
template<class T_FEATURE> std::ostream& operator<< (std::ostream & os, const MatrixBase< T_FEATURE > & aimatrix_a) friend
Definition at line 127 of file matrix_base.hpp.
Member Data Documentation
_ui_numColumns
template<class T_FEATURE> uintidx mat::MatrixBase< T_FEATURE >::_ui_numColumns protected
Definition at line 148 of file matrix_base.hpp.
Referenced by mat::MatrixBase< T_GENE >::_setNumColumns(), mat::MatrixBase< T_GENE >::getNumColumns(), and mat::MatrixBase< T_GENE >::operator=().
_ui_numRows
template<class T_FEATURE> uintidx mat::MatrixBase< T_FEATURE >::_ui_numRows protected
Definition at line 147 of file matrix_base.hpp.
Referenced by mat::MatrixBase< T_GENE >::_setNumRows(), mat::MatrixBase< T_GENE >::getNumRows(), mat::MatrixTriang< T_DIST >::operator=(), and mat::MatrixBase< T_GENE >::operator=().
The documentation for this class was generated from the following file:
include/matrix_base.hpp