Library Evolutionary Algorithms for Clustering (LEAC): data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
Patterns, usually vectors in a multidimensional space, which is classified and with a number of occurrences.
#include <instance_class_frequency.hpp>
Public Member Functions
InstanceClassFreq ()
InstanceClassFreq (const InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstclassfreq_b)
InstanceClassFreq (InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstclassfreq_b)
virtual ~InstanceClassFreq ()
InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (const InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstclassfreq_b)
InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstclassfreq_b)
virtual void print (std::ostream &os=std::cout, const char aic_delim='\t') const
virtual std::string getToString (const char aic_delim='\t')
Public Member Functions inherited from data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >
InstanceFreq ()
InstanceFreq (T_INSTANCE_FREQUENCY ait_frequency)
InstanceFreq (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
InstanceFreq (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
virtual ~InstanceFreq ()
InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & operator= (const InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &aiinstfreq_b)
InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > & operator= (InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY > &&aiinstfreq_b)
void setFrequency (T_INSTANCE_FREQUENCY ait_frequency)
const T_INSTANCE_FREQUENCY getFrequency () const
Public Member Functions inherited from data::Instance< T_FEATURE >
Instance ()
Instance (T_FEATURE *aiarrayt_feature)
Instance (const Instance< T_FEATURE > &aiinst_b)
Instance (Instance< T_FEATURE > &&aiinst_b)
virtual ~Instance ()
Instance< T_FEATURE > & operator= (const Instance< T_FEATURE > &aiinst_b)
Instance< T_FEATURE > & operator= (Instance< T_FEATURE > &&aiinst_b)
const T_FEATURE * getFeatures () const
T_FEATURE * getFeatures ()
const T_FEATURE getAttribute (uintidx aui_idxAttribute) const
void readFeature (inout::LineSplit &ails_linesplit)
void setId (const std::string &aistr_id)
const char * getId () const
Public Member Functions inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
InstanceIterfazClass ()
InstanceIterfazClass (const InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstiterclass_b)
InstanceIterfazClass (InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstiterclass_b)
virtual ~InstanceIterfazClass ()
InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (const InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstiterclass_b)
InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstiterclass_b)
void setClassIdx (std::string &aistr_keyMapClass)
T_CLUSTERIDX getClassIdx ()
Additional Inherited Members
Public Types inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
typedef std::map< const std::string, CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > > MapClassLabel
Static Public Member Functions inherited from data::Instance< T_FEATURE >
static void setNumDimensions (uintidx aiuintidx_numDimensions)
static uintidx getNumDimensions ()
static void setHomogeneousCoord (bool aib_homogeneousCoord)
static bool getHomogeneousCoord ()
static T_FEATURE type ()
static T_FEATURE getInfiniteFeature ()
static bool isInfiniteFeature (T_FEATURE aiT_feacture)
Static Public Member Functions inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
static void initialize ()
static void setVectorClassLabel ()
static const std::vector< CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > * > & getVectorClassLabel ()
static std::vector< std::string > getLabelClass (uintidx aiui_numClass)
Protected Attributes inherited from data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >
T_INSTANCE_FREQUENCY _t_frequency
Protected Attributes inherited from data::Instance< T_FEATURE >
char * _ptc_id
T_FEATURE * _arrayt_feature
Protected Attributes inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
T_CLUSTERIDX _cidx_classIdx
Static Protected Attributes inherited from data::Instance< T_FEATURE >
static uintidx _stcuintidx_numDimensions = 0
static bool _stcb_homogeneousCoord = false
Static Protected Attributes inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
static MapClassLabel _stmap_instanceClass
static T_CLUSTERIDX _idxmcT_consecutiveClass = 0
static std::vector< CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > * > _stcvector_classLabel
Detailed Description
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX>
class data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
Patterns, usually vectors in a multidimensional space, which is classified and with a number of occurrences.
Definition at line 36 of file instance_class_frequency.hpp.
Constructor & Destructor Documentation
InstanceClassFreq() [1/3]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClassFreq () inline
Definition at line 41 of file instance_class_frequency.hpp.
InstanceClassFreq() [2/3]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClassFreq (const InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiinstclassfreq_b) inline
Definition at line 48 of file instance_class_frequency.hpp.
InstanceClassFreq() [3/3]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClassFreq (InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > && aiinstclassfreq_b) inline
Definition at line 56 of file instance_class_frequency.hpp.
~InstanceClassFreq()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::~InstanceClassFreq () inline virtual
Definition at line 62 of file instance_class_frequency.hpp.
Member Function Documentation
getToString()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual std::string data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getToString (const char aic_delim = '\t') inline virtual
Reimplemented from data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >.
Definition at line 93 of file instance_class_frequency.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_cidx_classIdx, and data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_stcvector_classLabel.
operator=() [1/2]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> InstanceClassFreq<T_FEATURE,T_INSTANCE_FREQUENCY,T_INSTANCES_CLUSTER_K,T_CLUSTERIDX>& data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator= (const InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiinstclassfreq_b) inline
Definition at line 65 of file instance_class_frequency.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=(), and data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator=().
operator=() [2/2]
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> InstanceClassFreq<T_FEATURE,T_INSTANCE_FREQUENCY,T_INSTANCES_CLUSTER_K,T_CLUSTERIDX>& data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator= (InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > && aiinstclassfreq_b) inline
Definition at line 76 of file instance_class_frequency.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=(), and data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator=().
print()
template<class T_FEATURE, class T_INSTANCE_FREQUENCY, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual void data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char aic_delim = '\t') const inline virtual
Reimplemented from data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >.
Definition at line 86 of file instance_class_frequency.hpp.
References data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::print(), and data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
The documentation for this class was generated from the following file:
include/instance_class_frequency.hpp