Library Evolutionary Algorithms for Clustering (LEAC): partition::PartitionFuzzy< T_U, T_CLUSTERIDX > Class Template Reference
partition::PartitionFuzzy< T_U, T_CLUSTERIDX > Class Template Reference
Partition of instances with fuzzy matrix [8] [6].
#include <partition_fuzzy.hpp>
Public Member Functions
PartitionFuzzy (const mat::MatrixRow< T_U > &aimatrixt_crisp)
~PartitionFuzzy ()
void begin ()
const T_CLUSTERIDX next ()
bool end () const
const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const
const uintidx getNumInstances () const
const T_CLUSTERIDX getNumCluster () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from partition::Partition< T_CLUSTERIDX >
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
Protected Attributes
const mat::MatrixRow< T_U > * _ptmatrix_crisp
uintidx _ui_iteratornext
Detailed Description
template<class T_U, class T_CLUSTERIDX>
class partition::PartitionFuzzy< T_U, T_CLUSTERIDX >
Partition of instances with fuzzy matrix [8] [6].
Definition at line 37 of file partition_fuzzy.hpp.
Constructor & Destructor Documentation
PartitionFuzzy()
template<class T_U , class T_CLUSTERIDX > partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::PartitionFuzzy (const mat::MatrixRow< T_U > & aimatrixt_crisp) inline
Definition at line 44 of file partition_fuzzy.hpp.
~PartitionFuzzy()
template<class T_U , class T_CLUSTERIDX > partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::~PartitionFuzzy () inline
Definition at line 50 of file partition_fuzzy.hpp.
Member Function Documentation
begin()
template<class T_U , class T_CLUSTERIDX > void partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::begin () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 53 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ui_iteratornext.
end()
template<class T_U , class T_CLUSTERIDX > bool partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::end () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 63 of file partition_fuzzy.hpp.
getClusterIdx()
template<class T_U , class T_CLUSTERIDX > const T_CLUSTERIDX partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx (uintidx aiuintidx_instanceIdx) const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 68 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ptmatrix_crisp, mat::MatrixBase< T_FEATURE >::getNumRows(), and inout::li_i.
Referenced by partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::next(), and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::print().
getNumCluster()
template<class T_U , class T_CLUSTERIDX > const T_CLUSTERIDX partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumCluster () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 90 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ptmatrix_crisp, and mat::MatrixBase< T_FEATURE >::getNumRows().
Referenced by partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::print().
getNumInstances()
template<class T_U , class T_CLUSTERIDX > const uintidx partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumInstances () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 85 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ptmatrix_crisp, and mat::MatrixBase< T_FEATURE >::getNumColumns().
next()
template<class T_U , class T_CLUSTERIDX > const T_CLUSTERIDX partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::next () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 58 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ui_iteratornext, and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx().
print()
template<class T_U , class T_CLUSTERIDX > virtual void partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 96 of file partition_fuzzy.hpp.
References partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ptmatrix_crisp, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumCluster(), and mat::MatrixBase< T_FEATURE >::getNumColumns().
Member Data Documentation
_ptmatrix_crisp
template<class T_U , class T_CLUSTERIDX > const mat::MatrixRow<T_U>* partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ptmatrix_crisp protected
Definition at line 125 of file partition_fuzzy.hpp.
Referenced by partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumCluster(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getNumInstances(), and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::print().
_ui_iteratornext
template<class T_U , class T_CLUSTERIDX > uintidx partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::_ui_iteratornext protected
Definition at line 126 of file partition_fuzzy.hpp.
Referenced by partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::begin(), and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::next().
The documentation for this class was generated from the following file:
include/partition_fuzzy.hpp