Library Evolutionary Algorithms for Clustering (LEAC): partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > Class Template Reference
partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > Class Template Reference
Partition of instances in base to following equation:
where , represents the medoid of cluster .
#include <partition_centroids.hpp>
Public Member Functions
PartitionCentroids ()
PartitionCentroids (mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numCluster, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
~PartitionCentroids ()
PartitionCentroids (const PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > &aipartcentroids_clustering)
PartitionCentroids (PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > &&aipartcentroids_clustering)
PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > & operator= (const PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > &aipartcentroids_clustering)
PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > & operator= (PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > &&aipartcentroids_clustering)
void begin ()
const T_CLUSTERIDX next ()
bool end () const
const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const
const uintidx getNumInstances () const
const T_CLUSTERIDX getNumCluster () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from partition::Partition< T_CLUSTERIDX >
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
Protected Attributes
mat::MatrixRow< T_FEATURE > * _ptmatrixt_centroids
const INPUT_ITERATOR _iterator_instfirst
const INPUT_ITERATOR _iterator_instlast
INPUT_ITERATOR _iterator_next
const dist::Dist< T_DIST, T_FEATURE > * _ptfunc2p_dist
Detailed Description
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR>
class partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >
Partition of instances in base to following equation:
where , represents the medoid of cluster .
Definition at line 48 of file partition_centroids.hpp.
Constructor & Destructor Documentation
PartitionCentroids() [1/4]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::PartitionCentroids () inline
Definition at line 53 of file partition_centroids.hpp.
PartitionCentroids() [2/4]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::PartitionCentroids (mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numCluster, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist) inline
Definition at line 60 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids.
~PartitionCentroids()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::~PartitionCentroids () inline
Definition at line 79 of file partition_centroids.hpp.
PartitionCentroids() [3/4]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::PartitionCentroids (const PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > & aipartcentroids_clustering) inline
Definition at line 82 of file partition_centroids.hpp.
PartitionCentroids() [4/4]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::PartitionCentroids (PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > && aipartcentroids_clustering) inline
Definition at line 93 of file partition_centroids.hpp.
Member Function Documentation
begin()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> void partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::begin () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 139 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst, and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print().
end()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> bool partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::end () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 169 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instlast, and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print().
getClusterIdx()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const T_CLUSTERIDX partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx (uintidx aiuintidx_instanceIdx) const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 175 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptfunc2p_dist, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids, data::Instance< T_FEATURE >::getFeatures(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumInstances(), and nearest::NN().
getNumCluster()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const T_CLUSTERIDX partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumCluster () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 209 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print().
getNumInstances()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const uintidx partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumInstances () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 204 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst, and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instlast.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print().
next()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const T_CLUSTERIDX partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 144 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptfunc2p_dist, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids, data::Instance< T_FEATURE >::getFeatures(), and nearest::NN().
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print().
operator=() [1/2]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> PartitionCentroids<T_FEATURE,T_CLUSTERIDX,T_DIST,INPUT_ITERATOR>& partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator= (const PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > & aipartcentroids_clustering) inline
Definition at line 106 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instlast, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptfunc2p_dist, and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids.
operator=() [2/2]
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> PartitionCentroids<T_FEATURE,T_CLUSTERIDX,T_DIST,INPUT_ITERATOR>& partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator= (PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > && aipartcentroids_clustering) inline
Definition at line 120 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instlast, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next, partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptfunc2p_dist, and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids.
print()
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> virtual void partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 215 of file partition_centroids.hpp.
References partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::begin(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::end(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumCluster(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumInstances(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next().
Member Data Documentation
_iterator_instfirst
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const INPUT_ITERATOR partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instfirst protected
Definition at line 243 of file partition_centroids.hpp.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::begin(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumInstances(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator=().
_iterator_instlast
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const INPUT_ITERATOR partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_instlast protected
Definition at line 244 of file partition_centroids.hpp.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::end(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumInstances(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator=().
_iterator_next
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> INPUT_ITERATOR partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_iterator_next protected
Definition at line 245 of file partition_centroids.hpp.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::begin(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::end(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator=().
_ptfunc2p_dist
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> const dist::Dist<T_DIST,T_FEATURE>* partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptfunc2p_dist protected
Definition at line 247 of file partition_centroids.hpp.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator=().
_ptmatrixt_centroids
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_DIST, typename INPUT_ITERATOR> mat::MatrixRow<T_FEATURE>* partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::_ptmatrixt_centroids protected
Definition at line 242 of file partition_centroids.hpp.
Referenced by partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getNumCluster(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::operator=(), and partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::PartitionCentroids().
The documentation for this class was generated from the following file:
include/partition_centroids.hpp