Library Evolutionary Algorithms for Clustering (LEAC): inout::LineSplit Class Reference
inout::LineSplit Class Reference
Used for processing files to read.
#include <line_split.hpp>
Public Member Functions
LineSplit ()
LineSplit (const std::string aistr_separator, std::string aistr_selectColumns)
~LineSplit ()
void setSeparator (const std::string &aistr_separator)
void getSelectColumns (std::string aistr_selectColumns)
uintidx split (std::string &str)
uintidx getNumSelectColumns ()
std::string & getItemSelect (uintidx aist_i)
std::string & getItem (uintidx aist_i)
void getVectorString (std::vector< std::string > &aovectorstr_item)
std::vector< std::string > & getVectorRawString ()
Protected Attributes
std::string _str_separator
std::vector< uintidx > _vectorst_selectColumns
std::vector< std::string > _vextorptc_columns
Detailed Description
Used for processing files to read.
Definition at line 38 of file line_split.hpp.
Constructor & Destructor Documentation
LineSplit() [1/2]
inout::LineSplit::LineSplit () inline
Definition at line 40 of file line_split.hpp.
LineSplit() [2/2]
inout::LineSplit::LineSplit (const std::string aistr_separator, std::string aistr_selectColumns) inline
Definition at line 47 of file line_split.hpp.
References getSelectColumns().
~LineSplit()
inout::LineSplit::~LineSplit () inline
Definition at line 57 of file line_split.hpp.
Member Function Documentation
getItem()
std::string& inout::LineSplit::getItem (uintidx aist_i) inline
Definition at line 153 of file line_split.hpp.
References _vextorptc_columns.
Referenced by inout::instancesReadDimName(), main(), mat::matrixread_get(), and mat::MatrixRow< T_METRIC >::r8mat_print().
getItemSelect()
std::string& inout::LineSplit::getItemSelect (uintidx aist_i) inline
Definition at line 148 of file line_split.hpp.
References _vectorst_selectColumns, and _vextorptc_columns.
Referenced by data::Instance< T_FEATURE >::readFeature().
getNumSelectColumns()
uintidx inout::LineSplit::getNumSelectColumns () inline
Definition at line 143 of file line_split.hpp.
References _vectorst_selectColumns.
Referenced by inout::instancesReadDimName().
getSelectColumns()
void inout::LineSplit::getSelectColumns (std::string aistr_selectColumns) inline
Definition at line 67 of file line_split.hpp.
References _vectorst_selectColumns.
Referenced by inout::instancesReadDimName(), and LineSplit().
getVectorRawString()
std::vector<std::string>& inout::LineSplit::getVectorRawString () inline
Definition at line 169 of file line_split.hpp.
References _vextorptc_columns.
Referenced by main().
getVectorString()
void inout::LineSplit::getVectorString (std::vector< std::string > & aovectorstr_item) inline
Definition at line 158 of file line_split.hpp.
References _vectorst_selectColumns, and _vextorptc_columns.
Referenced by inout::instancesReadDimName().
setSeparator()
void inout::LineSplit::setSeparator (const std::string & aistr_separator) inline
Definition at line 62 of file line_split.hpp.
References _str_separator.
Referenced by inout::instancesReadDimName(), and mat::MatrixRow< T_METRIC >::r8mat_print().
split()
uintidx inout::LineSplit::split (std::string & str) inline
Definition at line 108 of file line_split.hpp.
References _str_separator, _vectorst_selectColumns, _vextorptc_columns, inout::li_i, and inout::str().
Referenced by inout::instancesReadDimName(), main(), mat::matrixread_get(), and mat::MatrixRow< T_METRIC >::r8mat_print().
Member Data Documentation
_str_separator
std::string inout::LineSplit::_str_separator protected
Definition at line 176 of file line_split.hpp.
Referenced by setSeparator(), and split().
_vectorst_selectColumns
std::vector<uintidx> inout::LineSplit::_vectorst_selectColumns protected
Definition at line 177 of file line_split.hpp.
Referenced by getItemSelect(), getNumSelectColumns(), getSelectColumns(), getVectorString(), and split().
_vextorptc_columns
std::vector<std::string> inout::LineSplit::_vextorptc_columns protected
Definition at line 178 of file line_split.hpp.
Referenced by getItem(), getItemSelect(), getVectorRawString(), getVectorString(), and split().
The documentation for this class was generated from the following file:
include/line_split.hpp