Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamClusteringMaxIter Class Reference
inout::InParamClusteringMaxIter Class Reference
Input parameter for algorithm with iteration maximum.
#include <inparam_clustering_max_iter.hpp>
Public Member Functions
InParamClusteringMaxIter (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamClusteringMaxIter ()
void setNumMaxIter (COMMON_IDOMAIN aiiT_numMaxIter)
COMMON_IDOMAIN getNumMaxIter ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Public Member Functions inherited from inout::InParamClustering
InParamClustering (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opDistance)
~InParamClustering ()
char * getFileNamePlotStatObjetiveFunc () const
bool getWithPlotStatObjetiveFunc () const
void setFileNamePlotStatObjetiveFunc (char *aips_nameFile)
void setOutFileMemberShip (char *aips_fileName)
char * getOutFileMemberShip ()
void setRandomSeed (const std::string &aistr_randomSeed)
void setRandomSeed (const char *aipc_randomSeed)
const std::string & getRandomSeed () const
void setOutFilePartitionsTable (char *aips_fileName)
char * getOutFilePartitionsTable ()
void setOutFileCentroids (char *aips_fileName)
char * getOutFileCentroids ()
void setOpDistance (int aii_opDistance)
int getOpDistance ()
double getMaxExecutiontime ()
void setMaxExecutiontime (double aird_maxExecutiontime)
bool getPrintCentroidsFormat ()
void setPrintCentroidsFormat (bool aib_printCentroidsFormat)
bool getPrintTableFormat ()
void setPrintTableFormat (bool aib_printTableFormat)
void setOutFileGraph (char *aips_fileName)
char * getOutFileGraph ()
Public Member Functions inherited from inout::InParamAlgorithmo
InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut)
~InParamAlgorithmo ()
void errorArgument (char *apc_command, const char *apc_options, const char *aas_arguments[])
bool isYesNo (char *optarg, char *apc_command, const char *apc_options)
void setFileNameTimesRun (char *aips_nameFile)
void setProgressBarPrinting (bool aib_bool)
void setTimesRunAlgorithm (int aii_timesRun)
void setGnuPlotCoreStyles (const char *aips_nameCoreStyle)
std::string getAlgorithmoAuthor () const
std::string getAlgorithmoName () const
char * getFileNameTimesRun () const
int getTimesRunAlgorithm () const
bool getProgressBarPrinting ()
const std::string getGnuPlotCoreStyles () const
InParam_algTypeOut getAlgorithTypeOut ()
const std::string & getRunningTimeId ()
void setRunningTimeId (const std::string aistr_runTimeId)
Protected Attributes
COMMON_IDOMAIN iT_numMaxIter
Protected Attributes inherited from inout::InParamClustering
int i_opDistance
char * ps_outFileCentroids
char * ps_outFileMemberShip
char * ps_outFilePartitionsTable
char * ps_outFileGraph
char * ps_fileNamePlotStatObjetiveFunc
std::string _str_randomSeed
double _rd_maxExecutiontime
bool _b_printCentroidsFormat
bool _b_printTableFormat
Protected Attributes inherited from inout::InParamAlgorithmo
std::string s_algorithmoName
std::string s_algorithmoAuthor
InParam_algTypeOut ato_algTypeOut
char * ps_fileNameTimesRun
bool b_progressBarPrinting
int i_timesRunAlgorithm
std::string _s_runTimeId
std::string s_gnuplotCoreStyles
Detailed Description
Input parameter for algorithm with iteration maximum.
Definition at line 30 of file inparam_clustering_max_iter.hpp.
Constructor & Destructor Documentation
InParamClusteringMaxIter()
inout::InParamClusteringMaxIter::InParamClusteringMaxIter (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm) inline
Definition at line 35 of file inparam_clustering_max_iter.hpp.
~InParamClusteringMaxIter()
inout::InParamClusteringMaxIter::~InParamClusteringMaxIter () inline
Definition at line 46 of file inparam_clustering_max_iter.hpp.
Member Function Documentation
getNumMaxIter()
COMMON_IDOMAIN inout::InParamClusteringMaxIter::getNumMaxIter () inline
Definition at line 53 of file inparam_clustering_max_iter.hpp.
References iT_numMaxIter.
print()
virtual void inout::InParamClusteringMaxIter::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented from inout::InParamClustering.
Reimplemented in inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, and inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >.
Definition at line 58 of file inparam_clustering_max_iter.hpp.
References iT_numMaxIter, and inout::InParamClustering::print().
Referenced by inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
setNumMaxIter()
void inout::InParamClusteringMaxIter::setNumMaxIter (COMMON_IDOMAIN aiiT_numMaxIter) inline
Definition at line 48 of file inparam_clustering_max_iter.hpp.
References iT_numMaxIter.
Member Data Documentation
iT_numMaxIter
COMMON_IDOMAIN inout::InParamClusteringMaxIter::iT_numMaxIter protected
Definition at line 66 of file inparam_clustering_max_iter.hpp.
Referenced by getNumMaxIter(), print(), and setNumMaxIter().
The documentation for this class was generated from the following file:
include_inout/inparam_clustering_max_iter.hpp