Library Evolutionary Algorithms for Clustering (LEAC): ds::PartitionLinked< T_CLUSTERIDX > Class Template Reference
ds::PartitionLinked< T_CLUSTERIDX > Class Template Reference
Data structure to define the instances that belong to a cluster consecutively.
#include <partition_linked.hpp>
Public Member Functions
PartitionLinked ()
PartitionLinked (const uintidx aiui_numInstances, const uintidx aiui_numClusterK)
PartitionLinked (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
~PartitionLinked ()
void resize (const uintidx aiui_numClusterK)
const T_CLUSTERIDX getNumPartitions () const
const uintidx getFirstInstClusterK (T_CLUSTERIDX aicidx_clusterK)
const uintidx getNumInstances () const
PartitionLinked< T_CLUSTERIDX > & operator= (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked< T_CLUSTERIDX > & operator= (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
void initialize ()
void addInstanceToCluster (T_CLUSTERIDX aiT_clusterIdx, uintidx aiidxiT_instanceI)
void subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI)
void changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI)
uintidx getInstanceIdxOfClusterK (T_CLUSTERIDX aicidx_clusterK, const uintidx aiuintidx_instanceNi)
void joinCluster (const T_CLUSTERIDX aiIdxK_clusterKFrom, const T_CLUSTERIDX aiIdxK_clusterKTo)
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimClusterK=';')
Protected Attributes
std::vector< uintidx > _vectorInstIdx_firstClusterK
std::vector< uintidx > _vectorInstIdx_nextClusterK
Friends
class IteratorPartitionLinked< T_CLUSTERIDX >
Detailed Description
template<typename T_CLUSTERIDX>
class ds::PartitionLinked< T_CLUSTERIDX >
Data structure to define the instances that belong to a cluster consecutively.
Definition at line 42 of file partition_linked.hpp.
Constructor & Destructor Documentation
PartitionLinked() [1/4]
template<typename T_CLUSTERIDX> ds::PartitionLinked< T_CLUSTERIDX >::PartitionLinked () inline
Definition at line 44 of file partition_linked.hpp.
PartitionLinked() [2/4]
template<typename T_CLUSTERIDX> ds::PartitionLinked< T_CLUSTERIDX >::PartitionLinked (const uintidx aiui_numInstances, const uintidx aiui_numClusterK) inline
Definition at line 50 of file partition_linked.hpp.
PartitionLinked() [3/4]
template<typename T_CLUSTERIDX> ds::PartitionLinked< T_CLUSTERIDX >::PartitionLinked (const PartitionLinked< T_CLUSTERIDX > & aipartlink_b) inline
Definition at line 58 of file partition_linked.hpp.
PartitionLinked() [4/4]
template<typename T_CLUSTERIDX> ds::PartitionLinked< T_CLUSTERIDX >::PartitionLinked (PartitionLinked< T_CLUSTERIDX > && aipartlink_b) inline
Definition at line 65 of file partition_linked.hpp.
~PartitionLinked()
template<typename T_CLUSTERIDX> ds::PartitionLinked< T_CLUSTERIDX >::~PartitionLinked () inline
Definition at line 71 of file partition_linked.hpp.
Member Function Documentation
addInstanceToCluster()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster (T_CLUSTERIDX aiT_clusterIdx, uintidx aiidxiT_instanceI) inline
Definition at line 219 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, and ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK.
Referenced by ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), and ds::PartitionLinked< T_CLUSTERIDX >::changeMemberShip().
changeMemberShip()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI) inline
Definition at line 263 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster(), NEARESTCENTROID_UNKNOWN, and ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster().
getFirstInstClusterK()
template<typename T_CLUSTERIDX> const uintidx ds::PartitionLinked< T_CLUSTERIDX >::getFirstInstClusterK (T_CLUSTERIDX aicidx_clusterK) inline
Definition at line 89 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK.
getInstanceIdxOfClusterK()
template<typename T_CLUSTERIDX> uintidx ds::PartitionLinked< T_CLUSTERIDX >::getInstanceIdxOfClusterK (T_CLUSTERIDX aicidx_clusterK, const uintidx aiuintidx_instanceNi) inline
Definition at line 277 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, and UINTIDX_NIL.
getNumInstances()
template<typename T_CLUSTERIDX> const uintidx ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances () const inline
Definition at line 94 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::initialize(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), and um::silhouette().
getNumPartitions()
template<typename T_CLUSTERIDX> const T_CLUSTERIDX ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions () const inline
Definition at line 84 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK.
Referenced by um::diameterClusterK(), um::distMinIntraClusterKj(), um::DunnIndex(), ds::PartitionLinked< T_CLUSTERIDX >::print(), um::silhouette(), and um::simplifiedDunnIndex().
initialize()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::initialize () inline
Definition at line 203 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, interfacesse::copya(), and UINTIDX_NIL.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::initialize(), and ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::initialize().
joinCluster()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::joinCluster (const T_CLUSTERIDX aiIdxK_clusterKFrom, const T_CLUSTERIDX aiIdxK_clusterKTo) inline
Definition at line 294 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, and UINTIDX_NIL.
operator=() [1/2]
template<typename T_CLUSTERIDX> PartitionLinked<T_CLUSTERIDX>& ds::PartitionLinked< T_CLUSTERIDX >::operator= (const PartitionLinked< T_CLUSTERIDX > & aipartlink_b) inline
Definition at line 101 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, interfacesse::copy(), and ds::PartitionLinked< T_CLUSTERIDX >::print().
Referenced by ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::operator=(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=().
operator=() [2/2]
template<typename T_CLUSTERIDX> PartitionLinked<T_CLUSTERIDX>& ds::PartitionLinked< T_CLUSTERIDX >::operator= (PartitionLinked< T_CLUSTERIDX > && aipartlink_b) inline
Definition at line 163 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, and ds::PartitionLinked< T_CLUSTERIDX >::print().
print()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimClusterK = ';') inline
Definition at line 316 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions().
Referenced by ds::PartitionLinked< T_CLUSTERIDX >::operator=(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::print(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print().
resize()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::resize (const uintidx aiui_numClusterK) inline
Definition at line 74 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, and UINTIDX_NIL.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize().
subInstanceFromCluster()
template<typename T_CLUSTERIDX> void ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI) inline
Definition at line 229 of file partition_linked.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK, ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK, NEARESTCENTROID_UNKNOWN, and UINTIDX_NIL.
Referenced by ds::PartitionLinked< T_CLUSTERIDX >::changeMemberShip(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::subInstanceFromCluster(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster().
Friends And Related Function Documentation
IteratorPartitionLinked< T_CLUSTERIDX >
template<typename T_CLUSTERIDX> friend class IteratorPartitionLinked< T_CLUSTERIDX > friend
Definition at line 351 of file partition_linked.hpp.
Member Data Documentation
_vectorInstIdx_firstClusterK
template<typename T_CLUSTERIDX> std::vector<uintidx> ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_firstClusterK protected
Definition at line 348 of file partition_linked.hpp.
Referenced by ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster(), ds::PartitionLinked< T_CLUSTERIDX >::getFirstInstClusterK(), ds::PartitionLinked< T_CLUSTERIDX >::getInstanceIdxOfClusterK(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::PartitionLinked< T_CLUSTERIDX >::initialize(), ds::PartitionLinked< T_CLUSTERIDX >::joinCluster(), ds::PartitionLinked< T_CLUSTERIDX >::operator=(), ds::PartitionLinked< T_CLUSTERIDX >::resize(), and ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster().
_vectorInstIdx_nextClusterK
template<typename T_CLUSTERIDX> std::vector<uintidx> ds::PartitionLinked< T_CLUSTERIDX >::_vectorInstIdx_nextClusterK protected
Definition at line 349 of file partition_linked.hpp.
Referenced by ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster(), ds::PartitionLinked< T_CLUSTERIDX >::getInstanceIdxOfClusterK(), ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances(), ds::PartitionLinked< T_CLUSTERIDX >::initialize(), ds::PartitionLinked< T_CLUSTERIDX >::joinCluster(), ds::PartitionLinked< T_CLUSTERIDX >::operator=(), and ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster().
The documentation for this class was generated from the following file:
include/partition_linked.hpp