Library Evolutionary Algorithms for Clustering (LEAC): ds::IteratorPartitionLinked< T_CLUSTERIDX > Class Template Reference
ds::IteratorPartitionLinked< T_CLUSTERIDX > Class Template Reference
An iterator for a PartitionLinked.
#include <partition_linked.hpp>
Public Member Functions
IteratorPartitionLinked (const PartitionLinked< T_CLUSTERIDX > *aippartl_partitionLinked)
~IteratorPartitionLinked ()
void begin (T_CLUSTERIDX aicidx_clusterK)
void next ()
bool end ()
uintidx getValue ()
Protected Attributes
const PartitionLinked< T_CLUSTERIDX > * _ppartl_partitionLinked
uintidx _uintidx_instI
Detailed Description
template<typename T_CLUSTERIDX>
class ds::IteratorPartitionLinked< T_CLUSTERIDX >
An iterator for a PartitionLinked.
Definition at line 35 of file partition_linked.hpp.
Constructor & Destructor Documentation
IteratorPartitionLinked()
template<typename T_CLUSTERIDX> ds::IteratorPartitionLinked< T_CLUSTERIDX >::IteratorPartitionLinked (const PartitionLinked< T_CLUSTERIDX > * aippartl_partitionLinked) inline
Definition at line 364 of file partition_linked.hpp.
~IteratorPartitionLinked()
template<typename T_CLUSTERIDX> ds::IteratorPartitionLinked< T_CLUSTERIDX >::~IteratorPartitionLinked () inline
Definition at line 369 of file partition_linked.hpp.
Member Function Documentation
begin()
template<typename T_CLUSTERIDX> void ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin (T_CLUSTERIDX aicidx_clusterK) inline
Definition at line 372 of file partition_linked.hpp.
Referenced by clusteringop::computeCostInstanceClusterJ(), gaclusteringop::crossoverCGA(), um::diameterClusterKj(), um::distMinIntraClusterKj(), um::DunnIndex(), clusteringop::joinPartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), um::radiusClusterKj(), um::silhouette(), and clusteringop::updateMedoids().
end()
template<typename T_CLUSTERIDX> bool ds::IteratorPartitionLinked< T_CLUSTERIDX >::end () inline
Definition at line 384 of file partition_linked.hpp.
Referenced by clusteringop::computeCostInstanceClusterJ(), gaclusteringop::crossoverCGA(), um::diameterClusterKj(), um::distMinIntraClusterKj(), um::DunnIndex(), clusteringop::joinPartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), um::radiusClusterKj(), um::silhouette(), and clusteringop::updateMedoids().
getValue()
template<typename T_CLUSTERIDX> uintidx ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue () inline
Definition at line 389 of file partition_linked.hpp.
Referenced by clusteringop::computeCostInstanceClusterJ(), gaclusteringop::crossoverCGA(), um::diameterClusterKj(), um::distMinIntraClusterKj(), um::DunnIndex(), clusteringop::joinPartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), um::radiusClusterKj(), um::silhouette(), and clusteringop::updateMedoids().
next()
template<typename T_CLUSTERIDX> void ds::IteratorPartitionLinked< T_CLUSTERIDX >::next () inline
Definition at line 378 of file partition_linked.hpp.
Referenced by clusteringop::computeCostInstanceClusterJ(), gaclusteringop::crossoverCGA(), um::diameterClusterKj(), um::distMinIntraClusterKj(), um::DunnIndex(), clusteringop::joinPartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), um::radiusClusterKj(), um::silhouette(), and clusteringop::updateMedoids().
Member Data Documentation
_ppartl_partitionLinked
template<typename T_CLUSTERIDX> const PartitionLinked<T_CLUSTERIDX>* ds::IteratorPartitionLinked< T_CLUSTERIDX >::_ppartl_partitionLinked protected
Definition at line 395 of file partition_linked.hpp.
_uintidx_instI
template<typename T_CLUSTERIDX> uintidx ds::IteratorPartitionLinked< T_CLUSTERIDX >::_uintidx_instI protected
Definition at line 396 of file partition_linked.hpp.
The documentation for this class was generated from the following file:
include/partition_linked.hpp