Library Evolutionary Algorithms for Clustering (LEAC): mat::MatrixWithRowNull< T > Class Template Reference
mat::MatrixWithRowNull< T > Class Template Reference
MatrixWithRowNull.
#include <matrix_withrownull.hpp>
Public Member Functions
MatrixWithRowNull ()
MatrixWithRowNull (const uintidx aiui_numRows, const uintidx aiui_numRowsMax, const uintidx aiui_numColumns)
MatrixWithRowNull (const mat::MatrixWithRowNull< T > &aimatrixwrownull_b)
MatrixWithRowNull (mat::MatrixWithRowNull< T > &&aimatrixwrownull_b)
~MatrixWithRowNull ()
mat::MatrixRow< T > getMatrix ()
void setMatrix (const mat::MatrixRow< T > &aimatrix_B)
void combination (uintidx aiui_numrow, mat::MatrixWithRowNull< T > &aimatrixwrownull_b)
T * getRow (uintidx i)
const T * getRow (uintidx i) const
void copyRow (const uintidx aiui_idxRow, const T *aiT_row)
const uintidx getNumRowsMax () const
T ** toArray ()
mat::MatrixWithRowNull< T > & operator= (const mat::MatrixWithRowNull< T > &aimatrixwrownull_b)
mat::MatrixWithRowNull< T > & operator= (mat::MatrixWithRowNull< T > &&aimatrixwrownull_b)
void keepRows (std::vector< uintidx > &aivectorT_idxRow)
void addRow (const T *aiT_row)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef='\t', const char aic_delimRow='\n') const
Public Member Functions inherited from mat::MatrixBase< T >
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T > &&B)
MatrixBase (const MatrixBase< T > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
MatrixBase< T > & operator= (const MatrixBase< T > &B)
MatrixBase< T > & operator= (MatrixBase< T > &&B)
Protected Attributes
uintidx _ui_numRowsMax
T ** _arrayt_row
Protected Attributes inherited from mat::MatrixBase< T >
uintidx _ui_numRows
uintidx _ui_numColumns
Friends
std::ostream & operator<< (std::ostream &os, const mat::MatrixWithRowNull< T > &aimatrixwrownull_a)
Additional Inherited Members
Protected Member Functions inherited from mat::MatrixBase< T >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Detailed Description
template<class T>
class mat::MatrixWithRowNull< T >
MatrixWithRowNull.
Definition at line 41 of file matrix_withrownull.hpp.
Constructor & Destructor Documentation
MatrixWithRowNull() [1/4]
template<class T> mat::MatrixWithRowNull< T >::MatrixWithRowNull () inline
Definition at line 45 of file matrix_withrownull.hpp.
MatrixWithRowNull() [2/4]
template<class T> mat::MatrixWithRowNull< T >::MatrixWithRowNull (const uintidx aiui_numRows, const uintidx aiui_numRowsMax, const uintidx aiui_numColumns) inline
Definition at line 52 of file matrix_withrownull.hpp.
MatrixWithRowNull() [3/4]
template<class T> mat::MatrixWithRowNull< T >::MatrixWithRowNull (const mat::MatrixWithRowNull< T > & aimatrixwrownull_b) inline
Definition at line 68 of file matrix_withrownull.hpp.
MatrixWithRowNull() [4/4]
template<class T> mat::MatrixWithRowNull< T >::MatrixWithRowNull (mat::MatrixWithRowNull< T > && aimatrixwrownull_b) inline
Definition at line 89 of file matrix_withrownull.hpp.
~MatrixWithRowNull()
template<class T> mat::MatrixWithRowNull< T >::~MatrixWithRowNull () inline
Definition at line 101 of file matrix_withrownull.hpp.
Member Function Documentation
addRow()
template<class T> void mat::MatrixWithRowNull< T >::addRow (const T * aiT_row) inline
Definition at line 310 of file matrix_withrownull.hpp.
Referenced by gaclusteringop::MO2().
combination()
template<class T> void mat::MatrixWithRowNull< T >::combination (uintidx aiui_numrow, mat::MatrixWithRowNull< T > & aimatrixwrownull_b) inline
Definition at line 153 of file matrix_withrownull.hpp.
copyRow()
template<class T> void mat::MatrixWithRowNull< T >::copyRow (const uintidx aiui_idxRow, const T * aiT_row) inline
Definition at line 181 of file matrix_withrownull.hpp.
Referenced by gaclusteringop::MO2().
getMatrix()
template<class T> mat::MatrixRow<T> mat::MatrixWithRowNull< T >::getMatrix () inline
Definition at line 112 of file matrix_withrownull.hpp.
getNumRowsMax()
template<class T> const uintidx mat::MatrixWithRowNull< T >::getNumRowsMax () const inline
Definition at line 187 of file matrix_withrownull.hpp.
getRow() [1/2]
template<class T> T* mat::MatrixWithRowNull< T >::getRow (uintidx i) inline virtual
Implements mat::MatrixBase< T >.
Definition at line 171 of file matrix_withrownull.hpp.
Referenced by gaclusteringop::kmeansfeac(), and gaclusteringop::MO1().
getRow() [2/2]
template<class T> const T* mat::MatrixWithRowNull< T >::getRow (uintidx i) const inline virtual
Implements mat::MatrixBase< T >.
Definition at line 176 of file matrix_withrownull.hpp.
keepRows()
template<class T> void mat::MatrixWithRowNull< T >::keepRows (std::vector< uintidx > & aivectorT_idxRow) inline
Definition at line 255 of file matrix_withrownull.hpp.
Referenced by gaclusteringop::kmeansfeac(), and gaclusteringop::MO1().
operator=() [1/2]
template<class T> mat::MatrixWithRowNull<T>& mat::MatrixWithRowNull< T >::operator= (const mat::MatrixWithRowNull< T > & aimatrixwrownull_b) inline
Definition at line 197 of file matrix_withrownull.hpp.
Referenced by gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::operator=().
operator=() [2/2]
template<class T> mat::MatrixWithRowNull<T>& mat::MatrixWithRowNull< T >::operator= (mat::MatrixWithRowNull< T > && aimatrixwrownull_b) inline
Definition at line 228 of file matrix_withrownull.hpp.
print()
template<class T> virtual void mat::MatrixWithRowNull< T >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = '\t', const char aic_delimRow = '\n') const inline virtual
Implements mat::MatrixBase< T >.
Reimplemented in gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >.
Definition at line 373 of file matrix_withrownull.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), mat::MatrixWithRowNull< T_GENE >::keepRows(), gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
setMatrix()
template<class T> void mat::MatrixWithRowNull< T >::setMatrix (const mat::MatrixRow< T > & aimatrix_B) inline
Definition at line 131 of file matrix_withrownull.hpp.
toArray()
template<class T> T** mat::MatrixWithRowNull< T >::toArray () inline
Definition at line 192 of file matrix_withrownull.hpp.
Friends And Related Function Documentation
operator<<
template<class T> std::ostream& operator<< (std::ostream & os, const mat::MatrixWithRowNull< T > & aimatrixwrownull_a) friend
Definition at line 416 of file matrix_withrownull.hpp.
Member Data Documentation
_arrayt_row
template<class T> T** mat::MatrixWithRowNull< T >::_arrayt_row protected
Definition at line 426 of file matrix_withrownull.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), mat::MatrixWithRowNull< T_GENE >::combination(), mat::MatrixWithRowNull< T_GENE >::copyRow(), mat::MatrixWithRowNull< T_GENE >::getMatrix(), mat::MatrixWithRowNull< T_GENE >::getRow(), mat::MatrixWithRowNull< T_GENE >::keepRows(), mat::MatrixWithRowNull< T_GENE >::MatrixWithRowNull(), mat::MatrixWithRowNull< T_GENE >::operator=(), mat::MatrixWithRowNull< T_GENE >::print(), mat::MatrixWithRowNull< T_GENE >::setMatrix(), mat::MatrixWithRowNull< T_GENE >::toArray(), and mat::MatrixWithRowNull< T_GENE >::~MatrixWithRowNull().
_ui_numRowsMax
template<class T> uintidx mat::MatrixWithRowNull< T >::_ui_numRowsMax protected
Definition at line 425 of file matrix_withrownull.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), mat::MatrixWithRowNull< T_GENE >::combination(), mat::MatrixWithRowNull< T_GENE >::getMatrix(), mat::MatrixWithRowNull< T_GENE >::getNumRowsMax(), mat::MatrixWithRowNull< T_GENE >::keepRows(), mat::MatrixWithRowNull< T_GENE >::MatrixWithRowNull(), mat::MatrixWithRowNull< T_GENE >::operator=(), mat::MatrixWithRowNull< T_GENE >::print(), mat::MatrixWithRowNull< T_GENE >::setMatrix(), and mat::MatrixWithRowNull< T_GENE >::~MatrixWithRowNull().
The documentation for this class was generated from the following file:
include/matrix_withrownull.hpp