Library Evolutionary Algorithms for Clustering (LEAC): inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX > Class Template Reference
inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX > Class Template Reference
Output parameter for Kmeans Algorithmo [31].
#include <outparam_kmeans.hpp>
Public Member Functions
OutParamKmeans (const OutParamNameObjectiveFunc aienum_usedObjectiveFunc)
virtual ~OutParamKmeans ()
void initialize (int aii_numRunAlgorithm)
void setNumThreshold (uintidx aist_numThreshold)
uintidx & getNumThreshold ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Public Member Functions inherited from inout::OutParamClustering< T_METRIC, T_MEMBERCLUSTER_IDX >
OutParamClustering (const OutParamNameObjectiveFunc aienum_usedObjectiveFunc)
virtual ~OutParamClustering ()
void initialize (int aii_numRunAlgorithm)
void setRunTimeGetsBest (runtime::ExecutionTime aiet_runTimeGetsBest)
void setIterationGetsBest (COMMON_IDOMAIN aiit_iterationGetsBest)
runtime::ExecutionTime getRunTimeGetsBest ()
COMMON_IDOMAIN getIterationGetsBest ()
void setTotalInvalidOffspring (long ail_totalInvalidOffspring)
void incTotalInvalidOffspring ()
void sumTotalInvalidOffspring (long ail_invalidOffspring)
long getTotalInvalidOffspring ()
void setMetricFuncRun (T_METRIC ait_objetiveFuncRun)
const T_METRIC getObjetiveFuncRun () const
const OutParamNameObjectiveFunc getUsedObjetiveFunc ()
const std::string getNameUsedObjetiveFunc ()
void setFileNameOutPlotStatObjetiveFunc (const char *aipstr_fileNamePlot, const int aii_timesRunAlgorithm)
void setFileNameOutPlotStatObjetiveFunc (const char *aipstr_fileNamePlot, const int aii_timesRunAlgorithm, const std::string &aistr_prefix)
const std::string getFileNameOutPlotStatObjetiveFunc ()
void setNumClusterK (T_MEMBERCLUSTER_IDX aiidxK_numClusterK)
const T_MEMBERCLUSTER_IDX getNumClusterK ()
void setNumClusterKTest (T_MEMBERCLUSTER_IDX aiidxK_numClusterKTest)
const T_MEMBERCLUSTER_IDX getNumClusterKTest ()
Public Member Functions inherited from inout::OutParamAlgorithm
OutParamAlgorithm ()
virtual ~OutParamAlgorithm ()
void initialize (int aii_numRunAlgorithm)
void setAlgorithmRunTime (runtime::ExecutionTime aiet_algorithmRunTime)
runtime::ExecutionTime getAlgorithmRunTime ()
const int getNumRunningAlgorithm ()
void setEndingCondition (const bool aib_endingCondition)
void setEndingConditionTest (const bool aib_endingCondition)
void setRuntimeMessage (const std::string ais_runtimeMessage)
const bool getEndingCondition ()
const bool getEndingConditionTest ()
const std::string & getRuntimeMessage ()
Protected Attributes
uintidx _uintidx_numThreshold
Protected Attributes inherited from inout::OutParamClustering< T_METRIC, T_MEMBERCLUSTER_IDX >
OutParamNameObjectiveFunc _enum_usedObjectiveFunc
T_METRIC _rt_objetiveFuncRun
COMMON_IDOMAIN _it_iterationGetsBest
runtime::ExecutionTime et_runTimeGetsBest
T_MEMBERCLUSTER_IDX _idxK_numClusterK
T_MEMBERCLUSTER_IDX _idxK_numClusterKTest
std::string s_fileNameOutPlotStatObjetiveFunc
long _l_totalInvalidOffspring
Protected Attributes inherited from inout::OutParamAlgorithm
int i_numRunAlgorithm
runtime::ExecutionTime et_algorithmRunTime
bool _b_endingCondition
bool _b_endingConditionTest
std::string _s_runtimeMessage
Detailed Description
template<typename T_METRIC, typename T_MEMBERCLUSTER_IDX>
class inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >
Output parameter for Kmeans Algorithmo [31].
Definition at line 35 of file outparam_kmeans.hpp.
Constructor & Destructor Documentation
OutParamKmeans()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::OutParamKmeans (const OutParamNameObjectiveFunc aienum_usedObjectiveFunc) inline
Definition at line 38 of file outparam_kmeans.hpp.
References inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::initialize().
~OutParamKmeans()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > virtual inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::~OutParamKmeans () inline virtual
Definition at line 45 of file outparam_kmeans.hpp.
Member Function Documentation
getNumThreshold()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > uintidx& inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::getNumThreshold () inline
Definition at line 59 of file outparam_kmeans.hpp.
References inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::_uintidx_numThreshold.
initialize()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > void inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::initialize (int aii_numRunAlgorithm) inline
Definition at line 47 of file outparam_kmeans.hpp.
References inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::_uintidx_numThreshold, inout::OutParamClustering< T_METRIC, T_CLUSTERIDX >::initialize(), and OUTPARAMCLUSTERING_INT_NaN.
Referenced by inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::OutParamKmeans().
print()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > virtual void inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented from inout::OutParamClustering< T_METRIC, T_MEMBERCLUSTER_IDX >.
Definition at line 64 of file outparam_kmeans.hpp.
References inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::_uintidx_numThreshold, and inout::OutParamClustering< T_METRIC, T_CLUSTERIDX >::print().
setNumThreshold()
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > void inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::setNumThreshold (uintidx aist_numThreshold) inline
Definition at line 54 of file outparam_kmeans.hpp.
References inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::_uintidx_numThreshold.
Member Data Documentation
_uintidx_numThreshold
template<typename T_METRIC , typename T_MEMBERCLUSTER_IDX > uintidx inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::_uintidx_numThreshold protected
Definition at line 72 of file outparam_kmeans.hpp.
Referenced by inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::getNumThreshold(), inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::initialize(), inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::print(), and inout::OutParamKmeans< T_METRIC, T_MEMBERCLUSTER_IDX >::setNumThreshold().
The documentation for this class was generated from the following file:
include_inout/outparam_kmeans.hpp