Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeString< T_GENE, T_METRIC > Class Template Reference
gaencode::ChromosomeString< T_GENE, T_METRIC > Class Template Reference abstract
Chhromosome String define Chromosome encode for an string.
#include <chromosome_string.hpp>
Public Member Functions
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_GENE, T_METRIC > & operator= (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
ChromosomeString< T_GENE, T_METRIC > & operator= (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
virtual const uintidx getStringSize () const =0
virtual void setString (T_GENE *aips_string)=0
virtual T_GENE * getString ()=0
virtual const T_GENE * getString () const =0
virtual const T_GENE getGene (const uintidx aiuintidx_idxGene) const =0
virtual void setGene (uintidx aiuintidx_idxGene, T_GENE aiT_newGene)=0
virtual T_GENE * begin ()=0
virtual T_GENE * end ()=0
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Additional Inherited Members
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Detailed Description
template<class T_GENE, class T_METRIC>
class gaencode::ChromosomeString< T_GENE, T_METRIC >
Chhromosome String define Chromosome encode for an string.
Definition at line 43 of file chromosome_string.hpp.
Constructor & Destructor Documentation
ChromosomeString() [1/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeString< T_GENE, T_METRIC >::ChromosomeString () inline
Definition at line 49 of file chromosome_string.hpp.
ChromosomeString() [2/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeString< T_GENE, T_METRIC >::ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness) inline
Definition at line 54 of file chromosome_string.hpp.
ChromosomeString() [3/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeString< T_GENE, T_METRIC >::ChromosomeString (ChromosomeString< T_GENE, T_METRIC > && aichrom_b) inline
Definition at line 59 of file chromosome_string.hpp.
ChromosomeString() [4/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeString< T_GENE, T_METRIC >::ChromosomeString (const ChromosomeString< T_GENE, T_METRIC > & aichrom_b) inline
Definition at line 65 of file chromosome_string.hpp.
~ChromosomeString()
template<class T_GENE, class T_METRIC> virtual gaencode::ChromosomeString< T_GENE, T_METRIC >::~ChromosomeString () inline virtual
Definition at line 69 of file chromosome_string.hpp.
Member Function Documentation
begin()
template<class T_GENE, class T_METRIC> virtual T_GENE* gaencode::ChromosomeString< T_GENE, T_METRIC >::begin () pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by gaintegerop::mutationD_PM().
end()
template<class T_GENE, class T_METRIC> virtual T_GENE* gaencode::ChromosomeString< T_GENE, T_METRIC >::end () pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by gaintegerop::mutationD_PM().
getGene()
template<class T_GENE, class T_METRIC> virtual const T_GENE gaencode::ChromosomeString< T_GENE, T_METRIC >::getGene (const uintidx aiuintidx_idxGene) const pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by gaintegerop::mutation().
getString() [1/2]
template<class T_GENE, class T_METRIC> virtual T_GENE* gaencode::ChromosomeString< T_GENE, T_METRIC >::getString () pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by garealop::averageCrossover(), gaclusteringop::biDirectionHMutation(), gaclusteringop::biDirectionMutation(), garealop::BLXalphaCrossover(), garealop::heuristicCrossover(), gaintegerop::isNotValid(), gaintegerop::labelKeep(), garealop::muhlenbeinMutation(), gaintegerop::oneChangelabel(), gaclusteringop::rearrangedCluster(), and gaintegerop::recombinationD_MX().
getString() [2/2]
template<class T_GENE, class T_METRIC> virtual const T_GENE* gaencode::ChromosomeString< T_GENE, T_METRIC >::getString () const pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
getStringSize()
template<class T_GENE, class T_METRIC> virtual const uintidx gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize () const pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by garealop::averageCrossover(), gaclusteringop::biDirectionHMutation(), gaclusteringop::biDirectionMutation(), garealop::BLXalphaCrossover(), garealop::heuristicCrossover(), gaintegerop::isNotValid(), gaintegerop::labelKeep(), garealop::muhlenbeinMutation(), gaintegerop::mutationD_PM(), gaintegerop::oneChangelabel(), and gaintegerop::recombinationD_MX().
operator=() [1/2]
template<class T_GENE, class T_METRIC> ChromosomeString<T_GENE,T_METRIC>& gaencode::ChromosomeString< T_GENE, T_METRIC >::operator= (const ChromosomeString< T_GENE, T_METRIC > & aichrom_b) inline
Definition at line 73 of file chromosome_string.hpp.
Referenced by gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::operator=(), and gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator=().
operator=() [2/2]
template<class T_GENE, class T_METRIC> ChromosomeString<T_GENE,T_METRIC>& gaencode::ChromosomeString< T_GENE, T_METRIC >::operator= (ChromosomeString< T_GENE, T_METRIC > && aichrom_b) inline
Definition at line 83 of file chromosome_string.hpp.
setGene()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromosomeString< T_GENE, T_METRIC >::setGene (uintidx aiuintidx_idxGene, T_GENE aiT_newGene) pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Referenced by gaintegerop::mutation(), and gaintegerop::mutationD_PM().
setString()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromosomeString< T_GENE, T_METRIC >::setString (T_GENE * aips_string) pure virtual
Implemented in gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
The documentation for this class was generated from the following file:
include/chromosome_string.hpp