Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeBase< T_METRIC > Class Template Reference
gaencode::ChromosomeBase< T_METRIC > Class Template Reference
Chromosome Base define basic attributes for a chromosome.
#include <chromosome_base.hpp>
Public Member Functions
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Protected Attributes
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Friends
std::ostream & operator<< (std::ostream &os, const ChromosomeBase< T_METRIC > &aich_chromosome)
Detailed Description
template<class T_METRIC>
class gaencode::ChromosomeBase< T_METRIC >
Chromosome Base define basic attributes for a chromosome.
Definition at line 36 of file chromosome_base.hpp.
Constructor & Destructor Documentation
ChromosomeBase() [1/4]
template<class T_METRIC> gaencode::ChromosomeBase< T_METRIC >::ChromosomeBase () inline
Definition at line 39 of file chromosome_base.hpp.
ChromosomeBase() [2/4]
template<class T_METRIC> gaencode::ChromosomeBase< T_METRIC >::ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness) inline
Definition at line 45 of file chromosome_base.hpp.
ChromosomeBase() [3/4]
template<class T_METRIC> gaencode::ChromosomeBase< T_METRIC >::ChromosomeBase (ChromosomeBase< T_METRIC > && aich_chromosome) inline
Definition at line 53 of file chromosome_base.hpp.
ChromosomeBase() [4/4]
template<class T_METRIC> gaencode::ChromosomeBase< T_METRIC >::ChromosomeBase (const ChromosomeBase< T_METRIC > & aich_chromosome) inline
Definition at line 62 of file chromosome_base.hpp.
~ChromosomeBase()
template<class T_METRIC> virtual gaencode::ChromosomeBase< T_METRIC >::~ChromosomeBase () inline virtual
Definition at line 69 of file chromosome_base.hpp.
Member Function Documentation
getFitness()
template<class T_METRIC> const T_METRIC gaencode::ChromosomeBase< T_METRIC >::getFitness () const inline
Definition at line 119 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_t_fitness.
Referenced by garealop::averageCrossover(), garealop::BLXalphaCrossover(), eac::cga_vklabel(), eac::clustering_genetic(), eac::clustering_vksubclusterbinary(), eac::feca_vklabel(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), garealop::heuristicCrossover(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), gagenericop::pathCrossover(), and eac::tgca_vkcentroid().
getObjetiveFunc()
template<class T_METRIC> const T_METRIC gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc () const inline
Definition at line 113 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
Referenced by gaclusteringop::biDirectionHMutation(), eac::cga_vklabel(), eac::clustering_vksubclusterbinary(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), eac::kga_fkcentroid(), gagenericop::pathCrossover(), and eac::tgca_vkcentroid().
getValidString()
template<class T_METRIC> const bool gaencode::ChromosomeBase< T_METRIC >::getValidString () const inline
Definition at line 103 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_b_stringInvalid.
Referenced by eac::kga_fkcentroid(), and gagenericop::pathCrossover().
operator=() [1/2]
template<class T_METRIC> ChromosomeBase<T_METRIC>& gaencode::ChromosomeBase< T_METRIC >::operator= (const ChromosomeBase< T_METRIC > & aich_chromosome) inline
Definition at line 74 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_b_stringInvalid, gaencode::ChromosomeBase< T_METRIC >::_t_fitness, and gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
Referenced by gaencode::ChromosomeString< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::operator=(), and gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::operator=().
operator=() [2/2]
template<class T_METRIC> ChromosomeBase<T_METRIC>& gaencode::ChromosomeBase< T_METRIC >::operator= (ChromosomeBase< T_METRIC > && aich_chromosome) inline
Definition at line 86 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_b_stringInvalid, gaencode::ChromosomeBase< T_METRIC >::_t_fitness, and gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
print()
template<class T_METRIC> virtual void gaencode::ChromosomeBase< T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented in gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, gaencode::ChromVariableLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_GENE, T_METRIC >, gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >, gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >, and gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >.
Definition at line 131 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_t_fitness, and gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
Referenced by garealop::averageCrossover(), gaclusteringop::biDirectionHMutation(), gaclusteringop::biDirectionMutation(), garealop::BLXalphaCrossover(), garealop::heuristicCrossover(), gaintegerop::labelKeep(), gaintegerop::mutation(), gaintegerop::mutationD_PM(), gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::print(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::print(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::print(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), gaclusteringop::rearrangedCluster(), and gaintegerop::recombinationD_MX().
setFitness()
template<class T_METRIC> void gaencode::ChromosomeBase< T_METRIC >::setFitness (T_METRIC ait_fitness) inline
Definition at line 124 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_t_fitness.
Referenced by garealop::averageCrossover(), garealop::BLXalphaCrossover(), eac::cga_vklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gga_vklabel(), garealop::heuristicCrossover(), eac::kga_fkcentroid(), gaclusteringop::newChromosome(), gaclusteringop::onePointCrossover(), gagenericop::pathCrossover(), and eac::tgca_vkcentroid().
setObjetiveFunc()
template<class T_METRIC> void gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc (T_METRIC ait_objetiveFunc) inline
Definition at line 108 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
Referenced by garealop::averageCrossover(), garealop::BLXalphaCrossover(), eac::cga_vklabel(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gga_vklabel(), garealop::heuristicCrossover(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), eac::kga_fkcentroid(), gaclusteringop::newChromosome(), gaclusteringop::onePointCrossover(), gagenericop::pathCrossover(), and eac::tgca_vkcentroid().
setValidString()
template<class T_METRIC> void gaencode::ChromosomeBase< T_METRIC >::setValidString (bool aib_stringInvalid) inline
Definition at line 98 of file chromosome_base.hpp.
References gaencode::ChromosomeBase< T_METRIC >::_b_stringInvalid.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), eac::kga_fkcentroid(), and gagenericop::pathCrossover().
Friends And Related Function Documentation
operator<<
template<class T_METRIC> std::ostream& operator<< (std::ostream & os, const ChromosomeBase< T_METRIC > & aich_chromosome) friend
Definition at line 155 of file chromosome_base.hpp.
Member Data Documentation
_b_stringInvalid
template<class T_METRIC> bool gaencode::ChromosomeBase< T_METRIC >::_b_stringInvalid protected
an bool for check is valid chromosome
Definition at line 164 of file chromosome_base.hpp.
Referenced by gaencode::ChromosomeBase< T_METRIC >::getValidString(), gaencode::ChromosomeBase< T_METRIC >::operator=(), and gaencode::ChromosomeBase< T_METRIC >::setValidString().
_t_fitness
template<class T_METRIC> T_METRIC gaencode::ChromosomeBase< T_METRIC >::_t_fitness protected
an real number for chromosome fitness
Definition at line 166 of file chromosome_base.hpp.
Referenced by gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaencode::ChromosomeBase< T_METRIC >::operator=(), gaencode::ChromosomeBase< T_METRIC >::print(), and gaencode::ChromosomeBase< T_METRIC >::setFitness().
_t_objetiveFunc
template<class T_METRIC> T_METRIC gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc protected
an real number for objetive function of solution
Definition at line 165 of file chromosome_base.hpp.
Referenced by gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gaencode::ChromosomeBase< T_METRIC >::operator=(), gaencode::ChromosomeBase< T_METRIC >::print(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::saveLastObjetiveFunc(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
The documentation for this class was generated from the following file:
include/chromosome_base.hpp