Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > Class Template Reference
gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > Class Template Reference
Chromosome encoding two parts.
#include <chromosome_gga.hpp>
Public Member Functions
ChromosomeGGA ()
ChromosomeGGA (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeGGA (const uintidx aiuintidx_groupSecSize)
ChromosomeGGA (ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromosomeGGA (const ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromosomeGGA ()
void initializeGroupSec ()
ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & operator= (const ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & operator= (ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
const T_CLUSTERIDX getNumClusterK () const
const uintidx getGroupSecSize () const
void increaseGroupSecSize ()
void decrementGroupSecSize (uintidx aiuintidx_decrement)
void setGroupSecString (T_CLUSTERIDX *aips_string)
T_CLUSTERIDX * getGroupSecString ()
const T_CLUSTERIDX * getGroupSecString () const
void deleteGroupNull (T_CLUSTERIDX aicidx_k)
bool isValid () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
ChromFixedLength ()
ChromFixedLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromFixedLength (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromFixedLength (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromFixedLength ()
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
virtual const uintidx getStringSize () const
virtual void setString (T_CLUSTERIDX *aips_string)
virtual T_CLUSTERIDX * getString ()
virtual const T_CLUSTERIDX * getString () const
T_CLUSTERIDX * begin ()
T_CLUSTERIDX * end ()
virtual const T_CLUSTERIDX getGene (const uintidx aiuintidx_idxGene) const
virtual void setGene (uintidx aiuintidx_idxGene, T_CLUSTERIDX ait_newGene)
Public Member Functions inherited from gaencode::ChromosomeString< T_CLUSTERIDX, T_METRIC >
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Static Public Member Functions
static void setElementSize (uintidx aiuintidx_elementSize)
static const uintidx getElementSize ()
Static Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static void setStringSize (uintidx aiuintidx_stringSize)
static const uintidx stcgetStringSize ()
Protected Attributes
uintidx _uintidx_groupSecCapacity
T_CLUSTERIDX * _pts_groupSecString
uintidx _uintidx_groupSecSize
Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
T_CLUSTERIDX * _pts_string
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Additional Inherited Members
Static Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static uintidx _stcui_stringSize
Detailed Description
template<class T_CLUSTERIDX, class T_METRIC>
class gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >
Chromosome encoding two parts.
The encoding is carried out by separating each individual two parts: c = [l|g], the first part is the element section, whereas the second part is called the group section of the individual [1]
Definition at line 41 of file chromosome_gga.hpp.
Constructor & Destructor Documentation
ChromosomeGGA() [1/5]
template<class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA () inline
Definition at line 45 of file chromosome_gga.hpp.
ChromosomeGGA() [2/5]
template<class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness) inline
Definition at line 54 of file chromosome_gga.hpp.
ChromosomeGGA() [3/5]
template<class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA (const uintidx aiuintidx_groupSecSize) inline
Definition at line 62 of file chromosome_gga.hpp.
ChromosomeGGA() [4/5]
template<class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA (ChromosomeGGA< T_CLUSTERIDX, T_METRIC > && aichrom_b) inline
Definition at line 70 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print().
ChromosomeGGA() [5/5]
template<class T_CLUSTERIDX, class T_METRIC> gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA (const ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & aichrom_b) inline
Definition at line 105 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, and interfacesse::copy().
~ChromosomeGGA()
template<class T_CLUSTERIDX, class T_METRIC> virtual gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::~ChromosomeGGA () inline virtual
Definition at line 117 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString.
Member Function Documentation
decrementGroupSecSize()
template<class T_CLUSTERIDX, class T_METRIC> void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize (uintidx aiuintidx_decrement) inline
Definition at line 281 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize.
Referenced by gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::deleteGroupNull(), eac::gga_vklabel(), gaclusteringop::mergeCrossover(), and gaclusteringop::mergeMutation().
deleteGroupNull()
template<class T_CLUSTERIDX, class T_METRIC> void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::deleteGroupNull (T_CLUSTERIDX aicidx_k) inline
Definition at line 305 of file chromosome_gga.hpp.
References gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::_stcui_stringSize, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize(), and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString().
Referenced by eac::gga_vklabel().
getElementSize()
template<class T_CLUSTERIDX, class T_METRIC> static const uintidx gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize () inline static
Definition at line 142 of file chromosome_gga.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize().
Referenced by eac::gga_vklabel(), gaclusteringop::mergeCrossover(), gaclusteringop::mergeMutation(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), and gaclusteringop::splittingMutation().
getGroupSecSize()
template<class T_CLUSTERIDX, class T_METRIC> const uintidx gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getGroupSecSize () const inline
Definition at line 261 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize.
getGroupSecString() [1/2]
template<class T_CLUSTERIDX, class T_METRIC> T_CLUSTERIDX* gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getGroupSecString () inline
Definition at line 295 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString.
getGroupSecString() [2/2]
template<class T_CLUSTERIDX, class T_METRIC> const T_CLUSTERIDX* gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getGroupSecString () const inline
Definition at line 300 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString.
getNumClusterK()
template<class T_CLUSTERIDX, class T_METRIC> const T_CLUSTERIDX gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK () const inline
Definition at line 254 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, and assert_msg.
Referenced by eac::gga_vklabel(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::isValid(), gaclusteringop::mergeCrossover(), gaclusteringop::mergeMutation(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), and gaclusteringop::splittingMutation().
increaseGroupSecSize()
template<class T_CLUSTERIDX, class T_METRIC> void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize () inline
Definition at line 266 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec().
Referenced by gaclusteringop::splittingMutation().
initializeGroupSec()
template<class T_CLUSTERIDX, class T_METRIC> void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec () inline
Definition at line 148 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize.
Referenced by eac::gga_vklabel(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize(), and gaclusteringop::mergeCrossover().
isValid()
template<class T_CLUSTERIDX, class T_METRIC> bool gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::isValid () const inline
Definition at line 319 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::_stcui_stringSize, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString().
Referenced by eac::gga_vklabel().
operator=() [1/2]
template<class T_CLUSTERIDX, class T_METRIC> ChromosomeGGA<T_CLUSTERIDX,T_METRIC>& gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator= (const ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & aichrom_b) inline
Definition at line 158 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, interfacesse::copy(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print().
operator=() [2/2]
template<class T_CLUSTERIDX, class T_METRIC> ChromosomeGGA<T_CLUSTERIDX,T_METRIC>& gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator= (ChromosomeGGA< T_CLUSTERIDX, T_METRIC > && aichrom_b) inline
Definition at line 210 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print().
print()
template<class T_CLUSTERIDX, class T_METRIC> virtual void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Definition at line 358 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::_pts_string, gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::_stcui_stringSize, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA(), eac::gga_vklabel(), gaclusteringop::mergeCrossover(), gaclusteringop::mergeMutation(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), and gaclusteringop::splittingMutation().
setElementSize()
template<class T_CLUSTERIDX, class T_METRIC> static void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setElementSize (uintidx aiuintidx_elementSize) inline static
Definition at line 136 of file chromosome_gga.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize().
Referenced by eac::gga_vklabel().
setGroupSecString()
template<class T_CLUSTERIDX, class T_METRIC> void gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setGroupSecString (T_CLUSTERIDX * aips_string) inline
Definition at line 286 of file chromosome_gga.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize, and interfacesse::copy().
Member Data Documentation
_pts_groupSecString
template<class T_CLUSTERIDX, class T_METRIC> T_CLUSTERIDX* gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_pts_groupSecString protected
Definition at line 397 of file chromosome_gga.hpp.
Referenced by gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getGroupSecString(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::isValid(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setGroupSecString(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::~ChromosomeGGA().
_uintidx_groupSecCapacity
template<class T_CLUSTERIDX, class T_METRIC> uintidx gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecCapacity protected
Definition at line 396 of file chromosome_gga.hpp.
Referenced by gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print().
_uintidx_groupSecSize
template<class T_CLUSTERIDX, class T_METRIC> uintidx gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::_uintidx_groupSecSize protected
Definition at line 398 of file chromosome_gga.hpp.
Referenced by gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::isValid(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setGroupSecString().
The documentation for this class was generated from the following file:
include/chromosome_gga.hpp