Library Evolutionary Algorithms for Clustering (LEAC): mat::MatrixTriang< T_FEATURE > Class Template Reference
mat::MatrixTriang< T_FEATURE > Class Template Reference
MatrixTriang.
#include <matrix_triangular.hpp>
Public Member Functions
MatrixTriang ()
MatrixTriang (const uintidx aiuintidx_numRows)
MatrixTriang (const MatrixTriang< T_FEATURE > &B)
MatrixTriang (MatrixTriang< T_FEATURE > &&B)
~MatrixTriang ()
MatrixRow< T_FEATURE > & operator= (const MatrixRow< T_FEATURE > &B)
MatrixRow< T_FEATURE > & operator= (MatrixRow< T_FEATURE > &&B)
const uintidx getNumRows () const
T_FEATURE & operator() (uintidx i, uintidx j)
T_FEATURE operator() (uintidx i, uintidx j) const
const T_FEATURE * getRow (const uintidx i) const
T_FEATURE * getRow (const uintidx i)
void print (std::ostream &os=std::cout, const char aic_delimCoef=',', const char aic_delimRow='\n') const
Protected Attributes
uintidx _ui_numRows
T_FEATURE ** _t_data
Friends
std::ostream & operator<< (std::ostream &os, const mat::MatrixTriang< T_FEATURE > &aimatrix_a)
Detailed Description
template<class T_FEATURE>
class mat::MatrixTriang< T_FEATURE >
MatrixTriang.
Definition at line 37 of file matrix_triangular.hpp.
Constructor & Destructor Documentation
MatrixTriang() [1/4]
template<class T_FEATURE> mat::MatrixTriang< T_FEATURE >::MatrixTriang () inline
Definition at line 40 of file matrix_triangular.hpp.
MatrixTriang() [2/4]
template<class T_FEATURE> mat::MatrixTriang< T_FEATURE >::MatrixTriang (const uintidx aiuintidx_numRows) inline
Definition at line 45 of file matrix_triangular.hpp.
MatrixTriang() [3/4]
template<class T_FEATURE> mat::MatrixTriang< T_FEATURE >::MatrixTriang (const MatrixTriang< T_FEATURE > & B) inline
Definition at line 55 of file matrix_triangular.hpp.
MatrixTriang() [4/4]
template<class T_FEATURE> mat::MatrixTriang< T_FEATURE >::MatrixTriang (MatrixTriang< T_FEATURE > && B) inline
Definition at line 66 of file matrix_triangular.hpp.
~MatrixTriang()
template<class T_FEATURE> mat::MatrixTriang< T_FEATURE >::~MatrixTriang () inline
Definition at line 74 of file matrix_triangular.hpp.
Member Function Documentation
getNumRows()
template<class T_FEATURE> const uintidx mat::MatrixTriang< T_FEATURE >::getNumRows () const inline
Definition at line 128 of file matrix_triangular.hpp.
Referenced by clusteringop::computeTotalCostSwap(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::end(), eac::gca_fkmedoid(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumInstances(), mat::MatrixTriang< T_DIST >::getRow(), eac::hka_fkmedoid(), clusteringop::nearestRepresentative(), mat::MatrixTriang< T_DIST >::operator()(), graph::prim(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print(), um::SSEMedoid(), and clusteringop::updateMedoids().
getRow() [1/2]
template<class T_FEATURE> const T_FEATURE* mat::MatrixTriang< T_FEATURE >::getRow (const uintidx i) const inline
Definition at line 145 of file matrix_triangular.hpp.
getRow() [2/2]
template<class T_FEATURE> T_FEATURE* mat::MatrixTriang< T_FEATURE >::getRow (const uintidx i) inline
Definition at line 151 of file matrix_triangular.hpp.
operator()() [1/2]
template<class T_FEATURE> T_FEATURE& mat::MatrixTriang< T_FEATURE >::operator() (uintidx i, uintidx j) inline
Definition at line 133 of file matrix_triangular.hpp.
operator()() [2/2]
template<class T_FEATURE> T_FEATURE mat::MatrixTriang< T_FEATURE >::operator() (uintidx i, uintidx j) const inline
Definition at line 139 of file matrix_triangular.hpp.
operator=() [1/2]
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixTriang< T_FEATURE >::operator= (const MatrixRow< T_FEATURE > & B) inline
Definition at line 84 of file matrix_triangular.hpp.
operator=() [2/2]
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixTriang< T_FEATURE >::operator= (MatrixRow< T_FEATURE > && B) inline
Definition at line 108 of file matrix_triangular.hpp.
print()
template<class T_FEATURE> void mat::MatrixTriang< T_FEATURE >::print (std::ostream & os = std::cout, const char aic_delimCoef = ',', const char aic_delimRow = '\n') const inline
Definition at line 159 of file matrix_triangular.hpp.
Referenced by dist::getMatrixDissimilarity().
Friends And Related Function Documentation
operator<<
template<class T_FEATURE> std::ostream& operator<< (std::ostream & os, const mat::MatrixTriang< T_FEATURE > & aimatrix_a) friend
Definition at line 173 of file matrix_triangular.hpp.
Member Data Documentation
_t_data
template<class T_FEATURE> T_FEATURE** mat::MatrixTriang< T_FEATURE >::_t_data protected
Definition at line 182 of file matrix_triangular.hpp.
Referenced by mat::MatrixTriang< T_DIST >::getRow(), mat::MatrixTriang< T_DIST >::MatrixTriang(), mat::MatrixTriang< T_DIST >::operator()(), mat::MatrixTriang< T_DIST >::operator=(), mat::MatrixTriang< T_DIST >::print(), and mat::MatrixTriang< T_DIST >::~MatrixTriang().
_ui_numRows
template<class T_FEATURE> uintidx mat::MatrixTriang< T_FEATURE >::_ui_numRows protected
Definition at line 181 of file matrix_triangular.hpp.
Referenced by mat::MatrixTriang< T_DIST >::getNumRows(), mat::MatrixTriang< T_DIST >::MatrixTriang(), mat::MatrixTriang< T_DIST >::operator=(), mat::MatrixTriang< T_DIST >::print(), and mat::MatrixTriang< T_DIST >::~MatrixTriang().
The documentation for this class was generated from the following file:
include/matrix_triangular.hpp