Library Evolutionary Algorithms for Clustering (LEAC): data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > Class Template Reference
Patterns, usually vectors in a multidimensional space, previamente clasificado.
#include <instance_class.hpp>
Public Member Functions
InstanceClass ()
InstanceClass (const InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstclass_b)
InstanceClass (InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstclass_b)
virtual ~InstanceClass ()
InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (const InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstclass_b)
InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstclass_b)
virtual void print (std::ostream &os=std::cout, const char aic_delim='\t') const
virtual std::string getToString (const char aic_delim='\t')
Public Member Functions inherited from data::Instance< T_FEATURE >
Instance ()
Instance (T_FEATURE *aiarrayt_feature)
Instance (const Instance< T_FEATURE > &aiinst_b)
Instance (Instance< T_FEATURE > &&aiinst_b)
virtual ~Instance ()
Instance< T_FEATURE > & operator= (const Instance< T_FEATURE > &aiinst_b)
Instance< T_FEATURE > & operator= (Instance< T_FEATURE > &&aiinst_b)
const T_FEATURE * getFeatures () const
T_FEATURE * getFeatures ()
const T_FEATURE getAttribute (uintidx aui_idxAttribute) const
void readFeature (inout::LineSplit &ails_linesplit)
void setId (const std::string &aistr_id)
const char * getId () const
Public Member Functions inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
InstanceIterfazClass ()
InstanceIterfazClass (const InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstiterclass_b)
InstanceIterfazClass (InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstiterclass_b)
virtual ~InstanceIterfazClass ()
InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (const InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiinstiterclass_b)
InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & operator= (InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &&aiinstiterclass_b)
void setClassIdx (std::string &aistr_keyMapClass)
T_CLUSTERIDX getClassIdx ()
Additional Inherited Members
Public Types inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
typedef std::map< const std::string, CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > > MapClassLabel
Static Public Member Functions inherited from data::Instance< T_FEATURE >
static void setNumDimensions (uintidx aiuintidx_numDimensions)
static uintidx getNumDimensions ()
static void setHomogeneousCoord (bool aib_homogeneousCoord)
static bool getHomogeneousCoord ()
static T_FEATURE type ()
static T_FEATURE getInfiniteFeature ()
static bool isInfiniteFeature (T_FEATURE aiT_feacture)
Static Public Member Functions inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
static void initialize ()
static void setVectorClassLabel ()
static const std::vector< CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > * > & getVectorClassLabel ()
static std::vector< std::string > getLabelClass (uintidx aiui_numClass)
Protected Attributes inherited from data::Instance< T_FEATURE >
char * _ptc_id
T_FEATURE * _arrayt_feature
Protected Attributes inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
T_CLUSTERIDX _cidx_classIdx
Static Protected Attributes inherited from data::Instance< T_FEATURE >
static uintidx _stcuintidx_numDimensions = 0
static bool _stcb_homogeneousCoord = false
Static Protected Attributes inherited from data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
static MapClassLabel _stmap_instanceClass
static T_CLUSTERIDX _idxmcT_consecutiveClass = 0
static std::vector< CountLabel< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > * > _stcvector_classLabel
Detailed Description
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX>
class data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
Patterns, usually vectors in a multidimensional space, previamente clasificado.
Definition at line 35 of file instance_class.hpp.
Constructor & Destructor Documentation
InstanceClass() [1/3]
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClass () inline
Definition at line 40 of file instance_class.hpp.
InstanceClass() [2/3]
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClass (const InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiinstclass_b) inline
Definition at line 47 of file instance_class.hpp.
InstanceClass() [3/3]
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::InstanceClass (InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > && aiinstclass_b) inline
Definition at line 54 of file instance_class.hpp.
~InstanceClass()
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::~InstanceClass () inline virtual
Definition at line 60 of file instance_class.hpp.
Member Function Documentation
getToString()
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual std::string data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getToString (const char aic_delim = '\t') inline virtual
Reimplemented from data::Instance< T_FEATURE >.
Definition at line 93 of file instance_class.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_cidx_classIdx, and data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::_stcvector_classLabel.
operator=() [1/2]
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> InstanceClass<T_FEATURE,T_INSTANCES_CLUSTER_K,T_CLUSTERIDX>& data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator= (const InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiinstclass_b) inline
Definition at line 63 of file instance_class.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=(), and data::Instance< T_FEATURE >::operator=().
operator=() [2/2]
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> InstanceClass<T_FEATURE,T_INSTANCES_CLUSTER_K,T_CLUSTERIDX>& data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator= (InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > && aiinstclass_b) inline
Definition at line 74 of file instance_class.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=(), and data::Instance< T_FEATURE >::operator=().
print()
template<class T_FEATURE, class T_INSTANCES_CLUSTER_K, class T_CLUSTERIDX> virtual void data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char aic_delim = '\t') const inline virtual
Reimplemented from data::Instance< T_FEATURE >.
Definition at line 86 of file instance_class.hpp.
References data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and data::Instance< T_FEATURE >::print().
The documentation for this class was generated from the following file:
include/instance_class.hpp