Library Evolutionary Algorithms for Clustering (LEAC): data::Instance< T_FEATURE > Class Template Reference
data::Instance< T_FEATURE > Class Template Reference
Patterns, usually vectors in a multidimensional space.
#include <instance.hpp>
Public Member Functions
Instance ()
Instance (T_FEATURE *aiarrayt_feature)
Instance (const Instance< T_FEATURE > &aiinst_b)
Instance (Instance< T_FEATURE > &&aiinst_b)
virtual ~Instance ()
Instance< T_FEATURE > & operator= (const Instance< T_FEATURE > &aiinst_b)
Instance< T_FEATURE > & operator= (Instance< T_FEATURE > &&aiinst_b)
const T_FEATURE * getFeatures () const
T_FEATURE * getFeatures ()
const T_FEATURE getAttribute (uintidx aui_idxAttribute) const
void readFeature (inout::LineSplit &ails_linesplit)
void setId (const std::string &aistr_id)
const char * getId () const
virtual std::string getToString (const char aic_delim='\t')
virtual void print (std::ostream &os=std::cout, const char aic_delim='\t') const
Static Public Member Functions
static void setNumDimensions (uintidx aiuintidx_numDimensions)
static uintidx getNumDimensions ()
static void setHomogeneousCoord (bool aib_homogeneousCoord)
static bool getHomogeneousCoord ()
static T_FEATURE type ()
static T_FEATURE getInfiniteFeature ()
static bool isInfiniteFeature (T_FEATURE aiT_feacture)
Protected Attributes
char * _ptc_id
T_FEATURE * _arrayt_feature
Static Protected Attributes
static uintidx _stcuintidx_numDimensions = 0
static bool _stcb_homogeneousCoord = false
Friends
std::ostream & operator<< (std::ostream &os, const Instance< T_FEATURE > &aiinst_instance)
Detailed Description
template<class T_FEATURE>
class data::Instance< T_FEATURE >
Patterns, usually vectors in a multidimensional space.
Definition at line 37 of file instance.hpp.
Constructor & Destructor Documentation
Instance() [1/4]
template<class T_FEATURE> data::Instance< T_FEATURE >::Instance () inline
Definition at line 41 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_stcb_homogeneousCoord, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Instance() [2/4]
template<class T_FEATURE> data::Instance< T_FEATURE >::Instance (T_FEATURE * aiarrayt_feature) inline
Definition at line 50 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Instance() [3/4]
template<class T_FEATURE> data::Instance< T_FEATURE >::Instance (const Instance< T_FEATURE > & aiinst_b) inline
Definition at line 62 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_ptc_id, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Instance() [4/4]
template<class T_FEATURE> data::Instance< T_FEATURE >::Instance (Instance< T_FEATURE > && aiinst_b) inline
Definition at line 78 of file instance.hpp.
~Instance()
template<class T_FEATURE> virtual data::Instance< T_FEATURE >::~Instance () inline virtual
Definition at line 86 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, and data::Instance< T_FEATURE >::_ptc_id.
Member Function Documentation
getAttribute()
template<class T_FEATURE> const T_FEATURE data::Instance< T_FEATURE >::getAttribute (uintidx aui_idxAttribute) const inline
Definition at line 201 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature.
Referenced by eac::tgca_vkcentroid().
getFeatures() [1/2]
template<class T_FEATURE> const T_FEATURE* data::Instance< T_FEATURE >::getFeatures () const inline
Definition at line 191 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), um::avgRadiusClusterK(), um::D2(), um::diameterClusterKj(), um::distMinIntraClusterKj(), um::distortion(), um::e1(), clusteringop::fillEmptyPartitions(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), um::indexI(), um::indexIreeval(), clusteringop::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), um::j1(), um::jm(), clusteringop::joinPartition(), main(), stats::maxFeatures(), um::maxRadiusClusterK(), stats::minFeatures(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next(), um::radiusClusterKj(), clusteringop::randomInitialize(), clusteringop::reassignCluster(), clusteringop::setUpCuster(), um::silhouette(), um::simplifiedSilhouette(), um::SSE(), um::sumDistInstCentInK(), stats::sumFeactures(), stats::sumFeacturesFreq(), stats::sumFeacturesFreqSQ(), stats::sumFeacturesSQ(), data::toMatrixRowTrans(), and um::xb().
getFeatures() [2/2]
template<class T_FEATURE> T_FEATURE* data::Instance< T_FEATURE >::getFeatures () inline
Definition at line 196 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature.
getHomogeneousCoord()
template<class T_FEATURE> static bool data::Instance< T_FEATURE >::getHomogeneousCoord () inline static
Definition at line 155 of file instance.hpp.
References data::Instance< T_FEATURE >::_stcb_homogeneousCoord.
getId()
template<class T_FEATURE> const char* data::Instance< T_FEATURE >::getId () const inline
Definition at line 237 of file instance.hpp.
References data::Instance< T_FEATURE >::_ptc_id.
Referenced by main().
getInfiniteFeature()
template<class T_FEATURE> static T_FEATURE data::Instance< T_FEATURE >::getInfiniteFeature () inline static
Definition at line 167 of file instance.hpp.
Referenced by gaclusteringop::kmeansfeac().
getNumDimensions()
template<class T_FEATURE> static uintidx data::Instance< T_FEATURE >::getNumDimensions () inline static
Definition at line 145 of file instance.hpp.
References data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), um::avgRadiusClusterK(), gaclusteringop::biDirectionHMutation(), gaclusteringop::biDirectionMutation(), eac::cbga_fkcentroid(), eac::clustering_vksubclusterbinary(), gaclusteringop::crossoverCGA(), um::D2(), um::diameterClusterKj(), um::Dinter(), um::Dintra(), um::distMinIntraClusterKj(), um::e1(), nearest::farthestInstanceFromS1(), clusteringop::fillEmptyPartitions(), eac::gaclustering_fklabel(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gcuk_vkcentroid(), graph::getAdjacencyMatrix(), clusteringop::getClusters(), eac::gga_vklabel(), eac::gka_fklabel(), eac::igka_fklabel(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), um::indexI(), um::indexIreeval(), clusteringop::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), um::j1(), um::jm(), eac::kga_fkcentroid(), gaclusteringop::kmeansfeac(), main(), stats::maxFeatures(), um::maxRadiusClusterK(), stats::minFeatures(), gaclusteringop::MO1(), gaintegerop::mutationgka(), graph::nearestNeighbor(), gaclusteringop::newChromosome(), um::radiusClusterKj(), clusteringop::randomInitialize(), gaclusteringop::rearrangedCluster(), um::scoreFunction(), um::scoreFunctionreeval(), um::silhouette(), um::simplifiedSilhouette(), um::ssbreeval(), um::SSE(), um::sumDistInstCentInK(), stats::sumFeactures(), stats::sumFeacturesFreq(), eac::tgca_vkcentroid(), stats::transform(), um::VRC(), um::VRCreeval(), um::WBIndex(), um::WBIndexreeval(), and um::xb().
getToString()
template<class T_FEATURE> virtual std::string data::Instance< T_FEATURE >::getToString (const char aic_delim = '\t') inline virtual
Reimplemented in data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >, data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, data::InstanceWeightClass< T_FEATURE, T_WEIGHT, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, and data::InstanceWeight< T_FEATURE, T_WEIGHT >.
Definition at line 250 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_ptc_id, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
isInfiniteFeature()
template<class T_FEATURE> static bool data::Instance< T_FEATURE >::isInfiniteFeature (T_FEATURE aiT_feacture) inline static
Definition at line 172 of file instance.hpp.
Referenced by nearest::checkNullCentroidsNN().
operator=() [1/2]
template<class T_FEATURE> Instance<T_FEATURE>& data::Instance< T_FEATURE >::operator= (const Instance< T_FEATURE > & aiinst_b) inline
Definition at line 96 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_ptc_id, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Referenced by data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::operator=(), and data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::operator=().
operator=() [2/2]
template<class T_FEATURE> Instance<T_FEATURE>& data::Instance< T_FEATURE >::operator= (Instance< T_FEATURE > && aiinst_b) inline
Definition at line 120 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, and data::Instance< T_FEATURE >::_ptc_id.
print()
template<class T_FEATURE> virtual void data::Instance< T_FEATURE >::print (std::ostream & os = std::cout, const char aic_delim = '\t') const inline virtual
Reimplemented in data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >, data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, data::InstanceClassFreq< T_FEATURE, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, data::InstanceWeight< T_FEATURE, T_WEIGHT >, and data::InstanceWeightClass< T_FEATURE, T_WEIGHT, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >.
Definition at line 266 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_ptc_id, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Referenced by data::InstanceWeight< T_FEATURE, T_WEIGHT >::print(), data::InstanceClass< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), and data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::print().
readFeature()
template<class T_FEATURE> void data::Instance< T_FEATURE >::readFeature (inout::LineSplit & ails_linesplit) inline
Definition at line 206 of file instance.hpp.
References data::Instance< T_FEATURE >::_arrayt_feature, data::Instance< T_FEATURE >::_stcb_homogeneousCoord, data::Instance< T_FEATURE >::_stcuintidx_numDimensions, and inout::LineSplit::getItemSelect().
Referenced by inout::instancesRead(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), and inout::instancesReadWithFreqClass().
setHomogeneousCoord()
template<class T_FEATURE> static void data::Instance< T_FEATURE >::setHomogeneousCoord (bool aib_homogeneousCoord) inline static
Definition at line 150 of file instance.hpp.
References data::Instance< T_FEATURE >::_stcb_homogeneousCoord.
Referenced by main().
setId()
template<class T_FEATURE> void data::Instance< T_FEATURE >::setId (const std::string & aistr_id) inline
Definition at line 223 of file instance.hpp.
References data::Instance< T_FEATURE >::_ptc_id.
setNumDimensions()
template<class T_FEATURE> static void data::Instance< T_FEATURE >::setNumDimensions (uintidx aiuintidx_numDimensions) inline static
Definition at line 139 of file instance.hpp.
References data::Instance< T_FEATURE >::_stcb_homogeneousCoord, and data::Instance< T_FEATURE >::_stcuintidx_numDimensions.
Referenced by inout::instancesRead(), inout::instancesReadWithClass(), inout::instancesReadWithFreq(), and inout::instancesReadWithFreqClass().
type()
template<class T_FEATURE> static T_FEATURE data::Instance< T_FEATURE >::type () inline static
Definition at line 160 of file instance.hpp.
Friends And Related Function Documentation
operator<<
template<class T_FEATURE> std::ostream& operator<< (std::ostream & os, const Instance< T_FEATURE > & aiinst_instance) friend
Definition at line 242 of file instance.hpp.
Member Data Documentation
_arrayt_feature
template<class T_FEATURE> T_FEATURE* data::Instance< T_FEATURE >::_arrayt_feature protected
Definition at line 280 of file instance.hpp.
Referenced by data::Instance< T_FEATURE >::getAttribute(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getToString(), data::Instance< T_FEATURE >::Instance(), data::Instance< T_FEATURE >::operator=(), data::Instance< T_FEATURE >::print(), data::Instance< T_FEATURE >::readFeature(), and data::Instance< T_FEATURE >::~Instance().
_ptc_id
template<class T_FEATURE> char* data::Instance< T_FEATURE >::_ptc_id protected
Definition at line 279 of file instance.hpp.
Referenced by data::Instance< T_FEATURE >::getId(), data::Instance< T_FEATURE >::getToString(), data::Instance< T_FEATURE >::Instance(), data::Instance< T_FEATURE >::operator=(), data::Instance< T_FEATURE >::print(), data::Instance< T_FEATURE >::setId(), and data::Instance< T_FEATURE >::~Instance().
_stcb_homogeneousCoord
template<class T_FEATURE> bool data::Instance< T_FEATURE >::_stcb_homogeneousCoord = false static protected
Definition at line 282 of file instance.hpp.
Referenced by data::Instance< T_FEATURE >::getHomogeneousCoord(), data::Instance< T_FEATURE >::Instance(), data::Instance< T_FEATURE >::readFeature(), data::Instance< T_FEATURE >::setHomogeneousCoord(), and data::Instance< T_FEATURE >::setNumDimensions().
_stcuintidx_numDimensions
template<class T_FEATURE> uintidx data::Instance< T_FEATURE >::_stcuintidx_numDimensions = 0 static protected
Definition at line 281 of file instance.hpp.
Referenced by data::Instance< T_FEATURE >::getNumDimensions(), data::Instance< T_FEATURE >::getToString(), data::Instance< T_FEATURE >::Instance(), data::Instance< T_FEATURE >::operator=(), data::Instance< T_FEATURE >::print(), data::Instance< T_FEATURE >::readFeature(), and data::Instance< T_FEATURE >::setNumDimensions().
The documentation for this class was generated from the following file:
include/instance.hpp