Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > Class Template Reference
gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > Class Template Reference
Matrix with row null chromosome.
#include <chromosome_withrownull.hpp>
Public Member Functions
ChromosomeMatrixWithRowNull ()
ChromosomeMatrixWithRowNull (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numRowsMax, const uintidx aiuintidx_numColumns)
ChromosomeMatrixWithRowNull (const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &aichromwrn_b)
ChromosomeMatrixWithRowNull (ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &&aichromwrn_b)
virtual ~ChromosomeMatrixWithRowNull ()
ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & operator= (const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &aichromwrn_b)
ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & operator= (ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &&aichromwrn_b)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Public Member Functions inherited from mat::MatrixWithRowNull< T_GENE >
MatrixWithRowNull ()
MatrixWithRowNull (const uintidx aiui_numRows, const uintidx aiui_numRowsMax, const uintidx aiui_numColumns)
MatrixWithRowNull (const mat::MatrixWithRowNull< T_GENE > &aimatrixwrownull_b)
MatrixWithRowNull (mat::MatrixWithRowNull< T_GENE > &&aimatrixwrownull_b)
~MatrixWithRowNull ()
mat::MatrixRow< T_GENE > getMatrix ()
void setMatrix (const mat::MatrixRow< T_GENE > &aimatrix_B)
void combination (uintidx aiui_numrow, mat::MatrixWithRowNull< T_GENE > &aimatrixwrownull_b)
T_GENE * getRow (uintidx i)
const T_GENE * getRow (uintidx i) const
void copyRow (const uintidx aiui_idxRow, const T_GENE *aiT_row)
const uintidx getNumRowsMax () const
T_GENE ** toArray ()
mat::MatrixWithRowNull< T_GENE > & operator= (const mat::MatrixWithRowNull< T_GENE > &aimatrixwrownull_b)
mat::MatrixWithRowNull< T_GENE > & operator= (mat::MatrixWithRowNull< T_GENE > &&aimatrixwrownull_b)
void keepRows (std::vector< uintidx > &aivectorT_idxRow)
void addRow (const T_GENE *aiT_row)
Public Member Functions inherited from mat::MatrixBase< T_GENE >
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T_GENE > &&B)
MatrixBase (const MatrixBase< T_GENE > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
MatrixBase< T_GENE > & operator= (const MatrixBase< T_GENE > &B)
MatrixBase< T_GENE > & operator= (MatrixBase< T_GENE > &&B)
Friends
std::ostream & operator<< (std::ostream &os, const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &aichromwrn_b)
Additional Inherited Members
Protected Member Functions inherited from mat::MatrixBase< T_GENE >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Protected Attributes inherited from mat::MatrixWithRowNull< T_GENE >
uintidx _ui_numRowsMax
T_GENE ** _arrayt_row
Protected Attributes inherited from mat::MatrixBase< T_GENE >
uintidx _ui_numRows
uintidx _ui_numColumns
Detailed Description
template<class T_GENE, class T_METRIC>
class gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >
Matrix with row null chromosome.
Definition at line 33 of file chromosome_withrownull.hpp.
Constructor & Destructor Documentation
ChromosomeMatrixWithRowNull() [1/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::ChromosomeMatrixWithRowNull () inline
Definition at line 38 of file chromosome_withrownull.hpp.
ChromosomeMatrixWithRowNull() [2/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::ChromosomeMatrixWithRowNull (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numRowsMax, const uintidx aiuintidx_numColumns) inline
Definition at line 45 of file chromosome_withrownull.hpp.
ChromosomeMatrixWithRowNull() [3/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::ChromosomeMatrixWithRowNull (const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & aichromwrn_b) inline
Definition at line 57 of file chromosome_withrownull.hpp.
References gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print().
ChromosomeMatrixWithRowNull() [4/4]
template<class T_GENE, class T_METRIC> gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::ChromosomeMatrixWithRowNull (ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > && aichromwrn_b) inline
Definition at line 87 of file chromosome_withrownull.hpp.
References gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print().
~ChromosomeMatrixWithRowNull()
template<class T_GENE, class T_METRIC> virtual gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::~ChromosomeMatrixWithRowNull () inline virtual
Definition at line 114 of file chromosome_withrownull.hpp.
Member Function Documentation
operator=() [1/2]
template<class T_GENE, class T_METRIC> ChromosomeMatrixWithRowNull<T_GENE,T_METRIC>& gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::operator= (const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & aichromwrn_b) inline
Definition at line 130 of file chromosome_withrownull.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), mat::MatrixWithRowNull< T >::operator=(), and gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print().
operator=() [2/2]
template<class T_GENE, class T_METRIC> ChromosomeMatrixWithRowNull<T_GENE,T_METRIC>& gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::operator= (ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > && aichromwrn_b) inline
Definition at line 163 of file chromosome_withrownull.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), mat::MatrixWithRowNull< T >::operator=(), and gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print().
print()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromosomeBase< T_METRIC >.
Definition at line 198 of file chromosome_withrownull.hpp.
References gaencode::ChromosomeBase< T_METRIC >::print(), and mat::MatrixWithRowNull< T >::print().
Referenced by gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::ChromosomeMatrixWithRowNull(), eac::gcuk_vkcentroid(), gaclusteringop::onePointCrossover(), and gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::operator=().
Friends And Related Function Documentation
operator<<
template<class T_GENE, class T_METRIC> std::ostream& operator<< (std::ostream & os, const ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & aichromwrn_b) friend
Definition at line 216 of file chromosome_withrownull.hpp.
The documentation for this class was generated from the following file:
include/chromosome_withrownull.hpp