Library Evolutionary Algorithms for Clustering (LEAC): mat::MatrixRow< T_FEATURE > Class Template Reference
mat::MatrixRow< T_FEATURE > Class Template Reference
Matrix store items for row.
#include <matrix.hpp>
Public Member Functions
MatrixRow ()
MatrixRow (const uintidx aiuintidx_numRows)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, const T_FEATURE ait_initialValue)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_FEATURE *aiT_data)
MatrixRow (const MatrixRow< T_FEATURE > &B)
MatrixRow (MatrixRow< T_FEATURE > &&B)
virtual ~MatrixRow ()
const T_FEATURE * toArray () const
T_FEATURE * toArray ()
void initialize (const T_FEATURE ait_value=T_FEATURE(0))
T_FEATURE & operator[] (uintidx i)
T_FEATURE operator[] (uintidx i) const
MatrixRow< T_FEATURE > & operator= (const MatrixRow< T_FEATURE > &B)
MatrixRow< T_FEATURE > & operator= (MatrixRow< T_FEATURE > &&B)
T_FEATURE & operator() (const uintidx i, const uintidx j)
T_FEATURE operator() (const uintidx i, const uintidx j) const
const T_FEATURE * getRow (const uintidx i) const
T_FEATURE * getRow (const uintidx i)
void swapRows (const uintidx i, const uintidx j)
void copyRow (const uintidx aiuintidx_idxFrom, const uintidx aiuintidx_idxTo)
void copyRow (const uintidx aiuintidx_idxRow, const T_FEATURE *aiT_row)
void copyRow (const uintidx aiuintidx_idxRow, const T_FEATURE *aiT_row, const uintidx aiuintidx_numColumns)
void cpyLoweToUpper ()
void cpyUpper (const MatrixRow< T_FEATURE > &B)
void cpySubMatrix (MatrixRow< T_FEATURE > &B, const uintidx aiuintidx_beginRow, const uintidx aiuintidx_beginCol, const uintidx aiuintidx_numRow, const uintidx aiuintidx_numCol)
MatrixRow< T_FEATURE > & operator+= (const MatrixRow< T_FEATURE > &B)
MatrixRow< T_FEATURE > & operator-= (const MatrixRow< T_FEATURE > &B)
std::pair< uintidx, uintidx > getMaximumElemIJ ()
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const
void r8mat_print (const char *aipc_label="", const char *aipc_labelColums="", const char aic_separatorlabels=',', const int aii_numColumns=5, std::ostream &os=std::cout) const
Public Member Functions inherited from mat::MatrixBase< T_FEATURE >
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T_FEATURE > &&B)
MatrixBase (const MatrixBase< T_FEATURE > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
MatrixBase< T_FEATURE > & operator= (const MatrixBase< T_FEATURE > &B)
MatrixBase< T_FEATURE > & operator= (MatrixBase< T_FEATURE > &&B)
Protected Attributes
bool _b_externalData
T_FEATURE * _arrayt_data
Protected Attributes inherited from mat::MatrixBase< T_FEATURE >
uintidx _ui_numRows
uintidx _ui_numColumns
Additional Inherited Members
Protected Member Functions inherited from mat::MatrixBase< T_FEATURE >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Detailed Description
template<class T_FEATURE>
class mat::MatrixRow< T_FEATURE >
Matrix store items for row.
Definition at line 46 of file matrix.hpp.
Constructor & Destructor Documentation
MatrixRow() [1/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow () inline
Definition at line 50 of file matrix.hpp.
MatrixRow() [2/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (const uintidx aiuintidx_numRows) inline
Definition at line 56 of file matrix.hpp.
MatrixRow() [3/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns) inline
Definition at line 64 of file matrix.hpp.
MatrixRow() [4/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, const T_FEATURE ait_initialValue) inline
Definition at line 72 of file matrix.hpp.
MatrixRow() [5/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_FEATURE * aiT_data) inline
Definition at line 84 of file matrix.hpp.
MatrixRow() [6/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (const MatrixRow< T_FEATURE > & B) inline
Definition at line 94 of file matrix.hpp.
MatrixRow() [7/7]
template<class T_FEATURE> mat::MatrixRow< T_FEATURE >::MatrixRow (MatrixRow< T_FEATURE > && B) inline
Definition at line 103 of file matrix.hpp.
~MatrixRow()
template<class T_FEATURE> virtual mat::MatrixRow< T_FEATURE >::~MatrixRow () inline virtual
Definition at line 112 of file matrix.hpp.
Member Function Documentation
copyRow() [1/3]
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::copyRow (const uintidx aiuintidx_idxFrom, const uintidx aiuintidx_idxTo) inline
Definition at line 205 of file matrix.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::getMatrix(), eac::gga_vklabel(), mat::keepRows(), and eac::tgca_vkcentroid().
copyRow() [2/3]
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::copyRow (const uintidx aiuintidx_idxRow, const T_FEATURE * aiT_row) inline
Definition at line 214 of file matrix.hpp.
copyRow() [3/3]
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::copyRow (const uintidx aiuintidx_idxRow, const T_FEATURE * aiT_row, const uintidx aiuintidx_numColumns) inline
Definition at line 222 of file matrix.hpp.
cpyLoweToUpper()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::cpyLoweToUpper () inline
Definition at line 230 of file matrix.hpp.
cpySubMatrix()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::cpySubMatrix (MatrixRow< T_FEATURE > & B, const uintidx aiuintidx_beginRow, const uintidx aiuintidx_beginCol, const uintidx aiuintidx_numRow, const uintidx aiuintidx_numCol) inline
Definition at line 259 of file matrix.hpp.
cpyUpper()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::cpyUpper (const MatrixRow< T_FEATURE > & B) inline
Definition at line 244 of file matrix.hpp.
getMaximumElemIJ()
template<class T_FEATURE> std::pair<uintidx,uintidx> mat::MatrixRow< T_FEATURE >::getMaximumElemIJ () inline
Definition at line 316 of file matrix.hpp.
getRow() [1/2]
template<class T_FEATURE> const T_FEATURE* mat::MatrixRow< T_FEATURE >::getRow (const uintidx i) const inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Definition at line 181 of file matrix.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), mat::bitgemm(), mat::MatrixRow< T_METRIC >::copyRow(), mat::MatrixRow< T_METRIC >::cpyLoweToUpper(), mat::MatrixRow< T_METRIC >::cpySubMatrix(), mat::MatrixRow< T_METRIC >::cpyUpper(), um::D2(), um::dbindex(), um::Dinter(), um::Dintra(), clusteringop::fuzzyPartition(), interfacesse::gemm(), interfacesse::gemv(), clusteringop::getCentroids(), clusteringop::getClusters(), mat::MatrixRow< T_METRIC >::getMaximumElemIJ(), clusteringop::getPartition(), eac::gga_vklabel(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), um::indexI(), um::indexIreeval(), um::j1(), um::jm(), mat::lange(), main(), mat::matrixread_get(), um::maxDistCjCjp(), um::maxRadiusClusterK(), stats::meanRow(), um::minDistCjCjp(), mat::mulRowsIColumns0N(), gaintegerop::mutationgka(), nearest::NN(), mat::point(), mat::MatrixRow< T_METRIC >::print(), gaclusteringop::rearrangedCluster(), clusteringop::reassignCluster(), mat::MatrixWithRowNull< T_GENE >::setMatrix(), um::ssb(), um::ssbreeval(), um::SSE(), um::sumMinCjCjp(), mat::MatrixRow< T_METRIC >::swapRows(), eac::tgca_vkcentroid(), clusteringop::updateCentroids(), clusteringop::updateClusterCj(), and um::xb().
getRow() [2/2]
template<class T_FEATURE> T_FEATURE* mat::MatrixRow< T_FEATURE >::getRow (const uintidx i) inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Definition at line 188 of file matrix.hpp.
initialize()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::initialize (const T_FEATURE ait_value = T_FEATURE(0)) inline
Definition at line 129 of file matrix.hpp.
Referenced by clusteringop::getCentroids(), mat::getIdentity(), stats::getMatrixDiagonal(), eac::gga_vklabel(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaclusteringop::kmeansfeac(), mat::MatrixRow< T_METRIC >::MatrixRow(), gaclusteringop::rearrangedCluster(), mat::scale(), mat::translation(), and clusteringop::updateClusterCj().
operator()() [1/2]
template<class T_FEATURE> T_FEATURE& mat::MatrixRow< T_FEATURE >::operator() (const uintidx i, const uintidx j) inline
Definition at line 174 of file matrix.hpp.
operator()() [2/2]
template<class T_FEATURE> T_FEATURE mat::MatrixRow< T_FEATURE >::operator() (const uintidx i, const uintidx j) const inline
Definition at line 177 of file matrix.hpp.
operator+=()
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixRow< T_FEATURE >::operator+= (const MatrixRow< T_FEATURE > & B) inline
Definition at line 280 of file matrix.hpp.
operator-=()
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixRow< T_FEATURE >::operator-= (const MatrixRow< T_FEATURE > & B) inline
Definition at line 298 of file matrix.hpp.
operator=() [1/2]
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixRow< T_FEATURE >::operator= (const MatrixRow< T_FEATURE > & B) inline
Definition at line 137 of file matrix.hpp.
Referenced by sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::operator=().
operator=() [2/2]
template<class T_FEATURE> MatrixRow<T_FEATURE>& mat::MatrixRow< T_FEATURE >::operator= (MatrixRow< T_FEATURE > && B) inline
Definition at line 157 of file matrix.hpp.
operator[]() [1/2]
template<class T_FEATURE> T_FEATURE& mat::MatrixRow< T_FEATURE >::operator[] (uintidx i) inline
Definition at line 134 of file matrix.hpp.
operator[]() [2/2]
template<class T_FEATURE> T_FEATURE mat::MatrixRow< T_FEATURE >::operator[] (uintidx i) const inline
Definition at line 135 of file matrix.hpp.
print()
template<class T_FEATURE> virtual void mat::MatrixRow< T_FEATURE >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = '\n') const inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Reimplemented in sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >.
Definition at line 336 of file matrix.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), mat::bitgemm(), eac::clustering_genetic(), eac::gaclustering_vktreebinary(), clusteringop::getCentroids(), clusteringop::getClusters(), mat::getIdentity(), stats::getMatrixDiagonal(), mat::getTranspose(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), mat::inverse(), mat::LUPdecompose(), mat::LUPinverse(), main(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::print(), clusteringop::randomInitialize(), mat::syevd(), eac::tgca_vkcentroid(), and clusteringop::updateClusterCj().
r8mat_print()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::r8mat_print (const char * aipc_label = "", const char * aipc_labelColums = "", const char aic_separatorlabels = ',', const int aii_numColumns = 5, std::ostream & os = std::cout) const inline
Definition at line 374 of file matrix.hpp.
Referenced by main().
swapRows()
template<class T_FEATURE> void mat::MatrixRow< T_FEATURE >::swapRows (const uintidx i, const uintidx j) inline
Definition at line 196 of file matrix.hpp.
toArray() [1/2]
template<class T_FEATURE> const T_FEATURE* mat::MatrixRow< T_FEATURE >::toArray () const inline
Definition at line 119 of file matrix.hpp.
Referenced by um::entropy(), interfacesse::gemm(), interfacesse::gemv(), clusteringop::getCentroids(), mat::getTranspose(), mat::inverse(), mat::lange(), um::partitioncoefficient(), and mat::syevd().
toArray() [2/2]
template<class T_FEATURE> T_FEATURE* mat::MatrixRow< T_FEATURE >::toArray () inline
Definition at line 124 of file matrix.hpp.
Member Data Documentation
_arrayt_data
template<class T_FEATURE> T_FEATURE* mat::MatrixRow< T_FEATURE >::_arrayt_data protected
Definition at line 531 of file matrix.hpp.
Referenced by mat::MatrixRow< T_METRIC >::getMaximumElemIJ(), mat::MatrixRow< T_METRIC >::getRow(), mat::MatrixRow< T_METRIC >::initialize(), mat::MatrixRow< T_METRIC >::MatrixRow(), mat::MatrixRow< T_METRIC >::operator()(), mat::MatrixRow< T_METRIC >::operator+=(), mat::MatrixRow< T_METRIC >::operator-=(), mat::MatrixRow< T_METRIC >::operator=(), mat::MatrixRow< T_METRIC >::operator[](), mat::MatrixRow< T_METRIC >::r8mat_print(), mat::MatrixRow< T_METRIC >::toArray(), and mat::MatrixRow< T_METRIC >::~MatrixRow().
_b_externalData
template<class T_FEATURE> bool mat::MatrixRow< T_FEATURE >::_b_externalData protected
Definition at line 530 of file matrix.hpp.
Referenced by mat::MatrixRow< T_METRIC >::operator=(), and mat::MatrixRow< T_METRIC >::~MatrixRow().
The documentation for this class was generated from the following file:
include/matrix.hpp