Library Evolutionary Algorithms for Clustering (LEAC): ds::DisjSets Class Reference
ds::DisjSets Class Reference
Disjoint-set.
#include <disjsets.hpp>
Public Member Functions
DisjSets ()
DisjSets (const uintidx ai_numObj)
DisjSets (DisjSets &&aids_disjset)
DisjSets (const DisjSets &aids_disjset)
~ DisjSets ()
DisjSets & operator= (DisjSets &&aids_disjset)
DisjSets & operator= (const DisjSets &aids_disjset)
void make_set (uintidx x)
uintidx find (uintidx x)
const uintidx constfind (uintidx x) const
void merge (uintidx x, uintidx y)
uintidx getNumSet ()
const uintidx size () const
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',') const
Protected Attributes
uintidx _m
std::vector< uintidx > _vectorst_parent
std::vector< unsigned > _vectorui_rank
Private Member Functions
void link (uintidx x, uintidx y)
Detailed Description
Disjoint-set.
A disjoint-set data structure, also called a union-find data structure or merge-find set, is a data structure that keeps track of a set of elements partitioned into a number of disjoint (nonoverlapping) subsets.
Definition at line 36 of file disjsets.hpp.
Constructor & Destructor Documentation
DisjSets() [1/4]
ds::DisjSets::DisjSets () inline
Definition at line 40 of file disjsets.hpp.
DisjSets() [2/4]
ds::DisjSets::DisjSets (const uintidx ai_numObj) inline
Definition at line 48 of file disjsets.hpp.
References _vectorst_parent.
DisjSets() [3/4]
ds::DisjSets::DisjSets (DisjSets && aids_disjset) inline
Definition at line 61 of file disjsets.hpp.
DisjSets() [4/4]
ds::DisjSets::DisjSets (const DisjSets & aids_disjset) inline
Definition at line 69 of file disjsets.hpp.
~ DisjSets()
ds::DisjSets::~ DisjSets () inline
Definition at line 77 of file disjsets.hpp.
Member Function Documentation
constfind()
const uintidx ds::DisjSets::constfind (uintidx x) const inline
Definition at line 126 of file disjsets.hpp.
References _vectorst_parent.
Referenced by partition::PartitionDisjSets< T_CLUSTERIDX >::getClusterIdx(), partition::PartitionDisjSets< T_CLUSTERIDX >::next(), and partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets().
find()
uintidx ds::DisjSets::find (uintidx x) inline
Definition at line 118 of file disjsets.hpp.
References _vectorst_parent.
Referenced by graph::component(), and merge().
getNumSet()
uintidx ds::DisjSets::getNumSet () inline
Definition at line 141 of file disjsets.hpp.
References _m.
Referenced by clusteringop::pointerToDisjSets().
link()
void ds::DisjSets::link (uintidx x, uintidx y) inline private
Definition at line 189 of file disjsets.hpp.
Referenced by merge().
make_set()
void ds::DisjSets::make_set (uintidx x) inline
Definition at line 111 of file disjsets.hpp.
References _vectorst_parent, and _vectorui_rank.
merge()
void ds::DisjSets::merge (uintidx x, uintidx y) inline
Definition at line 135 of file disjsets.hpp.
References _m, find(), and link().
Referenced by graph::component(), and clusteringop::pointerToDisjSets().
operator=() [1/2]
DisjSets& ds::DisjSets::operator= (DisjSets && aids_disjset) inline
Definition at line 82 of file disjsets.hpp.
References _m, _vectorst_parent, and _vectorui_rank.
operator=() [2/2]
DisjSets& ds::DisjSets::operator= (const DisjSets & aids_disjset) inline
Definition at line 98 of file disjsets.hpp.
References _m, _vectorst_parent, and _vectorui_rank.
print()
void ds::DisjSets::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') const inline
Definition at line 152 of file disjsets.hpp.
References _vectorst_parent.
Referenced by graph::component(), and clusteringop::pointerToDisjSets().
size()
const uintidx ds::DisjSets::size () const inline
Definition at line 146 of file disjsets.hpp.
References _vectorst_parent.
Referenced by clusteringop::pointerToDisjSets().
Member Data Documentation
_m
uintidx ds::DisjSets::_m protected
Definition at line 183 of file disjsets.hpp.
Referenced by partition::PartitionDisjSets< T_CLUSTERIDX >::getNumCluster(), getNumSet(), merge(), and operator=().
_vectorst_parent
std::vector<uintidx> ds::DisjSets::_vectorst_parent protected
Definition at line 184 of file disjsets.hpp.
Referenced by constfind(), DisjSets(), partition::PartitionDisjSets< T_CLUSTERIDX >::end(), find(), partition::PartitionDisjSets< T_CLUSTERIDX >::getNumInstances(), make_set(), operator=(), partition::PartitionDisjSets< T_CLUSTERIDX >::PartitionDisjSets(), print(), and size().
_vectorui_rank
std::vector<unsigned> ds::DisjSets::_vectorui_rank protected
Definition at line 185 of file disjsets.hpp.
Referenced by make_set(), and operator=().
The documentation for this class was generated from the following file:
include/disjsets.hpp