Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
Chromosome IGKA.
#include <chromosome_igka.hpp>
Public Member Functions
ChromosomeIGKA (const uintidx aiuintidx_numClusterK)
ChromosomeIGKA (const ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aich_chromosome)
ChromosomeIGKA (ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &&aich_chromosome)
virtual ~ChromosomeIGKA ()
void initialize (const std::vector< data::Instance< T_FEATURE > * > &aivectorptinst_instances, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dista)
mat::MatrixRow< T_FEATURE > & getCentroids ()
T_METRIC getDistINSTiCLUSTE1k (uintidx aiuintidx_idxInstance, T_CLUSTERIDX aicidx_clusterK)
T_METRIC getDistINSTiCLUSTE1k (uintidx aiuintidx_idxInstance, uintidx aiuintidx_clusterK)
T_METRIC getDistSumINSTiCLUSTE1k (uintidx aiuintidx_idxInstance)
T_METRIC getDistMaxINSTiCLUSTEk (uintidx aiuintidx_idxInstance)
T_CLUSTERIDX getIdxMinINSTiCLUSTEk (uintidx aiuintidx_idxInstance)
T_CLUSTERIDX getNumClusterNotNull ()
T_METRIC getLegalityRation () const
bool getSelected ()
void setSelected (bool aib_selected)
void accumulateUpdate (T_CLUSTERIDX aicidx_newAllen, T_CLUSTERIDX aicidx_oldAllen, data::Instance< T_FEATURE > *aiptinst_instance)
void incrementalUpdate (std::vector< data::Instance< T_FEATURE > * > &aivectorptinst_instances, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dista)
ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & operator= (const ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aichrom_b)
ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & operator= (ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &&aichrom_b)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
ChromFixedLength ()
ChromFixedLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromFixedLength (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromFixedLength (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromFixedLength ()
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
virtual const uintidx getStringSize () const
virtual void setString (T_CLUSTERIDX *aips_string)
virtual T_CLUSTERIDX * getString ()
virtual const T_CLUSTERIDX * getString () const
T_CLUSTERIDX * begin ()
T_CLUSTERIDX * end ()
virtual const T_CLUSTERIDX getGene (const uintidx aiuintidx_idxGene) const
virtual void setGene (uintidx aiuintidx_idxGene, T_CLUSTERIDX ait_newGene)
Public Member Functions inherited from gaencode::ChromosomeString< T_CLUSTERIDX, T_METRIC >
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Protected Attributes
mat::MatrixRow< T_FEATURE > _matrixrowt_centroids
mat::MatrixRow< T_FEATURE_SUM > _matrixrowt_sumInstancesCluster
std::vector< T_INSTANCES_CLUSTER_K > _vectorT_numInstancesClusterK
T_METRIC * _arrayT_WCV
mat::MatrixRow< T_METRIC > _matrixrowt_distINSTiCLUSTE1k
T_METRIC * _arrayT_distSumINSTiCLUSTE1k
T_METRIC * _arrayT_distMaxINSTiCLUSTEk
T_METRIC * _arrayT_distMinINSTiCLUSTEk
T_CLUSTERIDX * _arraycidx_idxMinINSTiCLUSTEk
T_CLUSTERIDX * _arraycidx_idxMaxINSTiCLUSTEk
mat::MatrixRow< T_FEATURE_SUM > _matrixrowt_sumInstancesClusterDelta
std::vector< T_INSTANCES_CLUSTER_K > _vectorT_numInstancesClusterKDelta
std::vector< bool > _vectorb_changeCluster
T_CLUSTERIDX _cidx_numClusterNotNull
T_METRIC _t_TWCVDelta
bool _b_selected
Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
T_CLUSTERIDX * _pts_string
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Additional Inherited Members
Static Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static void setStringSize (uintidx aiuintidx_stringSize)
static const uintidx stcgetStringSize ()
Static Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static uintidx _stcui_stringSize
Detailed Description
template<class T_CLUSTERIDX, class T_METRIC, class T_FEATURE, class T_FEATURE_SUM, class T_INSTANCES_CLUSTER_K>
class gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >
Chromosome IGKA.
Definition at line 45 of file chromosome_igka.hpp.
Constructor & Destructor Documentation
ChromosomeIGKA() [1/3]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA (const uintidx aiuintidx_numClusterK) inline
Definition at line 50 of file chromosome_igka.hpp.
ChromosomeIGKA() [2/3]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA (const ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aich_chromosome) inline
Definition at line 88 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, and interfacesse::copy().
ChromosomeIGKA() [3/3]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA (ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > && aich_chromosome) inline
Definition at line 159 of file chromosome_igka.hpp.
~ChromosomeIGKA()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > virtual gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA () inline virtual
Definition at line 201 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV.
Member Function Documentation
accumulateUpdate()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate (T_CLUSTERIDX aicidx_newAllen, T_CLUSTERIDX aicidx_oldAllen, data::Instance< T_FEATURE > * aiptinst_instance) inline
Definition at line 370 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorb_changeCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterKDelta, interfacesse::axpy(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixRow< T_FEATURE >::getRow(), and mat::MatrixRow< T_FEATURE >::print().
getCentroids()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixRow<T_FEATURE>& gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getCentroids () inline
Definition at line 311 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids.
getDistINSTiCLUSTE1k() [1/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistINSTiCLUSTE1k (uintidx aiuintidx_idxInstance, T_CLUSTERIDX aicidx_clusterK) inline
Definition at line 318 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k.
getDistINSTiCLUSTE1k() [2/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistINSTiCLUSTE1k (uintidx aiuintidx_idxInstance, uintidx aiuintidx_clusterK) inline
Definition at line 325 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k.
getDistMaxINSTiCLUSTEk()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistMaxINSTiCLUSTEk (uintidx aiuintidx_idxInstance) inline
Definition at line 337 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk.
getDistSumINSTiCLUSTE1k()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistSumINSTiCLUSTE1k (uintidx aiuintidx_idxInstance) inline
Definition at line 331 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k.
getIdxMinINSTiCLUSTEk()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getIdxMinINSTiCLUSTEk (uintidx aiuintidx_idxInstance) inline
Definition at line 343 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk.
getLegalityRation()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLegalityRation () const inline
Definition at line 353 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull, and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
getNumClusterNotNull()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumClusterNotNull () inline
Definition at line 348 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull.
getSelected()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > bool gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getSelected () inline
Definition at line 359 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_b_selected.
incrementalUpdate()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate (std::vector< data::Instance< T_FEATURE > * > & aivectorptinst_instances, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dista) inline
Definition at line 431 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_TWCVDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorb_changeCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterKDelta, data::Instance< T_FEATURE >::getFeatures(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getGene(), mat::MatrixBase< T_FEATURE >::getNumColumns(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), mat::MatrixRow< T_FEATURE >::getRow(), stats::meanVector(), mat::MatrixRow< T_FEATURE >::print(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), and gaencode::ChromosomeBase< T_METRIC >::setValidString().
initialize()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize (const std::vector< data::Instance< T_FEATURE > * > & aivectorptinst_instances, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dista) inline
Definition at line 220 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, interfacesse::copya(), clusteringop::getCentroids(), data::Instance< T_FEATURE >::getFeatures(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getGene(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getStringSize(), mat::MatrixRow< T_FEATURE >::initialize(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromosomeBase< T_METRIC >::setValidString(), and interfacesse::sum().
operator=() [1/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > ChromosomeIGKA<T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K>& gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator= (const ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aichrom_b) inline
Definition at line 617 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_b_selected, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_TWCVDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorb_changeCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterKDelta, interfacesse::copy(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
operator=() [2/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > ChromosomeIGKA<T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K>& gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator= (ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > && aichrom_b) inline
Definition at line 718 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_b_selected, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_TWCVDelta, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorb_changeCluster, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterKDelta, and gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=().
print()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > virtual void gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Definition at line 764 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids, gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLegalityRation(), and gaencode::ChromFixedLength< T_GENE, T_METRIC >::print().
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
setSelected()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setSelected (bool aib_selected) inline
Definition at line 364 of file chromosome_igka.hpp.
References gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_b_selected.
Member Data Documentation
_arraycidx_idxMaxINSTiCLUSTEk
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMaxINSTiCLUSTEk protected
Definition at line 800 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_arraycidx_idxMinINSTiCLUSTEk
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arraycidx_idxMinINSTiCLUSTEk protected
Definition at line 799 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getIdxMinINSTiCLUSTEk(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_arrayT_distMaxINSTiCLUSTEk
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMaxINSTiCLUSTEk protected
Definition at line 797 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistMaxINSTiCLUSTEk(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_arrayT_distMinINSTiCLUSTEk
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distMinINSTiCLUSTEk protected
Definition at line 798 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_arrayT_distSumINSTiCLUSTE1k
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_distSumINSTiCLUSTE1k protected
Definition at line 796 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistSumINSTiCLUSTE1k(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_arrayT_WCV
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC* gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_arrayT_WCV protected
Definition at line 794 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeIGKA().
_b_selected
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > bool gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_b_selected protected
Definition at line 809 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getSelected(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setSelected().
_cidx_numClusterNotNull
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_cidx_numClusterNotNull protected
Definition at line 807 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLegalityRation(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumClusterNotNull(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_matrixrowt_centroids
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixRow<T_FEATURE> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_centroids protected
Definition at line 789 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getCentroids(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLegalityRation(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
_matrixrowt_distINSTiCLUSTE1k
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixRow<T_METRIC> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_distINSTiCLUSTE1k protected
Definition at line 795 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getDistINSTiCLUSTE1k(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_matrixrowt_sumInstancesCluster
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixRow<T_FEATURE_SUM> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesCluster protected
Definition at line 790 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_matrixrowt_sumInstancesClusterDelta
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixRow<T_FEATURE_SUM> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixrowt_sumInstancesClusterDelta protected
Definition at line 802 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_t_TWCVDelta
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_TWCVDelta protected
Definition at line 808 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_vectorb_changeCluster
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<bool> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorb_changeCluster protected
Definition at line 805 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_vectorT_numInstancesClusterK
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_INSTANCES_CLUSTER_K> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK protected
Definition at line 792 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
_vectorT_numInstancesClusterKDelta
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_INSTANCES_CLUSTER_K> gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterKDelta protected
Definition at line 804 of file chromosome_igka.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
The documentation for this class was generated from the following file:
include/chromosome_igka.hpp