Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
Chromosome encoded integer string and centroids.
#include <chromosome_feac.hpp>
Public Member Functions
ChromosomeFEAC ()
ChromosomeFEAC (const uintidx aiuintidx_numClusterK, const uintidx aiuintidx_numDimensions)
ChromosomeFEAC (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &ichromfeac_b)
ChromosomeFEAC (ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &&ichromfeac_b)
virtual ~ChromosomeFEAC ()
ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & operator= (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &ichromfeac_b)
ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & operator= (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &&ichromfeac_b)
mat::MatrixWithRowNull< T_FEATURE > & getCentroids ()
std::vector< T_INSTANCES_CLUSTER_K > & getNumInstancesClusterK ()
T_CLUSTERIDX getNumClusterK ()
void setPartialFcC (const std::vector< T_METRIC > &aivectorrt_partialFcC)
std::vector< T_METRIC > & getPartialFcC ()
void setAppliedOperator (const EnumFeacOperatorApplied aienum_feacOperatorApplied)
const EnumFeacOperatorApplied getAppliedOperator () const
void saveLastObjetiveFunc ()
const T_METRIC getLastObjetiveFunc () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
ChromFixedLength ()
ChromFixedLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromFixedLength (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromFixedLength (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromFixedLength ()
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (const ChromFixedLength< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromFixedLength< T_CLUSTERIDX, T_METRIC > & operator= (ChromFixedLength< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
virtual const uintidx getStringSize () const
virtual void setString (T_CLUSTERIDX *aips_string)
virtual T_CLUSTERIDX * getString ()
virtual const T_CLUSTERIDX * getString () const
T_CLUSTERIDX * begin ()
T_CLUSTERIDX * end ()
virtual const T_CLUSTERIDX getGene (const uintidx aiuintidx_idxGene) const
virtual void setGene (uintidx aiuintidx_idxGene, T_CLUSTERIDX ait_newGene)
Public Member Functions inherited from gaencode::ChromosomeString< T_CLUSTERIDX, T_METRIC >
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (const ChromosomeString< T_CLUSTERIDX, T_METRIC > &aichrom_b)
ChromosomeString< T_CLUSTERIDX, T_METRIC > & operator= (ChromosomeString< T_CLUSTERIDX, T_METRIC > &&aichrom_b)
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Protected Attributes
mat::MatrixWithRowNull< T_FEATURE > _matrixwrownull_centroids
std::vector< T_INSTANCES_CLUSTER_K > _vectorT_numInstancesClusterK
std::vector< T_METRIC > _vectorT_partialFcC
EnumFeacOperatorApplied _enum_feacOperatorApplied
T_METRIC _t_lastObjetiveFunc
Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
T_CLUSTERIDX * _pts_string
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Additional Inherited Members
Static Public Member Functions inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static void setStringSize (uintidx aiuintidx_stringSize)
static const uintidx stcgetStringSize ()
Static Protected Attributes inherited from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >
static uintidx _stcui_stringSize
Detailed Description
template<class T_CLUSTERIDX, class T_METRIC, class T_FEATURE, class T_FEATURE_SUM, class T_INSTANCES_CLUSTER_K>
class gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >
Chromosome encoded integer string and centroids.
A partition is encoded as an integer string (genotype) of N positions. Each string position corresponds to a dataset object, i.e., the i-th position represents the i-thobject of the dataset. Thus, each string component has avalue over the possible cluster labels {1,2,3,...,k} [2].
Definition at line 48 of file chromosome_feac.hpp.
Constructor & Destructor Documentation
ChromosomeFEAC() [1/4]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC () inline
Definition at line 51 of file chromosome_feac.hpp.
References gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
ChromosomeFEAC() [2/4]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC (const uintidx aiuintidx_numClusterK, const uintidx aiuintidx_numDimensions) inline
Definition at line 63 of file chromosome_feac.hpp.
ChromosomeFEAC() [3/4]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & ichromfeac_b) inline
Definition at line 76 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
ChromosomeFEAC() [4/4]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC (ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > && ichromfeac_b) inline
Definition at line 121 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
~ChromosomeFEAC()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > virtual gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~ChromosomeFEAC () inline virtual
Definition at line 161 of file chromosome_feac.hpp.
Member Function Documentation
getAppliedOperator()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > const EnumFeacOperatorApplied gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getAppliedOperator () const inline
Definition at line 286 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied.
getCentroids()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixWithRowNull<T_FEATURE>& gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getCentroids () inline
Definition at line 244 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids.
getLastObjetiveFunc()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > const T_METRIC gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLastObjetiveFunc () const inline
Definition at line 296 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc.
getNumClusterK()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_CLUSTERIDX gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumClusterK () inline
Definition at line 258 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids, and mat::MatrixBase< T_FEATURE >::getNumRows().
getNumInstancesClusterK()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_INSTANCES_CLUSTER_K>& gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumInstancesClusterK () inline
Definition at line 251 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK.
getPartialFcC()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_METRIC>& gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getPartialFcC () inline
Definition at line 273 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC.
operator=() [1/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > ChromosomeFEAC<T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K>& gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator= (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & ichromfeac_b) inline
Definition at line 170 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC, gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
operator=() [2/2]
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > ChromosomeFEAC<T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K>& gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator= (const ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > && ichromfeac_b) inline
Definition at line 223 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC, and gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator=().
print()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > virtual void gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >.
Definition at line 302 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK, gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC, inout::containerprint(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), and mat::MatrixWithRowNull< T >::print().
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeFEAC(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
saveLastObjetiveFunc()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::saveLastObjetiveFunc () inline
Definition at line 291 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc, and gaencode::ChromosomeBase< T_METRIC >::_t_objetiveFunc.
setAppliedOperator()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setAppliedOperator (const EnumFeacOperatorApplied aienum_feacOperatorApplied) inline
Definition at line 280 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied.
setPartialFcC()
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > void gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setPartialFcC (const std::vector< T_METRIC > & aivectorrt_partialFcC) inline
Definition at line 263 of file chromosome_feac.hpp.
References gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC, and interfacesse::copy().
Member Data Documentation
_enum_feacOperatorApplied
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > EnumFeacOperatorApplied gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_enum_feacOperatorApplied protected
Definition at line 387 of file chromosome_feac.hpp.
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getAppliedOperator(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setAppliedOperator().
_matrixwrownull_centroids
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > mat::MatrixWithRowNull<T_FEATURE> gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_matrixwrownull_centroids protected
Definition at line 383 of file chromosome_feac.hpp.
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getCentroids(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumClusterK(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
_t_lastObjetiveFunc
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > T_METRIC gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_t_lastObjetiveFunc protected
Definition at line 388 of file chromosome_feac.hpp.
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getLastObjetiveFunc(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::saveLastObjetiveFunc().
_vectorT_numInstancesClusterK
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_INSTANCES_CLUSTER_K> gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_numInstancesClusterK protected
Definition at line 385 of file chromosome_feac.hpp.
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getNumInstancesClusterK(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
_vectorT_partialFcC
template<class T_CLUSTERIDX , class T_METRIC , class T_FEATURE , class T_FEATURE_SUM , class T_INSTANCES_CLUSTER_K > std::vector<T_METRIC> gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::_vectorT_partialFcC protected
Definition at line 386 of file chromosome_feac.hpp.
Referenced by gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::getPartialFcC(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setPartialFcC().
The documentation for this class was generated from the following file:
include/chromosome_feac.hpp