Library Evolutionary Algorithms for Clustering (LEAC): sm::PartitionMatrix< T_INSTANCES_CLUSTER_K > Class Template Reference
sm::PartitionMatrix< T_INSTANCES_CLUSTER_K > Class Template Reference
Partition Matrix also known as matching matrix is similar to the matrix of confusion, but is used in the unsupervised learning.
#include <matching_matrix.hpp>
Public Member Functions
PartitionMatrix ()
PartitionMatrix (const uintidx aist_numClusterK, const std::vector< std::string > &aivectorstr_labelClusterV)
PartitionMatrix (PartitionMatrix< T_INSTANCES_CLUSTER_K > &&B)
PartitionMatrix (const PartitionMatrix< T_INSTANCES_CLUSTER_K > &B)
virtual ~PartitionMatrix ()
PartitionMatrix< T_INSTANCES_CLUSTER_K > & operator= (const PartitionMatrix< T_INSTANCES_CLUSTER_K > &B)
PartitionMatrix< T_INSTANCES_CLUSTER_K > operator= (PartitionMatrix< T_INSTANCES_CLUSTER_K > &&B)
void sumPartitionTable ()
const T_INSTANCES_CLUSTER_K getNumObjetos () const
virtual const T_INSTANCES_CLUSTER_K getSomeClassUSomeClusterV () const
virtual const T_INSTANCES_CLUSTER_K getDiffClassUDiffClusterV () const
virtual const T_INSTANCES_CLUSTER_K getAgreementObjects () const
virtual const T_INSTANCES_CLUSTER_K getDiffClassUSomeClusterV () const
std::vector< uintidx > getIdxMaximum () const
const T_INSTANCES_CLUSTER_K getMisclassified () const
void setLabelClusterV (std::vector< std::string > aivectorstr_labelClusterV)
const std::vector< std::string > & getlabelClass () const
std::vector< T_INSTANCES_CLUSTER_K > getInstClusterK ()
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
void r8mat_print (const char *aipc_label="", const int aii_numColumns=5, std::ostream &os=std::cout) const
Public Member Functions inherited from mat::MatrixRow< T_INSTANCES_CLUSTER_K >
MatrixRow ()
MatrixRow (const uintidx aiuintidx_numRows)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, const T_INSTANCES_CLUSTER_K ait_initialValue)
MatrixRow (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_INSTANCES_CLUSTER_K *aiT_data)
MatrixRow (const MatrixRow< T_INSTANCES_CLUSTER_K > &B)
MatrixRow (MatrixRow< T_INSTANCES_CLUSTER_K > &&B)
virtual ~MatrixRow ()
const T_INSTANCES_CLUSTER_K * toArray () const
T_INSTANCES_CLUSTER_K * toArray ()
void initialize (const T_INSTANCES_CLUSTER_K ait_value=T_INSTANCES_CLUSTER_K(0))
T_INSTANCES_CLUSTER_K & operator[] (uintidx i)
T_INSTANCES_CLUSTER_K operator[] (uintidx i) const
MatrixRow< T_INSTANCES_CLUSTER_K > & operator= (const MatrixRow< T_INSTANCES_CLUSTER_K > &B)
MatrixRow< T_INSTANCES_CLUSTER_K > & operator= (MatrixRow< T_INSTANCES_CLUSTER_K > &&B)
T_INSTANCES_CLUSTER_K & operator() (const uintidx i, const uintidx j)
T_INSTANCES_CLUSTER_K operator() (const uintidx i, const uintidx j) const
const T_INSTANCES_CLUSTER_K * getRow (const uintidx i) const
T_INSTANCES_CLUSTER_K * getRow (const uintidx i)
void swapRows (const uintidx i, const uintidx j)
void copyRow (const uintidx aiuintidx_idxFrom, const uintidx aiuintidx_idxTo)
void copyRow (const uintidx aiuintidx_idxRow, const T_INSTANCES_CLUSTER_K *aiT_row)
void copyRow (const uintidx aiuintidx_idxRow, const T_INSTANCES_CLUSTER_K *aiT_row, const uintidx aiuintidx_numColumns)
void cpyLoweToUpper ()
void cpyUpper (const MatrixRow< T_INSTANCES_CLUSTER_K > &B)
void cpySubMatrix (MatrixRow< T_INSTANCES_CLUSTER_K > &B, const uintidx aiuintidx_beginRow, const uintidx aiuintidx_beginCol, const uintidx aiuintidx_numRow, const uintidx aiuintidx_numCol)
MatrixRow< T_INSTANCES_CLUSTER_K > & operator+= (const MatrixRow< T_INSTANCES_CLUSTER_K > &B)
MatrixRow< T_INSTANCES_CLUSTER_K > & operator-= (const MatrixRow< T_INSTANCES_CLUSTER_K > &B)
std::pair< uintidx, uintidx > getMaximumElemIJ ()
void r8mat_print (const char *aipc_label="", const char *aipc_labelColums="", const char aic_separatorlabels=',', const int aii_numColumns=5, std::ostream &os=std::cout) const
Public Member Functions inherited from mat::MatrixBase< T_INSTANCES_CLUSTER_K >
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T_INSTANCES_CLUSTER_K > &&B)
MatrixBase (const MatrixBase< T_INSTANCES_CLUSTER_K > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
MatrixBase< T_INSTANCES_CLUSTER_K > & operator= (const MatrixBase< T_INSTANCES_CLUSTER_K > &B)
MatrixBase< T_INSTANCES_CLUSTER_K > & operator= (MatrixBase< T_INSTANCES_CLUSTER_K > &&B)
Protected Attributes
std::vector< std::string > _vectorstr_labelClusterV
Protected Attributes inherited from mat::MatrixRow< T_INSTANCES_CLUSTER_K >
bool _b_externalData
T_INSTANCES_CLUSTER_K * _arrayt_data
Protected Attributes inherited from mat::MatrixBase< T_INSTANCES_CLUSTER_K >
uintidx _ui_numRows
uintidx _ui_numColumns
Additional Inherited Members
Protected Member Functions inherited from mat::MatrixBase< T_INSTANCES_CLUSTER_K >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Detailed Description
template<class T_INSTANCES_CLUSTER_K>
class sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >
Partition Matrix also known as matching matrix is similar to the matrix of confusion, but is used in the unsupervised learning.
Definition at line 40 of file matching_matrix.hpp.
Constructor & Destructor Documentation
PartitionMatrix() [1/4]
template<class T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::PartitionMatrix () inline
Definition at line 43 of file matching_matrix.hpp.
PartitionMatrix() [2/4]
template<class T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::PartitionMatrix (const uintidx aist_numClusterK, const std::vector< std::string > & aivectorstr_labelClusterV) inline
Definition at line 49 of file matching_matrix.hpp.
PartitionMatrix() [3/4]
template<class T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::PartitionMatrix (PartitionMatrix< T_INSTANCES_CLUSTER_K > && B) inline
Definition at line 55 of file matching_matrix.hpp.
PartitionMatrix() [4/4]
template<class T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::PartitionMatrix (const PartitionMatrix< T_INSTANCES_CLUSTER_K > & B) inline
Definition at line 60 of file matching_matrix.hpp.
~PartitionMatrix()
template<class T_INSTANCES_CLUSTER_K> virtual sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::~PartitionMatrix () inline virtual
Definition at line 65 of file matching_matrix.hpp.
Member Function Documentation
getAgreementObjects()
template<class T_INSTANCES_CLUSTER_K> virtual const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getAgreementObjects () const inline virtual
Reimplemented in sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >.
Definition at line 138 of file matching_matrix.hpp.
getDiffClassUDiffClusterV()
template<class T_INSTANCES_CLUSTER_K> virtual const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUDiffClusterV () const inline virtual
Reimplemented in sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >.
Definition at line 127 of file matching_matrix.hpp.
getDiffClassUSomeClusterV()
template<class T_INSTANCES_CLUSTER_K> virtual const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUSomeClusterV () const inline virtual
Reimplemented in sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >.
Definition at line 144 of file matching_matrix.hpp.
getIdxMaximum()
template<class T_INSTANCES_CLUSTER_K> std::vector<uintidx> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getIdxMaximum () const inline
Definition at line 149 of file matching_matrix.hpp.
References mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and inout::li_i.
Referenced by sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getMisclassified(), and sm::partialRandIndex().
getInstClusterK()
template<class T_INSTANCES_CLUSTER_K> std::vector<T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getInstClusterK () inline
Definition at line 244 of file matching_matrix.hpp.
References mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and mat::MatrixRow< T_INSTANCES_CLUSTER_K >::getRow().
Referenced by main().
getlabelClass()
template<class T_INSTANCES_CLUSTER_K> const std::vector<std::string>& sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getlabelClass () const inline
Definition at line 233 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV.
getMisclassified()
template<class T_INSTANCES_CLUSTER_K> const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getMisclassified () const inline
Definition at line 166 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getIdxMaximum(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and inout::li_i.
Referenced by eac::gaclustering_fkcrispmatrix(), and main().
getNumObjetos()
template<class T_INSTANCES_CLUSTER_K> const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getNumObjetos () const inline
Definition at line 114 of file matching_matrix.hpp.
References mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), and mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows().
Referenced by sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getAgreementObjects(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUDiffClusterV(), sm::jaccardIndex(), main(), and sm::randIndex().
getSomeClassUSomeClusterV()
template<class T_INSTANCES_CLUSTER_K> virtual const T_INSTANCES_CLUSTER_K sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV () const inline virtual
Reimplemented in sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >.
Definition at line 122 of file matching_matrix.hpp.
operator=() [1/2]
template<class T_INSTANCES_CLUSTER_K> PartitionMatrix<T_INSTANCES_CLUSTER_K>& sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::operator= (const PartitionMatrix< T_INSTANCES_CLUSTER_K > & B) inline
Definition at line 68 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV, and mat::MatrixRow< T_FEATURE >::operator=().
operator=() [2/2]
template<class T_INSTANCES_CLUSTER_K> PartitionMatrix<T_INSTANCES_CLUSTER_K> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::operator= (PartitionMatrix< T_INSTANCES_CLUSTER_K > && B) inline
Definition at line 78 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV, and mat::MatrixRow< T_FEATURE >::operator=().
print()
template<class T_INSTANCES_CLUSTER_K> virtual void sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from mat::MatrixRow< T_INSTANCES_CLUSTER_K >.
Definition at line 276 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV, mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by main().
r8mat_print()
template<class T_INSTANCES_CLUSTER_K> void sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::r8mat_print (const char * aipc_label = "", const int aii_numColumns = 5, std::ostream & os = std::cout) const inline
Definition at line 312 of file matching_matrix.hpp.
References mat::MatrixRow< T_INSTANCES_CLUSTER_K >::_arrayt_data, sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV, mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), and mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows().
Referenced by main().
setLabelClusterV()
template<class T_INSTANCES_CLUSTER_K> void sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::setLabelClusterV (std::vector< std::string > aivectorstr_labelClusterV) inline
Definition at line 228 of file matching_matrix.hpp.
References sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV.
sumPartitionTable()
template<class T_INSTANCES_CLUSTER_K> void sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::sumPartitionTable () inline
Definition at line 87 of file matching_matrix.hpp.
References mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and inout::li_i.
Referenced by sm::getConfusionMatrix(), and sm::getMatchingMatrix().
Member Data Documentation
_vectorstr_labelClusterV
template<class T_INSTANCES_CLUSTER_K> std::vector<std::string> sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::_vectorstr_labelClusterV protected
Definition at line 473 of file matching_matrix.hpp.
Referenced by sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getlabelClass(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::operator=(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::print(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::r8mat_print(), and sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::setLabelClusterV().
The documentation for this class was generated from the following file:
include/matching_matrix.hpp