Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamVk< T_CLUSTERIDX > Class Template Reference
inout::InParamVk< T_CLUSTERIDX > Class Template Reference
#include <inparam_variablek.hpp>
Public Member Functions
InParamVk ()
~InParamVk ()
void setNumClusterKMinimum (T_CLUSTERIDX aiidxK_numClusterKMinimum)
const T_CLUSTERIDX getNumClusterKMinimum ()
void setNumClusterKMaximum (T_CLUSTERIDX aiidxK_numClusterKMaximum)
const T_CLUSTERIDX getNumClusterKMaximum ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Protected Attributes
T_CLUSTERIDX _idxK_numClusterKMinimum
T_CLUSTERIDX _idxK_numClusterKMaximum
Detailed Description
template<class T_CLUSTERIDX>
class inout::InParamVk< T_CLUSTERIDX >
Definition at line 31 of file inparam_variablek.hpp.
Constructor & Destructor Documentation
InParamVk()
template<class T_CLUSTERIDX > inout::InParamVk< T_CLUSTERIDX >::InParamVk () inline
Definition at line 33 of file inparam_variablek.hpp.
~InParamVk()
template<class T_CLUSTERIDX > inout::InParamVk< T_CLUSTERIDX >::~InParamVk () inline
Definition at line 37 of file inparam_variablek.hpp.
Member Function Documentation
getNumClusterKMaximum()
template<class T_CLUSTERIDX > const T_CLUSTERIDX inout::InParamVk< T_CLUSTERIDX >::getNumClusterKMaximum () inline
Definition at line 54 of file inparam_variablek.hpp.
References inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMaximum.
getNumClusterKMinimum()
template<class T_CLUSTERIDX > const T_CLUSTERIDX inout::InParamVk< T_CLUSTERIDX >::getNumClusterKMinimum () inline
Definition at line 44 of file inparam_variablek.hpp.
References inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMinimum.
print()
template<class T_CLUSTERIDX > virtual void inout::InParamVk< T_CLUSTERIDX >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented in inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamTGCA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, and inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >.
Definition at line 59 of file inparam_variablek.hpp.
References inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMaximum, and inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMinimum.
Referenced by inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
setNumClusterKMaximum()
template<class T_CLUSTERIDX > void inout::InParamVk< T_CLUSTERIDX >::setNumClusterKMaximum (T_CLUSTERIDX aiidxK_numClusterKMaximum) inline
Definition at line 49 of file inparam_variablek.hpp.
References inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMaximum.
setNumClusterKMinimum()
template<class T_CLUSTERIDX > void inout::InParamVk< T_CLUSTERIDX >::setNumClusterKMinimum (T_CLUSTERIDX aiidxK_numClusterKMinimum) inline
Definition at line 39 of file inparam_variablek.hpp.
References inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMinimum.
Member Data Documentation
_idxK_numClusterKMaximum
template<class T_CLUSTERIDX > T_CLUSTERIDX inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMaximum protected
Definition at line 70 of file inparam_variablek.hpp.
Referenced by inout::InParamVk< T_CLUSTERIDX >::getNumClusterKMaximum(), inout::InParamVk< T_CLUSTERIDX >::print(), and inout::InParamVk< T_CLUSTERIDX >::setNumClusterKMaximum().
_idxK_numClusterKMinimum
template<class T_CLUSTERIDX > T_CLUSTERIDX inout::InParamVk< T_CLUSTERIDX >::_idxK_numClusterKMinimum protected
Definition at line 69 of file inparam_variablek.hpp.
Referenced by inout::InParamVk< T_CLUSTERIDX >::getNumClusterKMinimum(), inout::InParamVk< T_CLUSTERIDX >::print(), and inout::InParamVk< T_CLUSTERIDX >::setNumClusterKMinimum().
The documentation for this class was generated from the following file:
include_inout/inparam_variablek.hpp