Library Evolutionary Algorithms for Clustering (LEAC): inout::OutFileName Class Reference
inout::OutFileName Class Reference
#include <outfilename.hpp>
Public Member Functions
OutFileName ()
~OutFileName ()
std::ostream & openFile (const char *aiptc_outfileName, const std::ios_base::openmode ai_openmode=std::ios::out|std::ios::app)
void closeFile ()
Static Public Member Functions
static void setDelim (const char aic_delim)
static const char getDelim ()
Protected Attributes
std::streamsize _stdstremamsize_precisionDefault
std::ostream * _ptostream_ostream
std::ofstream _ofstream_filename
Static Protected Attributes
static char _c_delim = OUTFILENAME_SEPARATOR_DEFAULT
Detailed Description
Definition at line 34 of file outfilename.hpp.
Constructor & Destructor Documentation
OutFileName()
inout::OutFileName::OutFileName () inline
Definition at line 36 of file outfilename.hpp.
~OutFileName()
inout::OutFileName::~OutFileName () inline
Definition at line 42 of file outfilename.hpp.
Member Function Documentation
closeFile()
void inout::OutFileName::closeFile () inline
Definition at line 63 of file outfilename.hpp.
References _ofstream_filename, _ptostream_ostream, and _stdstremamsize_precisionDefault.
Referenced by main().
getDelim()
static const char inout::OutFileName::getDelim () inline static
Definition at line 79 of file outfilename.hpp.
References _c_delim.
Referenced by main(), and operator<<().
openFile()
std::ostream& inout::OutFileName::openFile (const char * aiptc_outfileName, const std::ios_base::openmode ai_openmode = std::ios::out | std::ios::app) inline
Definition at line 45 of file outfilename.hpp.
References _ofstream_filename, _ptostream_ostream, and OUTFILENAME_STDOUT.
Referenced by main().
setDelim()
static void inout::OutFileName::setDelim (const char aic_delim) inline static
Definition at line 73 of file outfilename.hpp.
References _c_delim.
Member Data Documentation
_c_delim
char inout::OutFileName::_c_delim = OUTFILENAME_SEPARATOR_DEFAULT static protected
Definition at line 91 of file outfilename.hpp.
Referenced by getDelim(), and setDelim().
_ofstream_filename
std::ofstream inout::OutFileName::_ofstream_filename protected
Definition at line 89 of file outfilename.hpp.
Referenced by closeFile(), and openFile().
_ptostream_ostream
std::ostream* inout::OutFileName::_ptostream_ostream protected
Definition at line 88 of file outfilename.hpp.
Referenced by closeFile(), and openFile().
_stdstremamsize_precisionDefault
std::streamsize inout::OutFileName::_stdstremamsize_precisionDefault protected
Definition at line 87 of file outfilename.hpp.
Referenced by closeFile().
The documentation for this class was generated from the following file:
include/outfilename.hpp