Library Evolutionary Algorithms for Clustering (LEAC): ds::BitContainer< T_BITSIZE > Class Template Reference
ds::BitContainer< T_BITSIZE > Class Template Reference
Bit container.
#include <bit_container.hpp>
Public Member Functions
BitContainer ()
BitContainer (const uintidx aiuintidx_numWords)
BitContainer (const uintidx aiuintidx_numWords, T_BITSIZE *aiarrayit_data)
BitContainer (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
BitContainer (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
virtual ~BitContainer ()
ds::BitContainer< T_BITSIZE > & operator= (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
ds::BitContainer< T_BITSIZE > & operator= (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
void setArray (T_BITSIZE *aiarrayit_data)
T_BITSIZE * toArray ()
void initialize ()
initialize
void initializeOn ()
initializeOn:
void toggleAll ()
toggleAll
void clearBit (uintidx i)
void setBit (uintidx i)
void toggleBit (uintidx i)
void assignBit (uintidx i, bool aib_bit)
bool getBit (uintidx i) const
uintidx getNumBitOn () const
std::list< uintidx > getIdxWithBitOn () const
void opXor (const ds::BitContainer< T_BITSIZE > &aibitc_bits)
opXor
void copyAligned (const ds::BitContainer< T_BITSIZE > &aibitc_source, const uintidx aiuintidx_idxTarget, uintidx aiuintidx_length)
void copyUnaligned (uintidx aiuintidx_idxTarget, BitContainer< T_BITSIZE > &aibitc_source, uintidx aiuintidx_idxSource, uintidx aiuintidx_length)
void print (std::ostream &os=std::cout, const char *aipc_label="") const
Static Public Member Functions
static const uintidx _getNumWords (uintidx aiuintidx_numBits)
_getNumWords
Static Public Attributes
static const unsigned short int _stusi_numBitsWords
static const T_BITSIZE t_wordMax = (~(T_BITSIZE)0)
Protected Member Functions
unsigned short int _getBitOffset (uintidx b) const
uintidx _bits_in_top_word (uintidx b)
uintidx _getWordIndexBit (uintidx b) const
T_BITSIZE _bitMask (uintidx length)
Protected Attributes
uintidx _uintidx_numWords
T_BITSIZE * _arrayuit_data
bool b_externalData
Private Member Functions
T_BITSIZE _setWordAligned (T_BITSIZE aiT_wordTarget, T_BITSIZE aiT_wordSource, unsigned short int at, unsigned short int numbits)
_setWordAligned
T_BITSIZE _setWordUnaligned (T_BITSIZE aiT_wordTarget, unsigned short int dstindx, T_BITSIZE aiT_wordSource, unsigned short int aiuintidx_idxSource, unsigned short int numbits)
void print (T_BITSIZE ai_word, std::ostream &os=std::cout) const
Friends
class mat::BitMatrix< T_BITSIZE >
Detailed Description
template<class T_BITSIZE>
class ds::BitContainer< T_BITSIZE >
Bit container.
Definition at line 49 of file bit_container.hpp.
Constructor & Destructor Documentation
BitContainer() [1/5]
template<class T_BITSIZE> ds::BitContainer< T_BITSIZE >::BitContainer () inline
Definition at line 56 of file bit_container.hpp.
BitContainer() [2/5]
template<class T_BITSIZE> ds::BitContainer< T_BITSIZE >::BitContainer (const uintidx aiuintidx_numWords) inline
Definition at line 62 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, ds::BitContainer< T_BITSIZE >::_uintidx_numWords, and ds::BitContainer< T_BITSIZE >::initialize().
BitContainer() [3/5]
template<class T_BITSIZE> ds::BitContainer< T_BITSIZE >::BitContainer (const uintidx aiuintidx_numWords, T_BITSIZE * aiarrayit_data) inline
Definition at line 75 of file bit_container.hpp.
BitContainer() [4/5]
template<class T_BITSIZE> ds::BitContainer< T_BITSIZE >::BitContainer (const ds::BitContainer< T_BITSIZE > & aibitcontainer_B) inline
Definition at line 83 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
BitContainer() [5/5]
template<class T_BITSIZE> ds::BitContainer< T_BITSIZE >::BitContainer (ds::BitContainer< T_BITSIZE > && aibitcontainer_B) inline
Definition at line 101 of file bit_container.hpp.
~BitContainer()
template<class T_BITSIZE> virtual ds::BitContainer< T_BITSIZE >::~BitContainer () inline virtual
Definition at line 111 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::b_externalData.
Member Function Documentation
_bitMask()
template<class T_BITSIZE> T_BITSIZE ds::BitContainer< T_BITSIZE >::_bitMask (uintidx length) inline protected
Definition at line 605 of file bit_container.hpp.
Referenced by mat::BitArray< T_BITSIZE >::_maskTopWord().
_bits_in_top_word()
template<class T_BITSIZE> uintidx ds::BitContainer< T_BITSIZE >::_bits_in_top_word (uintidx b) inline protected
Definition at line 595 of file bit_container.hpp.
Referenced by mat::BitArray< T_BITSIZE >::_maskTopWord().
_getBitOffset()
template<class T_BITSIZE> unsigned short int ds::BitContainer< T_BITSIZE >::_getBitOffset (uintidx b) const inline protected
Definition at line 590 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::copyAligned(), and ds::BitContainer< T_BITSIZE >::copyUnaligned().
_getNumWords()
template<class T_BITSIZE> static const uintidx ds::BitContainer< T_BITSIZE >::_getNumWords (uintidx aiuintidx_numBits) inline static
_getNumWords
Number of words required to store a given number of bits 0 -> 0 1..WORD_SIZE -> 1 WORD_SIZE+1..2*WORD_SIZE -> 2 etc.
Definition at line 516 of file bit_container.hpp.
_getWordIndexBit()
template<class T_BITSIZE> uintidx ds::BitContainer< T_BITSIZE >::_getWordIndexBit (uintidx b) const inline protected
Definition at line 600 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::clearBit(), ds::BitContainer< T_BITSIZE >::copyAligned(), ds::BitContainer< T_BITSIZE >::copyUnaligned(), ds::BitContainer< T_BITSIZE >::setBit(), and ds::BitContainer< T_BITSIZE >::toggleBit().
_setWordAligned()
template<class T_BITSIZE> T_BITSIZE ds::BitContainer< T_BITSIZE >::_setWordAligned (T_BITSIZE aiT_wordTarget, T_BITSIZE aiT_wordSource, unsigned short int at, unsigned short int numbits) inline private
_setWordAligned
common internal functions
Definition at line 546 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::copyAligned().
_setWordUnaligned()
template<class T_BITSIZE> T_BITSIZE ds::BitContainer< T_BITSIZE >::_setWordUnaligned (T_BITSIZE aiT_wordTarget, unsigned short int dstindx, T_BITSIZE aiT_wordSource, unsigned short int aiuintidx_idxSource, unsigned short int numbits) inline private
Definition at line 561 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::copyUnaligned().
assignBit()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::assignBit (uintidx i, bool aib_bit) inline
Definition at line 219 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::clearBit(), and ds::BitContainer< T_BITSIZE >::setBit().
clearBit()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::clearBit (uintidx i) inline
Definition at line 201 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_getWordIndexBit().
Referenced by ds::BitContainer< T_BITSIZE >::assignBit().
copyAligned()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::copyAligned (const ds::BitContainer< T_BITSIZE > & aibitc_source, const uintidx aiuintidx_idxTarget, uintidx aiuintidx_length) inline
Definition at line 326 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, ds::BitContainer< T_BITSIZE >::_getBitOffset(), ds::BitContainer< T_BITSIZE >::_getWordIndexBit(), ds::BitContainer< T_BITSIZE >::_setWordAligned(), ds::BitContainer< T_BITSIZE >::getBit(), and ds::BitContainer< T_BITSIZE >::print().
Referenced by mat::BitMatrix< T_BITSIZE >::copyAligned(), gabinaryop::onePointCrossover(), and gabinaryop::onePointDistCrossover().
copyUnaligned()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::copyUnaligned (uintidx aiuintidx_idxTarget, BitContainer< T_BITSIZE > & aibitc_source, uintidx aiuintidx_idxSource, uintidx aiuintidx_length) inline
Definition at line 429 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, ds::BitContainer< T_BITSIZE >::_getBitOffset(), ds::BitContainer< T_BITSIZE >::_getWordIndexBit(), ds::BitContainer< T_BITSIZE >::_setWordUnaligned(), and ds::BitContainer< T_BITSIZE >::print().
Referenced by mat::BitMatrix< T_BITSIZE >::copyUnaligned().
getBit()
template<class T_BITSIZE> bool ds::BitContainer< T_BITSIZE >::getBit (uintidx i) const inline
Definition at line 224 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data.
Referenced by graph::component(), ds::BitContainer< T_BITSIZE >::copyAligned(), graph::fromPiToGraph(), clusteringop::getClusters(), mat::mulRowsIColumns0N(), mat::BitArray< T_BITSIZE >::print(), and gabinaryop::uniformCrossover().
getIdxWithBitOn()
template<class T_BITSIZE> std::list<uintidx> ds::BitContainer< T_BITSIZE >::getIdxWithBitOn () const inline
Definition at line 269 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, ds::BitContainer< T_BITSIZE >::_uintidx_numWords, and inout::containerprint().
getNumBitOn()
template<class T_BITSIZE> uintidx ds::BitContainer< T_BITSIZE >::getNumBitOn () const inline
Definition at line 230 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
Referenced by eac::clustering_vksubclusterbinary(), eac::gaclustering_vktreebinary(), eac::gaprototypes_fkmedoid(), clusteringop::getClusters(), mat::BitMatrix< T_BITSIZE >::getRowNumBitOn(), mat::BitMatrix< T_BITSIZE >::maxNorm(), and mat::BitArray< T_BITSIZE >::print().
initialize()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::initialize () inline
initialize
set all elements of data to zero
Definition at line 172 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
Referenced by ds::BitContainer< T_BITSIZE >::BitContainer(), and gabinaryop::initializeGenes().
initializeOn()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::initializeOn () inline
initializeOn:
set all elements of data to one
Definition at line 181 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
operator=() [1/2]
template<class T_BITSIZE> ds::BitContainer<T_BITSIZE>& ds::BitContainer< T_BITSIZE >::operator= (const ds::BitContainer< T_BITSIZE > & aibitcontainer_B) inline
Definition at line 118 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
Referenced by mat::BitArray< T_BITSIZE >::operator=().
operator=() [2/2]
template<class T_BITSIZE> ds::BitContainer<T_BITSIZE>& ds::BitContainer< T_BITSIZE >::operator= (ds::BitContainer< T_BITSIZE > && aibitcontainer_B) inline
Definition at line 142 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, ds::BitContainer< T_BITSIZE >::_uintidx_numWords, and ds::BitContainer< T_BITSIZE >::b_externalData.
opXor()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::opXor (const ds::BitContainer< T_BITSIZE > & aibitc_bits) inline
opXor
xor
Definition at line 318 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
print() [1/2]
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::print (std::ostream & os = std::cout, const char * aipc_label = "") const inline
Definition at line 522 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::copyAligned(), and ds::BitContainer< T_BITSIZE >::copyUnaligned().
print() [2/2]
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::print (T_BITSIZE ai_word, std::ostream & os = std::cout) const inline private
Definition at line 580 of file bit_container.hpp.
setArray()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::setArray (T_BITSIZE * aiarrayit_data) inline
Definition at line 158 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data.
Referenced by mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::copyUnaligned(), mat::BitMatrix< T_BITSIZE >::getRowNumBitOn(), and mat::BitMatrix< T_BITSIZE >::maxNorm().
setBit()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::setBit (uintidx i) inline
Definition at line 207 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_getWordIndexBit().
Referenced by ds::BitContainer< T_BITSIZE >::assignBit(), gabinaryop::initializeGenes(), gaclusteringop::kmeansfeac(), and gaclusteringop::rearrangedCluster().
toArray()
template<class T_BITSIZE> T_BITSIZE* ds::BitContainer< T_BITSIZE >::toArray () inline
Definition at line 163 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data.
toggleAll()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::toggleAll () inline
toggleAll
Set all 1 bits to 0, and all 0 bits to 1. AKA flip
Definition at line 191 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
Referenced by mat::BitArray< T_BITSIZE >::toggleAll().
toggleBit()
template<class T_BITSIZE> void ds::BitContainer< T_BITSIZE >::toggleBit (uintidx i) inline
Definition at line 213 of file bit_container.hpp.
References ds::BitContainer< T_BITSIZE >::_arrayuit_data, and ds::BitContainer< T_BITSIZE >::_getWordIndexBit().
Referenced by gabinaryop::bitMutation(), gabinaryop::eachBitArrayMutation(), and gabinaryop::uniformCrossover().
Friends And Related Function Documentation
mat::BitMatrix< T_BITSIZE >
template<class T_BITSIZE> friend class mat::BitMatrix< T_BITSIZE > friend
Definition at line 617 of file bit_container.hpp.
Member Data Documentation
_arrayuit_data
template<class T_BITSIZE> T_BITSIZE* ds::BitContainer< T_BITSIZE >::_arrayuit_data protected
Definition at line 614 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::BitContainer(), ds::BitContainer< T_BITSIZE >::clearBit(), ds::BitContainer< T_BITSIZE >::copyAligned(), ds::BitContainer< T_BITSIZE >::copyUnaligned(), ds::BitContainer< T_BITSIZE >::getBit(), ds::BitContainer< T_BITSIZE >::getIdxWithBitOn(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), ds::BitContainer< T_BITSIZE >::initialize(), ds::BitContainer< T_BITSIZE >::initializeOn(), ds::BitContainer< T_BITSIZE >::operator=(), ds::BitContainer< T_BITSIZE >::opXor(), ds::BitContainer< T_BITSIZE >::setArray(), ds::BitContainer< T_BITSIZE >::setBit(), ds::BitContainer< T_BITSIZE >::toArray(), ds::BitContainer< T_BITSIZE >::toggleAll(), ds::BitContainer< T_BITSIZE >::toggleBit(), and ds::BitContainer< T_BITSIZE >::~BitContainer().
_stusi_numBitsWords
template<class T_BITSIZE> const unsigned short int ds::BitContainer< T_BITSIZE >::_stusi_numBitsWords static
Initial value:
=
    (unsigned short int) (sizeof(T_BITSIZE) * 8)
Definition at line 52 of file bit_container.hpp.
_uintidx_numWords
template<class T_BITSIZE> uintidx ds::BitContainer< T_BITSIZE >::_uintidx_numWords protected
Definition at line 613 of file bit_container.hpp.
Referenced by mat::BitArray< T_BITSIZE >::_maskTopWord(), ds::BitContainer< T_BITSIZE >::BitContainer(), ds::BitContainer< T_BITSIZE >::getIdxWithBitOn(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), ds::BitContainer< T_BITSIZE >::initialize(), ds::BitContainer< T_BITSIZE >::initializeOn(), ds::BitContainer< T_BITSIZE >::operator=(), ds::BitContainer< T_BITSIZE >::opXor(), and ds::BitContainer< T_BITSIZE >::toggleAll().
b_externalData
template<class T_BITSIZE> bool ds::BitContainer< T_BITSIZE >::b_externalData protected
Definition at line 615 of file bit_container.hpp.
Referenced by ds::BitContainer< T_BITSIZE >::operator=(), and ds::BitContainer< T_BITSIZE >::~BitContainer().
t_wordMax
template<class T_BITSIZE> const T_BITSIZE ds::BitContainer< T_BITSIZE >::t_wordMax = (~(T_BITSIZE)0) static
Definition at line 54 of file bit_container.hpp.
The documentation for this class was generated from the following file:
include/bit_container.hpp