Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromFixedLength< T_GENE, T_METRIC > Class Template Reference
gaencode::ChromFixedLength< T_GENE, T_METRIC > Class Template Reference
Chromosome with fixed length string.
#include <chromosome_fixedlength.hpp>
Public Member Functions
ChromFixedLength ()
ChromFixedLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromFixedLength (ChromFixedLength< T_GENE, T_METRIC > &&aichrom_b)
ChromFixedLength (const ChromFixedLength< T_GENE, T_METRIC > &aichrom_b)
virtual ~ChromFixedLength ()
ChromFixedLength< T_GENE, T_METRIC > & operator= (const ChromFixedLength< T_GENE, T_METRIC > &aichrom_b)
ChromFixedLength< T_GENE, T_METRIC > & operator= (ChromFixedLength< T_GENE, T_METRIC > &&aichrom_b)
virtual const uintidx getStringSize () const
virtual void setString (T_GENE *aips_string)
virtual T_GENE * getString ()
virtual const T_GENE * getString () const
T_GENE * begin ()
T_GENE * end ()
virtual const T_GENE getGene (const uintidx aiuintidx_idxGene) const
virtual void setGene (uintidx aiuintidx_idxGene, T_GENE ait_newGene)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromosomeString< T_GENE, T_METRIC >
ChromosomeString ()
ChromosomeString (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeString (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
ChromosomeString (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
virtual ~ChromosomeString ()
ChromosomeString< T_GENE, T_METRIC > & operator= (const ChromosomeString< T_GENE, T_METRIC > &aichrom_b)
ChromosomeString< T_GENE, T_METRIC > & operator= (ChromosomeString< T_GENE, T_METRIC > &&aichrom_b)
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Static Public Member Functions
static void setStringSize (uintidx aiuintidx_stringSize)
static const uintidx stcgetStringSize ()
Protected Attributes
T_GENE * _pts_string
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Static Protected Attributes
static uintidx _stcui_stringSize = 0
Detailed Description
template<class T_GENE, class T_METRIC>
class gaencode::ChromFixedLength< T_GENE, T_METRIC >
Chromosome with fixed length string.
Definition at line 44 of file chromosome_fixedlength.hpp.
Constructor & Destructor Documentation
ChromFixedLength() [1/4]
template<class T_GENE, class T_METRIC> gaencode::ChromFixedLength< T_GENE, T_METRIC >::ChromFixedLength () inline
Definition at line 50 of file chromosome_fixedlength.hpp.
ChromFixedLength() [2/4]
template<class T_GENE, class T_METRIC> gaencode::ChromFixedLength< T_GENE, T_METRIC >::ChromFixedLength (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness) inline
Definition at line 55 of file chromosome_fixedlength.hpp.
ChromFixedLength() [3/4]
template<class T_GENE, class T_METRIC> gaencode::ChromFixedLength< T_GENE, T_METRIC >::ChromFixedLength (ChromFixedLength< T_GENE, T_METRIC > && aichrom_b) inline
Definition at line 61 of file chromosome_fixedlength.hpp.
ChromFixedLength() [4/4]
template<class T_GENE, class T_METRIC> gaencode::ChromFixedLength< T_GENE, T_METRIC >::ChromFixedLength (const ChromFixedLength< T_GENE, T_METRIC > & aichrom_b) inline
Definition at line 93 of file chromosome_fixedlength.hpp.
~ChromFixedLength()
template<class T_GENE, class T_METRIC> virtual gaencode::ChromFixedLength< T_GENE, T_METRIC >::~ChromFixedLength () inline virtual
Definition at line 103 of file chromosome_fixedlength.hpp.
Member Function Documentation
begin()
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 211 of file chromosome_fixedlength.hpp.
Referenced by gaclusteringop::crossoverCGA(), eac::gaclustering_fklabel(), eac::gca_fkmedoid(), eac::hka_fkmedoid(), main(), gaclusteringop::MO1(), and gaclusteringop::MO2().
end()
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromFixedLength< T_GENE, T_METRIC >::end () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 216 of file chromosome_fixedlength.hpp.
Referenced by gaclusteringop::crossoverCGA(), eac::gaclustering_fklabel(), eac::gca_fkmedoid(), eac::hka_fkmedoid(), gaclusteringop::MO1(), and gaclusteringop::MO2().
getGene()
template<class T_GENE, class T_METRIC> virtual const T_GENE gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene (const uintidx aiuintidx_idxGene) const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 221 of file chromosome_fixedlength.hpp.
Referenced by eac::cga_vklabel(), gaclusteringop::crossoverCGA(), gaclusteringop::MO1(), gaclusteringop::MO2(), and garealop::randomMutation().
getString() [1/2]
template<class T_GENE, class T_METRIC> virtual T_GENE* gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString () inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 201 of file chromosome_fixedlength.hpp.
Referenced by gaclusteringop::crossoverCGA(), eac::gagr_fkcentroid(), gagenericop::GAGRdist(), eac::kga_fkcentroid(), main(), gaclusteringop::MO1(), gagenericop::onePointCrossover(), and gagenericop::pathCrossover().
getString() [2/2]
template<class T_GENE, class T_METRIC> virtual const T_GENE* gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString () const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 206 of file chromosome_fixedlength.hpp.
getStringSize()
template<class T_GENE, class T_METRIC> virtual const uintidx gaencode::ChromFixedLength< T_GENE, T_METRIC >::getStringSize () const inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 187 of file chromosome_fixedlength.hpp.
Referenced by main(), gagenericop::onePointCrossover(), and gagenericop::pathCrossover().
operator=() [1/2]
template<class T_GENE, class T_METRIC> ChromFixedLength<T_GENE,T_METRIC>& gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator= (const ChromFixedLength< T_GENE, T_METRIC > & aichrom_b) inline
Definition at line 124 of file chromosome_fixedlength.hpp.
Referenced by gaencode::ChromosomeFGKA< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), and gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=().
operator=() [2/2]
template<class T_GENE, class T_METRIC> ChromFixedLength<T_GENE,T_METRIC>& gaencode::ChromFixedLength< T_GENE, T_METRIC >::operator= (ChromFixedLength< T_GENE, T_METRIC > && aichrom_b) inline
Definition at line 163 of file chromosome_fixedlength.hpp.
print()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromFixedLength< T_GENE, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromosomeBase< T_METRIC >.
Reimplemented in gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >, and gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >.
Definition at line 258 of file chromosome_fixedlength.hpp.
Referenced by eac::cga_vklabel(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::ChromFixedLength(), gaclusteringop::crossoverCGA(), eac::gaclustering_fklabel(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::hka_fkmedoid(), eac::kga_fkcentroid(), gaclusteringop::MO1(), gaclusteringop::MO2(), gagenericop::onePointCrossover(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::operator=(), gagenericop::pathCrossover(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and garealop::randomMutation().
setGene()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromFixedLength< T_GENE, T_METRIC >::setGene (uintidx aiuintidx_idxGene, T_GENE ait_newGene) inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 227 of file chromosome_fixedlength.hpp.
Referenced by gaclusteringop::crossoverCGA(), gaclusteringop::MO1(), gaclusteringop::MO2(), and garealop::randomMutation().
setString()
template<class T_GENE, class T_METRIC> virtual void gaencode::ChromFixedLength< T_GENE, T_METRIC >::setString (T_GENE * aips_string) inline virtual
Implements gaencode::ChromosomeString< T_GENE, T_METRIC >.
Definition at line 192 of file chromosome_fixedlength.hpp.
Referenced by gagenericop::pathCrossover().
setStringSize()
template<class T_GENE, class T_METRIC> static void gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize (uintidx aiuintidx_stringSize) inline static
Definition at line 177 of file chromosome_fixedlength.hpp.
Referenced by eac::cga_vklabel(), eac::gaclustering_fklabel(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::kga_fkcentroid(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setElementSize().
stcgetStringSize()
template<class T_GENE, class T_METRIC> static const uintidx gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize () inline static
Definition at line 182 of file chromosome_fixedlength.hpp.
Referenced by gaclusteringop::crossoverCGA(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), eac::igka_fklabel(), gaclusteringop::MO1(), and gagenericop::pathCrossover().
Member Data Documentation
_pts_string
template<class T_GENE, class T_METRIC> T_GENE* gaencode::ChromFixedLength< T_GENE, T_METRIC >::_pts_string protected
Definition at line 283 of file chromosome_fixedlength.hpp.
Referenced by gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::begin(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::ChromFixedLength(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::end(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getGene(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setGene(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setString(), and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::~ChromFixedLength().
_stcui_stringSize
template<class T_GENE, class T_METRIC> uintidx gaencode::ChromFixedLength< T_GENE, T_METRIC >::_stcui_stringSize = 0 static protected
Definition at line 284 of file chromosome_fixedlength.hpp.
Referenced by gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::ChromFixedLength(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::end(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getGene(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getStringSize(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::operator=(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setGene(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setString(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setStringSize(), and gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::stcgetStringSize().
The documentation for this class was generated from the following file:
include/chromosome_fixedlength.hpp