Library Evolutionary Algorithms for Clustering (LEAC): ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > Class Template Reference
ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > Class Template Reference
Partition with an array of membership.
#include <partition_linked_stats.hpp>
Public Member Functions
PartitionLinkedStats (const uintidx aiui_numClusterK, const uintidx aiui_numInstances, const uintidx aiui_numDimensionsInstances, const uintidx aiui_numClusterKSpace)
PartitionLinkedStats (const PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aipartlinkstats_b)
PartitionLinkedStats (PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &&aipartlinkstats_b)
~PartitionLinkedStats ()
void initialize ()
const T_CLUSTERIDX getNumPartitions () const
void decreasePartition ()
void increasesPartition ()
void resize (const uintidx aiui_numClusterK)
T_CLUSTERIDX numClusterEmpty ()
mat::MatrixResizableRow< T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & getSumInstancesClusterK ()
T_FEATURE_SUM * getSumInstancesClusterKi (T_CLUSTERIDX aicidx_clusterK)
std::vector< T_INSTANCES_CLUSTER_K > & getNumInstancesClusterK ()
T_INSTANCES_CLUSTER_K getNumInstancesClusterKi (T_CLUSTERIDX aicidx_clusterK)
T_CLUSTERIDX * getMembersShip ()
T_CLUSTERIDX getMemberShip (const uintidx aiui_idxinstanceI) const
void setMemberShip (const uintidx aiui_idxinstanceI, const T_CLUSTERIDX aiidxk_clusterK)
PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & operator= (const PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aipartlinkstats_b)
PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & operator= (PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &&aipartlinkstats_b)
void addInstanceToCluster (T_CLUSTERIDX aicidx_toClusterIdx, uintidx aiui_idxInstance, const T_FEATURE *aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency=1)
void subInstanceFromCluster (uintidx aiui_idxInstance, const T_FEATURE *aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency=1)
void changeSumInstances (const T_CLUSTERIDX aicidx_clusterKFrom, const T_CLUSTERIDX aicidx_clusterKTo, const T_FEATURE *aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency=1)
void changeMemberShip (T_CLUSTERIDX aicidx_toClusterIdx, uintidx aiui_idxInstance, const T_FEATURE *aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency=1)
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from ds::PartitionLinked< T_CLUSTERIDX >
PartitionLinked ()
PartitionLinked (const uintidx aiui_numInstances, const uintidx aiui_numClusterK)
PartitionLinked (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
~PartitionLinked ()
void resize (const uintidx aiui_numClusterK)
const T_CLUSTERIDX getNumPartitions () const
const uintidx getFirstInstClusterK (T_CLUSTERIDX aicidx_clusterK)
const uintidx getNumInstances () const
PartitionLinked< T_CLUSTERIDX > & operator= (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked< T_CLUSTERIDX > & operator= (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
void initialize ()
void addInstanceToCluster (T_CLUSTERIDX aiT_clusterIdx, uintidx aiidxiT_instanceI)
void subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI)
void changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI)
uintidx getInstanceIdxOfClusterK (T_CLUSTERIDX aicidx_clusterK, const uintidx aiuintidx_instanceNi)
void joinCluster (const T_CLUSTERIDX aiIdxK_clusterKFrom, const T_CLUSTERIDX aiIdxK_clusterKTo)
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimClusterK=';')
Protected Attributes
T_CLUSTERIDX * _arrayidxk_memberShip
mat::MatrixResizableRow< T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > _matrixresizerow_m
std::vector< T_INSTANCES_CLUSTER_K > _vectorit_n
Protected Attributes inherited from ds::PartitionLinked< T_CLUSTERIDX >
std::vector< uintidx > _vectorInstIdx_firstClusterK
std::vector< uintidx > _vectorInstIdx_nextClusterK
Detailed Description
template<typename T_FEATURE, typename T_CLUSTERIDX, typename T_INSTANCE_FREQUENCY, typename T_INSTANCES_CLUSTER_K, typename T_FEATURE_SUM>
class ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >
Partition with an array of membership.
Definition at line 44 of file partition_linked_stats.hpp.
Constructor & Destructor Documentation
PartitionLinkedStats() [1/3]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats (const uintidx aiui_numClusterK, const uintidx aiui_numInstances, const uintidx aiui_numDimensionsInstances, const uintidx aiui_numClusterKSpace) inline
Definition at line 49 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, interfacesse::copya(), mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::initialize(), and NEARESTCENTROID_UNKNOWN.
PartitionLinkedStats() [2/3]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats (const PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aipartlinkstats_b) inline
Definition at line 75 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, and interfacesse::copy().
PartitionLinkedStats() [3/3]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats (PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > && aipartlinkstats_b) inline
Definition at line 97 of file partition_linked_stats.hpp.
~PartitionLinkedStats()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::~PartitionLinkedStats () inline
Definition at line 112 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip.
Member Function Documentation
addInstanceToCluster()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster (T_CLUSTERIDX aicidx_toClusterIdx, uintidx aiui_idxInstance, const T_FEATURE * aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency = 1) inline
Definition at line 396 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster(), interfacesse::axpy(), and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow().
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeMemberShip().
changeMemberShip()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeMemberShip (T_CLUSTERIDX aicidx_toClusterIdx, uintidx aiui_idxInstance, const T_FEATURE * aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency = 1) inline
Definition at line 533 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), NEARESTCENTROID_UNKNOWN, and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster().
changeSumInstances()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeSumInstances (const T_CLUSTERIDX aicidx_clusterKFrom, const T_CLUSTERIDX aicidx_clusterKTo, const T_FEATURE * aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency = 1) inline
Definition at line 499 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, interfacesse::axpy(), and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow().
decreasePartition()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::decreasePartition () inline
Definition at line 134 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::decreaseRow().
getMemberShip()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_CLUSTERIDX ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getMemberShip (const uintidx aiui_idxinstanceI) const inline
Definition at line 243 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip.
Referenced by gaclusteringop::merge().
getMembersShip()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_CLUSTERIDX* ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getMembersShip () inline
Definition at line 236 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip.
getNumInstancesClusterK()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > std::vector<T_INSTANCES_CLUSTER_K>& ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumInstancesClusterK () inline
Definition at line 222 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n.
getNumInstancesClusterKi()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_INSTANCES_CLUSTER_K ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumInstancesClusterKi (T_CLUSTERIDX aicidx_clusterK) inline
Definition at line 229 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n.
getNumPartitions()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > const T_CLUSTERIDX ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumPartitions () const inline
Definition at line 129 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, and mat::MatrixBase< T_FEATURE >::getNumRows().
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print().
getSumInstancesClusterK()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > mat::MatrixResizableRow<T_FEATURE_SUM,T_INSTANCES_CLUSTER_K>& ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getSumInstancesClusterK () inline
Definition at line 208 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m.
getSumInstancesClusterKi()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_FEATURE_SUM* ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getSumInstancesClusterKi (T_CLUSTERIDX aicidx_clusterK) inline
Definition at line 215 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow().
increasesPartition()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::increasesPartition () inline
Definition at line 139 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::increasesRow().
initialize()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::initialize () inline
Definition at line 118 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances(), ds::PartitionLinked< T_CLUSTERIDX >::initialize(), and NEARESTCENTROID_UNKNOWN.
numClusterEmpty()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_CLUSTERIDX ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::numClusterEmpty () inline
Definition at line 196 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, and mat::MatrixBase< T_FEATURE >::getNumRows().
operator=() [1/2]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > PartitionLinkedStats<T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >& ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator= (const PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aipartlinkstats_b) inline
Definition at line 263 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, interfacesse::copy(), ds::PartitionLinked< T_CLUSTERIDX >::operator=(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print().
operator=() [2/2]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > PartitionLinkedStats<T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >& ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator= (PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > && aipartlinkstats_b) inline
Definition at line 338 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, ds::PartitionLinked< T_CLUSTERIDX >::operator=(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print().
print()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline
Definition at line 583 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), inout::containerprint(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::next(), ds::PartitionLinked< T_CLUSTERIDX >::print(), and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::print().
Referenced by gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::checkChangedCodeVectors(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize().
resize()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize (const uintidx aiui_numClusterK) inline
Definition at line 144 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getNumRowsMaximum(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), ds::PartitionLinked< T_CLUSTERIDX >::resize(), and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::resize().
setMemberShip()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::setMemberShip (const uintidx aiui_idxinstanceI, const T_CLUSTERIDX aiidxk_clusterK) inline
Definition at line 250 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip.
subInstanceFromCluster()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > void ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster (uintidx aiui_idxInstance, const T_FEATURE * aiarrayt_feature, const T_INSTANCE_FREQUENCY aiit_instfrequency = 1) inline
Definition at line 445 of file partition_linked_stats.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m, ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n, interfacesse::axpy(), mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow(), NEARESTCENTROID_UNKNOWN, and ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster().
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeMemberShip().
Member Data Documentation
_arrayidxk_memberShip
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > T_CLUSTERIDX* ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_arrayidxk_memberShip protected
Definition at line 649 of file partition_linked_stats.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getMemberShip(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getMembersShip(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::initialize(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::setMemberShip(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::~PartitionLinkedStats().
_matrixresizerow_m
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > mat::MatrixResizableRow<T_FEATURE_SUM,T_INSTANCES_CLUSTER_K> ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_matrixresizerow_m protected
Definition at line 653 of file partition_linked_stats.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeSumInstances(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::decreasePartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumPartitions(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getSumInstancesClusterK(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getSumInstancesClusterKi(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::increasesPartition(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::numClusterEmpty(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster().
_vectorit_n
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM > std::vector<T_INSTANCES_CLUSTER_K> ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::_vectorit_n protected
Definition at line 657 of file partition_linked_stats.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeSumInstances(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumInstancesClusterK(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getNumInstancesClusterKi(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::numClusterEmpty(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster().
The documentation for this class was generated from the following file:
include/partition_linked_stats.hpp