Library Evolutionary Algorithms for Clustering (LEAC): inout::OutParamClusteringMetric< T_METRIC > Class Template Reference
inout::OutParamClusteringMetric< T_METRIC > Class Template Reference
Output parameters for a generic clustering algorithm.
#include <outparam_clustering.hpp>
Public Member Functions
OutParamClusteringMetric ()
virtual ~OutParamClusteringMetric ()
const uintidx getNumObjetiveFunc () const
void initialize (int aii_numRunAlgorithm)
void setMetricFunc (OutParamNameObjectiveFunc aienum_usedObjectiveFunc, T_METRIC ait_objetiveFunc)
void setMetricFuncTest (OutParamNameObjectiveFunc aienum_usedObjectiveFunc, T_METRIC ait_objetiveFuncTest)
T_METRIC getObjetiveFunc (OutParamNameObjectiveFunc aienum_metricFunc)
T_METRIC getObjetiveFuncTest (OutParamNameObjectiveFunc aienum_metricFunc)
void setUsedObjetiveFunc (const OutParamNameObjectiveFunc aienum_usedObjectiveFunc)
const OutParamNameObjectiveFunc getUsedObjetiveFunc ()
void setPercentageSensitivity (std::string aistr_percentageSensitivity)
const std::string & getPercentageSensitivity ()
void setPercentageSensitivityTest (std::string aistr_percentageSensitivityTest)
const std::string & getPercentageSensitivityTest ()
void setPercentageSpecificity (std::string aistr_percentageSpecificity)
const std::string & getPercentageSpecificity ()
void setPercentageSpecificityTest (std::string aistr_percentageSpecificityTest)
const std::string & getPercentageSpecificityTest ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Protected Attributes
T_METRIC * _arrayrt_metricFunc
T_METRIC * _arrayrt_metricFuncTest
std::string _str_percentageSensitivity
std::string _str_percentageSensitivityTest
std::string _str_percentageSpecificity
std::string _str_percentageSpecificityTest
Friends
std::ostream & operator<< (std::ostream &os, const OutParamClusteringMetric< T_METRIC > &aiom_outParamMetric)
Detailed Description
template<typename T_METRIC>
class inout::OutParamClusteringMetric< T_METRIC >
Output parameters for a generic clustering algorithm.
Definition at line 441 of file outparam_clustering.hpp.
Constructor & Destructor Documentation
OutParamClusteringMetric()
template<typename T_METRIC> inout::OutParamClusteringMetric< T_METRIC >::OutParamClusteringMetric () inline
Definition at line 444 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc, inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest, and inout::OutParamClusteringMetric< T_METRIC >::getNumObjetiveFunc().
~OutParamClusteringMetric()
template<typename T_METRIC> virtual inout::OutParamClusteringMetric< T_METRIC >::~OutParamClusteringMetric () inline virtual
Definition at line 459 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc, and inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest.
Member Function Documentation
getNumObjetiveFunc()
template<typename T_METRIC> const uintidx inout::OutParamClusteringMetric< T_METRIC >::getNumObjetiveFunc () const inline
Definition at line 465 of file outparam_clustering.hpp.
References inout::garray_nameObjetiveFunc.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::OutParamClusteringMetric(), and inout::OutParamClusteringMetric< T_METRIC >::print().
getObjetiveFunc()
template<typename T_METRIC> T_METRIC inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFunc (OutParamNameObjectiveFunc aienum_metricFunc) inline
Definition at line 507 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc.
Referenced by main().
getObjetiveFuncTest()
template<typename T_METRIC> T_METRIC inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFuncTest (OutParamNameObjectiveFunc aienum_metricFunc) inline
Definition at line 513 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest.
Referenced by main().
getPercentageSensitivity()
template<typename T_METRIC> const std::string& inout::OutParamClusteringMetric< T_METRIC >::getPercentageSensitivity () inline
Definition at line 533 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivity.
getPercentageSensitivityTest()
template<typename T_METRIC> const std::string& inout::OutParamClusteringMetric< T_METRIC >::getPercentageSensitivityTest () inline
Definition at line 543 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivityTest.
getPercentageSpecificity()
template<typename T_METRIC> const std::string& inout::OutParamClusteringMetric< T_METRIC >::getPercentageSpecificity () inline
Definition at line 553 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificity.
getPercentageSpecificityTest()
template<typename T_METRIC> const std::string& inout::OutParamClusteringMetric< T_METRIC >::getPercentageSpecificityTest () inline
Definition at line 563 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificityTest.
getUsedObjetiveFunc()
template<typename T_METRIC> const OutParamNameObjectiveFunc inout::OutParamClusteringMetric< T_METRIC >::getUsedObjetiveFunc () inline
Definition at line 523 of file outparam_clustering.hpp.
initialize()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::initialize (int aii_numRunAlgorithm) inline
Definition at line 479 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc, inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivity, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivityTest, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificity, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificityTest, inout::OutParamClusteringMetric< T_METRIC >::getNumObjetiveFunc(), and OUTPARAMCLUSTERING_METRIC_NaN.
Referenced by main().
print()
template<typename T_METRIC> virtual void inout::OutParamClusteringMetric< T_METRIC >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Definition at line 569 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc, inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivity, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivityTest, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificity, inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificityTest, inout::garray_nameObjetiveFunc, and inout::OutParamClusteringMetric< T_METRIC >::getNumObjetiveFunc().
Referenced by main().
setMetricFunc()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setMetricFunc (OutParamNameObjectiveFunc aienum_usedObjectiveFunc, T_METRIC ait_objetiveFunc) inline
Definition at line 493 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc.
Referenced by main().
setMetricFuncTest()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setMetricFuncTest (OutParamNameObjectiveFunc aienum_usedObjectiveFunc, T_METRIC ait_objetiveFuncTest) inline
Definition at line 500 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest.
Referenced by main().
setPercentageSensitivity()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivity (std::string aistr_percentageSensitivity) inline
Definition at line 528 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivity.
Referenced by main().
setPercentageSensitivityTest()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivityTest (std::string aistr_percentageSensitivityTest) inline
Definition at line 538 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivityTest.
Referenced by main().
setPercentageSpecificity()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificity (std::string aistr_percentageSpecificity) inline
Definition at line 548 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificity.
Referenced by main().
setPercentageSpecificityTest()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificityTest (std::string aistr_percentageSpecificityTest) inline
Definition at line 558 of file outparam_clustering.hpp.
References inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificityTest.
Referenced by main().
setUsedObjetiveFunc()
template<typename T_METRIC> void inout::OutParamClusteringMetric< T_METRIC >::setUsedObjetiveFunc (const OutParamNameObjectiveFunc aienum_usedObjectiveFunc) inline
Definition at line 518 of file outparam_clustering.hpp.
Friends And Related Function Documentation
operator<<
template<typename T_METRIC> std::ostream& operator<< (std::ostream & os, const OutParamClusteringMetric< T_METRIC > & aiom_outParamMetric) friend
Definition at line 597 of file outparam_clustering.hpp.
Member Data Documentation
_arrayrt_metricFunc
template<typename T_METRIC> T_METRIC* inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFunc protected
Definition at line 606 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFunc(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::OutParamClusteringMetric(), inout::OutParamClusteringMetric< T_METRIC >::print(), inout::OutParamClusteringMetric< T_METRIC >::setMetricFunc(), and inout::OutParamClusteringMetric< T_METRIC >::~OutParamClusteringMetric().
_arrayrt_metricFuncTest
template<typename T_METRIC> T_METRIC* inout::OutParamClusteringMetric< T_METRIC >::_arrayrt_metricFuncTest protected
Definition at line 607 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFuncTest(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::OutParamClusteringMetric(), inout::OutParamClusteringMetric< T_METRIC >::print(), inout::OutParamClusteringMetric< T_METRIC >::setMetricFuncTest(), and inout::OutParamClusteringMetric< T_METRIC >::~OutParamClusteringMetric().
_str_percentageSensitivity
template<typename T_METRIC> std::string inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivity protected
Definition at line 608 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getPercentageSensitivity(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::print(), and inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivity().
_str_percentageSensitivityTest
template<typename T_METRIC> std::string inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSensitivityTest protected
Definition at line 609 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getPercentageSensitivityTest(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::print(), and inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivityTest().
_str_percentageSpecificity
template<typename T_METRIC> std::string inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificity protected
Definition at line 610 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getPercentageSpecificity(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::print(), and inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificity().
_str_percentageSpecificityTest
template<typename T_METRIC> std::string inout::OutParamClusteringMetric< T_METRIC >::_str_percentageSpecificityTest protected
Definition at line 611 of file outparam_clustering.hpp.
Referenced by inout::OutParamClusteringMetric< T_METRIC >::getPercentageSpecificityTest(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), inout::OutParamClusteringMetric< T_METRIC >::print(), and inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificityTest().
The documentation for this class was generated from the following file:
include_inout/outparam_clustering.hpp