Library Evolutionary Algorithms for Clustering (LEAC): ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > Class Template Reference
ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > Class Template Reference
A data structure for managing an instance partition with the number of instances per cluster.
#include <partition_linked_numinst.hpp>
Public Member Functions
PartitionLinkedNumInst ()
PartitionLinkedNumInst (const uintidx aiuintidx_numInstances, const uintidx aiuintidx_numClusterK)
PartitionLinkedNumInst (PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &&aipartlink_b)
PartitionLinkedNumInst (const PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &aipartlink_b)
~PartitionLinkedNumInst ()
const T_INSTANCES_CLUSTER_K getNumInstClusterK (T_CLUSTERIDX aicidx_clusterK) const
const std::vector< T_INSTANCES_CLUSTER_K > & getVectorNumInstClusterK () const
const bool haveNullCluster () const
const T_CLUSTERIDX getNumNullCluster () const
PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & operator= (const PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &aipartlink_b)
PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & operator= (PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &&aipartlink_b)
void initialize ()
void addInstanceToCluster (const T_CLUSTERIDX aiT_clusterIdx, const uintidx aiidxiT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec=1)
void subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec=1)
void changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec=1)
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimClusterK=';')
Public Member Functions inherited from ds::PartitionLinked< T_CLUSTERIDX >
PartitionLinked ()
PartitionLinked (const uintidx aiui_numInstances, const uintidx aiui_numClusterK)
PartitionLinked (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
~PartitionLinked ()
void resize (const uintidx aiui_numClusterK)
const T_CLUSTERIDX getNumPartitions () const
const uintidx getFirstInstClusterK (T_CLUSTERIDX aicidx_clusterK)
const uintidx getNumInstances () const
PartitionLinked< T_CLUSTERIDX > & operator= (const PartitionLinked< T_CLUSTERIDX > &aipartlink_b)
PartitionLinked< T_CLUSTERIDX > & operator= (PartitionLinked< T_CLUSTERIDX > &&aipartlink_b)
void initialize ()
void addInstanceToCluster (T_CLUSTERIDX aiT_clusterIdx, uintidx aiidxiT_instanceI)
void subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI)
void changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI)
uintidx getInstanceIdxOfClusterK (T_CLUSTERIDX aicidx_clusterK, const uintidx aiuintidx_instanceNi)
void joinCluster (const T_CLUSTERIDX aiIdxK_clusterKFrom, const T_CLUSTERIDX aiIdxK_clusterKTo)
void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimClusterK=';')
Protected Attributes
std::vector< T_INSTANCES_CLUSTER_K > _vectorit_numInstClusterK
Protected Attributes inherited from ds::PartitionLinked< T_CLUSTERIDX >
std::vector< uintidx > _vectorInstIdx_firstClusterK
std::vector< uintidx > _vectorInstIdx_nextClusterK
Detailed Description
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K>
class ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >
A data structure for managing an instance partition with the number of instances per cluster.
Definition at line 43 of file partition_linked_numinst.hpp.
Constructor & Destructor Documentation
PartitionLinkedNumInst() [1/4]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::PartitionLinkedNumInst () inline
Definition at line 46 of file partition_linked_numinst.hpp.
PartitionLinkedNumInst() [2/4]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::PartitionLinkedNumInst (const uintidx aiuintidx_numInstances, const uintidx aiuintidx_numClusterK) inline
Definition at line 52 of file partition_linked_numinst.hpp.
PartitionLinkedNumInst() [3/4]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::PartitionLinkedNumInst (PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > && aipartlink_b) inline
Definition at line 63 of file partition_linked_numinst.hpp.
PartitionLinkedNumInst() [4/4]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::PartitionLinkedNumInst (const PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & aipartlink_b) inline
Definition at line 71 of file partition_linked_numinst.hpp.
~PartitionLinkedNumInst()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::~PartitionLinkedNumInst () inline
Definition at line 78 of file partition_linked_numinst.hpp.
Member Function Documentation
addInstanceToCluster()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> void ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::addInstanceToCluster (const T_CLUSTERIDX aiT_clusterIdx, const uintidx aiidxiT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec = 1) inline
Definition at line 145 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, and ds::PartitionLinked< T_CLUSTERIDX >::addInstanceToCluster().
Referenced by ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::changeMemberShip().
changeMemberShip()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> void ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::changeMemberShip (T_CLUSTERIDX aicidx_nearestClusterK, uintidx aiidxinstT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec = 1) inline
Definition at line 170 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::addInstanceToCluster(), NEARESTCENTROID_UNKNOWN, and ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::subInstanceFromCluster().
getNumInstClusterK()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> const T_INSTANCES_CLUSTER_K ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumInstClusterK (T_CLUSTERIDX aicidx_clusterK) const inline
Definition at line 83 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK.
Referenced by um::silhouette().
getNumNullCluster()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> const T_CLUSTERIDX ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumNullCluster () const inline
Definition at line 101 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK.
Referenced by um::silhouette().
getVectorNumInstClusterK()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> const std::vector<T_INSTANCES_CLUSTER_K>& ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getVectorNumInstClusterK () const inline
Definition at line 88 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK.
Referenced by eac::gga_vklabel(), and um::silhouette().
haveNullCluster()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> const bool ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::haveNullCluster () const inline
Definition at line 93 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK.
initialize()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> void ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::initialize () inline
Definition at line 133 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, interfacesse::copya(), and ds::PartitionLinked< T_CLUSTERIDX >::initialize().
operator=() [1/2]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> PartitionLinkedNumInst<T_CLUSTERIDX,T_INSTANCES_CLUSTER_K>& ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::operator= (const PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & aipartlink_b) inline
Definition at line 112 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, and ds::PartitionLinked< T_CLUSTERIDX >::operator=().
operator=() [2/2]
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> PartitionLinkedNumInst<T_CLUSTERIDX,T_INSTANCES_CLUSTER_K>& ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::operator= (PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > && aipartlink_b) inline
Definition at line 123 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, and ds::PartitionLinked< T_CLUSTERIDX >::operator=().
print()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> void ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimClusterK = ';') inline
Definition at line 183 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, inout::containerprint(), and ds::PartitionLinked< T_CLUSTERIDX >::print().
Referenced by um::silhouette().
subInstanceFromCluster()
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> void ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::subInstanceFromCluster (T_CLUSTERIDX aiidxmcT_clusterIdx, uintidx aiidxinstT_instanceI, const T_INSTANCES_CLUSTER_K aiit_numInstFrec = 1) inline
Definition at line 156 of file partition_linked_numinst.hpp.
References ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK, NEARESTCENTROID_UNKNOWN, and ds::PartitionLinked< T_CLUSTERIDX >::subInstanceFromCluster().
Referenced by ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::changeMemberShip().
Member Data Documentation
_vectorit_numInstClusterK
template<typename T_CLUSTERIDX, typename T_INSTANCES_CLUSTER_K> std::vector<T_INSTANCES_CLUSTER_K> ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::_vectorit_numInstClusterK protected
Definition at line 206 of file partition_linked_numinst.hpp.
Referenced by ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::addInstanceToCluster(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumInstClusterK(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumNullCluster(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getVectorNumInstClusterK(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::haveNullCluster(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::initialize(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::operator=(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::print(), and ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::subInstanceFromCluster().
The documentation for this class was generated from the following file:
include/partition_linked_numinst.hpp