Library Evolutionary Algorithms for Clustering (LEAC): runtime::ListRuntimeFunction< T_INTEGERDOMAIN > Class Template Reference
runtime::ListRuntimeFunction< T_INTEGERDOMAIN > Class Template Reference
ListRuntimeFunction store metrics in run time and count genetations.
#include <list_runtime_function.hpp>
Public Member Functions
ListRuntimeFunction (T_INTEGERDOMAIN aiiT_sizeInterval, const std::string &ais_labelX, const std::string &ais_labelY)
~ListRuntimeFunction ()
void initialize ()
void addFuntion (RuntimeFunction *aifh_functionHistNew)
std::vector< RuntimeFunction * > & getListRuntimeFunction ()
IntervalPositiveInteger< T_INTEGERDOMAIN > * getDomainInterval ()
T_INTEGERDOMAIN getDomainSize ()
T_INTEGERDOMAIN getDomainLowerBound ()
const T_INTEGERDOMAIN getDomainUpperBound () const
void setDomainSize (T_INTEGERDOMAIN aiT_integerDomain)
void increaseDomainUpperBound ()
std::string getLabelX ()
std::string getLabelY ()
uintidx getNumberFuntions ()
std::string getHeaderFuntions ()
const char getPlotStatSeparator () const
Private Attributes
std::string s_labelX
std::string s_labelY
IntervalPositiveInteger< T_INTEGERDOMAIN > * pIntervalZT_domain
std::vector< RuntimeFunction * > _vector_ptRuntimeFunction
char _c_plotStatSeparator
Friends
template<typename U_INTEGERDOMAIN >
std::ostream & operator<< (std::ostream &out, const ListRuntimeFunction< U_INTEGERDOMAIN > &ailfhT_listFuntionHist)
Detailed Description
template<typename T_INTEGERDOMAIN>
class runtime::ListRuntimeFunction< T_INTEGERDOMAIN >
ListRuntimeFunction store metrics in run time and count genetations.
Definition at line 38 of file list_runtime_function.hpp.
Constructor & Destructor Documentation
ListRuntimeFunction()
template<typename T_INTEGERDOMAIN> runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::ListRuntimeFunction (T_INTEGERDOMAIN aiiT_sizeInterval, const std::string & ais_labelX, const std::string & ais_labelY) inline
Definition at line 41 of file list_runtime_function.hpp.
~ListRuntimeFunction()
template<typename T_INTEGERDOMAIN> runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::~ListRuntimeFunction () inline
Definition at line 52 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction, and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
Member Function Documentation
addFuntion()
template<typename T_INTEGERDOMAIN> void runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::addFuntion (RuntimeFunction * aifh_functionHistNew) inline
Definition at line 70 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction.
getDomainInterval()
template<typename T_INTEGERDOMAIN> IntervalPositiveInteger<T_INTEGERDOMAIN>* runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainInterval () inline
Definition at line 82 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
getDomainLowerBound()
template<typename T_INTEGERDOMAIN> T_INTEGERDOMAIN runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainLowerBound () inline
Definition at line 92 of file list_runtime_function.hpp.
References runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getLowerBound(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
getDomainSize()
template<typename T_INTEGERDOMAIN> T_INTEGERDOMAIN runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainSize () inline
Definition at line 87 of file list_runtime_function.hpp.
References runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getSizeInterval(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
getDomainUpperBound()
template<typename T_INTEGERDOMAIN> const T_INTEGERDOMAIN runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainUpperBound () const inline
Definition at line 97 of file list_runtime_function.hpp.
References runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getUpperBound(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
Referenced by runtime::operator<<().
getHeaderFuntions()
template<typename T_INTEGERDOMAIN> std::string runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions () inline
Definition at line 128 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_c_plotStatSeparator, runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction, and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::s_labelX.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
getLabelX()
template<typename T_INTEGERDOMAIN> std::string runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getLabelX () inline
Definition at line 112 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::s_labelX.
getLabelY()
template<typename T_INTEGERDOMAIN> std::string runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getLabelY () inline
Definition at line 117 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::s_labelY.
getListRuntimeFunction()
template<typename T_INTEGERDOMAIN> std::vector<RuntimeFunction* >& runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getListRuntimeFunction () inline
Definition at line 76 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction.
getNumberFuntions()
template<typename T_INTEGERDOMAIN> uintidx runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getNumberFuntions () inline
Definition at line 122 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction.
getPlotStatSeparator()
template<typename T_INTEGERDOMAIN> const char runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getPlotStatSeparator () const inline
Definition at line 143 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_c_plotStatSeparator.
Referenced by runtime::operator<<().
increaseDomainUpperBound()
template<typename T_INTEGERDOMAIN> void runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::increaseDomainUpperBound () inline
Definition at line 107 of file list_runtime_function.hpp.
References runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::increaseUpperBound(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
Referenced by eac::gaclustering_vktreebinary().
initialize()
template<typename T_INTEGERDOMAIN> void runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::initialize () inline
Definition at line 60 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction, runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::initialize(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain.
setDomainSize()
template<typename T_INTEGERDOMAIN> void runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::setDomainSize (T_INTEGERDOMAIN aiT_integerDomain) inline
Definition at line 102 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain, and runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::setSizeInterval().
Friends And Related Function Documentation
operator<<
template<typename T_INTEGERDOMAIN> template<typename U_INTEGERDOMAIN > std::ostream& operator<< (std::ostream & out, const ListRuntimeFunction< U_INTEGERDOMAIN > & ailfhT_listFuntionHist) friend
Member Data Documentation
_c_plotStatSeparator
template<typename T_INTEGERDOMAIN> char runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_c_plotStatSeparator private
Definition at line 158 of file list_runtime_function.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getPlotStatSeparator().
_vector_ptRuntimeFunction
template<typename T_INTEGERDOMAIN> std::vector<RuntimeFunction* > runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction private
Definition at line 157 of file list_runtime_function.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::addFuntion(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getListRuntimeFunction(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getNumberFuntions(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::initialize(), runtime::operator<<(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::~ListRuntimeFunction().
pIntervalZT_domain
template<typename T_INTEGERDOMAIN> IntervalPositiveInteger<T_INTEGERDOMAIN>* runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::pIntervalZT_domain private
Definition at line 156 of file list_runtime_function.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainInterval(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainLowerBound(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainSize(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainUpperBound(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::increaseDomainUpperBound(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::initialize(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::setDomainSize(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::~ListRuntimeFunction().
s_labelX
template<typename T_INTEGERDOMAIN> std::string runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::s_labelX private
Definition at line 154 of file list_runtime_function.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getLabelX().
s_labelY
template<typename T_INTEGERDOMAIN> std::string runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::s_labelY private
Definition at line 155 of file list_runtime_function.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getLabelY().
The documentation for this class was generated from the following file:
include_inout/list_runtime_function.hpp