Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamGAClustering Class Reference
inout::InParamGAClustering Class Reference
Input parameter for genetic algorithm.
#include <inparam_gaclustering.hpp>
Public Member Functions
InParamGAClustering (const std::string &ais_algorithmoName, const std::string &ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamGAClustering ()
void setNumMaxGenerations (COMMON_IDOMAIN aiT_numMaxGenerations)
COMMON_IDOMAIN getNumMaxGenerations () const
void setSizePopulation (uintidx aist_sizePopulation)
uintidx getSizePopulation () const
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Public Member Functions inherited from inout::InParamClustering
InParamClustering (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opDistance)
~InParamClustering ()
char * getFileNamePlotStatObjetiveFunc () const
bool getWithPlotStatObjetiveFunc () const
void setFileNamePlotStatObjetiveFunc (char *aips_nameFile)
void setOutFileMemberShip (char *aips_fileName)
char * getOutFileMemberShip ()
void setRandomSeed (const std::string &aistr_randomSeed)
void setRandomSeed (const char *aipc_randomSeed)
const std::string & getRandomSeed () const
void setOutFilePartitionsTable (char *aips_fileName)
char * getOutFilePartitionsTable ()
void setOutFileCentroids (char *aips_fileName)
char * getOutFileCentroids ()
void setOpDistance (int aii_opDistance)
int getOpDistance ()
double getMaxExecutiontime ()
void setMaxExecutiontime (double aird_maxExecutiontime)
bool getPrintCentroidsFormat ()
void setPrintCentroidsFormat (bool aib_printCentroidsFormat)
bool getPrintTableFormat ()
void setPrintTableFormat (bool aib_printTableFormat)
void setOutFileGraph (char *aips_fileName)
char * getOutFileGraph ()
Public Member Functions inherited from inout::InParamAlgorithmo
InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut)
~InParamAlgorithmo ()
void errorArgument (char *apc_command, const char *apc_options, const char *aas_arguments[])
bool isYesNo (char *optarg, char *apc_command, const char *apc_options)
void setFileNameTimesRun (char *aips_nameFile)
void setProgressBarPrinting (bool aib_bool)
void setTimesRunAlgorithm (int aii_timesRun)
void setGnuPlotCoreStyles (const char *aips_nameCoreStyle)
std::string getAlgorithmoAuthor () const
std::string getAlgorithmoName () const
char * getFileNameTimesRun () const
int getTimesRunAlgorithm () const
bool getProgressBarPrinting ()
const std::string getGnuPlotCoreStyles () const
InParam_algTypeOut getAlgorithTypeOut ()
const std::string & getRunningTimeId ()
void setRunningTimeId (const std::string aistr_runTimeId)
Protected Attributes
uintidx st_sizePopulation
COMMON_IDOMAIN t_numMaxGenerations
Protected Attributes inherited from inout::InParamClustering
int i_opDistance
char * ps_outFileCentroids
char * ps_outFileMemberShip
char * ps_outFilePartitionsTable
char * ps_outFileGraph
char * ps_fileNamePlotStatObjetiveFunc
std::string _str_randomSeed
double _rd_maxExecutiontime
bool _b_printCentroidsFormat
bool _b_printTableFormat
Protected Attributes inherited from inout::InParamAlgorithmo
std::string s_algorithmoName
std::string s_algorithmoAuthor
InParam_algTypeOut ato_algTypeOut
char * ps_fileNameTimesRun
bool b_progressBarPrinting
int i_timesRunAlgorithm
std::string _s_runTimeId
std::string s_gnuplotCoreStyles
Detailed Description
Input parameter for genetic algorithm.
Definition at line 31 of file inparam_gaclustering.hpp.
Constructor & Destructor Documentation
InParamGAClustering()
inout::InParamGAClustering::InParamGAClustering (const std::string & ais_algorithmoName, const std::string & ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm) inline
Definition at line 36 of file inparam_gaclustering.hpp.
~InParamGAClustering()
inout::InParamGAClustering::~InParamGAClustering () inline
Definition at line 43 of file inparam_gaclustering.hpp.
Member Function Documentation
getNumMaxGenerations()
COMMON_IDOMAIN inout::InParamGAClustering::getNumMaxGenerations () const inline
Definition at line 50 of file inparam_gaclustering.hpp.
References t_numMaxGenerations.
getSizePopulation()
uintidx inout::InParamGAClustering::getSizePopulation () const inline
Definition at line 60 of file inparam_gaclustering.hpp.
References st_sizePopulation.
print()
virtual void inout::InParamGAClustering::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented from inout::InParamClustering.
Reimplemented in inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >, inout::InParamTGCA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPm< T_REAL >, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, and inout::InParamPm< T_REAL >.
Definition at line 65 of file inparam_gaclustering.hpp.
References inout::InParamClustering::print(), st_sizePopulation, and t_numMaxGenerations.
Referenced by inout::InParamPm< T_REAL >::print(), inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), inout::InParamPcPm< T_REAL >::print(), inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print().
setNumMaxGenerations()
void inout::InParamGAClustering::setNumMaxGenerations (COMMON_IDOMAIN aiT_numMaxGenerations) inline
Definition at line 45 of file inparam_gaclustering.hpp.
References t_numMaxGenerations.
setSizePopulation()
void inout::InParamGAClustering::setSizePopulation (uintidx aist_sizePopulation) inline
Definition at line 55 of file inparam_gaclustering.hpp.
References st_sizePopulation.
Member Data Documentation
st_sizePopulation
uintidx inout::InParamGAClustering::st_sizePopulation protected
Definition at line 74 of file inparam_gaclustering.hpp.
Referenced by getSizePopulation(), print(), and setSizePopulation().
t_numMaxGenerations
COMMON_IDOMAIN inout::InParamGAClustering::t_numMaxGenerations protected
Definition at line 75 of file inparam_gaclustering.hpp.
Referenced by getNumMaxGenerations(), print(), and setNumMaxGenerations().
The documentation for this class was generated from the following file:
include_inout/inparam_gaclustering.hpp