Library Evolutionary Algorithms for Clustering (LEAC): mat::BitMatrix< T_BITSIZE > Class Template Reference
mat::BitMatrix< T_BITSIZE > Class Template Reference
Bit matrix.
#include <bit_container.hpp>
Public Member Functions
BitMatrix ()
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns)
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns, T_BITSIZE *aiarrayT_data)
BitMatrix (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
BitMatrix (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
~BitMatrix ()
void initialize ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
void setAll ()
void toggleAll ()
void clearBit (uintidx i, uintidx j)
void setBit (uintidx i, uintidx j)
const T_BITSIZE * getRow (const uintidx i) const
T_BITSIZE * getRow (const uintidx i)
bool operator() (uintidx i, uintidx j) const
void copyAligned (BitMatrix< T_BITSIZE > &aibitmatrix_source, const uintidx aiui_idxTarget, const uintidx aiui_length)
uintidx getRowNumBitOn (uintidx aiui_rowi)
uintidx maxNorm ()
void copyUnaligned (uintidx aiui_idxTarget, BitMatrix< T_BITSIZE > &aibitmatrix_source, uintidx aiui_idxSource, uintidx aiui_length)
void print_listAdj (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimVert=',', const char aic_delimAdj=';') const
void printByColumns (std::ostream &os=std::cout, const uintidx aiui_numRows=80, const char aic_delimRow='\n') const
void opXor (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
opXor
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const
Protected Member Functions
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Protected Attributes
ds::BitContainer< T_BITSIZE > _bitContainer_data
uintidx _ui_numRows
uintidx _ui_numColumns
uintidx _st_numWordsRows
Private Member Functions
void _maskTopWord ()
Friends
std::ostream & operator<< (std::ostream &os, const BitMatrix< T_BITSIZE > &aibitmatrix_A)
Detailed Description
template<class T_BITSIZE>
class mat::BitMatrix< T_BITSIZE >
Bit matrix.
Definition at line 29 of file bit_container.hpp.
Constructor & Destructor Documentation
BitMatrix() [1/5]
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::BitMatrix () inline
Definition at line 46 of file bit_matrix.hpp.
BitMatrix() [2/5]
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns) inline
Definition at line 54 of file bit_matrix.hpp.
BitMatrix() [3/5]
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns, T_BITSIZE * aiarrayT_data) inline
Definition at line 65 of file bit_matrix.hpp.
BitMatrix() [4/5]
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::BitMatrix (const BitMatrix< T_BITSIZE > & aibitmatrixb_B) inline
Definition at line 76 of file bit_matrix.hpp.
BitMatrix() [5/5]
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::BitMatrix (BitMatrix< T_BITSIZE > && aibitmatrixb_B) inline
Definition at line 84 of file bit_matrix.hpp.
~BitMatrix()
template<class T_BITSIZE> mat::BitMatrix< T_BITSIZE >::~BitMatrix () inline
Definition at line 127 of file bit_matrix.hpp.
Member Function Documentation
_maskTopWord()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::_maskTopWord () inline private
Definition at line 514 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, mat::BitMatrix< T_BITSIZE >::_ui_numRows, and mat::BitMatrix< T_BITSIZE >::getRow().
Referenced by mat::BitMatrix< T_BITSIZE >::setAll(), and mat::BitMatrix< T_BITSIZE >::toggleAll().
_setNumColumns()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::_setNumColumns (uintidx aiui_numColumns) inline protected
Definition at line 532 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_ui_numColumns.
_setNumRows()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::_setNumRows (uintidx aiui_numRows) inline protected
Definition at line 527 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_ui_numRows.
clearBit()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::clearBit (uintidx i, uintidx j) inline
Definition at line 164 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_st_numWordsRows.
Referenced by mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember().
copyAligned()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::copyAligned (BitMatrix< T_BITSIZE > & aibitmatrix_source, const uintidx aiui_idxTarget, const uintidx aiui_length) inline
Definition at line 194 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numRows, ds::BitContainer< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::getNumRows(), mat::BitMatrix< T_BITSIZE >::getRow(), mat::BitMatrix< T_BITSIZE >::print(), and ds::BitContainer< T_BITSIZE >::setArray().
Referenced by gabinaryop::onePointDistCrossover().
copyUnaligned()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::copyUnaligned (uintidx aiui_idxTarget, BitMatrix< T_BITSIZE > & aibitmatrix_source, uintidx aiui_idxSource, uintidx aiui_length) inline
Definition at line 342 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numRows, ds::BitContainer< T_BITSIZE >::copyUnaligned(), mat::BitMatrix< T_BITSIZE >::getRow(), and ds::BitContainer< T_BITSIZE >::setArray().
getNumColumns()
template<class T_BITSIZE> const uintidx mat::BitMatrix< T_BITSIZE >::getNumColumns () const inline
Definition at line 139 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_ui_numColumns.
Referenced by mat::bitgemm(), gabinaryop::bitMutation(), gabinaryop::onePointDistCrossover(), mat::BitMatrix< T_BITSIZE >::print(), mat::BitMatrix< T_BITSIZE >::printByColumns(), and clusteringop::randomInitialize().
getNumElems()
template<class T_BITSIZE> const uintidx mat::BitMatrix< T_BITSIZE >::getNumElems () const inline
Definition at line 144 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_ui_numColumns, and mat::BitMatrix< T_BITSIZE >::_ui_numRows.
getNumRows()
template<class T_BITSIZE> const uintidx mat::BitMatrix< T_BITSIZE >::getNumRows () const inline
Definition at line 134 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_ui_numRows.
Referenced by mat::bitgemm(), gabinaryop::bitMutation(), mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getMember(), gabinaryop::onePointDistCrossover(), mat::BitMatrix< T_BITSIZE >::print(), and clusteringop::randomInitialize().
getRow() [1/2]
template<class T_BITSIZE> const T_BITSIZE* mat::BitMatrix< T_BITSIZE >::getRow (const uintidx i) const inline
Definition at line 176 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_st_numWordsRows.
Referenced by mat::BitMatrix< T_BITSIZE >::_maskTopWord(), mat::bitgemm(), mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::copyUnaligned(), mat::BitMatrix< T_BITSIZE >::getRowNumBitOn(), mat::BitMatrix< T_BITSIZE >::maxNorm(), mat::BitMatrix< T_BITSIZE >::print(), mat::BitMatrix< T_BITSIZE >::print_listAdj(), and mat::BitMatrix< T_BITSIZE >::printByColumns().
getRow() [2/2]
template<class T_BITSIZE> T_BITSIZE* mat::BitMatrix< T_BITSIZE >::getRow (const uintidx i) inline
Definition at line 181 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_st_numWordsRows.
getRowNumBitOn()
template<class T_BITSIZE> uintidx mat::BitMatrix< T_BITSIZE >::getRowNumBitOn (uintidx aiui_rowi) inline
Definition at line 271 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, ds::BitContainer< T_BITSIZE >::getNumBitOn(), mat::BitMatrix< T_BITSIZE >::getRow(), and ds::BitContainer< T_BITSIZE >::setArray().
initialize()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::initialize () inline
Definition at line 129 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data.
Referenced by graph::getAdjacencyMatrix(), clusteringop::initializeOptimal(), and clusteringop::randomInitialize().
maxNorm()
template<class T_BITSIZE> uintidx mat::BitMatrix< T_BITSIZE >::maxNorm () inline
Definition at line 305 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numRows, ds::BitContainer< T_BITSIZE >::getNumBitOn(), mat::BitMatrix< T_BITSIZE >::getRow(), and ds::BitContainer< T_BITSIZE >::setArray().
operator()()
template<class T_BITSIZE> bool mat::BitMatrix< T_BITSIZE >::operator() (uintidx i, uintidx j) const inline
Definition at line 186 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_st_numWordsRows.
operator=() [1/2]
template<class T_BITSIZE> BitMatrix<T_BITSIZE>& mat::BitMatrix< T_BITSIZE >::operator= (BitMatrix< T_BITSIZE > && aibitmatrixb_B) inline
Definition at line 95 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, and mat::BitMatrix< T_BITSIZE >::_ui_numRows.
Referenced by mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::operator=().
operator=() [2/2]
template<class T_BITSIZE> BitMatrix<T_BITSIZE>& mat::BitMatrix< T_BITSIZE >::operator= (const BitMatrix< T_BITSIZE > & aibitmatrixb_B) inline
Definition at line 112 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, mat::BitMatrix< T_BITSIZE >::_st_numWordsRows, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, and mat::BitMatrix< T_BITSIZE >::_ui_numRows.
opXor()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::opXor (const BitMatrix< T_BITSIZE > & aibitmatrixb_B) inline
opXor
xor
Definition at line 457 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data.
print()
template<class T_BITSIZE> virtual void mat::BitMatrix< T_BITSIZE >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = '\n') const inline virtual
Reimplemented in gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >.
Definition at line 463 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, mat::BitMatrix< T_BITSIZE >::_ui_numRows, mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumRows(), and mat::BitMatrix< T_BITSIZE >::getRow().
Referenced by gabinaryop::bitMutation(), mat::BitMatrix< T_BITSIZE >::copyAligned(), clusteringop::getPartition(), clusteringop::initializeOptimal(), gabinaryop::onePointDistCrossover(), gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::print(), and clusteringop::randomInitialize().
print_listAdj()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::print_listAdj (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimVert = ',', const char aic_delimAdj = ';') const inline
Definition at line 385 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, mat::BitMatrix< T_BITSIZE >::_ui_numRows, and mat::BitMatrix< T_BITSIZE >::getRow().
Referenced by graph::getAdjacencyMatrix().
printByColumns()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::printByColumns (std::ostream & os = std::cout, const uintidx aiui_numRows = 80, const char aic_delimRow = '\n') const inline
Definition at line 419 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, mat::BitMatrix< T_BITSIZE >::_ui_numColumns, mat::BitMatrix< T_BITSIZE >::_ui_numRows, mat::BitMatrix< T_BITSIZE >::getNumColumns(), and mat::BitMatrix< T_BITSIZE >::getRow().
setAll()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::setAll () inline
Definition at line 152 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_maskTopWord().
setBit()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::setBit (uintidx i, uintidx j) inline
Definition at line 170 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_st_numWordsRows.
Referenced by graph::getAdjacencyMatrix(), clusteringop::initializeOptimal(), clusteringop::randomInitialize(), and mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember().
toggleAll()
template<class T_BITSIZE> void mat::BitMatrix< T_BITSIZE >::toggleAll () inline
Definition at line 158 of file bit_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::_bitContainer_data, and mat::BitMatrix< T_BITSIZE >::_maskTopWord().
Friends And Related Function Documentation
operator<<
template<class T_BITSIZE> std::ostream& operator<< (std::ostream & os, const BitMatrix< T_BITSIZE > & aibitmatrix_A) friend
Definition at line 506 of file bit_matrix.hpp.
Member Data Documentation
_bitContainer_data
template<class T_BITSIZE> ds::BitContainer<T_BITSIZE> mat::BitMatrix< T_BITSIZE >::_bitContainer_data protected
Definition at line 537 of file bit_matrix.hpp.
Referenced by mat::BitMatrix< T_BITSIZE >::clearBit(), mat::BitMatrix< T_BITSIZE >::getRow(), mat::BitMatrix< T_BITSIZE >::initialize(), mat::BitMatrix< T_BITSIZE >::operator()(), mat::BitMatrix< T_BITSIZE >::operator=(), mat::BitMatrix< T_BITSIZE >::opXor(), mat::BitMatrix< T_BITSIZE >::print(), mat::BitMatrix< T_BITSIZE >::print_listAdj(), mat::BitMatrix< T_BITSIZE >::printByColumns(), mat::BitMatrix< T_BITSIZE >::setAll(), mat::BitMatrix< T_BITSIZE >::setBit(), and mat::BitMatrix< T_BITSIZE >::toggleAll().
_st_numWordsRows
template<class T_BITSIZE> uintidx mat::BitMatrix< T_BITSIZE >::_st_numWordsRows protected
Definition at line 540 of file bit_matrix.hpp.
Referenced by mat::BitMatrix< T_BITSIZE >::_maskTopWord(), mat::BitMatrix< T_BITSIZE >::clearBit(), mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::copyUnaligned(), mat::BitMatrix< T_BITSIZE >::getRow(), mat::BitMatrix< T_BITSIZE >::getRowNumBitOn(), mat::BitMatrix< T_BITSIZE >::maxNorm(), mat::BitMatrix< T_BITSIZE >::operator()(), mat::BitMatrix< T_BITSIZE >::operator=(), and mat::BitMatrix< T_BITSIZE >::setBit().
_ui_numColumns
template<class T_BITSIZE> uintidx mat::BitMatrix< T_BITSIZE >::_ui_numColumns protected
Definition at line 539 of file bit_matrix.hpp.
Referenced by mat::BitMatrix< T_BITSIZE >::_maskTopWord(), mat::BitMatrix< T_BITSIZE >::_setNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumElems(), mat::BitMatrix< T_BITSIZE >::operator=(), mat::BitMatrix< T_BITSIZE >::print(), mat::BitMatrix< T_BITSIZE >::print_listAdj(), and mat::BitMatrix< T_BITSIZE >::printByColumns().
_ui_numRows
template<class T_BITSIZE> uintidx mat::BitMatrix< T_BITSIZE >::_ui_numRows protected
Definition at line 538 of file bit_matrix.hpp.
Referenced by mat::BitMatrix< T_BITSIZE >::_maskTopWord(), mat::BitMatrix< T_BITSIZE >::_setNumRows(), mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::copyUnaligned(), mat::BitMatrix< T_BITSIZE >::getNumElems(), mat::BitMatrix< T_BITSIZE >::getNumRows(), mat::BitMatrix< T_BITSIZE >::maxNorm(), mat::BitMatrix< T_BITSIZE >::operator=(), mat::BitMatrix< T_BITSIZE >::print(), mat::BitMatrix< T_BITSIZE >::print_listAdj(), and mat::BitMatrix< T_BITSIZE >::printByColumns().
The documentation for this class was generated from the following files:
include/bit_container.hpp
include/bit_matrix.hpp