Library Evolutionary Algorithms for Clustering (LEAC): mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > Class Template Reference
mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > Class Template Reference
Bit crisp matrix.
#include <crisp_matrix.hpp>
Public Member Functions
CrispMatrix ()
CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns)
CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_BITSIZE *aiarrayT_data)
CrispMatrix (const CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aibitcrispmatrix_B)
CrispMatrix (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &&aibitcrispmatrix_B)
virtual ~CrispMatrix ()
mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & operator= (const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aibitcrispmatrix_B)
mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & operator= (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &&aibitcrispmatrix_B)
const T_CLUSTERIDX getMember (uintidx aiuintidx_instanceIdx) const
bool setMember (uintidx aiuintidx_instanceIdx, T_CLUSTERIDX aimgidxT_memberCluster)
Public Member Functions inherited from mat::BitMatrix< T_BITSIZE >
BitMatrix ()
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns)
BitMatrix (const uintidx aiui_numRows, const uintidx aiui_numColumns, T_BITSIZE *aiarrayT_data)
BitMatrix (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
BitMatrix (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (BitMatrix< T_BITSIZE > &&aibitmatrixb_B)
BitMatrix< T_BITSIZE > & operator= (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
~BitMatrix ()
void initialize ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
void setAll ()
void toggleAll ()
void clearBit (uintidx i, uintidx j)
void setBit (uintidx i, uintidx j)
const T_BITSIZE * getRow (const uintidx i) const
T_BITSIZE * getRow (const uintidx i)
bool operator() (uintidx i, uintidx j) const
void copyAligned (BitMatrix< T_BITSIZE > &aibitmatrix_source, const uintidx aiui_idxTarget, const uintidx aiui_length)
uintidx getRowNumBitOn (uintidx aiui_rowi)
uintidx maxNorm ()
void copyUnaligned (uintidx aiui_idxTarget, BitMatrix< T_BITSIZE > &aibitmatrix_source, uintidx aiui_idxSource, uintidx aiui_length)
void print_listAdj (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimVert=',', const char aic_delimAdj=';') const
void printByColumns (std::ostream &os=std::cout, const uintidx aiui_numRows=80, const char aic_delimRow='\n') const
void opXor (const BitMatrix< T_BITSIZE > &aibitmatrixb_B)
opXor
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const
Additional Inherited Members
Protected Member Functions inherited from mat::BitMatrix< T_BITSIZE >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Protected Attributes inherited from mat::BitMatrix< T_BITSIZE >
ds::BitContainer< T_BITSIZE > _bitContainer_data
uintidx _ui_numRows
uintidx _ui_numColumns
uintidx _st_numWordsRows
Detailed Description
template<class T_BITSIZE, class T_CLUSTERIDX>
class mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >
Bit crisp matrix.
Definition at line 36 of file crisp_matrix.hpp.
Constructor & Destructor Documentation
CrispMatrix() [1/5]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::CrispMatrix () inline
Definition at line 38 of file crisp_matrix.hpp.
CrispMatrix() [2/5]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns) inline
Definition at line 43 of file crisp_matrix.hpp.
CrispMatrix() [3/5]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::CrispMatrix (const uintidx aiuintidx_numRows, const uintidx aiuintidx_numColumns, T_BITSIZE * aiarrayT_data) inline
Definition at line 50 of file crisp_matrix.hpp.
CrispMatrix() [4/5]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::CrispMatrix (const CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aibitcrispmatrix_B) inline
Definition at line 59 of file crisp_matrix.hpp.
CrispMatrix() [5/5]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::CrispMatrix (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > && aibitcrispmatrix_B) inline
Definition at line 68 of file crisp_matrix.hpp.
~CrispMatrix()
template<class T_BITSIZE, class T_CLUSTERIDX> virtual mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::~CrispMatrix () inline virtual
Definition at line 75 of file crisp_matrix.hpp.
Member Function Documentation
getMember()
template<class T_BITSIZE, class T_CLUSTERIDX> const T_CLUSTERIDX mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getMember (uintidx aiuintidx_instanceIdx) const inline
Definition at line 99 of file crisp_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::getNumRows().
Referenced by gabinaryop::bitMutation(), and mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember().
operator=() [1/2]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix<T_BITSIZE,T_CLUSTERIDX>& mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::operator= (const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aibitcrispmatrix_B) inline
Definition at line 79 of file crisp_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::operator=().
Referenced by gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_METRIC >::operator=().
operator=() [2/2]
template<class T_BITSIZE, class T_CLUSTERIDX> mat::CrispMatrix<T_BITSIZE,T_CLUSTERIDX>& mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::operator= (CrispMatrix< T_BITSIZE, T_CLUSTERIDX > && aibitcrispmatrix_B) inline
Definition at line 90 of file crisp_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::operator=().
setMember()
template<class T_BITSIZE, class T_CLUSTERIDX> bool mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember (uintidx aiuintidx_instanceIdx, T_CLUSTERIDX aimgidxT_memberCluster) inline
Definition at line 109 of file crisp_matrix.hpp.
References mat::BitMatrix< T_BITSIZE >::clearBit(), mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getMember(), and mat::BitMatrix< T_BITSIZE >::setBit().
Referenced by gabinaryop::bitMutation(), and clusteringop::getPartition().
The documentation for this class was generated from the following file:
include/crisp_matrix.hpp