Library Evolutionary Algorithms for Clustering (LEAC): mat::BitArray< T_BITSIZE > Class Template Reference
mat::BitArray< T_BITSIZE > Class Template Reference
Bit array.
#include <bit_array.hpp>
Public Member Functions
BitArray ()
BitArray (const uintidx aiintidx_numBits)
BitArray (const uintidx aiintidx_numBits, T_BITSIZE *aiarrayT_data)
BitArray (const BitArray< T_BITSIZE > &aibitarray_B)
BitArray (const BitArray< T_BITSIZE > &&aibitarray_B)
BitArray< T_BITSIZE > & operator= (BitArray< T_BITSIZE > &&aibitarray_B)
BitArray< T_BITSIZE > & operator= (const BitArray< T_BITSIZE > &aibitarray_B)
~BitArray ()
void initializeOn ()
void toggleAll ()
uintidx size () const
void print (std::ostream &os=std::cout, const char *aipc_label="") const
Public Member Functions inherited from ds::BitContainer< T_BITSIZE >
BitContainer ()
BitContainer (const uintidx aiuintidx_numWords)
BitContainer (const uintidx aiuintidx_numWords, T_BITSIZE *aiarrayit_data)
BitContainer (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
BitContainer (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
virtual ~BitContainer ()
ds::BitContainer< T_BITSIZE > & operator= (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
ds::BitContainer< T_BITSIZE > & operator= (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
void setArray (T_BITSIZE *aiarrayit_data)
T_BITSIZE * toArray ()
void initialize ()
initialize
void initializeOn ()
initializeOn:
void toggleAll ()
toggleAll
void clearBit (uintidx i)
void setBit (uintidx i)
void toggleBit (uintidx i)
void assignBit (uintidx i, bool aib_bit)
bool getBit (uintidx i) const
uintidx getNumBitOn () const
std::list< uintidx > getIdxWithBitOn () const
void opXor (const ds::BitContainer< T_BITSIZE > &aibitc_bits)
opXor
void copyAligned (const ds::BitContainer< T_BITSIZE > &aibitc_source, const uintidx aiuintidx_idxTarget, uintidx aiuintidx_length)
void copyUnaligned (uintidx aiuintidx_idxTarget, BitContainer< T_BITSIZE > &aibitc_source, uintidx aiuintidx_idxSource, uintidx aiuintidx_length)
void print (std::ostream &os=std::cout, const char *aipc_label="") const
Protected Attributes
uintidx _uintidx_numBits
Protected Attributes inherited from ds::BitContainer< T_BITSIZE >
uintidx _uintidx_numWords
T_BITSIZE * _arrayuit_data
bool b_externalData
Private Member Functions
void _maskTopWord ()
Friends
std::ostream & operator<< (std::ostream &os, const BitArray< T_BITSIZE > &aibitarray_B)
Additional Inherited Members
Static Public Member Functions inherited from ds::BitContainer< T_BITSIZE >
static const uintidx _getNumWords (uintidx aiuintidx_numBits)
_getNumWords
Static Public Attributes inherited from ds::BitContainer< T_BITSIZE >
static const unsigned short int _stusi_numBitsWords
static const T_BITSIZE t_wordMax = (~(T_BITSIZE)0)
Protected Member Functions inherited from ds::BitContainer< T_BITSIZE >
unsigned short int _getBitOffset (uintidx b) const
uintidx _bits_in_top_word (uintidx b)
uintidx _getWordIndexBit (uintidx b) const
T_BITSIZE _bitMask (uintidx length)
Detailed Description
template<class T_BITSIZE>
class mat::BitArray< T_BITSIZE >
Bit array.
Definition at line 43 of file bit_array.hpp.
Constructor & Destructor Documentation
BitArray() [1/5]
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::BitArray () inline
Definition at line 45 of file bit_array.hpp.
BitArray() [2/5]
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::BitArray (const uintidx aiintidx_numBits) inline
Definition at line 50 of file bit_array.hpp.
BitArray() [3/5]
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::BitArray (const uintidx aiintidx_numBits, T_BITSIZE * aiarrayT_data) inline
Definition at line 55 of file bit_array.hpp.
BitArray() [4/5]
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::BitArray (const BitArray< T_BITSIZE > & aibitarray_B) inline
Definition at line 62 of file bit_array.hpp.
BitArray() [5/5]
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::BitArray (const BitArray< T_BITSIZE > && aibitarray_B) inline
Definition at line 68 of file bit_array.hpp.
~BitArray()
template<class T_BITSIZE> mat::BitArray< T_BITSIZE >::~BitArray () inline
Definition at line 96 of file bit_array.hpp.
Member Function Documentation
_maskTopWord()
template<class T_BITSIZE> void mat::BitArray< T_BITSIZE >::_maskTopWord () inline private
Definition at line 154 of file bit_array.hpp.
References ds::BitContainer< T_BITSIZE >::_bitMask(), ds::BitContainer< T_BITSIZE >::_bits_in_top_word(), mat::BitArray< T_BITSIZE >::_uintidx_numBits, and ds::BitContainer< T_BITSIZE >::_uintidx_numWords.
Referenced by mat::BitArray< T_BITSIZE >::initializeOn(), and mat::BitArray< T_BITSIZE >::toggleAll().
initializeOn()
template<class T_BITSIZE> void mat::BitArray< T_BITSIZE >::initializeOn () inline
Definition at line 103 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_maskTopWord().
operator=() [1/2]
template<class T_BITSIZE> BitArray<T_BITSIZE>& mat::BitArray< T_BITSIZE >::operator= (BitArray< T_BITSIZE > && aibitarray_B) inline
Definition at line 75 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_uintidx_numBits, and ds::BitContainer< T_BITSIZE >::operator=().
Referenced by gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::operator=().
operator=() [2/2]
template<class T_BITSIZE> BitArray<T_BITSIZE>& mat::BitArray< T_BITSIZE >::operator= (const BitArray< T_BITSIZE > & aibitarray_B) inline
Definition at line 86 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_uintidx_numBits, and ds::BitContainer< T_BITSIZE >::operator=().
print()
template<class T_BITSIZE> void mat::BitArray< T_BITSIZE >::print (std::ostream & os = std::cout, const char * aipc_label = "") const inline
Definition at line 123 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_uintidx_numBits, ds::BitContainer< T_BITSIZE >::getBit(), and ds::BitContainer< T_BITSIZE >::getNumBitOn().
Referenced by clusteringop::getClusters(), and gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print().
size()
template<class T_BITSIZE> uintidx mat::BitArray< T_BITSIZE >::size () const inline
Definition at line 117 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_uintidx_numBits.
Referenced by gabinaryop::bitMutation(), gabinaryop::eachBitArrayMutation(), clusteringop::getClusters(), gabinaryop::initializeGenes(), gabinaryop::onePointCrossover(), gabinaryop::onePointDistCrossover(), and gabinaryop::uniformCrossover().
toggleAll()
template<class T_BITSIZE> void mat::BitArray< T_BITSIZE >::toggleAll () inline
Definition at line 109 of file bit_array.hpp.
References mat::BitArray< T_BITSIZE >::_maskTopWord(), and ds::BitContainer< T_BITSIZE >::toggleAll().
Friends And Related Function Documentation
operator<<
template<class T_BITSIZE> std::ostream& operator<< (std::ostream & os, const BitArray< T_BITSIZE > & aibitarray_B) friend
Definition at line 145 of file bit_array.hpp.
Member Data Documentation
_uintidx_numBits
template<class T_BITSIZE> uintidx mat::BitArray< T_BITSIZE >::_uintidx_numBits protected
Definition at line 168 of file bit_array.hpp.
Referenced by mat::BitArray< T_BITSIZE >::_maskTopWord(), mat::BitArray< T_BITSIZE >::operator=(), mat::BitArray< T_BITSIZE >::print(), and mat::BitArray< T_BITSIZE >::size().
The documentation for this class was generated from the following file:
include/bit_array.hpp