Library Evolutionary Algorithms for Clustering (LEAC): mat::MatrixResizableRow< T_FEATURE, T_WEIGHT > Class Template Reference
mat::MatrixResizableRow< T_FEATURE, T_WEIGHT > Class Template Reference
MatrixResizableRow [17].
#include <matrix_resizablerow.hpp>
Public Member Functions
MatrixResizableRow ()
MatrixResizableRow (const uintidx aiui_numRows, const uintidx aiui_numColumns, const uintidx aiui_numRowsMaximum)
MatrixResizableRow (const MatrixResizableRow< T_FEATURE, T_WEIGHT > &aimatrixresizerow_B)
MatrixResizableRow (MatrixResizableRow< T_FEATURE, T_WEIGHT > &&aimatrixresizerow_B)
virtual ~MatrixResizableRow ()
MatrixResizableRow< T_FEATURE, T_WEIGHT > & operator= (const MatrixResizableRow< T_FEATURE, T_WEIGHT > &B)
MatrixResizableRow< T_FEATURE, T_WEIGHT > & operator= (MatrixResizableRow< T_FEATURE, T_WEIGHT > &&aimatrixresizerow_B)
void resize (const uintidx aiui_numRowsMaximum)
void merge (const MatrixResizableRow< T_FEATURE, T_WEIGHT > &aimatrixresizerow_B, const MatrixResizableRow< T_FEATURE, T_WEIGHT > &aimatrixresizerow_C)
const uintidx getNumElemsMaximum () const
const uintidx getNumRowsMaximum () const
const T_FEATURE * toArray () const
T_FEATURE * toArray ()
void initialize ()
const T_FEATURE * getRow (const uintidx i) const
T_FEATURE * getRow (const uintidx i)
void decreaseRow ()
void increasesRow ()
void mergeTwoRow (std::pair< uintidx, uintidx > aipairst_idxRow, T_WEIGHT aiT_weightRowFirst, T_WEIGHT aiT_weightRowSecond)
void copyRow (const uintidx aiui_idxFrom, const uintidx aiui_idxTo)
void copyRows (const MatrixResizableRow< T_FEATURE, T_WEIGHT > &B, const uintidx aiui_idxRows)
void swapRows (const uintidx i, const uintidx j)
void removeRow (const uintidx aiui_idxRow)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow='\n') const
Public Member Functions inherited from mat::MatrixBase< T_FEATURE >
MatrixBase ()
MatrixBase (const uintidx aiui_numRows)
MatrixBase (const uintidx aiui_numRows, const uintidx aiui_numColumns)
MatrixBase (MatrixBase< T_FEATURE > &&B)
MatrixBase (const MatrixBase< T_FEATURE > &B)
virtual ~MatrixBase ()
const uintidx getNumRows () const
const uintidx getNumColumns () const
const uintidx getNumElems () const
MatrixBase< T_FEATURE > & operator= (const MatrixBase< T_FEATURE > &B)
MatrixBase< T_FEATURE > & operator= (MatrixBase< T_FEATURE > &&B)
Protected Attributes
uintidx _ui_numRowsMaximum
T_FEATURE * _arrayt_data
Protected Attributes inherited from mat::MatrixBase< T_FEATURE >
uintidx _ui_numRows
uintidx _ui_numColumns
Additional Inherited Members
Protected Member Functions inherited from mat::MatrixBase< T_FEATURE >
void _setNumRows (uintidx aiui_numRows)
void _setNumColumns (uintidx aiui_numColumns)
Detailed Description
template<class T_FEATURE, class T_WEIGHT>
class mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >
MatrixResizableRow [17].
Definition at line 40 of file matrix_resizablerow.hpp.
Constructor & Destructor Documentation
MatrixResizableRow() [1/4]
template<class T_FEATURE, class T_WEIGHT> mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::MatrixResizableRow () inline
Definition at line 42 of file matrix_resizablerow.hpp.
MatrixResizableRow() [2/4]
template<class T_FEATURE, class T_WEIGHT> mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::MatrixResizableRow (const uintidx aiui_numRows, const uintidx aiui_numColumns, const uintidx aiui_numRowsMaximum) inline
Definition at line 49 of file matrix_resizablerow.hpp.
MatrixResizableRow() [3/4]
template<class T_FEATURE, class T_WEIGHT> mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::MatrixResizableRow (const MatrixResizableRow< T_FEATURE, T_WEIGHT > & aimatrixresizerow_B) inline
Definition at line 62 of file matrix_resizablerow.hpp.
MatrixResizableRow() [4/4]
template<class T_FEATURE, class T_WEIGHT> mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::MatrixResizableRow (MatrixResizableRow< T_FEATURE, T_WEIGHT > && aimatrixresizerow_B) inline
Definition at line 79 of file matrix_resizablerow.hpp.
~MatrixResizableRow()
template<class T_FEATURE, class T_WEIGHT> virtual mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::~MatrixResizableRow () inline virtual
Definition at line 88 of file matrix_resizablerow.hpp.
Member Function Documentation
copyRow()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::copyRow (const uintidx aiui_idxFrom, const uintidx aiui_idxTo) inline
Definition at line 446 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::removeRow().
copyRows()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::copyRows (const MatrixResizableRow< T_FEATURE, T_WEIGHT > & B, const uintidx aiui_idxRows) inline
Definition at line 456 of file matrix_resizablerow.hpp.
decreaseRow()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::decreaseRow () inline
Definition at line 310 of file matrix_resizablerow.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::decreasePartition(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::removeRow().
getNumElemsMaximum()
template<class T_FEATURE, class T_WEIGHT> const uintidx mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getNumElemsMaximum () const inline
Definition at line 270 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::initialize(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::operator=().
getNumRowsMaximum()
template<class T_FEATURE, class T_WEIGHT> const uintidx mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getNumRowsMaximum () const inline
Definition at line 275 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::decreaseRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::increasesRow(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize().
getRow() [1/2]
template<class T_FEATURE, class T_WEIGHT> const T_FEATURE* mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow (const uintidx i) const inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Definition at line 296 of file matrix_resizablerow.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeSumInstances(), gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::checkChangedCodeVectors(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRow(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getSumInstancesClusterKi(), gaclusteringop::merge(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::swapRows().
getRow() [2/2]
template<class T_FEATURE, class T_WEIGHT> T_FEATURE* mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow (const uintidx i) inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Definition at line 303 of file matrix_resizablerow.hpp.
increasesRow()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::increasesRow () inline
Definition at line 318 of file matrix_resizablerow.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::increasesPartition().
initialize()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::initialize () inline
Definition at line 290 of file matrix_resizablerow.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats().
merge()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::merge (const MatrixResizableRow< T_FEATURE, T_WEIGHT > & aimatrixresizerow_B, const MatrixResizableRow< T_FEATURE, T_WEIGHT > & aimatrixresizerow_C) inline
Definition at line 190 of file matrix_resizablerow.hpp.
Referenced by gaclusteringop::merge().
mergeTwoRow()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::mergeTwoRow (std::pair< uintidx, uintidx > aipairst_idxRow, T_WEIGHT aiT_weightRowFirst, T_WEIGHT aiT_weightRowSecond) inline
Definition at line 327 of file matrix_resizablerow.hpp.
operator=() [1/2]
template<class T_FEATURE, class T_WEIGHT> MatrixResizableRow<T_FEATURE,T_WEIGHT>& mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::operator= (const MatrixResizableRow< T_FEATURE, T_WEIGHT > & B) inline
Definition at line 95 of file matrix_resizablerow.hpp.
operator=() [2/2]
template<class T_FEATURE, class T_WEIGHT> MatrixResizableRow<T_FEATURE,T_WEIGHT>& mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::operator= (MatrixResizableRow< T_FEATURE, T_WEIGHT > && aimatrixresizerow_B) inline
Definition at line 113 of file matrix_resizablerow.hpp.
print()
template<class T_FEATURE, class T_WEIGHT> virtual void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = '\n') const inline virtual
Implements mat::MatrixBase< T_FEATURE >.
Definition at line 502 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::print(), and ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print().
removeRow()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::removeRow (const uintidx aiui_idxRow) inline
Definition at line 472 of file matrix_resizablerow.hpp.
resize()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::resize (const uintidx aiui_numRowsMaximum) inline
Definition at line 127 of file matrix_resizablerow.hpp.
Referenced by ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::resize().
swapRows()
template<class T_FEATURE, class T_WEIGHT> void mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::swapRows (const uintidx i, const uintidx j) inline
Definition at line 463 of file matrix_resizablerow.hpp.
toArray() [1/2]
template<class T_FEATURE, class T_WEIGHT> const T_FEATURE* mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::toArray () const inline
Definition at line 280 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge().
toArray() [2/2]
template<class T_FEATURE, class T_WEIGHT> T_FEATURE* mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::toArray () inline
Definition at line 285 of file matrix_resizablerow.hpp.
Member Data Documentation
_arrayt_data
template<class T_FEATURE, class T_WEIGHT> T_FEATURE* mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::_arrayt_data protected
Definition at line 543 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRows(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::initialize(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::MatrixResizableRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::operator=(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::toArray(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::~MatrixResizableRow().
_ui_numRowsMaximum
template<class T_FEATURE, class T_WEIGHT> uintidx mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::_ui_numRowsMaximum protected
Definition at line 542 of file matrix_resizablerow.hpp.
Referenced by mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getNumElemsMaximum(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::getNumRowsMaximum(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::MatrixResizableRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::operator=(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::print(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize().
The documentation for this class was generated from the following file:
include/matrix_resizablerow.hpp