Library Evolutionary Algorithms for Clustering (LEAC): runtime::RuntimeFunctionValue< T_VALUE > Class Template Reference
runtime::RuntimeFunctionValue< T_VALUE > Class Template Reference
Function store metrics in run time.
#include <runtime_function_value.hpp>
Public Member Functions
RuntimeFunctionValue (const std::string &as_funcName, const std::string &ais_algorithmoName, char aic_typeFunc)
virtual ~RuntimeFunctionValue ()
void setValue (T_VALUE aiT_value)
T_VALUE getValue ()
virtual std::ostream & print (std::ostream &out) const
Public Member Functions inherited from runtime::RuntimeFunction
RuntimeFunction (const std::string &as_funcName, const std::string &as_algorithmoName, char aic_typeFunc)
virtual ~RuntimeFunction ()
std::string & getName ()
bool isNotStorage ()
bool isStorageBuffer ()
bool isStorageLinkedList ()
Protected Attributes
T_VALUE t_value
Protected Attributes inherited from runtime::RuntimeFunction
std::string _str_nameFunc
char _c_typeFunc
Detailed Description
template<class T_VALUE>
class runtime::RuntimeFunctionValue< T_VALUE >
Function store metrics in run time.
Definition at line 32 of file runtime_function_value.hpp.
Constructor & Destructor Documentation
RuntimeFunctionValue()
template<class T_VALUE> runtime::RuntimeFunctionValue< T_VALUE >::RuntimeFunctionValue (const std::string & as_funcName, const std::string & ais_algorithmoName, char aic_typeFunc) inline
Definition at line 36 of file runtime_function_value.hpp.
~RuntimeFunctionValue()
template<class T_VALUE> virtual runtime::RuntimeFunctionValue< T_VALUE >::~RuntimeFunctionValue () inline virtual
Definition at line 44 of file runtime_function_value.hpp.
Member Function Documentation
getValue()
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionValue< T_VALUE >::getValue () inline
Definition at line 50 of file runtime_function_value.hpp.
References runtime::RuntimeFunctionValue< T_VALUE >::t_value.
print()
template<class T_VALUE> virtual std::ostream& runtime::RuntimeFunctionValue< T_VALUE >::print (std::ostream & out) const inline virtual
Implements runtime::RuntimeFunction.
Definition at line 55 of file runtime_function_value.hpp.
References runtime::RuntimeFunctionValue< T_VALUE >::t_value.
setValue()
template<class T_VALUE> void runtime::RuntimeFunctionValue< T_VALUE >::setValue (T_VALUE aiT_value) inline
Definition at line 46 of file runtime_function_value.hpp.
References runtime::RuntimeFunctionValue< T_VALUE >::t_value.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), runtime::functionhiststat_evaluateAll(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
Member Data Documentation
t_value
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionValue< T_VALUE >::t_value protected
Definition at line 63 of file runtime_function_value.hpp.
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::evaluate(), runtime::RuntimeFunctionValue< T_VALUE >::getValue(), runtime::RuntimeFunctionValue< T_VALUE >::print(), and runtime::RuntimeFunctionValue< T_VALUE >::setValue().
The documentation for this class was generated from the following file:
include_inout/runtime_function_value.hpp