Library Evolutionary Algorithms for Clustering (LEAC): partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST > Class Template Reference
partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST > Class Template Reference
Partition of instances with closest medoids
where , represents the medoid of cluster .
#include <partition_medoids.hpp>
Public Member Functions
PartitionMedoids (T_INSTANCES_IDX *aiarrayidxinstT_medoids, T_CLUSTERIDX aicidx_numClusterK, mat::MatrixTriang< T_DIST > &aipmatrixtriagT_dissimilarity)
~PartitionMedoids ()
const uintidx getNumInstances () const
void begin ()
const T_CLUSTERIDX next ()
bool end () const
const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const
const T_CLUSTERIDX getNumCluster () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from partition::Partition< T_CLUSTERIDX >
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
Protected Attributes
T_INSTANCES_IDX * _arrayidxinst_medoids
T_CLUSTERIDX _cidx_numClusterK
mat::MatrixTriang< T_DIST > * _ptmatrixtriagt_dissimilarity
uintidx _ui_iteratornextInstIdx
Detailed Description
template<class T_INSTANCES_IDX, class T_CLUSTERIDX, class T_DIST>
class partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >
Partition of instances with closest medoids
where , represents the medoid of cluster .
Definition at line 41 of file partition_medoids.hpp.
Constructor & Destructor Documentation
PartitionMedoids()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::PartitionMedoids (T_INSTANCES_IDX * aiarrayidxinstT_medoids, T_CLUSTERIDX aicidx_numClusterK, mat::MatrixTriang< T_DIST > & aipmatrixtriagT_dissimilarity) inline
Definition at line 47 of file partition_medoids.hpp.
~PartitionMedoids()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::~PartitionMedoids () inline
Definition at line 57 of file partition_medoids.hpp.
Member Function Documentation
begin()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > void partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::begin () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 64 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ui_iteratornextInstIdx.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print().
end()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > bool partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::end () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 90 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ui_iteratornextInstIdx, and mat::MatrixTriang< T_FEATURE >::getNumRows().
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print().
getClusterIdx()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > const T_CLUSTERIDX partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getClusterIdx (uintidx aiuintidx_instanceIdx) const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 95 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_arrayidxinst_medoids, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_cidx_numClusterK, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity, and nearest::medoidsNN().
getNumCluster()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > const T_CLUSTERIDX partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumCluster () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 133 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_cidx_numClusterK.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print().
getNumInstances()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > const uintidx partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumInstances () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 59 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity, and mat::MatrixTriang< T_FEATURE >::getNumRows().
next()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > const T_CLUSTERIDX partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 69 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_arrayidxinst_medoids, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_cidx_numClusterK, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ui_iteratornextInstIdx, and nearest::medoidsNN().
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print().
print()
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > virtual void partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 139 of file partition_medoids.hpp.
References partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::begin(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::end(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumCluster(), mat::MatrixTriang< T_FEATURE >::getNumRows(), and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next().
Member Data Documentation
_arrayidxinst_medoids
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > T_INSTANCES_IDX* partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_arrayidxinst_medoids protected
Definition at line 174 of file partition_medoids.hpp.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getClusterIdx(), and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next().
_cidx_numClusterK
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > T_CLUSTERIDX partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_cidx_numClusterK protected
Definition at line 175 of file partition_medoids.hpp.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getClusterIdx(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumCluster(), and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next().
_ptmatrixtriagt_dissimilarity
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > mat::MatrixTriang<T_DIST>* partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ptmatrixtriagt_dissimilarity protected
Definition at line 176 of file partition_medoids.hpp.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::end(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getClusterIdx(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getNumInstances(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next(), and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::print().
_ui_iteratornextInstIdx
template<class T_INSTANCES_IDX , class T_CLUSTERIDX , class T_DIST > uintidx partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::_ui_iteratornextInstIdx protected
Definition at line 177 of file partition_medoids.hpp.
Referenced by partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::begin(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::end(), and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next().
The documentation for this class was generated from the following file:
include/partition_medoids.hpp