Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamAlgorithmo Class Reference
inout::InParamAlgorithmo Class Reference
Input parameter for define propertys of the algorithmos.
#include <inparam.hpp>
Public Member Functions
InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut)
~InParamAlgorithmo ()
void errorArgument (char *apc_command, const char *apc_options, const char *aas_arguments[])
bool isYesNo (char *optarg, char *apc_command, const char *apc_options)
void setFileNameTimesRun (char *aips_nameFile)
void setProgressBarPrinting (bool aib_bool)
void setTimesRunAlgorithm (int aii_timesRun)
void setGnuPlotCoreStyles (const char *aips_nameCoreStyle)
std::string getAlgorithmoAuthor () const
std::string getAlgorithmoName () const
char * getFileNameTimesRun () const
int getTimesRunAlgorithm () const
bool getProgressBarPrinting ()
const std::string getGnuPlotCoreStyles () const
InParam_algTypeOut getAlgorithTypeOut ()
const std::string & getRunningTimeId ()
void setRunningTimeId (const std::string aistr_runTimeId)
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Protected Attributes
std::string s_algorithmoName
std::string s_algorithmoAuthor
InParam_algTypeOut ato_algTypeOut
char * ps_fileNameTimesRun
bool b_progressBarPrinting
int i_timesRunAlgorithm
std::string _s_runTimeId
std::string s_gnuplotCoreStyles
Friends
std::ostream & operator<< (std::ostream &os, const InParamAlgorithmo &aiinparamalg_inParam)
Detailed Description
Input parameter for define propertys of the algorithmos.
Definition at line 37 of file inparam.hpp.
Constructor & Destructor Documentation
InParamAlgorithmo()
inout::InParamAlgorithmo::InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut) inline
Definition at line 40 of file inparam.hpp.
References _s_runTimeId, and INPARAM_SIZE_STRING_ID_TIME.
~InParamAlgorithmo()
inout::InParamAlgorithmo::~InParamAlgorithmo () inline
Definition at line 70 of file inparam.hpp.
Member Function Documentation
errorArgument()
void inout::InParamAlgorithmo::errorArgument (char * apc_command, const char * apc_options, const char * aas_arguments[]) inline
Definition at line 72 of file inparam.hpp.
References inout::li_i.
Referenced by isYesNo().
getAlgorithmoAuthor()
std::string inout::InParamAlgorithmo::getAlgorithmoAuthor () const inline
Definition at line 130 of file inparam.hpp.
References s_algorithmoAuthor.
getAlgorithmoName()
std::string inout::InParamAlgorithmo::getAlgorithmoName () const inline
Definition at line 135 of file inparam.hpp.
References s_algorithmoName.
getAlgorithTypeOut()
InParam_algTypeOut inout::InParamAlgorithmo::getAlgorithTypeOut () inline
Definition at line 161 of file inparam.hpp.
References ato_algTypeOut.
getFileNameTimesRun()
char* inout::InParamAlgorithmo::getFileNameTimesRun () const inline
Definition at line 140 of file inparam.hpp.
References ps_fileNameTimesRun.
getGnuPlotCoreStyles()
const std::string inout::InParamAlgorithmo::getGnuPlotCoreStyles () const inline
Definition at line 156 of file inparam.hpp.
References s_gnuplotCoreStyles.
Referenced by runtime::plot_funtionHist().
getProgressBarPrinting()
bool inout::InParamAlgorithmo::getProgressBarPrinting () inline
Definition at line 151 of file inparam.hpp.
References b_progressBarPrinting.
getRunningTimeId()
const std::string& inout::InParamAlgorithmo::getRunningTimeId () inline
Definition at line 166 of file inparam.hpp.
References _s_runTimeId.
getTimesRunAlgorithm()
int inout::InParamAlgorithmo::getTimesRunAlgorithm () const inline
Definition at line 146 of file inparam.hpp.
References i_timesRunAlgorithm.
Referenced by runtime::plot_funtionHist().
isYesNo()
bool inout::InParamAlgorithmo::isYesNo (char * optarg, char * apc_command, const char * apc_options) inline
Definition at line 90 of file inparam.hpp.
References errorArgument(), getsubopt_getsubopt(), inout::las_optTokensYesNo, and optarg.
print()
virtual void inout::InParamAlgorithmo::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented in inout::InParamPlotClustering< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamClustering, inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamDBSCAN< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamPCA< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >, inout::InParamTGCA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamIsoData< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamFCM< T_CLUSTERIDX, T_REAL, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamKmeans< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamGAClustering, inout::InParamPcPm< T_REAL >, inout::InParamStdVar< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamSlink< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >, inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamClusteringMaxIter, inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >, inout::InParamPAM< T_CLUSTERIDX, T_FEATURE, T_INSTANCES_CLUSTER_K >, and inout::InParamPm< T_REAL >.
Definition at line 176 of file inparam.hpp.
References _s_runTimeId, i_timesRunAlgorithm, s_algorithmoAuthor, and s_algorithmoName.
Referenced by inout::InParamStdVar< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamPCA< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamPCAtransmatrix< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print(), inout::InParamClustering::print(), and inout::InParamPlotClustering< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
setFileNameTimesRun()
void inout::InParamAlgorithmo::setFileNameTimesRun (char * aips_nameFile) inline
Definition at line 109 of file inparam.hpp.
References ps_fileNameTimesRun.
setGnuPlotCoreStyles()
void inout::InParamAlgorithmo::setGnuPlotCoreStyles (const char * aips_nameCoreStyle) inline
Definition at line 125 of file inparam.hpp.
References s_gnuplotCoreStyles.
setProgressBarPrinting()
void inout::InParamAlgorithmo::setProgressBarPrinting (bool aib_bool) inline
Definition at line 115 of file inparam.hpp.
References b_progressBarPrinting.
setRunningTimeId()
void inout::InParamAlgorithmo::setRunningTimeId (const std::string aistr_runTimeId) inline
Definition at line 171 of file inparam.hpp.
References _s_runTimeId.
setTimesRunAlgorithm()
void inout::InParamAlgorithmo::setTimesRunAlgorithm (int aii_timesRun) inline
Definition at line 120 of file inparam.hpp.
References i_timesRunAlgorithm.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const InParamAlgorithmo & aiinparamalg_inParam) friend
Definition at line 190 of file inparam.hpp.
Member Data Documentation
_s_runTimeId
std::string inout::InParamAlgorithmo::_s_runTimeId protected
Definition at line 206 of file inparam.hpp.
Referenced by getRunningTimeId(), InParamAlgorithmo(), print(), and setRunningTimeId().
ato_algTypeOut
InParam_algTypeOut inout::InParamAlgorithmo::ato_algTypeOut protected
Definition at line 201 of file inparam.hpp.
Referenced by getAlgorithTypeOut().
b_progressBarPrinting
bool inout::InParamAlgorithmo::b_progressBarPrinting protected
Definition at line 204 of file inparam.hpp.
Referenced by getProgressBarPrinting(), and setProgressBarPrinting().
i_timesRunAlgorithm
int inout::InParamAlgorithmo::i_timesRunAlgorithm protected
Definition at line 205 of file inparam.hpp.
Referenced by getTimesRunAlgorithm(), print(), and setTimesRunAlgorithm().
ps_fileNameTimesRun
char* inout::InParamAlgorithmo::ps_fileNameTimesRun protected
Definition at line 203 of file inparam.hpp.
Referenced by getFileNameTimesRun(), and setFileNameTimesRun().
s_algorithmoAuthor
std::string inout::InParamAlgorithmo::s_algorithmoAuthor protected
Definition at line 200 of file inparam.hpp.
Referenced by getAlgorithmoAuthor(), and print().
s_algorithmoName
std::string inout::InParamAlgorithmo::s_algorithmoName protected
Definition at line 199 of file inparam.hpp.
Referenced by getAlgorithmoName(), and print().
s_gnuplotCoreStyles
std::string inout::InParamAlgorithmo::s_gnuplotCoreStyles protected
Definition at line 207 of file inparam.hpp.
Referenced by getGnuPlotCoreStyles(), and setGnuPlotCoreStyles().
The documentation for this class was generated from the following file:
include_inout/inparam.hpp