Library Evolutionary Algorithms for Clustering (LEAC): gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC > Class Template Reference
gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC > Class Template Reference
Chromosome encoding string of bits.
#include <chromosome_bitarray.hpp>
Public Member Functions
ChromosomeBitArray ()
ChromosomeBitArray (const uintidx aiintidx_numBits)
ChromosomeBitArray (const ChromosomeBitArray< T_BITSIZE, T_METRIC > &aichrombitarray_b)
ChromosomeBitArray (ChromosomeBitArray< T_BITSIZE, T_METRIC > &&aichrombitarray_b)
virtual ~ChromosomeBitArray ()
ChromosomeBitArray< T_BITSIZE, T_METRIC > & operator= (const ChromosomeBitArray< T_BITSIZE, T_METRIC > &aichrombitarray_b)
ChromosomeBitArray< T_BITSIZE, T_METRIC > & operator= (ChromosomeBitArray< T_BITSIZE, T_METRIC > &&aichrombitarray_b)
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';') const
Public Member Functions inherited from gaencode::ChromosomeBase< T_METRIC >
ChromosomeBase ()
ChromosomeBase (const T_METRIC airt_objetiveFunc, const T_METRIC airt_fitness)
ChromosomeBase (ChromosomeBase< T_METRIC > &&aich_chromosome)
ChromosomeBase (const ChromosomeBase< T_METRIC > &aich_chromosome)
virtual ~ChromosomeBase ()
ChromosomeBase< T_METRIC > & operator= (const ChromosomeBase< T_METRIC > &aich_chromosome)
ChromosomeBase< T_METRIC > & operator= (ChromosomeBase< T_METRIC > &&aich_chromosome)
void setValidString (bool aib_stringInvalid)
const bool getValidString () const
void setObjetiveFunc (T_METRIC ait_objetiveFunc)
const T_METRIC getObjetiveFunc () const
const T_METRIC getFitness () const
void setFitness (T_METRIC ait_fitness)
Public Member Functions inherited from mat::BitArray< T_BITSIZE >
BitArray ()
BitArray (const uintidx aiintidx_numBits)
BitArray (const uintidx aiintidx_numBits, T_BITSIZE *aiarrayT_data)
BitArray (const BitArray< T_BITSIZE > &aibitarray_B)
BitArray (const BitArray< T_BITSIZE > &&aibitarray_B)
BitArray< T_BITSIZE > & operator= (BitArray< T_BITSIZE > &&aibitarray_B)
BitArray< T_BITSIZE > & operator= (const BitArray< T_BITSIZE > &aibitarray_B)
~BitArray ()
void initializeOn ()
void toggleAll ()
uintidx size () const
void print (std::ostream &os=std::cout, const char *aipc_label="") const
Public Member Functions inherited from ds::BitContainer< T_BITSIZE >
BitContainer ()
BitContainer (const uintidx aiuintidx_numWords)
BitContainer (const uintidx aiuintidx_numWords, T_BITSIZE *aiarrayit_data)
BitContainer (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
BitContainer (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
virtual ~BitContainer ()
ds::BitContainer< T_BITSIZE > & operator= (const ds::BitContainer< T_BITSIZE > &aibitcontainer_B)
ds::BitContainer< T_BITSIZE > & operator= (ds::BitContainer< T_BITSIZE > &&aibitcontainer_B)
void setArray (T_BITSIZE *aiarrayit_data)
T_BITSIZE * toArray ()
void initialize ()
initialize
void initializeOn ()
initializeOn:
void toggleAll ()
toggleAll
void clearBit (uintidx i)
void setBit (uintidx i)
void toggleBit (uintidx i)
void assignBit (uintidx i, bool aib_bit)
bool getBit (uintidx i) const
uintidx getNumBitOn () const
std::list< uintidx > getIdxWithBitOn () const
void opXor (const ds::BitContainer< T_BITSIZE > &aibitc_bits)
opXor
void copyAligned (const ds::BitContainer< T_BITSIZE > &aibitc_source, const uintidx aiuintidx_idxTarget, uintidx aiuintidx_length)
void copyUnaligned (uintidx aiuintidx_idxTarget, BitContainer< T_BITSIZE > &aibitc_source, uintidx aiuintidx_idxSource, uintidx aiuintidx_length)
void print (std::ostream &os=std::cout, const char *aipc_label="") const
Friends
std::ostream & operator<< (std::ostream &os, const ChromosomeBitArray< T_BITSIZE, T_METRIC > &aichrombitarray_b)
Additional Inherited Members
Static Public Member Functions inherited from ds::BitContainer< T_BITSIZE >
static const uintidx _getNumWords (uintidx aiuintidx_numBits)
_getNumWords
Static Public Attributes inherited from ds::BitContainer< T_BITSIZE >
static const unsigned short int _stusi_numBitsWords
static const T_BITSIZE t_wordMax = (~(T_BITSIZE)0)
Protected Member Functions inherited from ds::BitContainer< T_BITSIZE >
unsigned short int _getBitOffset (uintidx b) const
uintidx _bits_in_top_word (uintidx b)
uintidx _getWordIndexBit (uintidx b) const
T_BITSIZE _bitMask (uintidx length)
Protected Attributes inherited from gaencode::ChromosomeBase< T_METRIC >
bool _b_stringInvalid
T_METRIC _t_objetiveFunc
T_METRIC _t_fitness
Protected Attributes inherited from mat::BitArray< T_BITSIZE >
uintidx _uintidx_numBits
Protected Attributes inherited from ds::BitContainer< T_BITSIZE >
uintidx _uintidx_numWords
T_BITSIZE * _arrayuit_data
bool b_externalData
Detailed Description
template<class T_BITSIZE, class T_METRIC>
class gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >
Chromosome encoding string of bits.
Definition at line 39 of file chromosome_bitarray.hpp.
Constructor & Destructor Documentation
ChromosomeBitArray() [1/4]
template<class T_BITSIZE, class T_METRIC> gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::ChromosomeBitArray () inline
Definition at line 44 of file chromosome_bitarray.hpp.
ChromosomeBitArray() [2/4]
template<class T_BITSIZE, class T_METRIC> gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::ChromosomeBitArray (const uintidx aiintidx_numBits) inline
Definition at line 50 of file chromosome_bitarray.hpp.
ChromosomeBitArray() [3/4]
template<class T_BITSIZE, class T_METRIC> gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::ChromosomeBitArray (const ChromosomeBitArray< T_BITSIZE, T_METRIC > & aichrombitarray_b) inline
Definition at line 57 of file chromosome_bitarray.hpp.
ChromosomeBitArray() [4/4]
template<class T_BITSIZE, class T_METRIC> gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::ChromosomeBitArray (ChromosomeBitArray< T_BITSIZE, T_METRIC > && aichrombitarray_b) inline
Definition at line 88 of file chromosome_bitarray.hpp.
~ChromosomeBitArray()
template<class T_BITSIZE, class T_METRIC> virtual gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::~ChromosomeBitArray () inline virtual
Definition at line 95 of file chromosome_bitarray.hpp.
Member Function Documentation
operator=() [1/2]
template<class T_BITSIZE, class T_METRIC> ChromosomeBitArray<T_BITSIZE,T_METRIC>& gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::operator= (const ChromosomeBitArray< T_BITSIZE, T_METRIC > & aichrombitarray_b) inline
Definition at line 114 of file chromosome_bitarray.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), mat::BitArray< T_BITSIZE >::operator=(), and gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print().
operator=() [2/2]
template<class T_BITSIZE, class T_METRIC> ChromosomeBitArray<T_BITSIZE,T_METRIC>& gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::operator= (ChromosomeBitArray< T_BITSIZE, T_METRIC > && aichrombitarray_b) inline
Definition at line 147 of file chromosome_bitarray.hpp.
References gaencode::ChromosomeBase< T_METRIC >::operator=(), and mat::BitArray< T_BITSIZE >::operator=().
print()
template<class T_BITSIZE, class T_METRIC> virtual void gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';') const inline virtual
Reimplemented from gaencode::ChromosomeBase< T_METRIC >.
Definition at line 159 of file chromosome_bitarray.hpp.
References mat::BitArray< T_BITSIZE >::print(), and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by gabinaryop::bitMutation(), eac::clustering_vksubclusterbinary(), gabinaryop::eachBitArrayMutation(), eac::gaclustering_vktreebinary(), eac::gaprototypes_fkmedoid(), gabinaryop::initializeGenes(), gabinaryop::onePointCrossover(), gabinaryop::onePointDistCrossover(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::operator=(), and gabinaryop::uniformCrossover().
Friends And Related Function Documentation
operator<<
template<class T_BITSIZE, class T_METRIC> std::ostream& operator<< (std::ostream & os, const ChromosomeBitArray< T_BITSIZE, T_METRIC > & aichrombitarray_b) friend
Definition at line 180 of file chromosome_bitarray.hpp.
The documentation for this class was generated from the following file:
include/chromosome_bitarray.hpp