Library Evolutionary Algorithms for Clustering (LEAC): runtime::IntervalPositiveInteger< T_INTEGERDATATYPE > Class Template Reference
runtime::IntervalPositiveInteger< T_INTEGERDATATYPE > Class Template Reference
Interval of positive integer.
#include <interval_positiveintegers.hpp>
Public Member Functions
IntervalPositiveInteger (T_INTEGERDATATYPE aiui_sizeInterval)
~IntervalPositiveInteger ()
void initialize ()
T_INTEGERDATATYPE getLowerBound ()
T_INTEGERDATATYPE getUpperBound ()
T_INTEGERDATATYPE upperBoundToEvaluate ()
void increaseUpperBound ()
void setSizeInterval (T_INTEGERDATATYPE aiui_sizeInterval)
T_INTEGERDATATYPE getSizeInterval ()
Private Attributes
T_INTEGERDATATYPE ui_upperBound
T_INTEGERDATATYPE ui_sizeInterval
Detailed Description
template<typename T_INTEGERDATATYPE>
class runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >
Interval of positive integer.
Definition at line 32 of file interval_positiveintegers.hpp.
Constructor & Destructor Documentation
IntervalPositiveInteger()
template<typename T_INTEGERDATATYPE> runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::IntervalPositiveInteger (T_INTEGERDATATYPE aiui_sizeInterval) inline
Definition at line 34 of file interval_positiveintegers.hpp.
~IntervalPositiveInteger()
template<typename T_INTEGERDATATYPE> runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::~IntervalPositiveInteger () inline
Definition at line 37 of file interval_positiveintegers.hpp.
Member Function Documentation
getLowerBound()
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getLowerBound () inline
Definition at line 43 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainLowerBound().
getSizeInterval()
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getSizeInterval () inline
Definition at line 68 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainSize().
getUpperBound()
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::getUpperBound () inline
Definition at line 49 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainUpperBound().
increaseUpperBound()
template<typename T_INTEGERDATATYPE> void runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::increaseUpperBound () inline
Definition at line 59 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::increaseDomainUpperBound().
initialize()
template<typename T_INTEGERDATATYPE> void runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::initialize () inline
Definition at line 39 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::initialize().
setSizeInterval()
template<typename T_INTEGERDATATYPE> void runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::setSizeInterval (T_INTEGERDATATYPE aiui_sizeInterval) inline
Definition at line 63 of file interval_positiveintegers.hpp.
Referenced by runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::setDomainSize().
upperBoundToEvaluate()
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::upperBoundToEvaluate () inline
Definition at line 54 of file interval_positiveintegers.hpp.
Member Data Documentation
ui_sizeInterval
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::ui_sizeInterval private
Definition at line 75 of file interval_positiveintegers.hpp.
Referenced by runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::getLowerBound(), runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::getSizeInterval(), runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::setSizeInterval(), and runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::upperBoundToEvaluate().
ui_upperBound
template<typename T_INTEGERDATATYPE> T_INTEGERDATATYPE runtime::IntervalPositiveInteger< T_INTEGERDATATYPE >::ui_upperBound private
Definition at line 74 of file interval_positiveintegers.hpp.
Referenced by runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::getLowerBound(), runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::getUpperBound(), runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::increaseUpperBound(), runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::initialize(), and runtime::IntervalPositiveInteger< T_INTEGERDOMAIN >::upperBoundToEvaluate().
The documentation for this class was generated from the following file:
include/interval_positiveintegers.hpp