Library Evolutionary Algorithms for Clustering (LEAC): runtime::RuntimeFunctionStat< T_VALUE > Class Template Reference
runtime::RuntimeFunctionStat< T_VALUE > Class Template Reference
Function statistical for metrics in run time.
#include <runtime_statistic.hpp>
Public Member Functions
RuntimeFunctionStat (const char aic_idStatistical, const std::string &ais_algorithmoName, char aic_typeFunc)
virtual ~RuntimeFunctionStat ()
void evaluate (std::vector< T_VALUE > &aivectorT_data)
Public Member Functions inherited from runtime::RuntimeFunctionValue< T_VALUE >
RuntimeFunctionValue (const std::string &as_funcName, const std::string &ais_algorithmoName, char aic_typeFunc)
virtual ~RuntimeFunctionValue ()
void setValue (T_VALUE aiT_value)
T_VALUE getValue ()
virtual std::ostream & print (std::ostream &out) const
Public Member Functions inherited from runtime::RuntimeFunction
RuntimeFunction (const std::string &as_funcName, const std::string &as_algorithmoName, char aic_typeFunc)
virtual ~RuntimeFunction ()
std::string & getName ()
bool isNotStorage ()
bool isStorageBuffer ()
bool isStorageLinkedList ()
Protected Attributes
int c_idStatistical
Protected Attributes inherited from runtime::RuntimeFunctionValue< T_VALUE >
T_VALUE t_value
Protected Attributes inherited from runtime::RuntimeFunction
std::string _str_nameFunc
char _c_typeFunc
Private Member Functions
T_VALUE _sum (std::vector< T_VALUE > &aivectorT_data)
T_VALUE _avg (std::vector< T_VALUE > &aivectorT_data)
T_VALUE _var (std::vector< T_VALUE > &aivectorT_data)
T_VALUE _devstd (std::vector< T_VALUE > &aivectorT_data)
Detailed Description
template<class T_VALUE>
class runtime::RuntimeFunctionStat< T_VALUE >
Function statistical for metrics in run time.
Definition at line 45 of file runtime_statistic.hpp.
Constructor & Destructor Documentation
RuntimeFunctionStat()
template<class T_VALUE> runtime::RuntimeFunctionStat< T_VALUE >::RuntimeFunctionStat (const char aic_idStatistical, const std::string & ais_algorithmoName, char aic_typeFunc) inline
Definition at line 50 of file runtime_statistic.hpp.
~RuntimeFunctionStat()
template<class T_VALUE> virtual runtime::RuntimeFunctionStat< T_VALUE >::~RuntimeFunctionStat () inline virtual
Definition at line 58 of file runtime_statistic.hpp.
Member Function Documentation
_avg()
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionStat< T_VALUE >::_avg (std::vector< T_VALUE > & aivectorT_data) inline private
Definition at line 94 of file runtime_statistic.hpp.
References runtime::RuntimeFunctionStat< T_VALUE >::_sum().
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::_var(), and runtime::RuntimeFunctionStat< T_VALUE >::evaluate().
_devstd()
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionStat< T_VALUE >::_devstd (std::vector< T_VALUE > & aivectorT_data) inline private
Definition at line 109 of file runtime_statistic.hpp.
References runtime::RuntimeFunctionStat< T_VALUE >::_var().
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::evaluate().
_sum()
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionStat< T_VALUE >::_sum (std::vector< T_VALUE > & aivectorT_data) inline private
Definition at line 89 of file runtime_statistic.hpp.
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::_avg(), and runtime::RuntimeFunctionStat< T_VALUE >::evaluate().
_var()
template<class T_VALUE> T_VALUE runtime::RuntimeFunctionStat< T_VALUE >::_var (std::vector< T_VALUE > & aivectorT_data) inline private
Definition at line 99 of file runtime_statistic.hpp.
References runtime::RuntimeFunctionStat< T_VALUE >::_avg().
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::_devstd(), and runtime::RuntimeFunctionStat< T_VALUE >::evaluate().
evaluate()
template<class T_VALUE> void runtime::RuntimeFunctionStat< T_VALUE >::evaluate (std::vector< T_VALUE > & aivectorT_data) inline
Definition at line 60 of file runtime_statistic.hpp.
References runtime::RuntimeFunctionStat< T_VALUE >::_avg(), runtime::RuntimeFunctionStat< T_VALUE >::_devstd(), runtime::RuntimeFunctionStat< T_VALUE >::_sum(), runtime::RuntimeFunctionStat< T_VALUE >::_var(), runtime::RuntimeFunctionStat< T_VALUE >::c_idStatistical, STATISTICAL_AVERAGE, STATISTICAL_MAXIMUM, STATISTICAL_MINIMUM, STATISTICAL_STD_DEVIATION, STATISTICAL_SUM, STATISTICAL_VARIANCE, and runtime::RuntimeFunctionValue< T_VALUE >::t_value.
Member Data Documentation
c_idStatistical
template<class T_VALUE> int runtime::RuntimeFunctionStat< T_VALUE >::c_idStatistical protected
Definition at line 115 of file runtime_statistic.hpp.
Referenced by runtime::RuntimeFunctionStat< T_VALUE >::evaluate().
The documentation for this class was generated from the following file:
include_inout/runtime_statistic.hpp