Library Evolutionary Algorithms for Clustering (LEAC): partition::Partition< T_CLUSTERIDX > Class Template Reference
partition::Partition< T_CLUSTERIDX > Class Template Reference abstract
Definition of the abstract class Partition, to build a cluster of a dataset.
#include <partition.hpp>
Public Member Functions
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
virtual const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const =0
virtual void begin ()=0
virtual const T_CLUSTERIDX next ()=0
virtual bool end () const =0
virtual const uintidx getNumInstances () const =0
virtual const T_CLUSTERIDX getNumCluster () const =0
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')=0
Detailed Description
template<class T_CLUSTERIDX>
class partition::Partition< T_CLUSTERIDX >
Definition of the abstract class Partition, to build a cluster of a dataset.
Definition at line 35 of file partition.hpp.
Constructor & Destructor Documentation
Partition() [1/3]
template<class T_CLUSTERIDX> partition::Partition< T_CLUSTERIDX >::Partition () inline
Definition at line 38 of file partition.hpp.
Partition() [2/3]
template<class T_CLUSTERIDX> partition::Partition< T_CLUSTERIDX >::Partition (const Partition< T_CLUSTERIDX > & aimembclassdisjset_b) inline
Definition at line 41 of file partition.hpp.
Partition() [3/3]
template<class T_CLUSTERIDX> partition::Partition< T_CLUSTERIDX >::Partition (Partition< T_CLUSTERIDX > && aimembclassdisjset_b) inline
Definition at line 44 of file partition.hpp.
~Partition()
template<class T_CLUSTERIDX> partition::Partition< T_CLUSTERIDX >::~Partition () inline
Definition at line 46 of file partition.hpp.
Member Function Documentation
begin()
template<class T_CLUSTERIDX> virtual void partition::Partition< T_CLUSTERIDX >::begin () pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >, and partition::PartitionLabelVector< T_CLUSTERIDX >.
Referenced by um::avgRadiusClusterK(), clusteringop::getCentroids(), sm::getConfusionMatrix(), sm::getMatchingMatrix(), ds::getPartitionLinkedNumInst(), um::maxRadiusClusterK(), um::simplifiedSilhouette(), um::SSE(), and um::sumDistInstCentInK().
end()
template<class T_CLUSTERIDX> virtual bool partition::Partition< T_CLUSTERIDX >::end () const pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionLabelVector< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >.
getClusterIdx()
template<class T_CLUSTERIDX> virtual const T_CLUSTERIDX partition::Partition< T_CLUSTERIDX >::getClusterIdx (uintidx aiuintidx_instanceIdx) const pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionLabelVector< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, and partition::PartitionFuzzy< T_U, T_CLUSTERIDX >.
Referenced by um::D2(), um::Dinter(), and um::Dintra().
getNumCluster()
template<class T_CLUSTERIDX> virtual const T_CLUSTERIDX partition::Partition< T_CLUSTERIDX >::getNumCluster () const pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, and partition::PartitionLabelVector< T_CLUSTERIDX >.
Referenced by clusteringop::getCentroids(), sm::getConfusionMatrix(), sm::getMatchingMatrix(), and ds::getPartitionLinkedNumInst().
getNumInstances()
template<class T_CLUSTERIDX> virtual const uintidx partition::Partition< T_CLUSTERIDX >::getNumInstances () const pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionLabelVector< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, and partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >.
next()
template<class T_CLUSTERIDX> virtual const T_CLUSTERIDX partition::Partition< T_CLUSTERIDX >::next () pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >, and partition::PartitionLabelVector< T_CLUSTERIDX >.
Referenced by um::avgRadiusClusterK(), clusteringop::getCentroids(), sm::getConfusionMatrix(), sm::getMatchingMatrix(), ds::getPartitionLinkedNumInst(), um::maxRadiusClusterK(), um::simplifiedSilhouette(), um::SSE(), and um::sumDistInstCentInK().
print()
template<class T_CLUSTERIDX> virtual void partition::Partition< T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') pure virtual
Implemented in partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >, partition::PartitionDisjSets< T_CLUSTERIDX >, partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >, partition::PartitionLabel< T_CLUSTERIDX >, partition::PartitionFuzzy< T_U, T_CLUSTERIDX >, partition::PartitionLabelVector< T_CLUSTERIDX >, and partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >.
The documentation for this class was generated from the following file:
include/partition.hpp