Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamPm< T_REAL > Class Template Reference
inout::InParamPm< T_REAL > Class Template Reference
Input parameter for GA with only probability mutation (Pm)
#include <inparam_pm.hpp>
Public Member Functions
InParamPm (const std::string &ais_algorithmoName, const std::string &ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamPm ()
void setProbMutation (T_REAL ait_probMutation)
const T_REAL getProbMutation () const
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Public Member Functions inherited from inout::InParamGAClustering
InParamGAClustering (const std::string &ais_algorithmoName, const std::string &ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamGAClustering ()
void setNumMaxGenerations (COMMON_IDOMAIN aiT_numMaxGenerations)
COMMON_IDOMAIN getNumMaxGenerations () const
void setSizePopulation (uintidx aist_sizePopulation)
uintidx getSizePopulation () const
Public Member Functions inherited from inout::InParamClustering
InParamClustering (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opDistance)
~InParamClustering ()
char * getFileNamePlotStatObjetiveFunc () const
bool getWithPlotStatObjetiveFunc () const
void setFileNamePlotStatObjetiveFunc (char *aips_nameFile)
void setOutFileMemberShip (char *aips_fileName)
char * getOutFileMemberShip ()
void setRandomSeed (const std::string &aistr_randomSeed)
void setRandomSeed (const char *aipc_randomSeed)
const std::string & getRandomSeed () const
void setOutFilePartitionsTable (char *aips_fileName)
char * getOutFilePartitionsTable ()
void setOutFileCentroids (char *aips_fileName)
char * getOutFileCentroids ()
void setOpDistance (int aii_opDistance)
int getOpDistance ()
double getMaxExecutiontime ()
void setMaxExecutiontime (double aird_maxExecutiontime)
bool getPrintCentroidsFormat ()
void setPrintCentroidsFormat (bool aib_printCentroidsFormat)
bool getPrintTableFormat ()
void setPrintTableFormat (bool aib_printTableFormat)
void setOutFileGraph (char *aips_fileName)
char * getOutFileGraph ()
Public Member Functions inherited from inout::InParamAlgorithmo
InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut)
~InParamAlgorithmo ()
void errorArgument (char *apc_command, const char *apc_options, const char *aas_arguments[])
bool isYesNo (char *optarg, char *apc_command, const char *apc_options)
void setFileNameTimesRun (char *aips_nameFile)
void setProgressBarPrinting (bool aib_bool)
void setTimesRunAlgorithm (int aii_timesRun)
void setGnuPlotCoreStyles (const char *aips_nameCoreStyle)
std::string getAlgorithmoAuthor () const
std::string getAlgorithmoName () const
char * getFileNameTimesRun () const
int getTimesRunAlgorithm () const
bool getProgressBarPrinting ()
const std::string getGnuPlotCoreStyles () const
InParam_algTypeOut getAlgorithTypeOut ()
const std::string & getRunningTimeId ()
void setRunningTimeId (const std::string aistr_runTimeId)
Protected Attributes
T_REAL _t_probMutation
Protected Attributes inherited from inout::InParamGAClustering
uintidx st_sizePopulation
COMMON_IDOMAIN t_numMaxGenerations
Protected Attributes inherited from inout::InParamClustering
int i_opDistance
char * ps_outFileCentroids
char * ps_outFileMemberShip
char * ps_outFilePartitionsTable
char * ps_outFileGraph
char * ps_fileNamePlotStatObjetiveFunc
std::string _str_randomSeed
double _rd_maxExecutiontime
bool _b_printCentroidsFormat
bool _b_printTableFormat
Protected Attributes inherited from inout::InParamAlgorithmo
std::string s_algorithmoName
std::string s_algorithmoAuthor
InParam_algTypeOut ato_algTypeOut
char * ps_fileNameTimesRun
bool b_progressBarPrinting
int i_timesRunAlgorithm
std::string _s_runTimeId
std::string s_gnuplotCoreStyles
Detailed Description
template<typename T_REAL>
class inout::InParamPm< T_REAL >
Input parameter for GA with only probability mutation (Pm)
Definition at line 32 of file inparam_pm.hpp.
Constructor & Destructor Documentation
InParamPm()
template<typename T_REAL > inout::InParamPm< T_REAL >::InParamPm (const std::string & ais_algorithmoName, const std::string & ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm) inline
Definition at line 37 of file inparam_pm.hpp.
~InParamPm()
template<typename T_REAL > inout::InParamPm< T_REAL >::~InParamPm () inline
Definition at line 45 of file inparam_pm.hpp.
Member Function Documentation
getProbMutation()
template<typename T_REAL > const T_REAL inout::InParamPm< T_REAL >::getProbMutation () const inline
Definition at line 51 of file inparam_pm.hpp.
References inout::InParamPm< T_REAL >::_t_probMutation.
print()
template<typename T_REAL > virtual void inout::InParamPm< T_REAL >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented from inout::InParamGAClustering.
Reimplemented in inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >, and inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >.
Definition at line 55 of file inparam_pm.hpp.
References inout::InParamPm< T_REAL >::_t_probMutation, and inout::InParamGAClustering::print().
Referenced by inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), and inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY >::print().
setProbMutation()
template<typename T_REAL > void inout::InParamPm< T_REAL >::setProbMutation (T_REAL ait_probMutation) inline
Definition at line 47 of file inparam_pm.hpp.
References inout::InParamPm< T_REAL >::_t_probMutation.
Member Data Documentation
_t_probMutation
template<typename T_REAL > T_REAL inout::InParamPm< T_REAL >::_t_probMutation protected
Definition at line 64 of file inparam_pm.hpp.
Referenced by inout::InParamPm< T_REAL >::getProbMutation(), inout::InParamPm< T_REAL >::print(), and inout::InParamPm< T_REAL >::setProbMutation().
The documentation for this class was generated from the following file:
include_inout/inparam_pm.hpp