Library Evolutionary Algorithms for Clustering (LEAC): inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > Class Template Reference
Input parameter for EA with adaptive probabilities of crossover and mutation [11].
#include <inparam_adaptiveprobcprobm.hpp>
Public Member Functions
InParamAdaptivePcPm (const std::string &ais_algorithmoName, const std::string &ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamAdaptivePcPm ()
virtual void print (std::ostream &aipf_outFile=std::cout, const char aic_separator=',') const
Public Member Functions inherited from inout::InParamGAClustering
InParamGAClustering (const std::string &ais_algorithmoName, const std::string &ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm)
~InParamGAClustering ()
void setNumMaxGenerations (COMMON_IDOMAIN aiT_numMaxGenerations)
COMMON_IDOMAIN getNumMaxGenerations () const
void setSizePopulation (uintidx aist_sizePopulation)
uintidx getSizePopulation () const
Public Member Functions inherited from inout::InParamClustering
InParamClustering (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opDistance)
~InParamClustering ()
char * getFileNamePlotStatObjetiveFunc () const
bool getWithPlotStatObjetiveFunc () const
void setFileNamePlotStatObjetiveFunc (char *aips_nameFile)
void setOutFileMemberShip (char *aips_fileName)
char * getOutFileMemberShip ()
void setRandomSeed (const std::string &aistr_randomSeed)
void setRandomSeed (const char *aipc_randomSeed)
const std::string & getRandomSeed () const
void setOutFilePartitionsTable (char *aips_fileName)
char * getOutFilePartitionsTable ()
void setOutFileCentroids (char *aips_fileName)
char * getOutFileCentroids ()
void setOpDistance (int aii_opDistance)
int getOpDistance ()
double getMaxExecutiontime ()
void setMaxExecutiontime (double aird_maxExecutiontime)
bool getPrintCentroidsFormat ()
void setPrintCentroidsFormat (bool aib_printCentroidsFormat)
bool getPrintTableFormat ()
void setPrintTableFormat (bool aib_printTableFormat)
void setOutFileGraph (char *aips_fileName)
char * getOutFileGraph ()
Public Member Functions inherited from inout::InParamAlgorithmo
InParamAlgorithmo (std::string ais_algorithmoName, std::string ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut)
~InParamAlgorithmo ()
void errorArgument (char *apc_command, const char *apc_options, const char *aas_arguments[])
bool isYesNo (char *optarg, char *apc_command, const char *apc_options)
void setFileNameTimesRun (char *aips_nameFile)
void setProgressBarPrinting (bool aib_bool)
void setTimesRunAlgorithm (int aii_timesRun)
void setGnuPlotCoreStyles (const char *aips_nameCoreStyle)
std::string getAlgorithmoAuthor () const
std::string getAlgorithmoName () const
char * getFileNameTimesRun () const
int getTimesRunAlgorithm () const
bool getProgressBarPrinting ()
const std::string getGnuPlotCoreStyles () const
InParam_algTypeOut getAlgorithTypeOut ()
const std::string & getRunningTimeId ()
void setRunningTimeId (const std::string aistr_runTimeId)
Public Member Functions inherited from inout::InParamFk< T_CLUSTERIDX >
InParamFk ()
~InParamFk ()
void setNumClusterK (T_CLUSTERIDX aiidxK_numClusterK)
const T_CLUSTERIDX getNumClusterK () const
Public Member Functions inherited from inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
InParamReadInst ()
InParamReadInst (const char *aips_fileNameInstance, EnumFormatInstanceFile aienum_formatInstanceFile, const char *ais_separatorAttributes, const char *aips_selectAttributes, bool aib_haveHeaderFile=false)
~InParamReadInst ()
void clearVectorFilesInstance ()
const std::vector< std::string > & getVectorFilesInstance () const
void setVectorFilesInstance (const std::vector< std::string > &aivectorstr_filesInstance)
uintidx getNumFilesInstance ()
void setVectorFilesInstanceTest (const std::vector< std::string > &aivectorstr_filesInstanceTest)
const std::vector< std::string > & getVectorFilesInstanceTest () const
uintidx getNumFilesInstanceTest ()
void setFileInstance (const char *aips_nameFile)
void setFileInstance (const std::string aistr_nameFile)
void setFileInstanceTest (const char *aips_nameFileTest)
void setFileInstanceTest (const std::string aistr_nameFileTest)
const std::string & getCurrentFileInstance () const
const std::string & getCurrentFileInstanceTest () const
void setCurrentFileInstance (uintidx aiui_i)
void setSelectAttributes (const char *aips_selectAttributes)
const std::string & getSelectAttributes ()
void setSeparateAttributes (const char *aipc_separateAttributes)
const std::string & getSeparateAttributes ()
char getSeparateAttributesChar ()
void setHaveHeaderFileInstance (bool aib_bool)
bool getHaveHeaderFileInstance ()
void setClassInstanceColumn (uintidx aiui_classInstanceColumn)
uintidx getClassInstanceColumn ()
void setClusterInstanceColumn (uintidx aiui_clusterInstanceColumn)
uintidx getClusterInstanceColumn ()
void setIDInstanceColumn (uintidx aiui_idInstanceColumn)
uintidx getIDInstanceColumn ()
void setInstanceFrequencyColumn (uintidx aiui_instancesFrequencyColumn)
uintidx getInstanceFrequencyColumn ()
void setFormatInstanceFile (EnumFormatInstanceFile aienum_formatInstanceFile)
EnumFormatInstanceFile getFormatInstanceFile ()
void setIDMultiInstanceColumn (uintidx aiui_idMultiInstanceColumn)
uintidx getIDMultiInstanceColumn ()
void setClassMultiInstColumn (uintidx aiui_classMultiInstColumn)
uintidx getClassMultiInstColumn ()
void setNumInstances (uintidx aiui_numInstances)
const uintidx getNumInstances () const
void setNumInstancesTest (uintidx aiui_numInstancesTest)
const uintidx getNumInstancesTest () const
void setNumDimensionsInstances (uintidx aiui_numDimensionsInstances)
const uintidx getNumDimensionsInstances () const
void setPrintMulLine (bool aib_printMulLine)
bool getPrintMulLine ()
Additional Inherited Members
Protected Attributes inherited from inout::InParamGAClustering
uintidx st_sizePopulation
COMMON_IDOMAIN t_numMaxGenerations
Protected Attributes inherited from inout::InParamClustering
int i_opDistance
char * ps_outFileCentroids
char * ps_outFileMemberShip
char * ps_outFilePartitionsTable
char * ps_outFileGraph
char * ps_fileNamePlotStatObjetiveFunc
std::string _str_randomSeed
double _rd_maxExecutiontime
bool _b_printCentroidsFormat
bool _b_printTableFormat
Protected Attributes inherited from inout::InParamAlgorithmo
std::string s_algorithmoName
std::string s_algorithmoAuthor
InParam_algTypeOut ato_algTypeOut
char * ps_fileNameTimesRun
bool b_progressBarPrinting
int i_timesRunAlgorithm
std::string _s_runTimeId
std::string s_gnuplotCoreStyles
Protected Attributes inherited from inout::InParamFk< T_CLUSTERIDX >
T_CLUSTERIDX _idxK_numClusterK
Protected Attributes inherited from inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >
uintidx _ui_idxCurrentFileInstance
std::vector< std::string > _vectorstr_filesInstance
std::vector< std::string > _vectorstr_filesInstanceTest
EnumFormatInstanceFile _enum_formatInstanceFile
bool _b_haveHeaderFile
std::string _s_separatorAttributes
std::string _ps_selectAttributes
uintidx _ui_classInstanceColumn
uintidx _ui_clusterInstanceColumn
uintidx _ui_idInstanceColumn
uintidx _ui_instancesFrequencyColumn
uintidx _ui_idMultiInstanceColumn
uintidx _ui_classMultiInstColumn
uintidx _ui_numInstances
uintidx _ui_numDimensionsInstances
uintidx _ui_numInstancesTest
bool _b_printMulLine
Detailed Description
template<typename T_CLUSTERIDX, typename T_FEATURE, typename T_FEATURE_SUM, typename T_INSTANCES_CLUSTER_K>
class inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >
Input parameter for EA with adaptive probabilities of crossover and mutation [11].
Definition at line 38 of file inparam_adaptiveprobcprobm.hpp.
Constructor & Destructor Documentation
InParamAdaptivePcPm()
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::InParamAdaptivePcPm (const std::string & ais_algorithmoName, const std::string & ais_algorithmoAuthor, InParam_algTypeOut aiato_algTypeOut, int aii_opNorm) inline
Definition at line 45 of file inparam_adaptiveprobcprobm.hpp.
~InParamAdaptivePcPm()
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::~InParamAdaptivePcPm () inline
Definition at line 56 of file inparam_adaptiveprobcprobm.hpp.
Member Function Documentation
print()
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > virtual void inout::InParamAdaptivePcPm< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print (std::ostream & aipf_outFile = std::cout, const char aic_separator = ',') const inline virtual
Reimplemented from inout::InParamFk< T_CLUSTERIDX >.
Definition at line 58 of file inparam_adaptiveprobcprobm.hpp.
References inout::InParamFk< T_CLUSTERIDX >::print(), inout::InParamGAClustering::print(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::print().
The documentation for this class was generated from the following file:
include_inout/inparam_adaptiveprobcprobm.hpp