Library Evolutionary Algorithms for Clustering (LEAC): partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX > Class Template Reference
partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX > Class Template Reference
Partition of instances with bit crisp matrix.
#include <partition_crispmatrix.hpp>
Public Member Functions
PartitionCrispMatrix (const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aibitcrisp_matrix)
~PartitionCrispMatrix ()
void begin ()
const T_CLUSTERIDX next ()
bool end () const
virtual const T_CLUSTERIDX getClusterIdx (uintidx aiuintidx_instanceIdx) const
const uintidx getNumInstances () const
const T_CLUSTERIDX getNumCluster () const
virtual void print (std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
Public Member Functions inherited from partition::Partition< T_CLUSTERIDX >
Partition ()
Partition (const Partition< T_CLUSTERIDX > &aimembclassdisjset_b)
Partition (Partition< T_CLUSTERIDX > &&aimembclassdisjset_b)
~Partition ()
Protected Attributes
const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > * _ptcrisp_matrix
uintidx _ui_iteratornext
Detailed Description
template<class T_BITSIZE, class T_CLUSTERIDX>
class partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >
Partition of instances with bit crisp matrix.
Definition at line 37 of file partition_crispmatrix.hpp.
Constructor & Destructor Documentation
PartitionCrispMatrix()
template<class T_BITSIZE , class T_CLUSTERIDX > partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::PartitionCrispMatrix (const mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aibitcrisp_matrix) inline
Definition at line 43 of file partition_crispmatrix.hpp.
~PartitionCrispMatrix()
template<class T_BITSIZE , class T_CLUSTERIDX > partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::~PartitionCrispMatrix () inline
Definition at line 50 of file partition_crispmatrix.hpp.
Member Function Documentation
begin()
template<class T_BITSIZE , class T_CLUSTERIDX > void partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::begin () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 53 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ui_iteratornext.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print().
end()
template<class T_BITSIZE , class T_CLUSTERIDX > bool partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::end () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 63 of file partition_crispmatrix.hpp.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print().
getClusterIdx()
template<class T_BITSIZE , class T_CLUSTERIDX > virtual const T_CLUSTERIDX partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getClusterIdx (uintidx aiuintidx_instanceIdx) const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 69 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix.
getNumCluster()
template<class T_BITSIZE , class T_CLUSTERIDX > const T_CLUSTERIDX partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getNumCluster () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 79 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print().
getNumInstances()
template<class T_BITSIZE , class T_CLUSTERIDX > const uintidx partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getNumInstances () const inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 74 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix.
next()
template<class T_BITSIZE , class T_CLUSTERIDX > const T_CLUSTERIDX partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::next () inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 58 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix, and partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ui_iteratornext.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print().
print()
template<class T_BITSIZE , class T_CLUSTERIDX > virtual void partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print (std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',') inline virtual
Implements partition::Partition< T_CLUSTERIDX >.
Definition at line 85 of file partition_crispmatrix.hpp.
References partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix, partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::begin(), partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::end(), partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getNumCluster(), and partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::next().
Member Data Documentation
_ptcrisp_matrix
template<class T_BITSIZE , class T_CLUSTERIDX > const mat::CrispMatrix<T_BITSIZE,T_CLUSTERIDX>* partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ptcrisp_matrix protected
Definition at line 111 of file partition_crispmatrix.hpp.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getClusterIdx(), partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getNumCluster(), partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getNumInstances(), partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::next(), and partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::print().
_ui_iteratornext
template<class T_BITSIZE , class T_CLUSTERIDX > uintidx partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::_ui_iteratornext protected
Definition at line 112 of file partition_crispmatrix.hpp.
Referenced by partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::begin(), and partition::PartitionCrispMatrix< T_BITSIZE, T_CLUSTERIDX >::next().
The documentation for this class was generated from the following file:
include/partition_crispmatrix.hpp