Library Evolutionary Algorithms for Clustering (LEAC): include_inout/getsubopt.hpp File Reference
getsubopt.hpp File Reference
#include <stdlib.h>
#include <string.h>
Functions
static char * __strchrnul (char *s, int c)
int getsubopt_getsubopt (char **optionp, const char **tokens, char **valuep)
Function Documentation
__strchrnul()
static char * __strchrnul (char * s, int c) static
Definition at line 32 of file getsubopt.hpp.
References inout::c.
Referenced by getsubopt_getsubopt().
getsubopt_getsubopt()
int getsubopt_getsubopt (char ** optionp, const char ** tokens, char ** valuep)
Definition at line 47 of file getsubopt.hpp.
References __strchrnul().
Referenced by inout::InParamAlgorithmo::isYesNo().