Library Evolutionary Algorithms for Clustering (LEAC): eac/gnuplot_i.h File Reference
gnuplot_i.h File Reference
C interface to gnuplot.
#include <stdio.h>
Classes
struct _GNUPLOT_CTRL_
Macros
#define GP_MAX_TMP_FILES 1024
Typedefs
typedef struct _GNUPLOT_CTRL_ gnuplot_ctrl
gnuplot session handle (opaque type).
Functions
const char * gnuplot_tmpfile (gnuplot_ctrl *handle)
void gnuplot_plot_atmpfile (gnuplot_ctrl *handle, const char *tmp_filename, const char *title)
gnuplot_ctrl * gnuplot_init (void)
Opens up a gnuplot session, ready to receive commands.
void gnuplot_close (gnuplot_ctrl *handle)
Closes a gnuplot session previously opened by gnuplot_init()
void gnuplot_cmd (gnuplot_ctrl *handle, const char *cmd,...)
Sends a command to an active gnuplot session.
void gnuplot_setstyle (gnuplot_ctrl *h, const char *plot_style)
Change the plotting style of a gnuplot session.
void gnuplot_set_xlabel (gnuplot_ctrl *h, const char *label)
Sets the x label of a gnuplot session.
void gnuplot_set_ylabel (gnuplot_ctrl *h, const char *label)
Sets the y label of a gnuplot session.
void gnuplot_resetplot (gnuplot_ctrl *h)
Resets a gnuplot session (next plot will erase previous ones).
void gnuplot_plot_x (gnuplot_ctrl *handle, double *d, int n, const char *title)
Plots a 2d graph from a list of doubles.
void gnuplot_plot_xy (gnuplot_ctrl *handle, double *x, double *y, int n, const char *title)
Plot a 2d graph from a list of points.
void gnuplot_plot_once (char *title, char *style, char *label_x, char *label_y, double *x, double *y, int n)
Open a new session, plot a signal, close the session.
void gnuplot_plot_slope (gnuplot_ctrl *handle, double a, double b, const char *title)
Plot a slope on a gnuplot session.
void gnuplot_plot_equation (gnuplot_ctrl *h, const char *equation, const char *title)
Plot a curve of given equation y=f(x).
int gnuplot_write_x_csv (const char *fileName, double const *d, int n, const char *title)
int gnuplot_write_xy_csv (const char *fileName, double const *x, double const *y, int n, const char *title)
int gnuplot_write_multi_csv (const char *fileName, double const **xListPtr, int n, int numColumns, const char *title)
Detailed Description
C interface to gnuplot.
Author
N. Devillard
Date
Sep 1998
Version
Revision
1.11
gnuplot is a freely available, command-driven graphical display tool for Unix. It compiles and works quite well on a number of Unix flavours as well as other operating systems. The following module enables sending display requests to gnuplot through simple C calls.
Definition in file gnuplot_i.h.
Macro Definition Documentation
GP_MAX_TMP_FILES
#define GP_MAX_TMP_FILES 1024
Maximal number of simultaneous temporary files
Definition at line 39 of file gnuplot_i.h.
Typedef Documentation
gnuplot_ctrl
gnuplot_ctrl
gnuplot session handle (opaque type).
This structure holds all necessary information to talk to a gnuplot session. It is built and returned by gnuplot_init() and later used by all functions in this module to communicate with the session, then meant to be closed by gnuplot_close().
This structure is meant to remain opaque, you normally do not need to know what is contained in there.
Function Documentation
gnuplot_close()
void gnuplot_close (gnuplot_ctrl * handle)
Closes a gnuplot session previously opened by gnuplot_init()
Parameters
handle Gnuplot session control handle.
Returns
void
Kills the child PID and deletes all opened temporary files. It is mandatory to call this function to close the handle, otherwise temporary files are not cleaned and child process might survive.
Definition at line 140 of file gnuplot_i.c.
References _GNUPLOT_CTRL_::gnucmd, _GNUPLOT_CTRL_::ntmp, and _GNUPLOT_CTRL_::tmp_filename_tbl.
Referenced by gnuplot_plot_once(), and main().
gnuplot_cmd()
void gnuplot_cmd (gnuplot_ctrl * handle, const char * cmd, ...)
Sends a command to an active gnuplot session.
Parameters
handle Gnuplot session control handle
cmd Command to send, same as a printf statement.
This sends a string to an active gnuplot session, to be executed. There is strictly no way to know if the command has been successfully executed or not. The command syntax is the same as printf.
Examples:
gnuplot_cmd(g, "plot %d*x", 23.0);
gnuplot_cmd(g, "plot %g * cos(%g * x)", 32.0, -3.0);
Since the communication to the gnuplot process is run through a standard Unix pipe, it is only unidirectional. This means that it is not possible for this interface to query an error status back from gnuplot.
Parameters
handle Gnuplot session control handle
cmd Command to send, same as a printf statement.
This sends a string to an active gnuplot session, to be executed. There is strictly no way to know if the command has been successfully executed or not. The command syntax is the same as printf.
Examples:
gnuplot_cmd(g, "plot %d*x", 23.0);
gnuplot_cmd(g, "plot %.18e * cos(%.18e * x)", 32.0, -3.0);
Since the communication to the gnuplot process is run through a standard Unix pipe, it is only unidirectional. This means that it is not possible for this interface to query an error status back from gnuplot.
Definition at line 186 of file gnuplot_i.c.
References _GNUPLOT_CTRL_::gnucmd.
Referenced by gnuplot_plot_atmpfile(), gnuplot_plot_equation(), gnuplot_plot_slope(), gnuplot_set_xlabel(), gnuplot_set_ylabel(), and main().
gnuplot_init()
gnuplot_ctrl* gnuplot_init (void)
Opens up a gnuplot session, ready to receive commands.
Returns
Newly allocated gnuplot control structure.
This opens up a new gnuplot session, ready for input. The struct controlling a gnuplot session should remain opaque and only be accessed through the provided functions.
The session must be closed using gnuplot_close().
Definition at line 90 of file gnuplot_i.c.
References _GNUPLOT_CTRL_::gnucmd, gnuplot_setstyle(), GP_MAX_TMP_FILES, _GNUPLOT_CTRL_::nplots, _GNUPLOT_CTRL_::ntmp, and _GNUPLOT_CTRL_::tmp_filename_tbl.
Referenced by gnuplot_plot_once(), and main().
gnuplot_plot_atmpfile()
void gnuplot_plot_atmpfile (gnuplot_ctrl * handle, const char * tmp_filename, const char * title)
Plot a temporary file.
Author
Peter (12/9/2011)
Parameters
handle
tmp_filename
title
Definition at line 714 of file gnuplot_i.c.
References gnuplot_cmd(), _GNUPLOT_CTRL_::nplots, and _GNUPLOT_CTRL_::pstyle.
Referenced by gnuplot_plot_x(), and gnuplot_plot_xy().
gnuplot_plot_equation()
void gnuplot_plot_equation (gnuplot_ctrl * h, const char * equation, const char * title)
Plot a curve of given equation y=f(x).
Parameters
h Gnuplot session control handle.
equation Equation to plot.
title Title of the plot.
Returns
void
Plots out a curve of given equation. The general form of the equation is y=f(x), you only provide the f(x) side of the equation.
Example:
gnuplot_ctrl    *h ;
char            eq[80] ;
h = gnuplot_init() ;
strcpy(eq, "sin(x) * cos(2*x)") ;
gnuplot_plot_equation(h, eq, "sine wave", normal) ;
gnuplot_close(h) ;
Definition at line 516 of file gnuplot_i.c.
References gnuplot_cmd(), _GNUPLOT_CTRL_::nplots, and _GNUPLOT_CTRL_::pstyle.
gnuplot_plot_once()
void gnuplot_plot_once (char * title, char * style, char * label_x, char * label_y, double * x, double * y, int n)
Open a new session, plot a signal, close the session.
Parameters
title Plot title
style Plot style
label_x Label for X
label_y Label for Y
x Array of X coordinates
y Array of Y coordinates (can be NULL)
n Number of values in x and y.
Returns
This function opens a new gnuplot session, plots the provided signal as an X or XY signal depending on a provided y, waits for a carriage return on stdin and closes the session.
It is Ok to provide an empty title, empty style, or empty labels for X and Y. Defaults are provided in this case.
Definition at line 457 of file gnuplot_i.c.
References gnuplot_close(), gnuplot_init(), gnuplot_plot_x(), gnuplot_plot_xy(), gnuplot_set_xlabel(), gnuplot_set_ylabel(), and gnuplot_setstyle().
gnuplot_plot_slope()
void gnuplot_plot_slope (gnuplot_ctrl * handle, double a, double b, const char * title)
Plot a slope on a gnuplot session.
Parameters
handle Gnuplot session control handle.
a Slope.
b Intercept.
title Title of the plot.
Returns
void
Plot a slope on a gnuplot session. The provided slope has an equation of the form y=ax+b
Example:
gnuplot_ctrl    *   h ;
double              a, b ;
h = gnuplot_init() ;
gnuplot_plot_slope(h, 1.0, 0.0, "unity slope") ;
sleep(2) ;
gnuplot_close(h) ;
Definition at line 498 of file gnuplot_i.c.
References inout::a, gnuplot_cmd(), _GNUPLOT_CTRL_::nplots, and _GNUPLOT_CTRL_::pstyle.
gnuplot_plot_x()
void gnuplot_plot_x (gnuplot_ctrl * handle, double * d, int n, const char * title)
Plots a 2d graph from a list of doubles.
Parameters
handle Gnuplot session control handle.
d Array of doubles.
n Number of values in the passed array.
title Title of the plot.
Returns
void
Plots out a 2d graph from a list of doubles. The x-coordinate is the index of the double in the list, the y coordinate is the double in the list.
Example:
gnuplot_ctrl    *h ;
double          d[50] ;
int             i ;
h = gnuplot_init() ;
for (i=0 ; i<50 ; i++) {
    d[i] = (double)(i*i) ;
}
gnuplot_plot_x(h, d, 50, "parabola") ;
sleep(2) ;
gnuplot_close(h) ;
Definition at line 335 of file gnuplot_i.c.
References inout::d, gnuplot_plot_atmpfile(), and gnuplot_tmpfile().
Referenced by gnuplot_plot_once().
gnuplot_plot_xy()
void gnuplot_plot_xy (gnuplot_ctrl * handle, double * x, double * y, int n, const char * title)
Plot a 2d graph from a list of points.
Parameters
handle Gnuplot session control handle.
x Pointer to a list of x coordinates.
y Pointer to a list of y coordinates.
n Number of doubles in x (assumed the same as in y).
title Title of the plot.
Returns
void
Plots out a 2d graph from a list of points. Provide points through a list of x and a list of y coordinates. Both provided arrays are assumed to contain the same number of values.
gnuplot_ctrl    *h ;
double          x[50] ;
double          y[50] ;
int             i ;
h = gnuplot_init() ;
for (i=0 ; i<50 ; i++) {
    x[i] = (double)(i)/10.0 ;
    y[i] = x[i] * x[i] ;
}
gnuplot_plot_xy(h, x, y, 50, "parabola") ;
sleep(2) ;
gnuplot_close(h) ;
Definition at line 401 of file gnuplot_i.c.
References gnuplot_plot_atmpfile(), and gnuplot_tmpfile().
Referenced by gnuplot_plot_once().
gnuplot_resetplot()
void gnuplot_resetplot (gnuplot_ctrl * h)
Resets a gnuplot session (next plot will erase previous ones).
Parameters
h Gnuplot session control handle.
Returns
void
Resets a gnuplot session, i.e. the next plot will erase all previous ones.
Definition at line 288 of file gnuplot_i.c.
References _GNUPLOT_CTRL_::nplots, _GNUPLOT_CTRL_::ntmp, and _GNUPLOT_CTRL_::tmp_filename_tbl.
gnuplot_set_xlabel()
void gnuplot_set_xlabel (gnuplot_ctrl * h, const char * label)
Sets the x label of a gnuplot session.
Parameters
h Gnuplot session control handle.
label Character string to use for X label.
Returns
void
Sets the x label for a gnuplot session.
Definition at line 254 of file gnuplot_i.c.
References gnuplot_cmd().
Referenced by gnuplot_plot_once().
gnuplot_set_ylabel()
void gnuplot_set_ylabel (gnuplot_ctrl * h, const char * label)
Sets the y label of a gnuplot session.
Parameters
h Gnuplot session control handle.
label Character string to use for Y label.
Returns
void
Sets the y label for a gnuplot session.
Definition at line 271 of file gnuplot_i.c.
References gnuplot_cmd().
Referenced by gnuplot_plot_once().
gnuplot_setstyle()
void gnuplot_setstyle (gnuplot_ctrl * h, const char * plot_style)
Change the plotting style of a gnuplot session.
Parameters
h Gnuplot session control handle
plot_style Plotting-style to use (character string)
Returns
void
The provided plotting style is a character string. It must be one of the following:
lines
points
linespoints
impulses
dots
steps
errorbars
boxes
boxeserrorbars
Definition at line 223 of file gnuplot_i.c.
References _GNUPLOT_CTRL_::pstyle.
Referenced by gnuplot_init(), and gnuplot_plot_once().
gnuplot_tmpfile()
const char* gnuplot_tmpfile (gnuplot_ctrl * handle)
Creates a temporary file name for writing
Author
Peter (12/9/2011)
Parameters
handle
Returns
const char * Pointer to file name string.
Definition at line 662 of file gnuplot_i.c.
References GP_MAX_TMP_FILES, _GNUPLOT_CTRL_::ntmp, and _GNUPLOT_CTRL_::tmp_filename_tbl.
Referenced by gnuplot_plot_x(), gnuplot_plot_xy(), and main().
gnuplot_write_multi_csv()
int gnuplot_write_multi_csv (const char * fileName, double const ** xListPtr, int n, int numColumns, const char * title)
Writes a multi column CSV file for use with gnuplot commands later. Allows files to also be saved for post analysis with excel for example. Note that when used with gnuplot, since there may be more than one column the whole "1:3" or whatever should be used.
Uses title as gnuplot "comment" on the first line.
Author
Peter H Maresh 11/8/2011
Parameters
fileName file name to write to. This should be the same name used in the gnuplot command
xListPtr A list of pointers to column buffers
n
numColumns Length of xListPtr list. Note that the CSV file will add an additional "index" column first.
title Title to write for the first line of the .csv file, will be preceeded by "#"
Returns
int <0 if file wasn't written.
Definition at line 609 of file gnuplot_i.c.
gnuplot_write_x_csv()
int gnuplot_write_x_csv (const char * fileName, double const * d, int n, const char * title)
Writes a CSV file for use with gnuplot commands later. Allows files to also be saved for post analysis with excel for example. Arguments are similar to gnuplot_plot_x()
Uses title as gnuplot "comment" on the first line.
Author
Peter H Maresh 11/8/2011
Parameters
fileName file name to write to. This should be the same name used in the gnuplot command
d
n
title
Returns
int <0 if error writing file.
Definition at line 532 of file gnuplot_i.c.
References inout::d.
gnuplot_write_xy_csv()
int gnuplot_write_xy_csv (const char * fileName, double const * x, double const * y, int n, const char * title)
Writes a CSV file for use with gnuplot commands later. Allows files to also be saved for post analysis with excel for example. Arguments are similar to gnuplot_plot_xy()
Uses title as gnuplot "comment" on the first line.
Author
Peter H Maresh 11/8/2011
Parameters
fileName file name to write to. This should be the same name used in the gnuplot command
x
y
n
title
Returns
int <0 if file wasn't written.
Definition at line 570 of file gnuplot_i.c.