Library Evolutionary Algorithms for Clustering (LEAC): eac/main_gas_clustering.cpp File Reference
main_gas_clustering.cpp File Reference
Main program of Evolutionary Algorithms.
#include <iostream>
#include <leac.hpp>
#include "inparamclustering_getparameter.hpp"
#include "instances_read.hpp"
#include "bar_progress.hpp"
Functions
int main (int argc, char **argv)
Detailed Description
Main program of Evolutionary Algorithms.
MAIN GET METRIC SATURDAY 30 JUNE
This file is part of the LEAC.
Version
1.0
Date
2015-2017
Authors
Hermes Robles herme.nosp@m.s@ua.nosp@m.z.edu.nosp@m..mx
Sebastian Ventura svent.nosp@m.ura@.nosp@m.uco.e.nosp@m.s
Amelia Zafra azafr.nosp@m.a@uc.nosp@m.o.es
Copyright
GPLv3 license
Definition in file main_gas_clustering.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 198 of file main_gas_clustering.cpp.
References inout::barprogress_update(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), clusteringop::bkinCiToMemberShip(), eac::cbga_fkcentroid(), inout::CENTROIDS, eac::cga_vklabel(), inout::OutFileName::closeFile(), eac::clustering_vksubclusterbinary(), COMMON_COUT_PRECISION, graph::component(), inout::CSmeasure, um::CSmeasure(), inout::dataSetRead(), inout::dataSetReadWithFreq(), DATATYPE_BITSIZE, DATATYPE_CLUSTERIDX, DATATYPE_FEATURE, DATATYPE_FEATURE_SUM, DATATYPE_INSTANCE_FREQUENCY, DATATYPE_INSTANCEIDX, DATATYPE_INSTANCES_CLUSTER_K, DATATYPE_REAL, inout::DBindex, um::dbindex(), inout::Distortion, inout::DunnIndex, um::DunnIndex(), inout::Entropy, um::entropy(), eac::feca_vklabel(), inout::Fmeasure, sm::fmeasure(), graph::fromPiToGraph(), clusteringop::fuzzyPartition(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), clusteringop::getCentroids(), clusteringop::getClusters(), sm::getConfusionMatrix(), inout::OutFileName::getDelim(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUDiffClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUSomeClusterV(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getFrequency(), mat::getIdentity(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getInstClusterK(), sm::getMatchingMatrix(), dist::getMatrixDissimilarity(), stats::getMatrixMahalonobis(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getMisclassified(), data::Instance< T_FEATURE >::getNumDimensions(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getNumObjetos(), mat::MatrixBase< T_FEATURE >::getNumRows(), inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFunc(), inout::OutParamClusteringMetric< T_METRIC >::getObjetiveFuncTest(), ds::getPartitionLinkedNumInst(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUDiffClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getStringSize(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getStringSize(), sm::getStrSenSpe(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), inout::IndexI, um::indexI(), inout::IndexI_cFuzzy, um::indexIreeval(), clusteringop::initialize(), inout::OutParamClusteringMetric< T_METRIC >::initialize(), INPARAMCLUSTERING_CBGA_SELECMETH_ELITIST1, INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, INPARAMCLUSTERING_DISTANCE_DIAGONAL_INDUCED, INPARAMCLUSTERING_DISTANCE_EUCLIDEAN, INPARAMCLUSTERING_DISTANCE_EUCLIDEAN_INDUCED, INPARAMCLUSTERING_DISTANCE_EUCLIDEAN_SQ, INPARAMCLUSTERING_DISTANCE_MAHALONOBIS_INDUCED, inout::instancesReadDimName(), inout::IntraInterClust, inout::J1, inout::JaccardIndex, sm::jaccardIndex(), inout::Jm, um::jm(), eac::kga_fkcentroid(), inout::LABEL, inout::li_i, partition::makePartition(), stats::meanVector(), measuare_undefSilhouette, measuare_undefSSE, inout::MEDOIDS, inout::Misclassified, inout::OutFileName::openFile(), inout::Pairs_a, inout::Pairs_b, inout::Pairs_c, inout::Pairs_d, inout::PartitionCoefficient, um::partitioncoefficient(), inout::precision, sm::precision(), partition::PartitionDisjSets< T_CLUSTERIDX >::print(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::print(), mat::MatrixRow< T_FEATURE >::print(), inout::OutParamClusteringMetric< T_METRIC >::print(), inout::Purity, sm::purity(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::r8mat_print(), mat::MatrixRow< T_FEATURE >::r8mat_print(), sm::randIndex(), inout::RandIndex, inout::recall, sm::recall(), inout::ScoreFunction, um::scoreFunction(), um::scoreFunctionreeval(), inout::SDunnIndex, inout::SED, inout::OutParamClusteringMetric< T_METRIC >::setMetricFunc(), inout::OutParamClusteringMetric< T_METRIC >::setMetricFuncTest(), inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivity(), inout::OutParamClusteringMetric< T_METRIC >::setPercentageSensitivityTest(), inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificity(), inout::OutParamClusteringMetric< T_METRIC >::setPercentageSpecificityTest(), randomext::setSeed(), inout::Silhouette, um::silhouette(), um::simplifiedDunnIndex(), um::simplifiedSilhouette(), inout::SSB, um::ssb(), um::ssbreeval(), inout::SSE, um::SSE(), inout::SSilhouette, interfacesse::sum(), stats::sumFeactures(), stats::sumFeacturesFreq(), stats::sumFeacturesFreqSQ(), stats::sumFeacturesSQ(), eac::tgca_vkcentroid(), data::toMatrixRow(), UNKNOWN_CLUSTER_REAL, stats::varTodesvstd(), inout::vectorlistprint(), inout::VRC, um::VRC(), um::VRCreeval(), inout::WBIndex, um::WBIndex(), um::WBIndexreeval(), um::xb(), inout::XieBeniIndex, and inout::XieBeniIndex_crisp.