Library Evolutionary Algorithms for Clustering (LEAC): eac/main_stdvar_milligan_cooper1988.cpp File Reference
main_stdvar_milligan_cooper1988.cpp File Reference
Main program for the standardization of instances [34].
#include "instances_read.hpp"
#include "datatype_instance_real.hpp"
#include "outfilename.hpp"
#include "file_utils.hpp"
#include "stats_instances.hpp"
#include "linear_algebra_level1.hpp"
#include "linear_algebra_level2.hpp"
#include "inparam_stdvar.hpp"
#include "inparamclustering_getparameter.hpp"
#include "verbose.hpp"
Functions
int main (int argc, char **argv)
Detailed Description
Main program for the standardization of instances [34].
This file is part of the LEAC.
Implementation of the standardization of variables based on the paper:
G.W. Milligan and M.C. Cooper. A study of standardization
of variables in cluster analysis. J. Classification,
5:181–204, 1988.
doi:http://www.springerlink.com/content/t588424722r23031
.
Library Evolutionary Algorithms for Clustering (LEAC) is a library
for the implementation of evolutionary and genetic algorithms
focused on the partition type clustering problem. Based on the
current standards of the C++ language, as well as on Standard
Template Library STL and also OpenBLAS to have a better performance.
Version
1.0
Date
2015-2017
Authors
Hermes Robles-Berumen herme.nosp@m.s@ua.nosp@m.z.edu.nosp@m..mx
Sebastian Ventura svent.nosp@m.ura@.nosp@m.uco.e.nosp@m.s
Amelia Zafra azafr.nosp@m.a@uc.nosp@m.o.es
KDIS
Copyright
GPLv3 license
Definition in file main_stdvar_milligan_cooper1988.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 39 of file main_stdvar_milligan_cooper1988.cpp.
References interfacesse::axpy(), inout::OutFileName::closeFile(), COMMON_COUT_PRECISION, DATATYPE_CLUSTERIDX, DATATYPE_FEATURE, DATATYPE_FEATURE_SUM, DATATYPE_INSTANCES_CLUSTER_K, inout::OutFileName::getDelim(), data::Instance< T_FEATURE >::getNumDimensions(), clusteringop::initialize(), inout::instancesRead(), inout::instancesReadDimName(), inout::instancesReadWithClass(), inout::li_i, stats::maxFeatures(), stats::meanVector(), stats::minFeatures(), inout::OutFileName::openFile(), inout::OTHER, stats::rank(), STD_VAR_Z0, STD_VAR_Z1, STD_VAR_Z2, STD_VAR_Z3, STD_VAR_Z4, STD_VAR_Z5, STD_VAR_Z6, STD_VAR_Z7, stats::sumFeactures(), stats::sumFeacturesSQ(), and stats::varTodesvstd().