Library Evolutionary Algorithms for Clustering (LEAC): eac/main_plot_clustering.cpp File Reference
main_plot_clustering.cpp File Reference
Main program for plot clustering.
#include <iostream>
#include <istream>
#include <stdexcept>
#include <sstream>
#include <fstream>
#include <string>
#include <cstring>
#include <algorithm>
#include <vector>
#include "matrix.hpp"
#include "matrix_read.hpp"
#include "instances_read.hpp"
#include "gnuplot_i.h"
#include "transformation.hpp"
#include "datatype_instance_real.hpp"
#include "stats_instances.hpp"
#include "inparam_plotclustering.hpp"
#include "inparamclustering_getparameter.hpp"
#include "verbose.hpp"
Functions
std::pair< bool, std::string > plotclustering_getDataFile (std::ifstream &lfp_file)
int main (int argc, char **argv)
Detailed Description
Main program for plot clustering.
This file is part of the LEAC.
Version
1.0
Date
2015-2017
Authors
Hermes Robles-Berumen herme.nosp@m.s@ua.nosp@m.z.edu.nosp@m..mx
Sebastian Ventura svent.nosp@m.ura@.nosp@m.uco.e.nosp@m.s
Amelia Zafra azafr.nosp@m.a@uc.nosp@m.o.es
KDIS
Copyright
GPLv3 license
Definition in file main_plot_clustering.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 55 of file main_plot_clustering.cpp.
References DATATYPE_CLUSTERIDX, DATATYPE_FEATURE, DATATYPE_INSTANCES_CLUSTER_K, data::InstanceIterfazClass< T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassIdx(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getId(), inout::LineSplit::getItem(), mat::getMatrixTransformPCA(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), inout::LineSplit::getVectorRawString(), gnuplot_close(), gnuplot_cmd(), gnuplot_init(), gnuplot_tmpfile(), clusteringop::initialize(), INPARAMCLUSTERING_PLOTPLOJECTION_PCA, inout::instancesReadWithClass(), inout::li_i, _GNUPLOT_CTRL_::nplots, inout::OTHER, plotclustering_getDataFile(), mat::point(), data::Instance< T_FEATURE >::setHomogeneousCoord(), and inout::LineSplit::split().
plotclustering_getDataFile()
std::pair<bool,std::string> plotclustering_getDataFile (std::ifstream & lfp_file)
Definition at line 35 of file main_plot_clustering.cpp.
Referenced by main().