Library Evolutionary Algorithms for Clustering (LEAC): gagenericop Namespace Reference
gagenericop Namespace Reference
Genetic operators independent of the data type.
Functions
template<typename ITERATOR , typename FUNCTION >
void initializeGenes (ITERATOR iterator_first, const ITERATOR iterator_last, const FUNCTION function)
Initialize genes.
template<typename T_GENE , typename T_METRIC >
void onePointCrossover (gaencode::ChromFixedLength< T_GENE, T_METRIC > &aochrom_child1, gaencode::ChromFixedLength< T_GENE, T_METRIC > &aochrom_child2, const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_parent1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_parent2)
single-point crossover (Michalewicz, 1992).
template<typename T_GENE , typename T_METRIC >
void onePointCrossover (gaencode::ChromVariableLength< T_GENE, T_METRIC > &aiochrom_child1, gaencode::ChromVariableLength< T_GENE, T_METRIC > &aiochrom_child2)
One point length variable crossover [18].
template<typename T_GENE , typename T_METRIC >
uintidx GAGRdist (const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_vector1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_vector2)
GAGRdist Definition 2. [11].
template<typename T_GENE >
void GAGRx1x2bar (T_GENE *aoaT_xr, uintidx aist_xrLength, T_GENE *aiaT_x1, T_GENE *aiaT_x2)
GAGRx1x2bar Definition 3. [11].
template<typename T_GENE >
void GAGRx1x2up (T_GENE *aoaT_xr, uintidx aist_xrLength, T_GENE *aiaT_x1, T_GENE *aiaT_x2)
GAGRx1x2up Definition 4. [11].
template<typename T_GENE >
void GAGRx1x2down (T_GENE *aoaT_xr, uintidx aist_xrLength, T_GENE *aiaT_x1, T_GENE *aiaT_x2)
GAGRx1x2down Definition 5. [11].
template<typename T_GENE >
uintidx GAGRcrossoverpathM1n (T_GENE *aioaf_m1n, uintidx aioaf_m1nLength, uintidx aii_initialIdx, T_GENE *aiaf_m1m2Bar)
GAGRcrossoverpathM1n [11].
template<typename T_GENE >
uintidx GAGRcrossoverpathM2n (T_GENE *aioaf_m2n, uintidx aii_initialIdx, T_GENE *aiaf_m2)
GAGRcrossoverpathM2n [11].
template<typename T_GENE , typename T_METRIC >
void pathCrossover (gaencode::ChromFixedLength< T_GENE, T_METRIC > &aochrom_child1, gaencode::ChromFixedLength< T_GENE, T_METRIC > &aochrom_child2, const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_parent1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > &aichrom_parent2, const uintidx aiuintidx_GAGRdistM1M2, gafuncobj::GAFunctionObjective< T_GENE, T_METRIC > &aigafo_gaFunctionObjective)
Detailed Description
Genetic operators independent of the data type.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
GAGRcrossoverpathM1n()
template<typename T_GENE > uintidx gagenericop::GAGRcrossoverpathM1n (T_GENE * aioaf_m1n, uintidx aioaf_m1nLength, uintidx aii_initialIdx, T_GENE * aiaf_m1m2Bar)
GAGRcrossoverpathM1n [11].
Definition at line 421 of file ga_generic_operator.hpp.
Referenced by pathCrossover().
GAGRcrossoverpathM2n()
template<typename T_GENE > uintidx gagenericop::GAGRcrossoverpathM2n (T_GENE * aioaf_m2n, uintidx aii_initialIdx, T_GENE * aiaf_m2)
GAGRcrossoverpathM2n [11].
Definition at line 443 of file ga_generic_operator.hpp.
Referenced by pathCrossover().
GAGRdist()
template<typename T_GENE , typename T_METRIC > uintidx gagenericop::GAGRdist (const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_vector1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_vector2)
GAGRdist Definition 2. [11].
Parameters
aichrom_vector1 a gaencode::ChromFixedLength
aichrom_vector2 a gaencode::ChromFixedLength
Definition at line 301 of file ga_generic_operator.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString().
Referenced by eac::gagr_fkcentroid().
GAGRx1x2bar()
template<typename T_GENE > void gagenericop::GAGRx1x2bar (T_GENE * aoaT_xr, uintidx aist_xrLength, T_GENE * aiaT_x1, T_GENE * aiaT_x2)
GAGRx1x2bar Definition 3. [11].
Definition at line 353 of file ga_generic_operator.hpp.
Referenced by pathCrossover().
GAGRx1x2down()
template<typename T_GENE > void gagenericop::GAGRx1x2down (T_GENE * aoaT_xr, uintidx aist_xrLength, T_GENE * aiaT_x1, T_GENE * aiaT_x2)
GAGRx1x2down Definition 5. [11].
Definition at line 394 of file ga_generic_operator.hpp.
GAGRx1x2up()
template<typename T_GENE > void gagenericop::GAGRx1x2up (T_GENE * aoaT_xr, uintidx aist_xrLength, T_GENE * aiaT_x1, T_GENE * aiaT_x2)
GAGRx1x2up Definition 4. [11].
Definition at line 370 of file ga_generic_operator.hpp.
initializeGenes()
template<typename ITERATOR , typename FUNCTION > void gagenericop::initializeGenes (ITERATOR iterator_first, const ITERATOR iterator_last, const FUNCTION function) inline
Initialize genes.
Parameters
iterator_first a conteiner iterator where items begin
iterator_last a conteiner iterator where items end
function a uniform integer _distribution for generate genes
for (auto lchromfixleng_iter :lvectorchromfixleng_population) {
  gaintegerop::initializeGenes
    (lchromfixleng_iter->begin(),
     lchromfixleng_iter->end(),
     [&]()
     {
       return uniformdis_cidx_0K(gmt19937_eng);
     }
     );
}
Definition at line 62 of file ga_generic_operator.hpp.
Referenced by eac::cga_vklabel(), eac::gaclustering_fklabel(), eac::gga_vklabel(), eac::gka_fklabel(), and eac::igka_fklabel().
onePointCrossover() [1/2]
template<typename T_GENE , typename T_METRIC > void gagenericop::onePointCrossover (gaencode::ChromFixedLength< T_GENE, T_METRIC > & aochrom_child1, gaencode::ChromFixedLength< T_GENE, T_METRIC > & aochrom_child2, const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_parent1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_parent2)
single-point crossover (Michalewicz, 1992).
Parameters
aochrom_child1 a gaencode::ChromFixedLength<T_GENE,T_METRIC>
aochrom_child2 a gaencode::ChromFixedLength<T_GENE,T_METRIC>
aichrom_parent1 a gaencode::ChromFixedLength<T_GENE,T_METRIC>
aichrom_parent2 a ChromFixedLength<T_GENE,T_METRIC>
gaiterator::crossover
  (lvectorchromfixleng_matingPool.begin(),
   lvectorchromfixleng_matingPool.end(),
   lvectorchromfixleng_population.begin(),
   lvectorchromfixleng_population.end(),
   [&](const gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>* aichrom_parent1,
       const gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>* aichrom_parent2,
       gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>*  aochrom_child1,
       gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>*  aochrom_child2
      )
   {
      if ( uniformdis_real01(gmt19937_eng) <
           aiinpcgaprobfixedk_inParamGA.getProbCrossover()  ) {
         gagenericop::onePointCrossover
           (*aochrom_child1,
            *aochrom_child2,
            *aichrom_parent1,
            *aichrom_parent2
           );
      } //if  Crossover
      else {
        *aochrom_child1 = *aichrom_parent1;
        *aochrom_child2 = *aichrom_parent2;
      }
   }
 );
Definition at line 121 of file ga_generic_operator.hpp.
References interfacesse::copy(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, and gaencode::ChromFixedLength< T_GENE, T_METRIC >::print().
Referenced by eac::gaclustering_fklabel(), eac::gas_fkcentroid(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
onePointCrossover() [2/2]
template<typename T_GENE , typename T_METRIC > void gagenericop::onePointCrossover (gaencode::ChromVariableLength< T_GENE, T_METRIC > & aiochrom_child1, gaencode::ChromVariableLength< T_GENE, T_METRIC > & aiochrom_child2)
One point length variable crossover [18].
Parameters
aiochrom_child1 a ChromVariableLength<T_GENE,T_METRIC>
aiochrom_child2 a ChromVariableLength<T_GENE,T_METRIC>
Definition at line 204 of file ga_generic_operator.hpp.
References interfacesse::copy(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, and gaencode::ChromVariableLength< T_GENE, T_METRIC >::print().
pathCrossover()
template<typename T_GENE , typename T_METRIC > void gagenericop::pathCrossover (gaencode::ChromFixedLength< T_GENE, T_METRIC > & aochrom_child1, gaencode::ChromFixedLength< T_GENE, T_METRIC > & aochrom_child2, const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_parent1, const gaencode::ChromFixedLength< T_GENE, T_METRIC > & aichrom_parent2, const uintidx aiuintidx_GAGRdistM1M2, gafuncobj::GAFunctionObjective< T_GENE, T_METRIC > & aigafo_gaFunctionObjective)
Definition at line 476 of file ga_generic_operator.hpp.
References inout::containerprint(), interfacesse::copy(), GAGRcrossoverpathM1n(), GAGRcrossoverpathM2n(), GAGRx1x2bar(), gafuncobj::GAFunctionObjective< T_GENE, T_METRIC >::getFitness(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), gafuncobj::GAFunctionObjective< T_GENE, T_METRIC >::getObjetiveFunc(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getStringSize(), gaencode::ChromosomeBase< T_METRIC >::getValidString(), gmt19937_eng, gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setString(), gaencode::ChromosomeBase< T_METRIC >::setValidString(), and gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize().
Referenced by eac::gagr_fkcentroid().