Library Evolutionary Algorithms for Clustering (LEAC): graph Namespace Reference
graph Namespace Reference
Algorithms and utilities for graphs.
Classes
class AlgorithmsDFS
Depth-first search algorithms.
class AlgorithmsDFSAdjMatrix
Depth-first search algorithms for a matrix of bits.
Enumerations
enum GraphStateVertex { VERTEXSTATE_WHITE =0, VERTEXSTATE_GRAY =1, VERTEXSTATE_BLACK =2 }
Functions
std::map< uintidx, std::list< uintidx > > fromPiToGraphMap (const std::vector< uintidx > &aivectorvertexidx_pi)
Constructs a list map graph from PI vertices for a Pi vector.
template<typename T_VERTEX_IDX >
std::vector< std::list< T_VERTEX_IDX > > fromPiToGraph (const std::vector< T_VERTEX_IDX > &aivectorvertexidx_pi)
Constructs a vector list graph from PI vertices for a Pi vector.
template<typename T_VERTEX_IDX , typename T_BITSIZE >
std::vector< std::list< T_VERTEX_IDX > > fromPiToGraph (const std::vector< T_VERTEX_IDX > &aivectorvertexidx_pi, const mat::BitArray< T_BITSIZE > &aibitarray_edgeRemains)
Constructs a vector list graph from PI vertices for a Pi vector.
ds::DisjSets component (const std::vector< uintidx > &aivectoruintidx_vertexPi)
Find connected component of a graph.
template<typename T_BITSIZE >
ds::DisjSets component (const std::vector< uintidx > &aivectoruintidx_vertexPi, const mat::BitArray< T_BITSIZE > &aibitarray_edgeRemains)
Find connected component of a graph.
template<typename T_W >
std::vector< uintidx > prim (const mat::MatrixTriang< T_W > &aimatrixtriagt_w, const uintidx lui_startVertex=0)
Prim’s algorithm.
template<typename T_BITSIZE , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR >
mat::BitMatrix< T_BITSIZE > getAdjacencyMatrix (const T_DIST ait_distAdj, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist, const T_BITSIZE aii_datatypeBitSize=0)
template<typename T_REAL , typename T_FEATURE , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
partition::PartitionDisjSets< T_CLUSTERIDX > nearestNeighbor (const T_REAL aitr_parameterU, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist, const T_CLUSTERIDX aii_datatypeClusterIdx=0)
Nearest neighbor [38].
Detailed Description
Algorithms and utilities for graphs.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Enumeration Type Documentation
GraphStateVertex
enum graph::GraphStateVertex
Enumerator
VERTEXSTATE_WHITE
VERTEXSTATE_GRAY
VERTEXSTATE_BLACK
Definition at line 43 of file graph_utils.hpp.
Function Documentation
component() [1/2]
ds::DisjSets graph::component (const std::vector< uintidx > & aivectoruintidx_vertexPi)
Find connected component of a graph.
A connected component (or just component) of an undirected graph is a subgraph in which any two vertices are connected to each other by paths [38]
Parameters
aivectoruintidx_vertexPi a vector of indices Pi
Definition at line 467 of file graph_utils.hpp.
References ds::DisjSets::find(), ds::DisjSets::merge(), ds::DisjSets::print(), and UINTIDX_NIL.
Referenced by eac::gaclustering_vktreebinary(), main(), and nearestNeighbor().
component() [2/2]
template<typename T_BITSIZE > ds::DisjSets graph::component (const std::vector< uintidx > & aivectoruintidx_vertexPi, const mat::BitArray< T_BITSIZE > & aibitarray_edgeRemains)
Find connected component of a graph.
A connected component (or just component) of an undirected graph is a subgraph in which any two vertices are connected to each other by paths [10]
Parameters
aivectoruintidx_vertexPi a vector of indices Pi
aibitarray_edgeRemains a bit array of edge remains
Definition at line 525 of file graph_utils.hpp.
References ds::DisjSets::find(), ds::BitContainer< T_BITSIZE >::getBit(), ds::DisjSets::merge(), ds::DisjSets::print(), and UINTIDX_NIL.
fromPiToGraph() [1/2]
template<typename T_VERTEX_IDX > std::vector< std::list< T_VERTEX_IDX > > graph::fromPiToGraph (const std::vector< T_VERTEX_IDX > & aivectorvertexidx_pi)
Constructs a vector list graph from PI vertices for a Pi vector.
Parameters
aivectorvertexidx_pi a vector from index Pi
Definition at line 355 of file graph_utils.hpp.
References UINTIDX_NIL.
Referenced by eac::gaclustering_vktreebinary(), main(), nearestNeighbor(), and prim().
fromPiToGraph() [2/2]
template<typename T_VERTEX_IDX , typename T_BITSIZE > std::vector< std::list< T_VERTEX_IDX > > graph::fromPiToGraph (const std::vector< T_VERTEX_IDX > & aivectorvertexidx_pi, const mat::BitArray< T_BITSIZE > & aibitarray_edgeRemains)
Constructs a vector list graph from PI vertices for a Pi vector.
Parameters
aivectorvertexidx_pi a vector from index Pi
aibitarray_edgeRemains a bit array of edge remains
Definition at line 410 of file graph_utils.hpp.
References ds::BitContainer< T_BITSIZE >::getBit(), and UINTIDX_NIL.
fromPiToGraphMap()
std::map< uintidx, std::list< uintidx > > graph::fromPiToGraphMap (const std::vector< uintidx > & aivectorvertexidx_pi)
Constructs a list map graph from PI vertices for a Pi vector.
Parameters
aivectorvertexidx_pi a vector from index Pi
Definition at line 289 of file graph_utils.hpp.
References UINTIDX_NIL.
getAdjacencyMatrix()
template<typename T_BITSIZE , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR > mat::BitMatrix<T_BITSIZE> graph::getAdjacencyMatrix (const T_DIST ait_distAdj, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist, const T_BITSIZE aii_datatypeBitSize = 0)
Definition at line 694 of file graph_utils.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::BitMatrix< T_BITSIZE >::initialize(), mat::BitMatrix< T_BITSIZE >::print_listAdj(), and mat::BitMatrix< T_BITSIZE >::setBit().
Referenced by nearestNeighbor().
nearestNeighbor()
template<typename T_REAL , typename T_FEATURE , typename T_CLUSTERIDX , typename INPUT_ITERATOR > partition::PartitionDisjSets< T_CLUSTERIDX > graph::nearestNeighbor (const T_REAL aitr_parameterU, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist, const T_CLUSTERIDX aii_datatypeClusterIdx = 0)
Nearest neighbor [38].
Make a grouping of the closest instances according to the parameter.
Parameters
aitr_parameterU a real number the parameter u
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type Dist for example dist::Euclidean
aii_datatypeClusterIdx
Definition at line 787 of file graph_utils.hpp.
References component(), fromPiToGraph(), getAdjacencyMatrix(), data::Instance< T_FEATURE >::getNumDimensions(), graph::AlgorithmsDFSAdjMatrix< T_BITSIZE >::getPi(), graph::AlgorithmsDFSAdjMatrix< T_BITSIZE >::resolve(), and inout::vectorlistprint().
Referenced by eac::clustering_vksubclusterbinary().
prim()
template<typename T_W > std::vector< uintidx > graph::prim (const mat::MatrixTriang< T_W > & aimatrixtriagt_w, const uintidx lui_startVertex = 0)
Prim’s algorithm.
Prim’s algorithm. It is assumed that in the graph for this function all the vertices are connected to everyone, not the graph is required. Used to obtain component
Parameters
aimatrixtriagt_w a matrix of distances all the vertices are joined with an edge of weight equal to the distance
lui_startVertex a starting vertex
Definition at line 589 of file graph_utils.hpp.
References fromPiToGraph(), mat::MatrixTriang< T_FEATURE >::getNumRows(), UINTIDX_NIL, and inout::vectorlistprint().
Referenced by eac::gaclustering_vktreebinary().