Library Evolutionary Algorithms for Clustering (LEAC): partition Namespace Reference
partition Namespace Reference
Gets the indexes of the group that each instance belongs to for different schemas representing a partition.
Classes
class Partition
Definition of the abstract class Partition, to build a cluster of a dataset.
class PartitionCentroids
Partition of instances in base to following equation:
where , represents the medoid of cluster .
class PartitionCrispMatrix
Partition of instances with bit crisp matrix.
class PartitionDisjSets
Partition of instances in base DisjSets data structure.
class PartitionFuzzy
Partition of instances with fuzzy matrix [8] [6].
class PartitionLabel
Partition of instances with label string assigned previous.
class PartitionLabelVector
Partition of instances with label vector assigned previous.
class PartitionMedoids
Partition of instances with closest medoids
where , represents the medoid of cluster .
Functions
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR >
PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR > makePartition (mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numClusters, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Detailed Description
Gets the indexes of the group that each instance belongs to for different schemas representing a partition.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
makePartition()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR > PartitionCentroids<T_FEATURE,T_CLUSTERIDX,T_DIST,INPUT_ITERATOR> partition::makePartition (mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numClusters, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 259 of file partition_centroids.hpp.
Referenced by eac::gcuk_vkcentroid(), main(), and eac::tgca_vkcentroid().