Library Evolutionary Algorithms for Clustering (LEAC): sm Namespace Reference
sm Namespace Reference
Supervised measures.
Classes
class ConfusionMatchingMatrix
Confusion Matching Matrix also known as an error matrix, is a specific table layout that allows visualization of the performance of an algorithm, typically a supervised learning.
class PartitionMatrix
Partition Matrix also known as matching matrix is similar to the matrix of confusion, but is used in the unsupervised learning.
Functions
template<class T_METRIC , class T_INSTANCES_CLUSTER_K >
std::vector< T_METRIC > getSensitivity (const PartitionMatrix< T_INSTANCES_CLUSTER_K > &aipartmatrix_a, const T_METRIC airt_percentage=100.0)
template<class T_METRIC , class T_INSTANCES_CLUSTER_K >
std::string getStrSenSpe (const PartitionMatrix< T_INSTANCES_CLUSTER_K > &aipartmatrix_a, const bool aib_sensitivity=true, const T_METRIC airt_percentage=100.0)
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename FUNCINSTCLASS >
auto getConfusionMatrix (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency, const FUNCINSTCLASS func_instclass) -> ConfusionMatchingMatrix< decltype(func_instfrequency(*aiiterator_instfirst))>
Get confusion matching matrix.
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY >
auto getMatchingMatrix (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency) -> ConfusionMatchingMatrix< decltype(func_instfrequency(*aiiterator_instfirst))>
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC randIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
std::vector< T_METRIC > partialRandIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC jaccardIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC precision (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC recall (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC fmeasure (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K >
T_METRIC purity (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > &aimatchmatrix_confusion)
Detailed Description
Supervised measures.
For a given algorithm's are measures that evaluate the quality of the cluster for previously partition of instances in clusters
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
For a given algorithm's are measures that evaluate the quality of the cluster for previously classified instances
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
fmeasure()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::fmeasure (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 255 of file supervised_measures.hpp.
References sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUSomeClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUDiffClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), and measuare_undefRandIndex.
Referenced by main().
getConfusionMatrix()
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename FUNCINSTCLASS > sm::ConfusionMatchingMatrix sm::getConfusionMatrix (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency, const FUNCINSTCLASS func_instclass) -> ConfusionMatchingMatrix<decltype(func_instfrequency(*aiiterator_instfirst))>
Get confusion matching matrix.
Parameters
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast a InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition::Partition of instances in clusters
func_instfrequency a function that returns the frequency of the instance
func_instclass a function that returns the class of the instance
Definition at line 776 of file matching_matrix.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), partition::Partition< T_CLUSTERIDX >::getNumCluster(), mat::MatrixRow< T_INSTANCES_CLUSTER_K >::initialize(), partition::Partition< T_CLUSTERIDX >::next(), and sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::sumPartitionTable().
Referenced by eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), main(), and gaclusteringop::MO2().
getMatchingMatrix()
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY > auto sm::getMatchingMatrix (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency) -> ConfusionMatchingMatrix<decltype(func_instfrequency(*aiiterator_instfirst))>
Definition at line 826 of file matching_matrix.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), partition::Partition< T_CLUSTERIDX >::getNumCluster(), mat::MatrixRow< T_INSTANCES_CLUSTER_K >::initialize(), partition::Partition< T_CLUSTERIDX >::next(), and sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::sumPartitionTable().
Referenced by main().
getSensitivity()
template<class T_METRIC , class T_INSTANCES_CLUSTER_K > std::vector<T_METRIC> sm::getSensitivity (const PartitionMatrix< T_INSTANCES_CLUSTER_K > & aipartmatrix_a, const T_METRIC airt_percentage = 100.0)
Definition at line 487 of file matching_matrix.hpp.
References inout::li_i.
getStrSenSpe()
template<class T_METRIC , class T_INSTANCES_CLUSTER_K > std::string sm::getStrSenSpe (const PartitionMatrix< T_INSTANCES_CLUSTER_K > & aipartmatrix_a, const bool aib_sensitivity = true, const T_METRIC airt_percentage = 100.0)
Definition at line 534 of file matching_matrix.hpp.
References COMMON_COUT_PRECISION, and inout::li_i.
Referenced by main().
jaccardIndex()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::jaccardIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 193 of file supervised_measures.hpp.
References sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUDiffClusterV(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getNumObjetos(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), and measuare_undefRandIndex.
Referenced by main().
partialRandIndex()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > std::vector<T_METRIC> sm::partialRandIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 101 of file supervised_measures.hpp.
References inout::containerprint(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getIdxMaximum(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), inout::li_i, and measuare_undefRandIndex.
precision()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::precision (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 215 of file supervised_measures.hpp.
References sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUSomeClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), and measuare_undefRandIndex.
Referenced by main().
purity()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::purity (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 285 of file supervised_measures.hpp.
References mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumColumns(), mat::MatrixBase< T_INSTANCES_CLUSTER_K >::getNumRows(), and measuare_undefPurity.
Referenced by main().
randIndex()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::randIndex (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 53 of file supervised_measures.hpp.
References sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getDiffClassUDiffClusterV(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getNumObjetos(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), and measuare_undefRandIndex.
Referenced by main().
recall()
template<typename T_METRIC , typename T_INSTANCES_CLUSTER_K > T_METRIC sm::recall (const ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K > & aimatchmatrix_confusion)
Definition at line 236 of file supervised_measures.hpp.
References sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUDiffClusterV(), sm::ConfusionMatchingMatrix< T_INSTANCES_CLUSTER_K >::getSomeClassUSomeClusterV(), and measuare_undefRandIndex.
Referenced by main().