Library Evolutionary Algorithms for Clustering (LEAC): um Namespace Reference
um Namespace Reference
Unsupervised measures for clustering analysis.
Functions
template<typename T_FEATURE , typename T_METRIC >
T_METRIC maxDistCjCjp (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Find the maximum distance beteen the centroids.
template<typename T_FEATURE , typename T_METRIC >
T_METRIC minDistCjCjp (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC >
T_METRIC minDistCjCjp (const T_CLUSTERIDX aicidx_Clusterj, const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_FEATURE , typename T_METRIC >
T_METRIC sumMinCjCjp (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Calculate minimum sum of distances between all centroids.
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
std::vector< T_METRIC > avgRadiusClusterK (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
std::vector< T_METRIC > maxRadiusClusterK (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Calculates the maximum radius of a cluster for a partition.
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC >
T_METRIC diameterClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC >
T_METRIC radiusClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const T_FEATURE *ait_centroid, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Radius of Clusterj.
template<typename T_METRIC , typename T_FEATURE , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
T_METRIC D2 (const mat::MatrixRow< T_FEATURE > &aimatrixrowt_S, const partition::Partition< T_CLUSTERIDX > &aipartition_clustersBkinCi, const partition::Partition< T_CLUSTERIDX > &aipartition_clustersBi, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_Vi, const std::vector< T_METRIC > &aivectorr_meanRadiusBk, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC Dintra (const mat::MatrixRow< T_FEATURE > &aimatrixrowt_S, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstBi, const partition::Partition< T_CLUSTERIDX > &aipartition_clustersBkinCi, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Dintra [38].
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC Dinter (const mat::MatrixRow< T_FEATURE > &aimatrixrowt_S, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstBi, const partition::Partition< T_CLUSTERIDX > &aipartition_clustersBkinCi, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Dinter [38].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC >
T_METRIC e1 (const T_FEATURE *aiarrayt_meanInstances, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
e1 [33]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename FUNCINSTFREQUENCY , typename T_METRIC >
T_METRIC e1 (const T_FEATURE *aiarrayt_meanInstances, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
e1 [33] for frequent instances
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
std::tuple< std::vector< T_METRIC >, std::vector< uintidx > > sumDistInstCentInK (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Computes the overall between-cluster variance and the number of instances in each cluster.
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename T_METRIC >
std::vector< T_METRIC > sumDistInstCentInK (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
Computes the overall between-cluster variance for instances for frequent instances.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC ssb (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const T_FEATURE *aiarrayt_meanInstances, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstancesClusterK, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
The overall between-cluster variance ssb.
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC ssbreeval (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstancesClusterK, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC VRC (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_squaredDist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC VRCreeval (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_squaredDist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC WBIndex (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_squaredDist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC WBIndexreeval (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_squaredDist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC scoreFunction (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Score function () [36].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC scoreFunctionreeval (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC >
T_METRIC distMinIntraClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Distance min intra cluster.
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC >
std::vector< T_METRIC > diameterClusterK (INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC DunnIndex (mat::MatrixTriang< T_METRIC > &aimatrixtriagt_dissimilarity, ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip)
The Dunn Index (DI) [15] [39].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC DunnIndex (INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
The Dunn Index (DI) [15] [39].
template<typename T_FEATURE , typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC simplifiedDunnIndex (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
The Simplified Dunn Index (SDI)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC CSmeasure (INPUT_ITERATOR aiiterator_instfirst, const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &aipartlinknuminst_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
CS measure [12] [13].
template<typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC silhouette (mat::MatrixTriang< T_METRIC > &aimatrixtriagt_dissimilarity, ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &aipartlinknuminst_memberShip)
Silhouette [2].
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC , typename T_FEATURE >
T_METRIC silhouette (INPUT_ITERATOR aiiterator_instfirst, ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > &aipartlinknuminst_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Silhouette [25].
template<typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC silhouette (const uintidx aiui_idxInstance, const T_CLUSTERIDX aicidx_instInClusterJ, mat::MatrixTriang< T_METRIC > &aimatrixtriagt_dissimilarity, ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_memberShip, const std::vector< T_INSTANCES_CLUSTER_K > &aivectorit_numInstClusterK)
Silhouette [25].
template<typename T_FEATURE , typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
std::vector< T_METRIC > simplifiedSilhouette (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const std::vector< T_INSTANCES_CLUSTER_K > &aivectorit_numInstClusterK, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Simplified Silhouette [2].
template<typename T_FEATURE , typename T_METRIC >
T_METRIC dbindex (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, const std::vector< T_METRIC > &aivectort_scatter, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
DB Index [14] [5].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC dbindex (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
DB Index [14] [5].
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE >
std::pair< T_METRIC, bool > SSE (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
SSE [4] [11]. A boolean is also returned to indicate if the partition is valid.
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE , typename T_CLUSTERIDX >
std::pair< T_METRIC, bool > SSE (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
SSE [4] [11]. A boolean is also returned to indicate if the partition is valid.
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC >
T_METRIC SSE (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_CLUSTERIDX *aiarraycidx_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
SSE [4] [11]. Also known as Total within cluster variation (TWCV) [35] [28].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename T_METRIC >
std::pair< T_METRIC, bool > distortion (const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_CLUSTERIDX *aiarraycidx_memberShip, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC >
T_METRIC distortion (T_FEATURE *aiarrayt_centroid1, T_INSTANCES_CLUSTER_K aiit_numInstClusterK1, T_FEATURE *aiarrayt_centroid2, T_INSTANCES_CLUSTER_K aiit_numInstClusterK2, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
Distortion metric distance between two centroids [17].
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE , typename T_BITSIZE >
T_METRIC j1 (mat::BitMatrix< T_BITSIZE > &aicrispmatrix_partition, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE >
T_METRIC jm (mat::MatrixRow< T_METRIC > &aimatrixt_u, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_METRIC aif_m, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_METRIC , typename T_CLUSTERIDX >
T_METRIC SSEMedoid (const uintidx *aiarrayidxinst_medoids, const T_CLUSTERIDX aicidx_numClustersK, const mat::MatrixTriang< T_METRIC > &aimatrixtriagt_dissimilarity)
SSEMedoid [30].
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE >
T_METRIC indexI (mat::MatrixRow< T_METRIC > &aimatrixt_u, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const T_METRIC airt_p=2.0)
Validity index I or index I for a fuzzy c-partition [33] [3].
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC indexI (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const T_METRIC airt_p=2.0)
Validity index I for a crisp partition [33] [3].
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE >
T_METRIC indexIreeval (mat::MatrixRow< T_METRIC > &aimatrixt_u, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const T_METRIC airt_p=2.0)
Validity index I or index I for a fuzzy c-partition [33] [3]. Use this function when the data set changes in the same execution, parameter is recalculated.
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC indexIreeval (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist, const T_METRIC airt_p=2.0)
Validity index I for a crisp partition [33] [3]. Use this function when the data set changes in the same execution, parameter is recalculated.
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE >
T_METRIC xb (mat::MatrixRow< T_METRIC > &aimatrixt_u, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC >
T_METRIC xb (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
template<typename T_METRIC >
T_METRIC entropy (const mat::MatrixRow< T_METRIC > &aimatrixt_u)
Get entropy [6].
template<typename T_METRIC >
T_METRIC partitioncoefficient (const mat::MatrixRow< T_METRIC > &aimatrixt_u)
Get partition coefficient [6].
Detailed Description
Unsupervised measures for clustering analysis.
Evaluate tries to determine the quality of a given obtained partition of the data without any external information available.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
avgRadiusClusterK()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > std::vector<T_METRIC> um::avgRadiusClusterK (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 361 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and partition::Partition< T_CLUSTERIDX >::next().
Referenced by eac::clustering_vksubclusterbinary(), dbindex(), and eac::gga_vklabel().
CSmeasure()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC T_METRIC um::CSmeasure (INPUT_ITERATOR aiiterator_instfirst, const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & aipartlinknuminst_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
CS measure [12] [13].
CS measure is a function of the ratio of the sum of within-cluster scatter to between-cluster separation. The smallest indicates a valid optimal partition.
Where is a distance function.
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aipartlinknuminst_memberShip a clusters partition in a ds::PartitionLinkedNumInst data structure
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 2652 of file unsupervised_measures.hpp.
References diameterClusterK(), measuare_undefCS, and sumMinCjCjp().
Referenced by main().
D2()
template<typename T_METRIC , typename T_FEATURE , typename T_CLUSTERIDX , typename INPUT_ITERATOR > T_METRIC um::D2 (const mat::MatrixRow< T_FEATURE > & aimatrixrowt_S, const partition::Partition< T_CLUSTERIDX > & aipartition_clustersBkinCi, const partition::Partition< T_CLUSTERIDX > & aipartition_clustersBi, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_Vi, const std::vector< T_METRIC > & aivectorr_meanRadiusBk, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 659 of file unsupervised_measures.hpp.
References inout::containerprint(), partition::Partition< T_CLUSTERIDX >::getClusterIdx(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by eac::clustering_vksubclusterbinary().
dbindex() [1/2]
template<typename T_FEATURE , typename T_METRIC > T_METRIC um::dbindex (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const std::vector< T_METRIC > & aivectort_scatter, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
DB Index [14] [5].
This index is a function of the ratio of the sum of within-cluster scatter to between-cluster separation
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aivectort_scatter a vector whith aivectort_scatter of the clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 3284 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and measuare_undefDBindex.
Referenced by eac::gcuk_vkcentroid(), eac::gga_vklabel(), and main().
dbindex() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::dbindex (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
DB Index [14] [5].
This index is a function of the ratio of the sum of within-cluster scatter to between-cluster separation
Parameters
aimatrixt_centroids a mat::MatrixBase with centroids
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 3392 of file unsupervised_measures.hpp.
References avgRadiusClusterK(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and measuare_undefDBindex.
diameterClusterK()
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC > std::vector<T_METRIC> um::diameterClusterK (INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 2252 of file unsupervised_measures.hpp.
References inout::containerprint(), diameterClusterKj(), and ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions().
Referenced by CSmeasure().
diameterClusterKj()
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC > T_METRIC um::diameterClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 554 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by diameterClusterK(), and DunnIndex().
Dinter()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::Dinter (const mat::MatrixRow< T_FEATURE > & aimatrixrowt_S, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstBi, const partition::Partition< T_CLUSTERIDX > & aipartition_clustersBkinCi, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Dinter [38].
Parameters
aimatrixrowt_S a matrix with centroid S mat::MatrixRow<T_FEATURE>
aimatrixrowt_Vi a matrix with centroid Vi
aivectort_numInstBi a vector with numero number of instances in Bi
aipartition_clustersBkinCi a partition of B in the groups Ci
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 862 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::getClusterIdx(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by eac::clustering_genetic().
Dintra()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::Dintra (const mat::MatrixRow< T_FEATURE > & aimatrixrowt_S, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstBi, const partition::Partition< T_CLUSTERIDX > & aipartition_clustersBkinCi, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Dintra [38].
Parameters
aimatrixrowt_S a matrix with centroid S mat::MatrixRow<T_FEATURE>
aimatrixrowt_Vi a matrix with centroid Vi
aivectort_numInstBi a vector with numero number of instances in Bi
aipartition_clustersBkinCi a partition of B in the groups Ci
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 778 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::getClusterIdx(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by eac::clustering_genetic().
distMinIntraClusterKj()
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC > T_METRIC um::distMinIntraClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Distance min intra cluster.
Parameters
aicidx_Clusterj an integer index of the cluster
aipartlink_memberShip a clusters partition in a ds::PartitionLinked data structure
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 2196 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by DunnIndex().
distortion() [1/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename T_METRIC > std::pair<T_METRIC,bool> um::distortion (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_CLUSTERIDX * aiarraycidx_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
Definition at line 3821 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), mat::MatrixBase< T_FEATURE >::getNumRows(), measuare_undefObjetiveFunc, measuare_undefSSE, and nearest::NN().
Referenced by eac::cbga_fkcentroid(), and nearest::findTwoNearestCentroids().
distortion() [2/2]
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC um::distortion (T_FEATURE * aiarrayt_centroid1, T_INSTANCES_CLUSTER_K aiit_numInstClusterK1, T_FEATURE * aiarrayt_centroid2, T_INSTANCES_CLUSTER_K aiit_numInstClusterK2, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Distortion metric distance between two centroids [17].
Parameters
aiarrayt_centroid1 an array with the coordinates of the centroid of the first cluster
aiit_numInstClusterK1 number of instances of the first group
aiarrayt_centroid2 an array with the coordinates of the centroid of the second cluster
aiit_numInstClusterK2 number of instances of the second group
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 3935 of file unsupervised_measures.hpp.
DunnIndex() [1/2]
template<typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::DunnIndex (mat::MatrixTriang< T_METRIC > & aimatrixtriagt_dissimilarity, ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip)
The Dunn Index (DI) [15] [39].
The Dunn Index determines the minimum ratio between inter-cluster distance and cluster diameter for a given partitioning. It captures the notion that, in a good clustering solution, data elements within one cluster should be much closer to each other than to elements within different clusters. It is defined as
Where
Parameters
aimatrixtriagt_dissimilarity a matrix of distances
aipartlink_memberShip a clusters partition in a ds::PartitionLinked data structure
Definition at line 2337 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), measuare_undefDunnIndex, and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by main().
DunnIndex() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::DunnIndex (INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
The Dunn Index (DI) [15] [39].
The Dunn Index determines the minimum ratio between inter-cluster distance and cluster diameter for a given partitioning. It captures the notion that, in a good clustering solution, data elements within one cluster should be much closer to each other than to elements within different clusters. It is defined as
Where
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aipartlink_memberShip a clusters partition in a ds::PartitionLinked data structure
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 2463 of file unsupervised_measures.hpp.
References diameterClusterKj(), distMinIntraClusterKj(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), and measuare_undefDunnIndex.
e1() [1/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC > T_METRIC um::e1 (const T_FEATURE * aiarrayt_meanInstances, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
e1 [33]
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aiarrayt_meanInstances an array with the average of the attributes of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 947 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by indexI(), and indexIreeval().
e1() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename FUNCINSTFREQUENCY , typename T_METRIC > T_METRIC um::e1 (const T_FEATURE * aiarrayt_meanInstances, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
e1 [33] for frequent instances
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aiarrayt_meanInstances an array with the average of the attributes of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
func_instfrequency a function that returns the frequency of the instance
DATATYPE_REAL lmetric_e1;
lmetric_e1 =
um::e1
(larray_meanFeactures,
lvectorptinst_instances.begin(),
lvectorptinst_instances.end(),
*pfunc2p_dist,
[](const data::Instance<DATATYPE_INST_CENT>* aiinst_iter) -> DATATYPE_REAL
{
data::InstanceFreq
<DATATYPE_INST_CENT,
DATATYPE_INSTANCE_FREQUENCY
>
*lptinstfreq_iter =
(data::InstanceFreq
<DATATYPE_INST_CENT,
DATATYPE_INSTANCE_FREQUENCY
>*)
aiinst_iter;
return  (DATATYPE_REAL) lptinstfreq_iter->getFrequency();
}
);
Definition at line 1041 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
entropy()
template<typename T_METRIC > T_METRIC um::entropy (const mat::MatrixRow< T_METRIC > & aimatrixt_u)
Get entropy [6].
Parameters
aimatrixt_u a fuzzy c-partitions mat::MatrixRow
Definition at line 4958 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumElems(), measuare_undefEntropy, and mat::MatrixRow< T_FEATURE >::toArray().
Referenced by main().
indexI() [1/2]
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE > T_METRIC um::indexI (mat::MatrixRow< T_METRIC > & aimatrixt_u, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const T_METRIC airt_p = 2.0)
Validity index I or index I for a fuzzy c-partition [33] [3].
The validity index I or simply Index I. It is used as a metric to measure clustering performance. It was proposed as a measure to indicate the (goodness) validity of the solution in the cluster. It is defined as follows:
Where is the number of clusters
and
is the total number of objects. is a partition matrix of the objects and is the centroid es el centro . The value of that maximizes is considered the correct number of clusters.
Parameters
&aimatrixt_u a fuzzy c-partitions mat::MatrixRow
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
airt_p the power used to calculate the index, by default 2.0
Definition at line 4222 of file unsupervised_measures.hpp.
References e1(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), maxDistCjCjp(), stats::meanVector(), measuare_undefIndexI, interfacesse::sum(), and stats::sumFeactures().
Referenced by main().
indexI() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::indexI (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const T_METRIC airt_p = 2.0)
Validity index I for a crisp partition [33] [3].
The validity index I or simply Index I. It is used as a metric to measure clustering performance. It was proposed as a measure to indicate the (goodness) validity of the solution in the cluster. It is defined as follows:
Where is the number of clusters
and
is the total number of objects. is a partition matrix of the objects and is the centroid es el centro . The value of that maximizes is considered the correct number of clusters.
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a crisp partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
airt_p the power used to calculate the index, by default 2.0
Definition at line 4388 of file unsupervised_measures.hpp.
References e1(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), maxDistCjCjp(), stats::meanVector(), measuare_undefIndexI, SSE(), interfacesse::sum(), and stats::sumFeactures().
indexIreeval() [1/2]
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE > T_METRIC um::indexIreeval (mat::MatrixRow< T_METRIC > & aimatrixt_u, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const T_METRIC airt_p = 2.0)
Validity index I or index I for a fuzzy c-partition [33] [3]. Use this function when the data set changes in the same execution, parameter is recalculated.
The validity index I or simply Index I. It is used as a metric to measure clustering performance. It was proposed as a measure to indicate the (goodness) validity of the solution in the cluster. It is defined as follows:
Where is the number of clusters
and
is the total number of objects. is a partition matrix of the objects and is the centroid es el centro . The value of that maximizes is considered the correct number of clusters.
Parameters
&aimatrixt_u a fuzzy c-partitions mat::MatrixRow
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
airt_p the power used to calculate the index, by default 2.0
Definition at line 4535 of file unsupervised_measures.hpp.
References e1(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), maxDistCjCjp(), stats::meanVector(), measuare_undefIndexI, interfacesse::sum(), and stats::sumFeactures().
Referenced by main().
indexIreeval() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::indexIreeval (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const T_METRIC airt_p = 2.0)
Validity index I for a crisp partition [33] [3]. Use this function when the data set changes in the same execution, parameter is recalculated.
The validity index I or simply Index I. It is used as a metric to measure clustering performance. It was proposed as a measure to indicate the (goodness) validity of the solution in the cluster. It is defined as follows:
Where is the number of clusters
and
is the total number of objects. is a partition matrix of the objects and is the centroid es el centro . The value of that maximizes is considered the correct number of clusters.
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a crisp partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
airt_p the power used to calculate the index, by default 2.0
Definition at line 4666 of file unsupervised_measures.hpp.
References e1(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), maxDistCjCjp(), stats::meanVector(), measuare_undefIndexI, SSE(), interfacesse::sum(), and stats::sumFeactures().
j1()
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE , typename T_BITSIZE > T_METRIC um::j1 (mat::BitMatrix< T_BITSIZE > & aicrispmatrix_partition, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 4000 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by eac::gaclustering_fkcrispmatrix(), and eac::gaprototypes_fkmedoid().
jm()
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE > T_METRIC um::jm (mat::MatrixRow< T_METRIC > & aimatrixt_u, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_METRIC aif_m, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 4080 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by main().
maxDistCjCjp()
template<typename T_FEATURE , typename T_METRIC > T_METRIC um::maxDistCjCjp (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Find the maximum distance beteen the centroids.
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 86 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by indexI(), and indexIreeval().
maxRadiusClusterK()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > std::vector< T_METRIC > um::maxRadiusClusterK (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Calculates the maximum radius of a cluster for a partition.
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition::Partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 463 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and partition::Partition< T_CLUSTERIDX >::next().
minDistCjCjp() [1/2]
template<typename T_FEATURE , typename T_METRIC > T_METRIC um::minDistCjCjp (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 151 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by eac::clustering_vksubclusterbinary(), simplifiedDunnIndex(), and xb().
minDistCjCjp() [2/2]
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC > T_METRIC um::minDistCjCjp (const T_CLUSTERIDX aicidx_Clusterj, const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 218 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixBase< T_FEATURE >::getRow().
partitioncoefficient()
template<typename T_METRIC > T_METRIC um::partitioncoefficient (const mat::MatrixRow< T_METRIC > & aimatrixt_u)
Get partition coefficient [6].
Parameters
aimatrixt_u a fuzzy c-partitions mat::MatrixRow
Definition at line 4997 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumElems(), measuare_undefPartitionCoefficient, and mat::MatrixRow< T_FEATURE >::toArray().
Referenced by main().
radiusClusterKj()
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename T_FEATURE , typename T_METRIC > T_METRIC um::radiusClusterKj (const T_CLUSTERIDX aicidx_Clusterj, const T_FEATURE * ait_centroid, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Radius of Clusterj.
Find the radius of cluster j, the maximum distance between an instance of the cluster and the centroid
Parameters
aicidx_Clusterj an integer index of the cluster
ait_centroid the centroid of the Clusterj
aipartlink_memberShip a clusters partition in a ds::PartitionLinked data structure
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 602 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by simplifiedDunnIndex().
scoreFunction()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::scoreFunction (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Score function () [36].
Score function is based on inter-cluster and intra-cluster distances. The score function is used for two purposes: i) to estimate the number of clusters and ii) to evaluate the quality of the clustering results [36]. The higher the value of the Score function, the more suitable the number of clusters.
Where
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition::Partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1939 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefScoreFunction, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by main().
scoreFunctionreeval()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::scoreFunctionreeval (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 2065 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefScoreFunction, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by main().
silhouette() [1/3]
template<typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC um::silhouette (mat::MatrixTriang< T_METRIC > & aimatrixtriagt_dissimilarity, ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & aipartlinknuminst_memberShip)
Silhouette [2].
Calculate the average of Silhouette for the instances
Parameters
aimatrixtriagt_dissimilarity a triangular matrix with distances between instances
aipartlinknuminst_memberShip a clusters partition in a ds::PartitionLinkedNumInst data structure
Note
Reduces the complexity of to , for data set d large better performance
Definition at line 2739 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), inout::containerprint(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getVectorNumInstClusterK(), measuare_undefSilhouette, and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by eac::cga_vklabel(), eac::gga_vklabel(), and main().
silhouette() [2/3]
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC , typename T_FEATURE > T_METRIC um::silhouette (INPUT_ITERATOR aiiterator_instfirst, ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K > & aipartlinknuminst_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Silhouette [25].
Calculate the average of Silhouette for the instances
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aipartlinknuminst_memberShip a clusters partition in a ds::PartitionLinkedNumInst data structure
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 2880 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), ds::PartitionLinked< T_CLUSTERIDX >::getNumInstances(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumInstClusterK(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getNumNullCluster(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), measuare_undefSilhouette, ds::IteratorPartitionLinked< T_CLUSTERIDX >::next(), and ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::print().
silhouette() [3/3]
template<typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC um::silhouette (const uintidx aiui_idxInstance, const T_CLUSTERIDX aicidx_instInClusterJ, mat::MatrixTriang< T_METRIC > & aimatrixtriagt_dissimilarity, ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, const std::vector< T_INSTANCES_CLUSTER_K > & aivectorit_numInstClusterK)
Silhouette [25].
Calculate Silhouette for an instance
Parameters
aiui_idxInstance Instance index to calculate
aicidx_instInClusterJ Index of the cluster to which the aiui_idxInstance belongs
aimatrixtriagt_dissimilarity a matrix of distances
aipartlink_memberShip a clusters partition in a ds::PartitionLinked data structure
aivectorit_numInstClusterK a vector with the number of instances per cluster
Definition at line 3038 of file unsupervised_measures.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), inout::containerprint(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), measuare_undefSilhouette, and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
simplifiedDunnIndex()
template<typename T_FEATURE , typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::simplifiedDunnIndex (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
The Simplified Dunn Index (SDI)
To simplify the calculations of the the Dunn Index, simplifiedDunnIndex uses the centroids to calculate the radius and decrease the computational complexity
Parameters
aimatrixt_centroids a matrix with the centroids of the clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aipartlink_memberShip a a clusters partition in a ds::PartitionLinked data structure
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 2547 of file unsupervised_measures.hpp.
References ds::PartitionLinked< T_CLUSTERIDX >::getNumPartitions(), mat::MatrixBase< T_FEATURE >::getRow(), measuare_undefDunnIndex, minDistCjCjp(), and radiusClusterKj().
Referenced by main().
simplifiedSilhouette()
template<typename T_FEATURE , typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > std::vector< T_METRIC > um::simplifiedSilhouette (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const std::vector< T_INSTANCES_CLUSTER_K > & aivectorit_numInstClusterK, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Simplified Silhouette [2].
The silhouette proposed in [25] depends on the computation of all distances between objects, leading to a computational cost of , which is often not sufficiently efficient for real-world clustering applications (e.g. data mining, text mining, gene-expression data analysis). To circumvent this limitation, a simplified silhouette can be employed. The simplified silhouette is based on the computation of distances between objects and cluster centroids, which are the mean vectors of the clusters [19].
Parameters
aimatrixt_centroids a mat::MatrixBase with centroids
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition of instances in clusters
aivectorit_numInstClusterK a vector with the number of instances per cluster
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 3145 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), interfacesse::copya(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and partition::Partition< T_CLUSTERIDX >::next().
Referenced by eac::feca_vklabel(), main(), gaclusteringop::MO1(), and gaclusteringop::MO2().
ssb()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC um::ssb (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const T_FEATURE * aiarrayt_meanInstances, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstancesClusterK, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
The overall between-cluster variance ssb.
Where is the centroid of cluster , is the overall mean of the instances
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids
aiarrayt_meanInstances an array with the mean of the attributes
aivectort_numInstancesClusterK a vector with the number of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1318 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by main(), scoreFunction(), scoreFunctionreeval(), VRC(), VRCreeval(), WBIndex(), and WBIndexreeval().
ssbreeval()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_METRIC > T_METRIC um::ssbreeval (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstancesClusterK, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 1346 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), stats::meanVector(), interfacesse::sum(), and stats::sumFeactures().
Referenced by main().
SSE() [1/3]
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE > std::pair< T_METRIC, bool > um::SSE (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
SSE [4] [11]. A boolean is also returned to indicate if the partition is valid.
SSE A common clustering criterion or quality indicator is the sum of squared error SSE measure
Or with some slight variation Sum of Euclidean Distance (SED):
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Note
The membership of an instance to a cluster for this function is determined by the nearest object rule
Definition at line 3522 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), mat::MatrixBase< T_FEATURE >::getNumRows(), and nearest::NN().
Referenced by eac::gaclustering_fklabel(), eac::gas_fkcentroid(), gafuncobj::GAFuncObjSSE< T_FEATURE, T_CLUSTERIDX, T_METRIC, INPUT_ITERATOR >::getObjetiveFunc(), eac::gka_fklabel(), eac::igka_fklabel(), indexI(), indexIreeval(), eac::kga_fkcentroid(), main(), and xb().
SSE() [2/3]
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE , typename T_CLUSTERIDX > std::pair< T_METRIC, bool > um::SSE (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
SSE [4] [11]. A boolean is also returned to indicate if the partition is valid.
SSE A common clustering criterion or quality indicator is the sum of squared error SSE measure
Or with some slight variation Sum of Euclidean Distance (SED):
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 3621 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), measuare_undefSSE, and partition::Partition< T_CLUSTERIDX >::next().
SSE() [3/3]
template<typename INPUT_ITERATOR , typename T_CLUSTERIDX , typename T_FEATURE , typename T_METRIC > T_METRIC um::SSE (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_CLUSTERIDX * aiarraycidx_memberShip, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
SSE [4] [11]. Also known as Total within cluster variation (TWCV) [35] [28].
SSE A common clustering criterion or quality indicator is the sum of squared error SSE measure
Or with some slight variation Sum of Euclidean Distance (SED):
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids clusters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aiarraycidx_memberShip an array with the labels belong to the cluster
aifunc2p_dist an object of type dist::Dist to calculate distances
Note
The membership of an instance to a cluster for this function is determined by aiarraycidx_memberShip
Definition at line 3733 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), and mat::MatrixRow< T_FEATURE >::getRow().
SSEMedoid()
template<typename T_METRIC , typename T_CLUSTERIDX > T_METRIC um::SSEMedoid (const uintidx * aiarrayidxinst_medoids, const T_CLUSTERIDX aicidx_numClustersK, const mat::MatrixTriang< T_METRIC > & aimatrixtriagt_dissimilarity)
SSEMedoid [30].
The cost function sum of Euclidean distances to the most representative instance
where represents the medoid or prototype of cluster
Parameters
aiarrayidxinst_medoids an array of indexes of more representative instances
aicidx_numClustersK Number of medoids or clusters
aimatrixtriagt_dissimilarity a matrix of distances
Definition at line 4131 of file unsupervised_measures.hpp.
References mat::MatrixTriang< T_FEATURE >::getNumRows(), and nearest::medoidsNN().
Referenced by eac::gca_fkmedoid(), eac::hka_fkmedoid(), and clusteringop::updateMedoids().
sumDistInstCentInK() [1/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > std::tuple< std::vector< T_METRIC >, std::vector< uintidx > > um::sumDistInstCentInK (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Computes the overall between-cluster variance and the number of instances in each cluster.
Parameters
aimatrixt_centroids a mat::MatrixBase with centroids
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition::Partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1112 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and partition::Partition< T_CLUSTERIDX >::next().
Referenced by eac::cbga_fkcentroid(), scoreFunction(), scoreFunctionreeval(), VRC(), VRCreeval(), WBIndex(), and WBIndexreeval().
sumDistInstCentInK() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename FUNCINSTFREQUENCY , typename T_METRIC > std::vector< T_METRIC > um::sumDistInstCentInK (const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist, const FUNCINSTFREQUENCY func_instfrequency)
Computes the overall between-cluster variance for instances for frequent instances.
Parameters
aimatrixt_centroids a mat::MatrixBase with centroids
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartition_clusters a partition of instances in clusters
aifunc2p_dist an object of type dist::Dist to calculate distances
func_instfrequency a function that returns the frequency of an instance
Definition at line 1225 of file unsupervised_measures.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and partition::Partition< T_CLUSTERIDX >::next().
sumMinCjCjp()
template<typename T_FEATURE , typename T_METRIC > T_METRIC um::sumMinCjCjp (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Calculate minimum sum of distances between all centroids.
where is a distance function
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 287 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by CSmeasure().
VRC()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::VRC (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_squaredDist)
Definition at line 1431 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefVRC, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by eac::gaclustering_vktreebinary(), main(), and eac::tgca_vkcentroid().
VRCreeval()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::VRCreeval (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_squaredDist)
Definition at line 1547 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefVRC, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by main().
WBIndex()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::WBIndex (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_squaredDist)
Definition at line 1690 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefWBIndex, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by main().
WBIndexreeval()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::WBIndexreeval (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_squaredDist)
Definition at line 1805 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), stats::meanVector(), measuare_undefWBIndex, ssb(), interfacesse::sum(), sumDistInstCentInK(), and stats::sumFeactures().
Referenced by main().
xb() [1/2]
template<typename INPUT_ITERATOR , typename T_METRIC , typename T_FEATURE > T_METRIC um::xb (mat::MatrixRow< T_METRIC > & aimatrixt_u, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 4806 of file unsupervised_measures.hpp.
References data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), measuare_undefXieBeniIndex, and minDistCjCjp().
Referenced by main().
xb() [2/2]
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_CLUSTERIDX , typename T_METRIC > T_METRIC um::xb (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
Definition at line 4878 of file unsupervised_measures.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), measuare_undefXieBeniIndex, minDistCjCjp(), and SSE().