Library Evolutionary Algorithms for Clustering (LEAC): interfacesse Namespace Reference
interfacesse Namespace Reference
Interface to Streaming SIMD Extensions (SSE) high Performance Level Low Functions.
Functions
template<typename T >
void copya (T *aoarrayt_x, const T ait_alpha, const uintidx aiui_lengthArray)
Initializes the array with a constant
.
template<typename T >
void copy (T *aoarrayt_y, const T *aiarrayt_x, const uintidx aiui_lengthArray)
copy array aoarrayt_x in aoarrayt_y of type T
template<typename T >
void swap (T *aoarrayt_y, T *aiarrayt_x, const uintidx aiui_lengthArray)
swap items of aoarrayt_y to aiarrayt_x
template<typename T >
T dot (T *aoarrayt_y, T *aiarrayt_x, const uintidx aiui_lengthArray)
swap items of aoarrayt_y to aiarrayt_x
template<typename T >
T sum (const T *aoarrayt_y, const uintidx aiui_lengthArray)
template<typename T_INT1 , typename T_INT2 , typename T_INT3 >
void axpy (T_INT1 *aoarrayt_y, const T_INT2 ait_alpha, const T_INT3 *aiarrayt_x, const uintidx aiui_lengthArray)
template<typename T_INT1 , typename T_INT3 , typename T_INT2 >
void axpyInv (T_INT1 *aoarrayint1_y, const T_INT2 aiint2_alpha, const T_INT3 *aiarrayint3_x, const uintidx aiui_lengthArray)
function xAXPY of blas for doubles vectors
template<typename T >
void scal (T *aoarrayt_x, const T ait_alpha, const uintidx aiui_lengthArray)
scal items of the array of type T
template<typename T_INT1 , typename T_INT2 >
void scal (T_INT1 *aoarrayint1_x, const T_INT2 ait_alpha, const uintidx aiui_lengthArray)
scal items of the array of type integer
template<typename T_INT1 , typename T_INT2 >
void scalInv (T_INT1 *aoarrayint1_x, const T_INT2 ait_alpha, const uintidx aiui_lengthArray)
template<typename T >
void transy (T *aoarrayt_y, const T ait_alpha, const uintidx aiui_lengthArray)
translate the aoarrayt_y array
template<typename T >
void aasxpa (const T ait_alpha, T *aimatrixrowt_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const T *aoarrayt_x)
For a matrix each items change for constant and a vector.
template<typename T >
void aysxpy (T *aoarrayt_y, const T ait_alpha, const T *aiarrayt_x, const uintidx aiui_lengthArray)
extension of xAXPY operation for T result
void aysxpy (int *aoarrayi_y, const double aid_alpha, const int *aiarrayi_x, const uintidx aiui_lengthArray)
extension of xAXPY operation
template<typename T >
void gemv (T *aoarrayt_y, const mat::MatrixRow< T > &aimatrixrowt_a, const T *aiarrayt_x)
template<typename T >
void gemm (mat::MatrixRow< T > &aomatrixrowt_C, const mat::MatrixRow< T > &aimatrixrowt_A, const mat::MatrixRow< T > &aimatrixrowt_B, const enum mat::TRANSPOSE aienum_transA=mat::CblasNoTrans, const enum mat::TRANSPOSE aienum_transB=mat::CblasNoTrans, const T airt_alpha=1.0, const T airt_beta=0.0)
void copya (unsigned int *aoarrayuint_x, const unsigned int aiui_alpha, const uintidx aiui_lengthArray)
copy array aid_alpha in aoarrayuint_x of unsigned int
void copya (int *aoarrayint_x, const int aii_alpha, const uintidx aiui_lengthArray)
copy array aii_alpha in aoarrayint_x of int
void copya (long int *aoarraylong_x, const long int ail_alpha, const uintidx aiui_lengthArray)
copy array aid_alpha in aoarraylong_x of long int
void copya (float *aoarrayfloat_x, float aif_alpha, uintidx aiui_lengthArray)
copy array aid_alpha in aoarrayfloat_x of float
void copya (double *aoarraydouble_x, double aid_alpha, uintidx aiui_lengthArray)
copy array aid_alpha in aoarraydouble_x of double
void swap (int *aioarrayint_y, int *aioarrayint_x, const uintidx aiui_lengthArray)
swap items of aioarrayint_y to aioarrayint_x
void scalInv (int *aoarrayint_x, const long ail_alpha, const uintidx aiui_lengthArray)
scal items of the array int
void scal (int *aoarrayint_x, const long ail_alpha, const uintidx aiui_lengthArray)
scal items of the array int
void copy (unsigned int *aoarrayuint_y, const unsigned int *aiarrayuint_x, const uintidx aiui_lengthArray)
copy array aiarrayuint_x in aoarrayuint_y of unsigned int
void copy (int *aoarrayint_y, const int *aiarrayint_x, const uintidx aiui_lengthArray)
copy array aiarrayint_x in aoarrayint_y of int
void copy (long int *aoarraylong_y, const long int *aiarraylong_x, const uintidx aiui_lengthArray)
copy array aoarrayt_x in aoarraylong_y of long int
long int dot (const int *aiarrayint_x, const int *aiarrayint_y, const uintidx aiui_lengthArray)
dot product
void axpyInv (int *aoarraint_y, const long int ail_alpha, const long int *aiarraylong_x, const uintidx aiui_lengthArray)
axpyInv
void axpy (int *aoarrayint_y, const int aii_alpha, const long int *aiarraylong_x, const uintidx aiui_lengthArray)
xAXPY operation of blas for int with long
void axpy (int *aoarrayint_y, const long int ail_alpha, const int *aiarrayint_x, const uintidx aiui_lengthArray)
xAXPY operation of blas for int with long and int
void axpy (long int *aoarraylong_y, const int aii_alpha, const int *aiarrayint_x, const uintidx aiui_lengthArray)
function xAXPY of blas for doubles vectors
void aysxpy (double *aioarraydouble_y, const double aid_alpha, const double *aiarraydouble_x, const uintidx aiui_lengthArray)
extension of xAXPY operation for double
void transy (int *aioarrayint_y, const int ait_alpha, const uintidx aiui_lengthArray)
translate aioarrayint_y array for int
void transy (double *aoarraydouble_y, const double aid_alpha, const uintidx aiui_lengthArray)
translate aoarraydouble_y array for double
long int sum (const int *aiarrayint_y, const uintidx aiui_lengthArray)
return the sum array items int
float sum (const float *aiarrayfloat_y, const uintidx aiui_lengthArray)
return the sum array items float
double sum (const double *aiarraydouble_y, const uintidx aiui_lengthArray)
return the sum array items double
void aasxpa (const float aif_alpha, float *aimatrixrowfloat_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const float *aiarrayfloat_x)
For a matrix each items change for constant and a vector.
void aasxpa (const double aid_alpha, double *aimatrixrowdouble_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const double *aoarrayt_x)
For a matrix each items change for constant and a vector.
void swap (float *aioarrayfloat_y, float *aioarrayfloat_x, const uintidx aiui_lengthArray)
swap items of aioarrayfloat_y to aioarrayfloat_x for float
void swap (double *aioarraydouble_y, double *aioarraydouble_x, const uintidx aiui_lengthArray)
swap items of aioarraydouble_y to aioarraydouble_x for double
void scal (float *aoarrayfloat_x, const float aif_alpha, const uintidx aiui_lengthArray)
scal items of the array float
void scalInv (float *aoarrayfloat_x, const long int ail_alpha, const uintidx aiui_lengthArray)
void scal (double *aoarraydouble_x, const double aid_alpha, const uintidx aiui_lengthArray)
scal items of the array float
void scal (double *aoarraydouble_x, const long int ail_alpha, const uintidx aiui_lengthArray)
scal items of the array double
void scalInv (double *aoarraydouble_x, const long int ail_alpha, const uintidx aiui_lengthArray)
void copy (float *aoarrayfloat_y, const float *aiarrayfloat_x, const uintidx aiui_lengthArray)
copy array aoarrayfloat_x in aoarrayfloat_y of float
void copy (double *aoarraydouble_y, const double *aiarraydouble_x, const uintidx aiui_lengthArray)
copy array aoarraydouble_x in aoarraydouble_y of double
float dot (const float *aiarrayfloat_x, const float *aiarrayfloat_y, const uintidx aiui_lengthArray)
dot product for float vectors
double dot (const double *aiarraydouble_x, const double *aiarraydouble_y, const uintidx aiui_lengthArray)
dot product for double vectors
void axpy (float *aoarrayfloat_y, const float ait_alpha, const float *aiarrayfloat_x, const uintidx aiui_lengthArray)
function xAXPY of blas for float vectors
void axpy (float *aoarrayfloat_y, const long ail_alpha, const float *aiarrayfloat_x, const uintidx aiui_lengthArray)
function xAXPY of blas for floats vectors
void axpyInv (float *aoarrayfloat_y, const long ail_alpha, const float *aiarrayfloat_x, const uintidx aiui_lengthArray)
function xAXPY-inverse of blas for floats vectors
void axpy (double *aoarraydouble_y, const double aid_alpha, const double *aiarraydouble_x, const uintidx aiui_lengthArray)
function xAXPY of blas for doubles vectors
void axpy (double *aoarraydouble_y, const long int ail_alpha, const double *aiarraydouble_x, const uintidx aiui_lengthArray)
function xAXPY of blas for doubles vectors
void axpyInv (double *aoarraydouble_y, const long ail_alpha, const double *aiarraydouble_x, const uintidx aiui_lengthArray)
function xAXPY-inverse of blas for doubles vectors
void gemv (double *aoarrayt_y, const mat::MatrixRow< double > &aimatrixrowt_a, const double *aiarrayt_x)
gemv of blas operation
void gemm (mat::MatrixRow< double > &aomatrixrowt_C, const mat::MatrixRow< double > &aimatrixrowt_A, const mat::MatrixRow< double > &aimatrixrowt_B, const enum mat::TRANSPOSE aienum_transA=mat::CblasNoTrans, const enum mat::TRANSPOSE aienum_transB=mat::CblasNoTrans, const double airt_alpha=1.0, const double airt_beta=0.0)
Detailed Description
Interface to Streaming SIMD Extensions (SSE) high Performance Level Low Functions.
Interface to Streaming SIMD Extensions (SSE) kernel function.
Functions base in SSE instructions operate on packed double-precision floating-point values contained in XMM registers and on packed integers contained in MMX and XMM registers [24]
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Functions base in SSE instructions operate on packed double-precision floating-point values contained in XMM registers and on packed integers contained in MMX and XMM registers [24].
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
aasxpa() [1/3]
template<typename T > void interfacesse::aasxpa (const T ait_alpha, T * aimatrixrowt_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const T * aoarrayt_x)
For a matrix each items change for constant and a vector.
Parameters
ait_alpha a constant with a T scaling factor
aimatrixrowt_a a matrix how a vector row
aiui_numRows a unsigned integer numer rows of matrix
aiui_numColumns a unsigned integer numer columns of matrix
aoarrayt_x a vector
Definition at line 386 of file interface_level1.hpp.
Referenced by gaclusteringop::biDirectionHMutation().
aasxpa() [2/3]
void interfacesse::aasxpa (const float aif_alpha, float * aimatrixrowfloat_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const float * aiarrayfloat_x) inline
For a matrix each items change for constant and a vector.
Parameters
aif_alpha a float constant
aimatrixrowfloat_a a matrix how a vector row
aiui_numRows a unsigned integer numer rows of matrix
aiui_numColumns a unsigned integer numer columns of matrix
aiarrayfloat_x an array of float
Definition at line 731 of file interface_sse_level1_64bits.hpp.
aasxpa() [3/3]
void interfacesse::aasxpa (const double aid_alpha, double * aimatrixrowdouble_a, const uintidx aiui_numRows, const uintidx aiui_numColumns, const double * aoarrayt_x) inline
For a matrix each items change for constant and a vector.
Parameters
aid_alpha a double constant
aimatrixrowdouble_a a matrix how a vector row
aiui_numRows a unsigned integer numer rows of matrix
aiui_numColumns a unsigned integer numer columns of matrix
aoarrayt_x a vector
Definition at line 761 of file interface_sse_level1_64bits.hpp.
axpy() [1/8]
template<typename T_INT1 , typename T_INT2 , typename T_INT3 > void interfacesse::axpy (T_INT1 * aoarrayt_y, const T_INT2 ait_alpha, const T_INT3 * aiarrayt_x, const uintidx aiui_lengthArray)
Definition at line 156 of file interface_level1.hpp.
Referenced by gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::accumulateUpdate(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::addInstanceToCluster(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::changeSumInstances(), clusteringop::getCentroids(), clusteringop::getClusters(), prob::getDistGKA(), eac::igka_fklabel(), gaclusteringop::kmeansfeac(), main(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), gaclusteringop::MO1(), gaclusteringop::MO2(), mat::mulRowsIColumns0N(), dist::Induced< T_DIST, T_FEATURE >::operator()(), mat::MatrixRow< T_METRIC >::operator+=(), mat::MatrixRow< T_METRIC >::operator-=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::subInstanceFromCluster(), stats::sumFeactures(), stats::sumFeacturesFreq(), clusteringop::updateCentroids(), and clusteringop::updateClusterCj().
axpy() [2/8]
void interfacesse::axpy (int * aoarrayint_y, const int aii_alpha, const long int * aiarraylong_x, const uintidx aiui_lengthArray) inline
xAXPY operation of blas for int with long
Parameters
aoarrayint_y a array of long int
aii_alpha a const double
aiarraylong_x a array of long int
aiui_lengthArray a unsigned integer with aiarraylong_x length
Definition at line 424 of file interface_sse_level1_64bits.hpp.
axpy() [3/8]
void interfacesse::axpy (int * aoarrayint_y, const long int ail_alpha, const int * aiarrayint_x, const uintidx aiui_lengthArray) inline
xAXPY operation of blas for int with long and int
Parameters
aoarrayint_y a array of long int
ail_alpha a const long int
aiarrayint_x a array of long int
aiui_lengthArray a unsigned integer with aiarrayint_x length
Definition at line 457 of file interface_sse_level1_64bits.hpp.
axpy() [4/8]
void interfacesse::axpy (long int * aoarraylong_y, const int aii_alpha, const int * aiarrayint_x, const uintidx aiui_lengthArray) inline
function xAXPY of blas for doubles vectors
xAXPY operation of blas for integer
Parameters
aoarraylongint_y a array of long int
ait_alpha a scale factor constant of type int
aiarrayint_x a array of int
aiui_lengthArray a unsigned integer with aoarrayt_x length
Parameters
aoarraylong_y a array of long int
aii_alpha a const double
aiarrayint_x a array of long int
aiui_lengthArray a unsigned integer with length of array
Definition at line 490 of file interface_sse_level1_64bits.hpp.
axpy() [5/8]
void interfacesse::axpy (float * aoarrayfloat_y, const float ait_alpha, const float * aiarrayfloat_x, const uintidx aiui_lengthArray) inline
function xAXPY of blas for float vectors
Parameters
aoarrayfloat_y a array of float
ait_alpha a scale factor constant
aiarrayfloat_x a array of float
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 1116 of file interface_sse_level1_64bits.hpp.
axpy() [6/8]
void interfacesse::axpy (float * aoarrayfloat_y, const long ail_alpha, const float * aiarrayfloat_x, const uintidx aiui_lengthArray) inline
function xAXPY of blas for floats vectors
Parameters
aoarrayfloat_y a array of float
ail_alpha a scale factor constant of long int
aiarrayfloat_x a array of float
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 1148 of file interface_sse_level1_64bits.hpp.
axpy() [7/8]
void interfacesse::axpy (double * aoarraydouble_y, const double aid_alpha, const double * aiarraydouble_x, const uintidx aiui_lengthArray) inline
function xAXPY of blas for doubles vectors
Parameters
aoarraydouble_y a array of double
aid_alpha a scale factor constant
aiarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 1216 of file interface_sse_level1_64bits.hpp.
axpy() [8/8]
void interfacesse::axpy (double * aoarraydouble_y, const long int ail_alpha, const double * aiarraydouble_x, const uintidx aiui_lengthArray) inline
function xAXPY of blas for doubles vectors
Parameters
aoarraydouble_y a array of double
ail_alpha a scale factor constant long int
aiarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 1248 of file interface_sse_level1_64bits.hpp.
axpyInv() [1/4]
template<typename T_INT1 , typename T_INT3 , typename T_INT2 > void interfacesse::axpyInv (T_INT1 * aoarrayint1_y, const T_INT2 aiint2_alpha, const T_INT3 * aiarrayint3_x, const uintidx aiui_lengthArray)
function xAXPY of blas for doubles vectors
Parameters
aoarrayint1_y a array of integer
aiint2_alpha a constant with an integer scaling factor
aiarrayint3_x a array of integer
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 244 of file interface_level1.hpp.
Referenced by stats::meanVector().
axpyInv() [2/4]
void interfacesse::axpyInv (int * aoarraint_y, const long int ail_alpha, const long int * aiarraylong_x, const uintidx aiui_lengthArray) inline
axpyInv
Parameters
aoarraint_y a array of int
ail_alpha a long integer scale factor
aiarraylong_x a array of long int
aiui_lengthArray a unsigned integer with aiarraylong_x length
Definition at line 390 of file interface_sse_level1_64bits.hpp.
References inout::d.
axpyInv() [3/4]
void interfacesse::axpyInv (float * aoarrayfloat_y, const long ail_alpha, const float * aiarrayfloat_x, const uintidx aiui_lengthArray) inline
function xAXPY-inverse of blas for floats vectors
Parameters
aoarrayfloat_y a array of float
ail_alpha a scale factor constant of long int
aiarrayfloat_x a array of float
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 1182 of file interface_sse_level1_64bits.hpp.
References inout::f.
axpyInv() [4/4]
void interfacesse::axpyInv (double * aoarraydouble_y, const long ail_alpha, const double * aiarraydouble_x, const uintidx aiui_lengthArray) inline
function xAXPY-inverse of blas for doubles vectors
Parameters
aoarraydouble_y a array of double
ail_alpha a scale factor constant of long int
aiarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 1283 of file interface_sse_level1_64bits.hpp.
References inout::d.
aysxpy() [1/3]
template<typename T > void interfacesse::aysxpy (T * aoarrayt_y, const T ait_alpha, const T * aiarrayt_x, const uintidx aiui_lengthArray)
extension of xAXPY operation for T result
Parameters
aoarrayt_y a array of type T
ait_alpha a const of type T
aiarrayt_x a array of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 420 of file interface_level1.hpp.
Referenced by garealop::averageCrossover(), gaclusteringop::biDirectionHMutation(), and garealop::heuristicCrossover().
aysxpy() [2/3]
void interfacesse::aysxpy (int * aioarrayint_y, const double aid_alpha, const int * aiarrayint_x, const uintidx aiui_lengthArray) inline
extension of xAXPY operation
extension of xAXPY operation for int result
Parameters
aoarrayt_y a array of T
T a const T
aoarrayt_x a array of T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Parameters
aioarrayint_y a array of int
aid_alpha a const double
aiarrayint_x a array of double
aiui_lengthArray a unsigned integer with aiarrayint_x length
Definition at line 448 of file interface_level1.hpp.
aysxpy() [3/3]
void interfacesse::aysxpy (double * aioarraydouble_y, const double aid_alpha, const double * aiarraydouble_x, const uintidx aiui_lengthArray) inline
extension of xAXPY operation for double
Parameters
aioarraydouble_y a array of double
aid_alpha a const double
aiarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aiarraydouble_x length
Definition at line 522 of file interface_sse_level1_64bits.hpp.
copy() [1/6]
template<typename T > void void interfacesse::copy (T * aoarrayt_y, const T * aiarrayt_x, const uintidx aiui_lengthArray) inline
copy array aoarrayt_x in aoarrayt_y of type T
Parameters
aoarrayt_y a array of type T
aiarrayt_x a array of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 69 of file interface_level1.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), garealop::averageCrossover(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::ChromFixedLength(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::ChromosomeGGA(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::ChromosomeIGKA(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::ChromVariableLength(), mat::MatrixWithRowNull< T_GENE >::copyRow(), mat::MatrixRow< T_METRIC >::copyRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRow(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::copyRows(), clusteringop::fillEmptyPartitions(), eac::gca_fkmedoid(), mat::getTranspose(), garealop::heuristicCrossover(), eac::hka_fkmedoid(), clusteringop::initialize(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::MatrixResizableRow(), mat::MatrixRow< T_METRIC >::MatrixRow(), mat::MatrixTriang< T_DIST >::MatrixTriang(), mat::MatrixWithRowNull< T_GENE >::MatrixWithRowNull(), stats::maxFeatures(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::merge(), stats::minFeatures(), gagenericop::onePointCrossover(), dist::Induced< T_DIST, T_FEATURE >::operator()(), mat::MatrixTriang< T_DIST >::operator=(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::operator=(), ds::PartitionLinked< T_CLUSTERIDX >::operator=(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::operator=(), mat::MatrixRow< T_METRIC >::operator=(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::operator=(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::operator=(), mat::MatrixWithRowNull< T_GENE >::operator=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::operator=(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::operator=(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats(), gagenericop::pathCrossover(), clusteringop::randomInitialize(), gaintegerop::recombinationD_MX(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setGroupSecString(), mat::MatrixWithRowNull< T_GENE >::setMatrix(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::setPartialFcC(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setString(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::setString(), data::toMatrixRow(), and stats::transform().
copy() [2/6]
void interfacesse::copy (unsigned int * aoarrayuint_y, const unsigned int * aiarrayuint_x, const uintidx aiui_lengthArray) inline
copy array aiarrayuint_x in aoarrayuint_y of unsigned int
Parameters
aoarrayuint_y a array unsigned int
aiarrayuint_x a array unsigned int
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 280 of file interface_sse_level1_64bits.hpp.
copy() [3/6]
void interfacesse::copy (int * aoarrayint_y, const int * aiarrayint_x, const uintidx aiui_lengthArray) inline
copy array aiarrayint_x in aoarrayint_y of int
Parameters
aoarrayint_y a array int
aiarrayint_x a array int
aiui_lengthArray a unsigned integer with aiarrayint_x length
Definition at line 302 of file interface_sse_level1_64bits.hpp.
copy() [4/6]
void interfacesse::copy (long int * aoarraylong_y, const long int * aiarraylong_x, const uintidx aiui_lengthArray) inline
copy array aoarrayt_x in aoarraylong_y of long int
Parameters
aoarraylong_y a array long int
aiarraylong_x a array long int
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 331 of file interface_sse_level1_64bits.hpp.
copy() [5/6]
void interfacesse::copy (float * aoarrayfloat_y, const float * aiarrayfloat_x, const uintidx aiui_lengthArray) inline
copy array aoarrayfloat_x in aoarrayfloat_y of float
Parameters
aoarrayfloat_y a array of float
aiarrayfloat_x a array of float
aiui_lengthArray a unsigned integer with aiarrayfloat_x length
Definition at line 999 of file interface_sse_level1_64bits.hpp.
copy() [6/6]
void interfacesse::copy (double * aoarraydouble_y, const double * aiarraydouble_x, const uintidx aiui_lengthArray) inline
copy array aoarraydouble_x in aoarraydouble_y of double
Parameters
aoarraydouble_y a array of double
aiarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aiarraydouble_x length
Definition at line 1026 of file interface_sse_level1_64bits.hpp.
copya() [1/6]
template<typename T > void interfacesse::copya (T * aoarrayt_x, const T ait_alpha, const uintidx aiui_lengthArray) inline
Initializes the array with a constant
.
Parameters
aoarrayt_x a array of type T
ait_alpha a constant of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 46 of file interface_level1.hpp.
Referenced by clusteringop::getCentroids(), eac::gga_vklabel(), mat::MatrixRow< T_METRIC >::initialize(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::initialize(), ds::PartitionLinked< T_CLUSTERIDX >::initialize(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::initialize(), gaclusteringop::kmeansfeac(), prob::makeDistRouletteWheel(), stats::meanVector(), gaclusteringop::mergeCrossover(), mat::mulRowsIColumns0N(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::PartitionLinkedStats(), clusteringop::randomInitialize(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::resize(), um::simplifiedSilhouette(), stats::sumFeactures(), stats::sumFeacturesFreq(), stats::sumFeacturesFreqSQ(), and stats::sumFeacturesSQ().
copya() [2/6]
void interfacesse::copya (unsigned int * aoarrayuint_x, const unsigned int aiui_alpha, const uintidx aiui_lengthArray) inline
copy array aid_alpha in aoarrayuint_x of unsigned int
Parameters
aoarrayuint_x a array of unsigned int
aiui_alpha a constant unsigned
aiui_lengthArray a unsigned integer with aoarrayuint_x length
Definition at line 51 of file interface_sse_level1_64bits.hpp.
copya() [3/6]
void interfacesse::copya (int * aoarrayint_x, const int aii_alpha, const uintidx aiui_lengthArray) inline
copy array aii_alpha in aoarrayint_x of int
Parameters
aoarrayint_x a array of int
aii_alpha a constant int
aiui_lengthArray a unsigned integer with aoarrayint_x length
Definition at line 80 of file interface_sse_level1_64bits.hpp.
copya() [4/6]
void interfacesse::copya (long int * aoarraylong_x, const long int ail_alpha, const uintidx aiui_lengthArray)
copy array aid_alpha in aoarraylong_x of long int
Parameters
aoarraylong_x a array of long int
ail_alpha a long int
aiui_lengthArray a unsigned integer with aoarraylong_x length
Definition at line 107 of file interface_sse_level1_64bits.hpp.
copya() [5/6]
void interfacesse::copya (float * aoarrayfloat_x, float aif_alpha, uintidx aiui_lengthArray) inline
copy array aid_alpha in aoarrayfloat_x of float
Parameters
aoarrayfloat_x a array of float
aif_alpha a float
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 135 of file interface_sse_level1_64bits.hpp.
copya() [6/6]
void void interfacesse::copya (double * aoarraydouble_x, double aid_alpha, uintidx aiui_lengthArray) inline
copy array aid_alpha in aoarraydouble_x of double
Parameters
aoarraydouble_x a array of double
aid_alpha a double
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 163 of file interface_sse_level1_64bits.hpp.
dot() [1/4]
template<typename T > T interfacesse::dot (T * aoarrayt_y, T * aiarrayt_x, const uintidx aiui_lengthArray) inline
swap items of aoarrayt_y to aiarrayt_x
Parameters
aoarrayt_y a array of type T
aiarrayt_x a array of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 114 of file interface_level1.hpp.
Referenced by mat::getMatrixTransformPCA(), dist::Induced< T_DIST, T_FEATURE >::operator()(), and mat::point().
dot() [2/4]
long int long int interfacesse::dot (const int * aiarrayint_x, const int * aiarrayint_y, const uintidx aiui_lengthArray) inline
dot product
Parameters
aiarrayint_x a array of int
aiarrayint_y a array of int
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 359 of file interface_sse_level1_64bits.hpp.
dot() [3/4]
float interfacesse::dot (const float * aiarrayfloat_x, const float * aiarrayfloat_y, const uintidx aiui_lengthArray) inline
dot product for float vectors
Parameters
aiarrayfloat_x a array of float
aiarrayfloat_y a array of float
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 1054 of file interface_sse_level1_64bits.hpp.
dot() [4/4]
double interfacesse::dot (const double * aiarraydouble_x, const double * aiarraydouble_y, const uintidx aiui_lengthArray) inline
dot product for double vectors
Parameters
aiarraydouble_x a array of float
aiarraydouble_y a array of float
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 1084 of file interface_sse_level1_64bits.hpp.
gemm() [1/2]
template<typename T > void interfacesse::gemm (mat::MatrixRow< T > & aomatrixrowt_C, const mat::MatrixRow< T > & aimatrixrowt_A, const mat::MatrixRow< T > & aimatrixrowt_B, const enum mat::TRANSPOSE aienum_transA = mat::CblasNoTrans, const enum mat::TRANSPOSE aienum_transB = mat::CblasNoTrans, const T airt_alpha = 1.0, const T airt_beta = 0.0)
Definition at line 74 of file interface_level2.hpp.
References mat::CblasNoTrans, mat::CblasTrans, mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), inout::li_i, and sum().
Referenced by clusteringop::getCentroids(), mat::getMatrixTransformPCA(), and stats::matrixVarcovar().
gemm() [2/2]
void interfacesse::gemm (mat::MatrixRow< double > & aomatrixrowt_C, const mat::MatrixRow< double > & aimatrixrowt_A, const mat::MatrixRow< double > & aimatrixrowt_B, const enum mat::TRANSPOSE aienum_transA = mat::CblasNoTrans, const enum mat::TRANSPOSE aienum_transB = mat::CblasNoTrans, const double airt_alpha = 1.0, const double airt_beta = 0.0) inline
Definition at line 85 of file interface_sse_level2_64bits.hpp.
References mat::CblasNoTrans, mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::toArray().
gemv() [1/2]
void interfacesse::gemv (double * aoarrayt_y, const mat::MatrixRow< double > & aimatrixrowt_a, const double * aiarrayt_x) inline
gemv of blas operation
Parameters
aoarrayt_y a array of number double
aimatrixrowt_a a const mat::MatrixRow<double>
aiarrayt_x a array of number double
Definition at line 41 of file interface_sse_level2_64bits.hpp.
References mat::CblasNoTrans, mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::toArray().
gemv() [2/2]
template<typename T > void interfacesse::gemv (T * aoarrayt_y, const mat::MatrixRow< T > & aimatrixrowt_a, const T * aiarrayt_x)
Definition at line 43 of file interface_level2.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by dist::Induced< T_DIST, T_FEATURE >::operator()(), and stats::transform().
scal() [1/6]
void interfacesse::scal (int * aoarrayint_x, const long ail_alpha, const uintidx aiui_lengthArray) inline
scal items of the array int
Parameters
aoarrayint_x a array of int
ail_alpha a long scale factor
aiui_lengthArray a unsigned integer with aoarrayint_x length
Definition at line 250 of file interface_sse_level1_64bits.hpp.
scal() [2/6]
template<typename T > void interfacesse::scal (T * aoarrayt_x, const T ait_alpha, const uintidx aiui_lengthArray)
scal items of the array of type T
Parameters
aoarrayt_x a array of type T
ait_alpha a scale factor constant of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 276 of file interface_level1.hpp.
Referenced by clusteringop::getCentroids(), clusteringop::getClusters(), prob::getDistGKA(), mat::getMatrixTransformPCA(), gaclusteringop::kmeansfeac(), prob::makeDistRouletteWheel(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), gaclusteringop::MO1(), and gaclusteringop::MO2().
scal() [3/6]
template<typename T_INT1 , typename T_INT2 > void interfacesse::scal (T_INT1 * aoarrayit_x, const T_INT2 ait_alpha, const uintidx aiui_lengthArray)
scal items of the array of type integer
Parameters
aoarrayit_x a array of type integer
ait_alpha a integer scale factor constant
aiui_lengthArray a unsigned integer with aoarrayit_x length
Definition at line 301 of file interface_level1.hpp.
scal() [4/6]
void interfacesse::scal (float * aoarrayfloat_x, const float aif_alpha, const uintidx aiui_lengthArray) inline
scal items of the array float
Parameters
aoarrayfloat_x a array of float
aif_alpha a float scale factor constant
aiui_lengthArray a unsigned integer with aoarrayfloat_x length
Definition at line 856 of file interface_sse_level1_64bits.hpp.
scal() [5/6]
void interfacesse::scal (double * aoarraydouble_x, const double aid_alpha, const uintidx aiui_lengthArray) inline
scal items of the array float
Parameters
aoarraydouble_x a array of float
aid_alpha a float scale factor constant
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 913 of file interface_sse_level1_64bits.hpp.
scal() [6/6]
void interfacesse::scal (double * aoarraydouble_x, const long int ail_alpha, const uintidx aiui_lengthArray) inline
scal items of the array double
Parameters
aoarraydouble_x a array of double
ail_alpha a long scale factor
aiui_lengthArray a unsigned integer with aoarrayint_x length
Definition at line 940 of file interface_sse_level1_64bits.hpp.
scalInv() [1/4]
void interfacesse::scalInv (int * aoarraydouble_x, const long ail_alpha, const uintidx aiui_lengthArray) inline
scal items of the array int
scal items of the array double
Parameters
aoarrayint_x a array of int
ail_alpha a long scale factor
aiui_lengthArray a unsigned integer with aoarrayint_x length
Parameters
aoarraydouble_x a array of double
ail_alpha a long scale factor
aiui_lengthArray a unsigned integer with aoarrayint_x length
Definition at line 221 of file interface_sse_level1_64bits.hpp.
References inout::d.
scalInv() [2/4]
template<typename T_INT1 , typename T_INT2 > void interfacesse::scalInv (T_INT1 * aoarrayint1_x, const T_INT2 ait_alpha, const uintidx aiui_lengthArray)
Definition at line 328 of file interface_level1.hpp.
Referenced by clusteringop::getClusters(), gaclusteringop::kmeansfeac(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), and gaclusteringop::MO1().
scalInv() [3/4]
void interfacesse::scalInv (float * aoarrayfloat_x, const long int ail_alpha, const uintidx aiui_lengthArray) inline
Definition at line 883 of file interface_sse_level1_64bits.hpp.
References inout::f.
scalInv() [4/4]
void interfacesse::scalInv (double * aoarraydouble_x, const long int ail_alpha, const uintidx aiui_lengthArray) inline
Definition at line 969 of file interface_sse_level1_64bits.hpp.
References inout::d.
sum() [1/4]
template<typename T > T interfacesse::sum (const T * aoarrayt_y, const uintidx aiui_lengthArray) inline
Parameters
aoarrayt_y a array of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 135 of file interface_level1.hpp.
Referenced by eac::cbga_fkcentroid(), eac::feca_vklabel(), gemm(), clusteringop::getCentroids(), prob::getDistGKA(), um::indexI(), um::indexIreeval(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), main(), prob::makeDistRouletteWheel(), stats::meanRow(), gaclusteringop::MO1(), gaclusteringop::MO2(), um::scoreFunction(), um::scoreFunctionreeval(), um::ssbreeval(), um::VRC(), um::VRCreeval(), um::WBIndex(), and um::WBIndexreeval().
sum() [2/4]
long int interfacesse::sum (const int * aiarrayint_y, const uintidx aiui_lengthArray) inline
return the sum array items int
Parameters
aiarrayint_y a array of int
aiui_lengthArray a unsigned integer with aiarrayint_y length
Definition at line 641 of file interface_sse_level1_64bits.hpp.
sum() [3/4]
float interfacesse::sum (const float * aiarrayfloat_y, const uintidx aiui_lengthArray) inline
return the sum array items float
Parameters
aiarrayfloat_y a array of float
aiui_lengthArray a unsigned integer with aiarrayfloat_y length
Definition at line 670 of file interface_sse_level1_64bits.hpp.
sum() [4/4]
double interfacesse::sum (const double * aiarraydouble_y, const uintidx aiui_lengthArray) inline
return the sum array items double
Parameters
aiarraydouble_y a array of double
aiui_lengthArray a unsigned integer with aiarraydouble_y length
Definition at line 698 of file interface_sse_level1_64bits.hpp.
swap() [1/4]
template<typename T > void interfacesse::swap (T * aoarrayt_y, T * aiarrayt_x, const uintidx aiui_lengthArray) inline
swap items of aoarrayt_y to aiarrayt_x
Parameters
aoarrayt_y a array of type T
aiarrayt_x a array of type T
aiui_lengthArray a unsigned integer with aoarrayt_x length
Definition at line 91 of file interface_level1.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), mat::MatrixWithRowNull< T_GENE >::combination(), gaclusteringop::crossoverCGA(), nearest::deleteNearestCentroid(), prob::getRandPairUnlikeInOrd(), mat::MatrixWithRowNull< T_GENE >::keepRows(), gaclusteringop::mergeMutation(), gaclusteringop::MO1(), mat::MatrixRow< T_METRIC >::swapRows(), and mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::swapRows().
swap() [2/4]
void interfacesse::swap (int * aioarrayint_y, int * aioarrayint_x, const uintidx aiui_lengthArray) inline
swap items of aioarrayint_y to aioarrayint_x
Parameters
aioarrayint_y a array of int
aioarrayint_x a array of int
aiui_lengthArray a unsigned integer with aoarrayint_x length
Definition at line 191 of file interface_sse_level1_64bits.hpp.
swap() [3/4]
void interfacesse::swap (float * aioarrayfloat_y, float * aioarrayfloat_x, const uintidx aiui_lengthArray) inline
swap items of aioarrayfloat_y to aioarrayfloat_x for float
Parameters
aioarrayfloat_y a array of float
aioarrayfloat_x a array of float
aiui_lengthArray a unsigned integer with aioarrayfloat_x length
Definition at line 795 of file interface_sse_level1_64bits.hpp.
swap() [4/4]
void void interfacesse::swap (double * aioarraydouble_y, double * aioarraydouble_x, const uintidx aiui_lengthArray) inline
swap items of aioarraydouble_y to aioarraydouble_x for double
Parameters
aioarraydouble_y a array of double
aioarraydouble_x a array of double
aiui_lengthArray a unsigned integer with aoarraydouble_x length
Definition at line 826 of file interface_sse_level1_64bits.hpp.
transy() [1/3]
template<typename T > void interfacesse::transy (T * aoarrayt_y, const T ait_alpha, const uintidx aiui_lengthArray)
translate the aoarrayt_y array
Parameters
aoarrayt_y a array of T
ait_alpha a T
aiui_lengthArray a unsigned integer with aoarrayt_y length
Definition at line 356 of file interface_level1.hpp.
Referenced by mat::getMatrixTransformPCA(), and stats::matrixVarcovar().
transy() [2/3]
void interfacesse::transy (int * aioarrayint_y, const int ait_alpha, const uintidx aiui_lengthArray) inline
translate aioarrayint_y array for int
Parameters
aioarrayint_y a array of int
ait_alpha a int
aiui_lengthArray a unsigned integer with aioarrayint_y length
Definition at line 587 of file interface_sse_level1_64bits.hpp.
transy() [3/3]
void interfacesse::transy (double * aoarraydouble_y, const double aid_alpha, const uintidx aiui_lengthArray) inline
translate aoarraydouble_y array for double
Parameters
aoarraydouble_y a array of int
aid_alpha a double
aiui_lengthArray a unsigned integer with aoarraydouble_y length
Definition at line 614 of file interface_sse_level1_64bits.hpp.