Library Evolutionary Algorithms for Clustering (LEAC): data Namespace Reference
data Namespace Reference
Module for the handling of instances or also called objects or points.
Classes
class CountLabel
Stores the number of occurrences of a label for an attribute in a dataset.
class Instance
Patterns, usually vectors in a multidimensional space.
class InstanceClass
Patterns, usually vectors in a multidimensional space, previamente clasificado.
class InstanceClassFreq
Patterns, usually vectors in a multidimensional space, which is classified and with a number of occurrences.
class InstanceFreq
Patterns, usually vectors in a multidimensional space, with an attribute to store occurrences of instances.
class InstanceIterfazClass
Instance with class.
class InstanceWeight
Patterns, usually vectors in a multidimensional space.
class InstanceWeightClass
Patterns, usually vectors in a multidimensional space.
Functions
template<typename INPUT_ITERATOR >
auto toMatrixRowTrans (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, bool aiWithOutHomogeneousCoord) -> mat::MatrixRow< decltype((*aiiterator_instfirst) ->getAttribute(0))>
Instaces matrix transpose.
template<typename INPUT_ITERATOR >
auto toMatrixRow (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow< decltype((*aiiterator_instfirst) ->getAttribute(0))>
Instaces matrix.
template<typename T_IDX_LABEL , typename T_COUNT_LABEL >
std::vector< CountLabel< T_IDX_LABEL, T_COUNT_LABEL > > mapcountlabel_mapToVector (std::map< const std::string, CountLabel< T_IDX_LABEL, T_COUNT_LABEL > > &aimap_countLabel)
Detailed Description
Module for the handling of instances or also called objects or points.
Module for the model object, point or instances.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
mapcountlabel_mapToVector()
template<typename T_IDX_LABEL , typename T_COUNT_LABEL > std::vector<CountLabel <T_IDX_LABEL, T_COUNT_LABEL> > data::mapcountlabel_mapToVector (std::map< const std::string, CountLabel< T_IDX_LABEL, T_COUNT_LABEL > > & aimap_countLabel)
Definition at line 177 of file count_label.hpp.
toMatrixRow()
template<typename INPUT_ITERATOR > auto data::toMatrixRow (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow<decltype((*aiiterator_instfirst)->getAttribute(0))>
Instaces matrix.
Gets a matrix from a container, where elements are the characteristics of instances stored by columns.
Parameters
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast a InputIterator to the final positions of the sequence of instances
Definition at line 115 of file container_instance.hpp.
References interfacesse::copy().
Referenced by eac::gaclustering_fkcrispmatrix(), eac::gaprototypes_fkmedoid(), and main().
toMatrixRowTrans()
template<typename INPUT_ITERATOR > auto data::toMatrixRowTrans (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, bool aiWithOutHomogeneousCoord) -> mat::MatrixRow<decltype((*aiiterator_instfirst)->getAttribute(0))>
Instaces matrix transpose.
Gets a matrix from a container, where elements are the characteristics of instances stored by columns.
Parameters
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast a InputIterator to the final positions of the sequence of instances
aiWithOutHomogeneousCoord a boolean to include another element and represent an instance in homogeneous coordinates
Definition at line 42 of file container_instance.hpp.
References data::Instance< T_FEATURE >::getFeatures().
Referenced by mat::getMatrixTransformPCA(), and stats::matrixVarcovar().