Library Evolutionary Algorithms for Clustering (LEAC): nearest Namespace Reference
nearest Namespace Reference
Function to find nearest instances.
Classes
class NearestCentroids
Stores the relationship between centroids, the closest and its distance.
Functions
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST >
T_CLUSTERIDX findTwoNearestCentroids (T_CLUSTERIDX aicidx_centroidCj, const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Find the centroid Cjp closest to the centroid Cj.
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST >
void findTwoNearestCentroids (NearestCentroids< T_CLUSTERIDX, T_DIST > &aonearcent_centroidCjp, mat::MatrixBase< T_CENTROIDS > &aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > &aivectorit_numInstClusterK, T_CLUSTERIDX aicidx_centroidCj, const dist::Dist< T_DIST, T_CENTROIDS > &aifunc2p_dist)
Find two nearest centroids.
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST >
void findAllPairCentroidsClosest (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > &aovector_nearestCentroids, mat::MatrixBase< T_CENTROIDS > &aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > &aivectorit_numInstClusterK, const dist::Dist< T_DIST, T_CENTROIDS > &aifunc2p_dist)
Find all pair of centroids closest.
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST >
void recalculateDistNearestCentroids (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > &aovector_nearestCentroids, mat::MatrixBase< T_CENTROIDS > &aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > &aivectorit_numInstClusterK, const dist::Dist< T_DIST, T_CENTROIDS > &aifunc2p_dist)
Recalculates distance between nearest::NearestCentroids.
template<typename T_CLUSTERIDX , typename T_DIST >
std::pair< T_CLUSTERIDX, T_CLUSTERIDX > findNearestCentroids (const std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > &aivector_nearestCentroidsDist)
Find the nearest pair of centroids.
template<typename T_CLUSTERIDX , typename T_DIST >
void markRecalculationNearest (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > &aovector_nearestCentroids, const std::pair< T_CLUSTERIDX, T_CLUSTERIDX > &aipair_merged)
Mark pairs of centroids that depend on the pair to be joined.
template<typename T_CLUSTERIDX , typename T_DIST >
void deleteNearestCentroid (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > &aovector_nearestCentroids, const T_CLUSTERIDX aicidx_clusterToDelete)
Delete a nearest::NearestCentroids.
template<typename ITERATOR_IDXINST , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR >
uintidx farthestInstanceFromS1 (const uintidx aiuintidx_S1, ITERATOR_IDXINST aiiterator_idxInstfirst, ITERATOR_IDXINST aiiterator_idxInstlast, const INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR >
uintidx farthestInstanceFromS1 (const uintidx aiuintidx_S1, const T_CLUSTERIDX *aiarraycidx_idxMemberShip, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST >
T_CLUSTERIDX NN (T_DIST &aort_distMinCentInst, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_centroids, const T_FEATURE *aiat_instance, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
NN Find the centroid closest to an instance.
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST >
T_CLUSTERIDX checkNullCentroidsNN (T_DIST &aort_distMinCentInst, const mat::MatrixBase< T_FEATURE > &aimatrixrowt_centroids, const T_FEATURE *aiat_instance, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Find the centroid closest to an instance and check null centroids.
template<typename T_CLUSTERIDX , typename T_DIST_INSTANCESINSTANCES >
T_CLUSTERIDX medoidsNN (T_DIST_INSTANCESINSTANCES &aort_distMinMedoidInst, const uintidx aiuidx_instance, const uintidx *aiarrayuidx_medoids, const T_CLUSTERIDX aicidx_numMedoisK, const mat::MatrixTriang< T_DIST_INSTANCESINSTANCES > &aimatrixtriagt_dissimilarity)
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST >
T_CLUSTERIDX NN (T_DIST &aort_distMinCentInst, const mat::MatrixBase< T_FEATURE > &aimatrixrowt_centroids, T_CLUSTERIDX aicidx_currentCentroidK, const T_FEATURE *aiat_instance, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
NN Find the centroid closest to an instance starting from a defined centroid.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_DIST >
std::vector< T_DIST > dist (const mat::MatrixBase< T_FEATURE > &aimatrixrowt_centroids, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstClusterK, const T_FEATURE *aiat_instance, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Calculate the distances of the instance to the centroids [28].
Detailed Description
Function to find nearest instances.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
checkNullCentroidsNN()
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST > T_CLUSTERIDX nearest::checkNullCentroidsNN (T_DIST & aort_distMinCentInst, const mat::MatrixBase< T_FEATURE > & aimatrixrowt_centroids, const T_FEATURE * aiat_instance, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Find the centroid closest to an instance and check null centroids.
Parameters
aort_distMinCentInst output distance between centroid and instance
aiat_instance characteristics of the instance
aimatrixrowt_centroids a matrix with centroids
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 238 of file nearestinstance_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), data::Instance< T_FEATURE >::isInfiniteFeature(), and NEARESTCENTROID_UNKNOWN.
Referenced by gaclusteringop::kmeansfeac().
deleteNearestCentroid()
template<typename T_CLUSTERIDX , typename T_DIST > void nearest::deleteNearestCentroid (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > & aovector_nearestCentroids, const T_CLUSTERIDX aicidx_clusterToDelete)
Delete a nearest::NearestCentroids.
Parameters
aovector_nearestCentroids a std::vector of nearest::NearestCentroids with the nearest pairs
aicidx_clusterToDelete cluster index to delete
Definition at line 438 of file nearestcentroids_operator.hpp.
References interfacesse::swap().
Referenced by clusteringop::pnnFast().
dist()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_DIST > std::vector< T_DIST > nearest::dist (const mat::MatrixBase< T_FEATURE > & aimatrixrowt_centroids, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstClusterK, const T_FEATURE * aiat_instance, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Calculate the distances of the instance to the centroids [28].
Parameters
aimatrixrowt_centroids a mat::MatrixBase with the centroids
aivectort_numInstClusterK a std::vector with the number of instances
aiat_instance a array with the instance attributes
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 460 of file nearestinstance_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixBase< T_FEATURE >::getRow().
Referenced by eac::igka_fklabel().
farthestInstanceFromS1() [1/2]
template<typename ITERATOR_IDXINST , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR > uintidx nearest::farthestInstanceFromS1 (const uintidx aiuintidx_S1, ITERATOR_IDXINST aiiterator_idxInstfirst, ITERATOR_IDXINST aiiterator_idxInstlast, const INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 55 of file nearestinstance_operator.hpp.
Referenced by gaclusteringop::MO2().
farthestInstanceFromS1() [2/2]
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR > uintidx nearest::farthestInstanceFromS1 (const uintidx aiuintidx_S1, const T_CLUSTERIDX * aiarraycidx_idxMemberShip, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 122 of file nearestinstance_operator.hpp.
References data::Instance< T_FEATURE >::getNumDimensions().
findAllPairCentroidsClosest()
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST > void nearest::findAllPairCentroidsClosest (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > & aovector_nearestCentroids, mat::MatrixBase< T_CENTROIDS > & aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > & aivectorit_numInstClusterK, const dist::Dist< T_DIST, T_CENTROIDS > & aifunc2p_dist)
Find all pair of centroids closest.
The pairs of centroids are determined by the index of the vector and the index stored in nearest::NearestCentroids
Parameters
aovector_nearestCentroids a std::vector of nearest::NearestCentroids where the nearest pairs of centroids are recorded
aimatrixt_centroids a mat::MatrixRow with centroids
aivectorit_numInstClusterK a vector with numero number of instances in each cluster
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 191 of file nearestcentroids_operator.hpp.
References findTwoNearestCentroids().
Referenced by clusteringop::pnnFast().
findNearestCentroids()
template<typename T_CLUSTERIDX , typename T_DIST > std::pair< T_CLUSTERIDX, T_CLUSTERIDX > nearest::findNearestCentroids (const std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > & aivector_nearestCentroidsDist)
Find the nearest pair of centroids.
Parameters
aivector_nearestCentroidsDist a std::vector of nearest::NearestCentroids with the nearest pairs
Definition at line 334 of file nearestcentroids_operator.hpp.
Referenced by clusteringop::pnnFast().
findTwoNearestCentroids() [1/2]
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST > T_CLUSTERIDX nearest::findTwoNearestCentroids (T_CLUSTERIDX aicidx_centroidCj, const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Find the centroid Cjp closest to the centroid Cj.
Parameters
aicidx_centroidCj an index of the centroid. From this look for the nearest
aimatrixt_centroids a mat::MatrixRow with centroids
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 46 of file nearestcentroids_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and NEARESTCENTROID_UNKNOWN.
Referenced by findAllPairCentroidsClosest(), gaclusteringop::MO1(), and recalculateDistNearestCentroids().
findTwoNearestCentroids() [2/2]
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST > void nearest::findTwoNearestCentroids (NearestCentroids< T_CLUSTERIDX, T_DIST > & aonearcent_centroidCjp, mat::MatrixBase< T_CENTROIDS > & aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > & aivectorit_numInstClusterK, T_CLUSTERIDX aicidx_centroidCj, const dist::Dist< T_DIST, T_CENTROIDS > & aifunc2p_dist)
Find two nearest centroids.
Parameters
aonearcent_centroidCjp a nearest::NearestCentroids stores the index and distance to the nearest centroid
aimatrixt_centroids a mat::MatrixRow with centroids
aivectorit_numInstClusterK a vector with the number of instances in each cluster
aicidx_centroidCj an index of the centroid. From this look for the nearest
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 127 of file nearestcentroids_operator.hpp.
References um::distortion(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixBase< T_FEATURE >::getRow().
markRecalculationNearest()
template<typename T_CLUSTERIDX , typename T_DIST > void nearest::markRecalculationNearest (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > & aovector_nearestCentroids, const std::pair< T_CLUSTERIDX, T_CLUSTERIDX > & aipair_merged)
Mark pairs of centroids that depend on the pair to be joined.
Parameters
aovector_nearestCentroids a std::vector of nearest::NearestCentroids with the nearest pairs
aipair_merged a std::pair with cluster indexes to Join
Definition at line 377 of file nearestcentroids_operator.hpp.
Referenced by clusteringop::pnnFast().
medoidsNN()
template<typename T_CLUSTERIDX , typename T_DIST_INSTANCESINSTANCES > T_CLUSTERIDX nearest::medoidsNN (T_DIST_INSTANCESINSTANCES & aort_distMinMedoidInst, const uintidx aiuidx_instance, const uintidx * aiarrayuidx_medoids, const T_CLUSTERIDX aicidx_numMedoisK, const mat::MatrixTriang< T_DIST_INSTANCESINSTANCES > & aimatrixtriagt_dissimilarity)
Definition at line 325 of file nearestinstance_operator.hpp.
Referenced by clusteringop::computeTotalCostSwap(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::getClusterIdx(), clusteringop::nearestRepresentative(), partition::PartitionMedoids< T_INSTANCES_IDX, T_CLUSTERIDX, T_DIST >::next(), and um::SSEMedoid().
NN() [1/2]
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST > T_CLUSTERIDX nearest::NN (T_DIST & aort_distMinCentInst, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_centroids, const T_FEATURE * aiat_instance, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
NN Find the centroid closest to an instance.
Parameters
aort_distMinCentInst output distance between centroid and instance
aimatrixrowt_centroids matrix with the centroids
aiat_instance a array with the instance attributes
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 192 of file nearestinstance_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and NEARESTCENTROID_UNKNOWN.
Referenced by um::distortion(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::getClusterIdx(), clusteringop::getClusters(), clusteringop::getPartition(), partition::PartitionCentroids< T_FEATURE, T_CLUSTERIDX, T_DIST, INPUT_ITERATOR >::next(), clusteringop::reassignCluster(), clusteringop::setUpCuster(), um::SSE(), clusteringop::updateCentroids(), and clusteringop::updateClusterCj().
NN() [2/2]
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_DIST > T_CLUSTERIDX nearest::NN (T_DIST & aort_distMinCentInst, const mat::MatrixBase< T_FEATURE > & aimatrixrowt_centroids, T_CLUSTERIDX aimcIdx_currentCentroidK, const T_FEATURE * aiat_instance, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
NN Find the centroid closest to an instance starting from a defined centroid.
Parameters
aort_distMinCentInst output distance between centroid and instance
aimatrixrowt_centroids matrix with the centroids
aimcIdx_currentCentroidK a current centroid that the instance belongs to
aiat_instance a array with the instance attributes
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 403 of file nearestinstance_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixBase< T_FEATURE >::getRow().
recalculateDistNearestCentroids()
template<typename T_CENTROIDS , typename T_CLUSTERIDX , typename T_INSTANCES_CLUSTER_K , typename T_DIST > void nearest::recalculateDistNearestCentroids (std::vector< NearestCentroids< T_CLUSTERIDX, T_DIST > > & aovector_nearestCentroids, mat::MatrixBase< T_CENTROIDS > & aimatrixt_centroids, std::vector< T_INSTANCES_CLUSTER_K > & aivectorit_numInstClusterK, const dist::Dist< T_DIST, T_CENTROIDS > & aifunc2p_dist)
Recalculates distance between nearest::NearestCentroids.
Parameters
aovector_nearestCentroids a std::vector of nearest::NearestCentroids where the nearest pairs of centroids are recorded
aimatrixt_centroids a mat::MatrixRow with centroids
aivectorit_numInstClusterK a vector with numero number of instances in each cluster
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 261 of file nearestcentroids_operator.hpp.
References findTwoNearestCentroids().
Referenced by clusteringop::pnnFast().