Library Evolutionary Algorithms for Clustering (LEAC): gaclusteringop Namespace Reference
gaclusteringop Namespace Reference
Genetic cluster-oriented operators.
Functions
template<typename T_FEATURE , typename T_REAL >
gaencode::ChromVariableLength< T_FEATURE, T_REAL > * newChromosome (mat::MatrixRow< T_FEATURE > &aimatrixrowt_minMaxKSegments, T_REAL airt_fitnessInitial, T_REAL airt_objetiveInitial)
Create new chromosome [18].
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR >
void merge (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aiochromcbga_offspring, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aiochromcbga_part1, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aiochromcbga_part2, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
Merge two chomosomas.
template<typename T_FEATURE , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR >
void crossPNNnew (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aochromcbga_new, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aichromcbga_old1, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aichromcbga_old2, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numclusterKToReduce, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_GENE , typename T_METRIC >
void onePointCrossover (gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &aiochrommwrn_child1, gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > &aiochrommwrn_child2)
template<typename T_CLUSTERIDX , typename T_METRIC >
gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > mergeCrossover (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &aichrom_parent1, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > &aichrom_parent2)
mergeCrossover [1]
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR >
void crossoverCGA (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aochrom_childC, gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aichrom_parentA, gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aichrom_parentB, mat::MatrixRow< T_FEATURE > &aomatrixrowt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixrowt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_REAL >
void splittingMutation (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > &aiochromab_toMutate)
Mutation by cluster splitting [1].
template<typename T_CLUSTERIDX , typename T_REAL >
void mergeMutation (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > &aiochromab_toMutate)
template<typename T_FEATURE , typename T_REAL >
void randomMutation (gaencode::ChromosomeMatrixWithRowNull< T_FEATURE, T_REAL > &aiochromatrixwrn_toMutate)
Random mutation [5].
template<typename T_GENE , typename T_METRIC >
void biDirectionHMutation (gaencode::ChromosomeString< T_GENE, T_METRIC > &aiochromstr_toMutate, const T_METRIC airt_minObjetiveFunc, const T_METRIC airt_maxObjetiveFunc, const T_GENE *aiarrayt_minFeatures, const T_GENE *aiarrayt_maxFeatures)
biDirectionHMutation [4]
template<typename T_FEATURE , typename T_REAL >
void biDirectionMutation (gaencode::ChromosomeString< T_FEATURE, T_REAL > &aiochromstr_toMutate, const T_FEATURE *aiarrayt_minFeatures, const T_FEATURE *aiarrayt_maxFeatures)
template<typename T_CENTROIDS , typename T_REAL >
bool rearrangedCluster (gaencode::ChromosomeString< T_CENTROIDS, T_REAL > &aochrom_YRearranged, const mat::MatrixRow< T_CENTROIDS > &aimatrixrowt_XReferenced, const dist::Dist< T_REAL, T_CENTROIDS > &aifunc2p_dist)
Rearranged cluster [11].
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_COMMON_IDOMAIN , typename INPUT_ITERATOR >
void kmeansfeac (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aochrom_feac, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_COMMON_IDOMAIN aiit_kmeansNumMaxIter, T_FEATURE airt_kmeansMaxDiffCent, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR >
void MO1 (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aiochromfixlen_toMutate, mat::MatrixRow< T_FEATURE > &aomatrixrowt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixrowt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
MO1 mutation operator [19].
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename INPUT_ITERATOR >
void MO2 (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aiochromfixlen_toMutate, const INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
void MO1 (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aochromfeac_toMutate, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
void MO2 (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aochromfeac_toMutate, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
Detailed Description
Genetic cluster-oriented operators.
Cluster-oriented operators mean the operators that are task-dependent, such as operators that copy, split, merge, and eliminate clusters of data objects, in contrast to conventional evolutionary operators that just exchange or switch bits without any regard to their task-dependent meaning [22]
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
biDirectionHMutation()
template<typename T_GENE , typename T_METRIC > void gaclusteringop::biDirectionHMutation (gaencode::ChromosomeString< T_GENE, T_METRIC > & aiochromstr_toMutate, const T_METRIC airt_minObjetiveFunc, const T_METRIC airt_maxObjetiveFunc, const T_GENE * aiarrayt_minFeatures, const T_GENE * aiarrayt_maxFeatures)
biDirectionHMutation [4]
The mutation does the following
Where is a random number in the interval :
and be the minimum and maximum values of the clustering metric, respectively, in the current population. is the clustering metric value of the current chromosome that must be mutated.
Parameters
aiochromstr_toMutate a gaencode::ChromosomeString chromosome to mutate
airt_minObjetiveFunc a real number with the minimum value of the objective function of the current population
airt_maxObjetiveFunc a real number with the maximum value of the objective function of the current population
aiarrayt_minFeatures an array with the minimum values of the dataset instances
aiarrayt_maxFeatures an array with the maximum values of the dataset instances
Note
The authors of this operator do not assign a specific name for this, here it is called gaclusteringop::biDirectionHMutation
Definition at line 1209 of file ga_clustering_operator.hpp.
References interfacesse::aasxpa(), interfacesse::aysxpy(), DATATYPE_REAL, data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by eac::gagr_fkcentroid(), and eac::kga_fkcentroid().
biDirectionMutation()
template<typename T_FEATURE , typename T_REAL > void gaclusteringop::biDirectionMutation (gaencode::ChromosomeString< T_FEATURE, T_REAL > & aiochromstr_toMutate, const T_FEATURE * aiarrayt_minFeatures, const T_FEATURE * aiarrayt_maxFeatures)
Definition at line 1359 of file ga_clustering_operator.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by eac::tgca_vkcentroid().
crossoverCGA()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR > void gaclusteringop::crossoverCGA (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aochrom_childC, gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aichrom_parentA, gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aichrom_parentB, mat::MatrixRow< T_FEATURE > & aomatrixrowt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixrowt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 690 of file ga_clustering_operator.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), inout::containerprint(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), clusteringop::getCentroids(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene(), data::Instance< T_FEATURE >::getNumDimensions(), ds::getPartitionlinked(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), prob::getWithoutRepeatsSet(), gmt19937_eng, NEARESTCENTROID_UNKNOWN, ds::IteratorPartitionLinked< T_CLUSTERIDX >::next(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setGene(), clusteringop::setUpCuster(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize(), and interfacesse::swap().
Referenced by eac::cga_vklabel().
crossPNNnew()
template<typename T_FEATURE , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR > void gaclusteringop::crossPNNnew (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aochromcbga_new, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aichromcbga_old1, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aichromcbga_old2, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numclusterKToReduce, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 339 of file ga_clustering_operator.hpp.
References merge(), and clusteringop::pnnFast().
Referenced by eac::cbga_fkcentroid().
kmeansfeac()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_COMMON_IDOMAIN , typename INPUT_ITERATOR > void gaclusteringop::kmeansfeac (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aochrom_feac, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_COMMON_IDOMAIN aiit_kmeansNumMaxIter, T_FEATURE airt_kmeansMaxDiffCent, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 1590 of file ga_clustering_operator.hpp.
References interfacesse::axpy(), nearest::checkNullCentroidsNN(), inout::containerprint(), interfacesse::copya(), data::Instance< T_FEATURE >::getInfiniteFeature(), mat::MatrixBase< T_FEATURE >::getNumColumns(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixWithRowNull< T >::getRow(), mat::MatrixRow< T_FEATURE >::initialize(), vectorutils::keepItems(), mat::MatrixWithRowNull< T >::keepRows(), gaintegerop::labelKeep(), NEARESTCENTROID_UNKNOWN, interfacesse::scal(), interfacesse::scalInv(), and ds::BitContainer< T_BITSIZE >::setBit().
Referenced by eac::feca_vklabel().
merge()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR > void gaclusteringop::merge (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aiochromcbga_offspring, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aiochromcbga_part1, gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aiochromcbga_part2, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Merge two chomosomas.
Parameters
aiochromcbga_offspring
aiochromcbga_part1
aiochromcbga_part2
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 168 of file ga_clustering_operator.hpp.
References ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::getMemberShip(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::getRow(), and mat::MatrixResizableRow< T_FEATURE, T_WEIGHT >::merge().
Referenced by crossPNNnew().
mergeCrossover()
template<typename T_CLUSTERIDX , typename T_METRIC > gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > gaclusteringop::mergeCrossover (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & aichrom_parent1, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC > & aichrom_parent2)
mergeCrossover [1]
Parameters
aichrom_parent1 a gaencode::ChromosomeGGA
aichrom_parent2 a gaencode::ChromosomeGGA
Definition at line 518 of file ga_clustering_operator.hpp.
References interfacesse::copya(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), prob::getRandPairUnlikeInOrd(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getStringSize(), gmt19937_eng, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec(), gaintegerop::labelKeep(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), and UNKNOWN_CLUSTER_IDX.
Referenced by eac::gga_vklabel().
mergeMutation()
template<typename T_CLUSTERIDX , typename T_REAL > void gaclusteringop::mergeMutation (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > & aiochromab_toMutate)
Definition at line 1019 of file ga_clustering_operator.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), prob::getIdxPairUnlikeRoulette(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), prob::makeDistRouletteWheel(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), interfacesse::swap(), and UNKNOWN_CLUSTER_IDX.
Referenced by eac::gga_vklabel().
MO1() [1/2]
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR > void gaclusteringop::MO1 (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aiochromfixlen_toMutate, mat::MatrixRow< T_FEATURE > & aomatrixrowt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixrowt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
MO1 mutation operator [19].
It eliminates one selected clusters, placing its objects into the nearest remaining clusters (according to their centroids).To remove a group it is necessary to calculate the centroids associated with the chromosome. The parameters of aomatrixt_meanCentroids, aimatrixtrowt_sumInstancesClusterK, and aovectort_numInstClusterK are returned with the centroid, the sum of instances, and the number of instances per group, respectively.
Parameters
aiochromfixlen_toMutate a gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>
aomatrixrowt_centroids a MatrixBase<T_CENTROIDS>
aomatrixrowt_sumInstCluster a MatrixBase<T_FEATURE_SUM>
aovectort_numInstClusterK a std::vector<T_INSTANCES_CLUSTER_K>
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1898 of file ga_clustering_operator.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), clusteringop::getCentroids(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), gmt19937_eng, NEARESTCENTROID_UNKNOWN, gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setGene(), clusteringop::setUpCuster(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize(), and interfacesse::swap().
Referenced by eac::cga_vklabel(), and eac::feca_vklabel().
MO1() [2/2]
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > void gaclusteringop::MO1 (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aochromfeac_toMutate, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 2191 of file ga_clustering_operator.hpp.
References interfacesse::axpy(), nearest::findTwoNearestCentroids(), gaselect::getIdxRouletteWheel(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixWithRowNull< T >::getRow(), gmt19937_eng, mat::MatrixWithRowNull< T >::keepRows(), gaintegerop::labelKeep(), prob::linearNormalization(), prob::makeDistRouletteWheel(), gaintegerop::oneChangelabel(), interfacesse::scal(), interfacesse::scalInv(), um::simplifiedSilhouette(), and interfacesse::sum().
MO2() [1/2]
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename INPUT_ITERATOR > void gaclusteringop::MO2 (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aiochromfixlen_toMutate, const INPUT_ITERATOR aiiterator_instfirst, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 2046 of file ga_clustering_operator.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), nearest::farthestInstanceFromS1(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene(), gmt19937_eng, gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), and gaencode::ChromFixedLength< T_GENE, T_METRIC >::setGene().
Referenced by eac::cga_vklabel(), and eac::feca_vklabel().
MO2() [2/2]
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > void gaclusteringop::MO2 (gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aochromfeac_toMutate, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 2589 of file ga_clustering_operator.hpp.
References mat::MatrixWithRowNull< T >::addRow(), interfacesse::axpy(), mat::MatrixWithRowNull< T >::copyRow(), nearest::farthestInstanceFromS1(), sm::getConfusionMatrix(), gaselect::getIdxRouletteWheel(), mat::MatrixBase< T_FEATURE >::getNumRows(), gmt19937_eng, prob::linearNormalization(), prob::makeDistRouletteWheel(), partition::PartitionLabel< T_CLUSTERIDX >::print(), interfacesse::scal(), um::simplifiedSilhouette(), interfacesse::sum(), and clusteringop::updateClusterCj().
newChromosome()
template<typename T_FEATURE , typename T_REAL > gaencode::ChromVariableLength< T_FEATURE, T_REAL > * gaclusteringop::newChromosome (mat::MatrixRow< T_FEATURE > & aimatrixrowt_minMaxKSegments, T_REAL airt_fitnessInitial, T_REAL airt_objetiveInitial)
Create new chromosome [18].
Create new chromosome initial values of cluster centers are produced through uniformly random selection in ki segments by hierarchical agglomerative clustering algorithm.
Parameters
aimatrixrowt_minMaxKSegments a matrix with ki segments
airt_fitnessInitial real number with value of the fitness initial
airt_objetiveInitial real number with value of the function objective initial
Definition at line 69 of file ga_clustering_operator.hpp.
References data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString(), gmt19937_eng, gaencode::ChromVariableLength< T_GENE, T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
Referenced by eac::tgca_vkcentroid().
onePointCrossover()
template<typename T_GENE , typename T_METRIC > void gaclusteringop::onePointCrossover (gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & aiochrommwrn_child1, gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC > & aiochrommwrn_child2) inline
Definition at line 454 of file ga_clustering_operator.hpp.
References mat::MatrixWithRowNull< T_GENE >::combination(), mat::MatrixWithRowNull< T_GENE >::getNumRowsMax(), gmt19937_eng, gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
Referenced by eac::gcuk_vkcentroid().
randomMutation()
template<typename T_FEATURE , typename T_REAL > void void gaclusteringop::randomMutation (gaencode::ChromosomeMatrixWithRowNull< T_FEATURE, T_REAL > & aiochromatrixwrn_toMutate)
Random mutation [5].
Each valid position (i.e., which is not ::) in a chromosome is mutated. A number in the range [0,1] is generated with uniform distribution. If the value at that position is , then after mutation it becomes
The + or sign occurs with equal probability.
Parameters
aiochromatrixwrn_toMutate a gaencode::ChromosomeMatrixWithRowNull chromosome to mutate
Definition at line 1120 of file ga_clustering_operator.hpp.
References DATATYPE_REAL, and gmt19937_eng.
Referenced by eac::gcuk_vkcentroid().
rearrangedCluster()
template<typename T_CENTROIDS , typename T_REAL > bool gaclusteringop::rearrangedCluster (gaencode::ChromosomeString< T_CENTROIDS, T_REAL > & aochrom_YRearranged, const mat::MatrixRow< T_CENTROIDS > & aimatrixrowt_XReferenced, const dist::Dist< T_REAL, T_CENTROIDS > & aifunc2p_dist)
Rearranged cluster [11].
For the new population, select the best chromosome as as a refrence, wich other chromosomes might fall into the gene rearrangement if needed
Parameters
aochrom_YRearranged
aimatrixrowt_XReferenced
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1459 of file ga_clustering_operator.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), mat::MatrixRow< T_FEATURE >::initialize(), gaencode::ChromosomeBase< T_METRIC >::print(), and ds::BitContainer< T_BITSIZE >::setBit().
Referenced by eac::gagr_fkcentroid().
splittingMutation()
template<typename T_CLUSTERIDX , typename T_REAL > void gaclusteringop::splittingMutation (gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > & aiochromab_toMutate)
Mutation by cluster splitting [1].
Mutation by clusters merging it consists of merging two existing clusters, randomly selected, into just one.
Parameters
aiochromab_toMutate a gaencode::ChromosomeGGA a mutate
Definition at line 938 of file ga_clustering_operator.hpp.
References gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::increaseGroupSecSize(), prob::makeDistRouletteWheel(), and gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print().
Referenced by eac::gga_vklabel().