Library Evolutionary Algorithms for Clustering (LEAC): prob Namespace Reference
prob Namespace Reference
Method for calculate probability distributions.
Functions
template<typename INPUT_ITERATOR , typename FITNESSOPERATION >
auto makeDistRouletteWheel (INPUT_ITERATOR aiiterator_instfirst, INPUT_ITERATOR aiiterator_instlast, const FITNESSOPERATION fitness_func) -> std::vector< decltype(fitness_func(*aiiterator_instfirst))>
template<typename INPUT_ITERATOR , typename FITNESSFUNCTGET , typename FITNESSFUNCTSET >
void linearNormalization (INPUT_ITERATOR aiiterator_first, const INPUT_ITERATOR aiiterator_last, const FITNESSFUNCTGET fitness_funcGet, const FITNESSFUNCTSET fitness_funcSet, const decltype(fitness_funcGet(*aiiterator_first)) lrt_scale=1.0)
Linear normalization.
template<typename INPUT_ITERATOR , typename FITNESSOPERATION >
auto linearNormalization (INPUT_ITERATOR aiiterator_first, const INPUT_ITERATOR aiiterator_last, const FITNESSOPERATION fitness_func, const decltype(fitness_func(*aiiterator_first)) lrt_scale=1.0) -> std::vector< decltype(fitness_func(*aiiterator_first))>
template<typename T_REAL >
std::vector< T_REAL > getDistGKA (const std::vector< T_REAL > &aivector_randVar, const T_REAL airt_cm)
GKA Probability Distribution [26].
template<typename T_REAL >
T_REAL adaptiveProb (T_REAL aiT_k1, T_REAL aiT_k3, T_REAL aiT_fmax, T_REAL aiT_faverage, T_REAL aiT_fprime)
Adaptively probability.
template<typename T_PROBABILITY >
std::pair< uintidx, uintidx > getIdxPairUnlikeRoulette (const std::vector< T_PROBABILITY > &aivectorrt_probDist, uintidx aiuintidx_begins)
Selection a pair random index in [IdxBegin,n].
template<typename T_PROBABILITY , typename FUNCTION_RAND >
std::vector< uintidx > getIdxVectorRoulette (const std::vector< T_PROBABILITY > &aivectort_probDist, const bool aib_withRepeatedValues, const uintidx aiuintidx_numbersToGenerate, const uintidx aiuintidx_begins, FUNCTION_RAND function_rand01)
Selection a vector of random index in [IdxBegin,n].
template<typename FUNCTION >
auto getRandPairUnlike (FUNCTION function_generate) -> std::pair< decltype(function_generate()), decltype(function_generate())>
Get two random number diferent.
template<typename FUNCTION >
auto getRandPairUnlikeInOrd (FUNCTION function_generate) -> std::pair< decltype(function_generate()), decltype(function_generate())>
Get two random number diferent in order.
template<typename FUNCTION >
auto getWithoutRepeatsSet (const uintidx aiuintidx_numbersToGenerate, FUNCTION function_generate) -> std::unordered_set< decltype(function_generate())>
Get a set of random number diferent.
template<typename T_RAND , typename FUNCTION >
auto getRandUnlike (const T_RAND at_unlike, FUNCTION function_generate) -> decltype(function_generate())
A random different than a given at_unlike.
template<typename T_RAND , typename FUNCTION >
T_RAND getRandSetUnlike (const std::unordered_set< T_RAND > &aiunorderedset_rand, FUNCTION function_generate)
Selection a random un like to set items.
std::pair< uintidx, uintidx > getElitistPairCross (std::vector< uintidx > *aoptvectoruintidx_chromPairsCross, uintidx aiuintidx_idxChromTMinIdxSelect, uintidx aiuintidx_idxChromTMaxIdxSelect)
Selection a pair random index.
Detailed Description
Method for calculate probability distributions.
functions for get randon number
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
adaptiveProb()
template<typename T_REAL > T_REAL prob::adaptiveProb (T_REAL aiT_k1, T_REAL aiT_k3, T_REAL aiT_fmax, T_REAL aiT_faverage, T_REAL aiT_fprime)
Adaptively probability.
Parameters
aiT_k1 a real number
aiT_k3 a real number
aiT_fmax a real number
aiT_faverage a real number
aiT_fprime a real number)
Definition at line 509 of file probability_distribution.hpp.
References utils::closeenough(), and inout::e.
Referenced by eac::gagr_fkcentroid().
getDistGKA()
template<typename T_REAL > std::vector< T_REAL > prob::getDistGKA (const std::vector< T_REAL > & aivector_randVar, const T_REAL airt_cm)
GKA Probability Distribution [26].
Obtains a probability distribution based on the Euclidean distance for the gene mutation
Parameters
aivector_randVar a vector with the values of a random variable
airt_cm a constant usually
Definition at line 411 of file probability_distribution.hpp.
References interfacesse::axpy(), inout::containerprint(), interfacesse::scal(), and interfacesse::sum().
Referenced by gaintegerop::mutationgka().
getElitistPairCross()
std::pair< uintidx, uintidx > prob::getElitistPairCross (std::vector< uintidx > * aoptvectoruintidx_chromPairsCross, uintidx aiuintidx_idxChromTMinIdxSelect, uintidx aiuintidx_idxChromTMaxIdxSelect)
Selection a pair random index.
Parameters
aoptvectoruintidx_chromPairsCross a std::vector<uintidx>
aiuintidx_idxChromTMinIdxSelect a unsigned integer
aiuintidx_idxChromTMaxIdxSelect a unsigned integer [17]
Definition at line 423 of file probability_selection.hpp.
Referenced by eac::cbga_fkcentroid().
getIdxPairUnlikeRoulette()
template<typename T_PROBABILITY > std::pair< uintidx, uintidx > prob::getIdxPairUnlikeRoulette (const std::vector< T_PROBABILITY > & aivectorrt_probDist, uintidx aiuintidx_begins)
Selection a pair random index in [IdxBegin,n].
Selection a pair random index proportional to its probability dstribution by aivectorrt_probDist
Parameters
aivectorrt_probDist a acumulate probability dstribution in [0,1]
aiuintidx_begins a unsigned integer where begin number to selected
 const std::vector<T_REAL>&& lvectorprob_selectBySizeClusterK =
  prob::makeDistRouletteWheel
  (lvectorrt_numInstClusterK.begin(),lvectorrt_numInstClusterK.end(),
   [](const uintidx& lui_numInstClusterK) -> T_REAL
   {
     return T_REAL(1.0) / T_REAL(lui_numInstClusterK);
   }
   );
std::pair<uintidx,uintidx> lpair_mergeIdxK =
  prob::getIdxPairUnlikeRoulette
  (lvectorprob_selectBySizeClusterK,
   uintidx(0)
   );
Definition at line 64 of file probability_selection.hpp.
References gaselect::getIdxRouletteWheel().
Referenced by gaclusteringop::mergeMutation().
getIdxVectorRoulette()
template<typename T_PROBABILITY , typename FUNCTION_RAND > std::vector< uintidx > prob::getIdxVectorRoulette (const std::vector< T_PROBABILITY > & aivectort_probDist, const bool aib_withRepeatedValues, const uintidx aiuintidx_numbersToGenerate, const uintidx aiuintidx_begins, FUNCTION_RAND function_rand01)
Selection a vector of random index in [IdxBegin,n].
Selection a vector of random index proportional to its probability dstribution by aivectorrt_probDist
Parameters
aivectort_probDist a const std::vector
aib_withRepeatedValues a bool if is false get get with repeated values
aiuintidx_numbersToGenerate a unsigned integer with numbers of items
aiuintidx_begins a unsigned integer where begin number to selected
function_rand01 a random distribution function in [0,1]
Definition at line 101 of file probability_selection.hpp.
References gaselect::getIdxRouletteWheel().
getRandPairUnlike()
template<typename FUNCTION > auto prob::getRandPairUnlike (FUNCTION function_generate) -> std::pair<decltype(function_generate()),decltype(function_generate())>
Get two random number diferent.
Parameters
function_generate a random distribution function
Definition at line 168 of file probability_selection.hpp.
Referenced by eac::gca_fkmedoid(), and eac::gga_vklabel().
getRandPairUnlikeInOrd()
template<typename FUNCTION > auto prob::getRandPairUnlikeInOrd (FUNCTION function_generate) -> std::pair<decltype(function_generate()),decltype(function_generate())>
Get two random number diferent in order.
Parameters
function_generate a random distribution function
Definition at line 190 of file probability_selection.hpp.
References interfacesse::swap().
Referenced by gaclusteringop::mergeCrossover(), and gabinaryop::onePointDistCrossover().
getRandSetUnlike()
template<typename T_RAND , typename FUNCTION > T_RAND prob::getRandSetUnlike (const std::unordered_set< T_RAND > & aiunorderedset_rand, FUNCTION function_generate)
Selection a random un like to set items.
this function is used for implementate a point mutation operator, D_PM [30]
Parameters
aiunorderedset_rand IN a std::unordered_set
function_generate a random distribution function
for (auto lchromfixleng_iter :lvectorchromfixleng_population) {
      if ( uniformdis_real01(gmt19937_eng)
           < aiipcgapc_inParamGALucasius.getProbMutation() )
        {
          std::unordered_set<uintidx> lunorderedset_medoids
            (lchromfixleng_iter->begin(),
             lchromfixleng_iter->end()
             );
          uintidx luintidx_medoidRand =
            prob::getRandSetUnlike
            (lunorderedset_medoids,
             [&]()
             {
         return uniformdis_idxInstance(gmt19937_eng);
             }
             );
          uintidx lui_positionGene = uniformdis_uiMutation0N(gmt19937_eng);
          lchromfixleng_iter->setGene(lui_positionGene,luintidx_medoidRand);
        }
    }
}
Definition at line 374 of file probability_selection.hpp.
Referenced by gaintegerop::mutationD_PM().
getRandUnlike()
template<typename T_RAND , typename FUNCTION > auto prob::getRandUnlike (const T_RAND at_unlike, FUNCTION function_generate) -> decltype(function_generate())
A random different than a given at_unlike.
Parameters
at_unlike a number
function_generate a random distribution function
// 3.7 Island migration
std::uniform_int_distribution<uintidx> uniformdis_ui0NumIsland
(0, aiinparam_GAProbAdapRangeK.getNumIsland()-1);
for (uintidx lui_l = 0; lui_l < lvectorchrom_bestIsland.size(); lui_l++) {
   if ( uniformdis_real01(gmt19937_eng) < aiinparam_GAProbAdapRangeK.getPe() ) {
      //2. Randomly choose the island toward each individual
      //  will migrate.
      uintidx lui_islandToward =
        prob::getRandUnlike
        (lui_l,
         [&]()
         {
           return uniformdis_ui0NumIsland(gmt19937_eng);
         }
         );
      std::vector<ChromAgustin2012<T_CLUSTERIDX,T_REAL>* >*
        lvectorchrom_subpopulation = lvectorvector_subPopulation.at(lui_islandToward);
      //3. Randomly choose an individual in the destiny island
      //  and change it by the migrating individual.
      uintidx lui_idxIndividual =
        uniformdis_ui0SubPopSize(gmt19937_eng);
       *lvectorchrom_subpopulation->at(lui_idxIndividual) =
         *lvectorchrom_bestIsland[lui_l];
   }
}
[1]
Definition at line 317 of file probability_selection.hpp.
Referenced by gabinaryop::bitMutation(), and eac::gga_vklabel().
getWithoutRepeatsSet()
template<typename FUNCTION > auto prob::getWithoutRepeatsSet (const uintidx aiuintidx_numbersToGenerate, FUNCTION function_generate) -> std::unordered_set<decltype(function_generate())>
Get a set of random number diferent.
Parameters
aiuintidx_numbersToGenerate a unsigned integer with numbers to Generate
function_generate a random distribution function
Definition at line 215 of file probability_selection.hpp.
References inout::containerprint().
Referenced by eac::clustering_genetic(), gaclusteringop::crossoverCGA(), eac::gca_fkmedoid(), eac::hka_fkmedoid(), clusteringop::randomInitialize(), and eac::tgca_vkcentroid().
linearNormalization() [1/2]
template<typename INPUT_ITERATOR , typename FITNESSFUNCTGET , typename FITNESSFUNCTSET > void prob::linearNormalization (INPUT_ITERATOR aiiterator_first, const INPUT_ITERATOR aiiterator_last, const FITNESSFUNCTGET fitness_funcGet, const FITNESSFUNCTSET fitness_funcSet, const decltype(fitness_funcGet(*aiiterator_first)) lrt_scale = 1.0)
Linear normalization.
Parameters
aiiterator_first a Iterator vector
aiiterator_last a Iterator vector
fitness_funcGet a Fitness funtion get
fitness_funcSet a Fitness funtion a set
lrt_scale a scaling factor the value by default is 1.0
prob::linearNormalization
  (lvectorchrom_population.begin(),
  lvectorchrom_population.end(),
  [](const ChromosomeFEAC<T_CLUSTERIDX,T_REAL,T_FEATURE,T_INSTANCES_CLUSTER_K>
  &lchromfeac_iter) -> T_REAL
  {
      return lchromfeac_iter.getObjetiveFunc();
  },
  [](ChromosomeFEAC<T_CLUSTERIDX,T_REAL,T_FEATURE,T_INSTANCES_CLUSTER_K>
  &lchromfeac_iter, T_REAL airt_funcFitnessLineal)
  {
      lchromfeac_iter.setFitness(airt_funcFitnessLineal);
  },
  T_REAL(1.0)
 );
Definition at line 199 of file probability_distribution.hpp.
References inout::containerprint().
Referenced by eac::cga_vklabel(), eac::feca_vklabel(), eac::gga_vklabel(), gaclusteringop::MO1(), and gaclusteringop::MO2().
linearNormalization() [2/2]
template<typename INPUT_ITERATOR , typename FITNESSOPERATION > auto prob::linearNormalization (INPUT_ITERATOR aiiterator_first, const INPUT_ITERATOR aiiterator_last, const FITNESSOPERATION fitness_func, const decltype(fitness_func(*aiiterator_first)) lrt_scale = 1.0) -> std::vector<decltype(fitness_func(*aiiterator_first))>
The values of the variable store in a container are normalized according to a linear normalization procedure [2]
Parameters
aiiterator_first a INPUT_ITERATOR
aiiterator_last a INPUT_ITERATOR
fitness_func a fintness function
lrt_scale a number scale default 1.0
std::vector<T_REAL>&& lvectorT_partialFcCLinearNorm =
linearNormalization
(lvectorrt_genotypePartialFcC.begin(),
 lvectorrt_genotypePartialFcC.end(),
 [](const T_REAL& lt_metrici) -> T_REAL
 {
   return lt_metrici;
 }
);
Definition at line 314 of file probability_distribution.hpp.
References inout::containerprint().
makeDistRouletteWheel()
template<typename INPUT_ITERATOR , typename FITNESSOPERATION > auto prob::makeDistRouletteWheel (INPUT_ITERATOR aiiterator_instfirst, INPUT_ITERATOR aiiterator_instlast, const FITNESSOPERATION fitness_func) -> std::vector<decltype(fitness_func(*aiiterator_instfirst))>
Parameters
aiiterator_instfirst
aiiterator_instlast
fitness_func
const std::vector<T_REAL>&& lvectorT_probDistRouletteWheel =
prob::makeDistRouletteWheel
  (lvectorchromfixleng_population.begin(),
   lvectorchromfixleng_population.end(),
   [](const gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL>* lchromfixleng_iter) -> T_REAL
   {
       return lchromfixleng_iter->getFitness();
   }
  );
Definition at line 71 of file probability_distribution.hpp.
References inout::containerprint(), interfacesse::copya(), inout::li_i, interfacesse::scal(), and interfacesse::sum().
Referenced by eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::igka_fklabel(), eac::kga_fkcentroid(), gaclusteringop::mergeMutation(), gaclusteringop::MO1(), gaclusteringop::MO2(), gaclusteringop::splittingMutation(), and eac::tgca_vkcentroid().