Library Evolutionary Algorithms for Clustering (LEAC): runtime Namespace Reference
runtime Namespace Reference
Module for obtaining run-time statistics.
Classes
class IntervalPositiveInteger
Interval of positive integer.
class ListRuntimeFunction
ListRuntimeFunction store metrics in run time and count genetations.
class RuntimeFunction
Function store metrics in run time.
class RuntimeFunctionStat
Function statistical for metrics in run time.
class RuntimeFunctionValue
Function store metrics in run time.
Typedefs
typedef double ExecutionTime
Functions
ExecutionTime initialize ()
ExecutionTime start ()
void stop (ExecutionTime &aoexetime_time)
ExecutionTime elapsedTime (const ExecutionTime &aoexetime_time)
ExecutionTime getTime (ExecutionTime &aoexetime_time)
template<typename T_INTEGERDOMAIN >
std::ostream & operator<< (std::ostream &out, const ListRuntimeFunction< T_INTEGERDOMAIN > &ailfhT_listFuntionHist)
template<typename T_METRIC , typename T_CLUSTERIDX >
void plot_funtionHist (runtime::ListRuntimeFunction< COMMON_IDOMAIN > &ailfhT_listFuntionHist, const inout::InParamClustering &aiipc_inParamClustering, inout::OutParamClustering< T_METRIC, T_CLUSTERIDX > &aiopcT_outParamClustering)
std::ostream & operator<< (std::ostream &os, const RuntimeFunction &airtf_runtimefunction)
template<class T_VALUE >
void functionhiststat_evaluateAll (RuntimeFunctionStat< T_VALUE > *aofhs_statObjectiveFunc[], std::vector< T_VALUE > &aivectorT_data)
Calculate statistical for metrics in run time.
Variables
const char * statistical_name [] = {"Min", "Max", "Avg", "Sum", "Var", "StdD"}
Detailed Description
Module for obtaining run-time statistics.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Typedef Documentation
ExecutionTime
typedef double runtime::ExecutionTime
ExecutionTime variable for count execution time.
Definition at line 30 of file execution_time.hpp.
Function Documentation
elapsedTime()
ExecutionTime runtime::elapsedTime (const ExecutionTime & aoexetime_time) inline
Definition at line 47 of file execution_time.hpp.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
functionhiststat_evaluateAll()
template<class T_VALUE > void runtime::functionhiststat_evaluateAll (RuntimeFunctionStat< T_VALUE > * aofhs_statObjectiveFunc[], std::vector< T_VALUE > & aivectorT_data)
Calculate statistical for metrics in run time.
Parameters
aofhs_statObjectiveFunc a array of RuntimeFunctionStat<T_VALUE>
aivectorT_data a std::vector<T_VALUE>
Definition at line 127 of file runtime_statistic.hpp.
References runtime::RuntimeFunctionValue< T_VALUE >::setValue(), STATISTICAL_AVERAGE, STATISTICAL_MAXIMUM, STATISTICAL_MINIMUM, STATISTICAL_STD_DEVIATION, STATISTICAL_SUM, and STATISTICAL_VARIANCE.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
getTime()
ExecutionTime runtime::getTime (ExecutionTime & aoexetime_time) inline
Definition at line 52 of file execution_time.hpp.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_vksubclusterbinary(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
initialize()
ExecutionTime runtime::initialize () inline
Definition at line 32 of file execution_time.hpp.
operator<<() [1/2]
std::ostream& runtime::operator<< (std::ostream & os, const RuntimeFunction & airtf_runtimefunction)
Definition at line 79 of file runtime_function.hpp.
References runtime::RuntimeFunction::print().
operator<<() [2/2]
template<typename T_INTEGERDOMAIN > std::ostream& runtime::operator<< (std::ostream & out, const ListRuntimeFunction< T_INTEGERDOMAIN > & ailfhT_listFuntionHist)
Definition at line 164 of file list_runtime_function.hpp.
References runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::_vector_ptRuntimeFunction, runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getDomainUpperBound(), and runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getPlotStatSeparator().
plot_funtionHist()
template<typename T_METRIC , typename T_CLUSTERIDX > void runtime::plot_funtionHist (runtime::ListRuntimeFunction< COMMON_IDOMAIN > & ailfhT_listFuntionHist, const inout::InParamClustering & aiipc_inParamClustering, inout::OutParamClustering< T_METRIC, T_CLUSTERIDX > & aiopcT_outParamClustering)
Definition at line 48 of file plot_runtime_function.hpp.
References inout::InParamClustering::getFileNamePlotStatObjetiveFunc(), inout::InParamAlgorithmo::getGnuPlotCoreStyles(), and inout::InParamAlgorithmo::getTimesRunAlgorithm().
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
start()
ExecutionTime runtime::start () inline
Definition at line 37 of file execution_time.hpp.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_vksubclusterbinary(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
stop()
void runtime::stop (ExecutionTime & aoexetime_time) inline
Definition at line 42 of file execution_time.hpp.
Referenced by eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_vksubclusterbinary(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), eac::gga_vklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), eac::kga_fkcentroid(), and eac::tgca_vkcentroid().
Variable Documentation
statistical_name
const char* runtime::statistical_name[] = {"Min", "Max", "Avg", "Sum", "Var", "StdD"}
Definition at line 39 of file runtime_statistic.hpp.