Library Evolutionary Algorithms for Clustering (LEAC): stats Namespace Reference
stats Namespace Reference
Model for transforming the data structure of the instances.
Functions
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_FEATURE_NUM >
void meanVector (T_FEATURE *aoarrayt_mean, const T_FEATURE_NUM ait_feactureNum, const T_FEATURE_SUM *aiarrayt_feactureSum, const uintidx aiu_idxVector=0)
￼Calculate average of a vector
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE >
void sumFeactures (T_FEATURE_SUM *aoarrayt_sumFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_FEATURE ait_initialValue)
Add the instances by attributes.
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE , typename FUNCTIONFREQ >
uintidx sumFeacturesFreq (T_FEATURE_SUM *aoarrayt_sumFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_FEATURE ait_initialValue, const FUNCTIONFREQ func_freq)
Add the instances with frequency by attributes.
template<typename T_FEATURE , typename T_FEATURE_SUM >
std::vector< T_FEATURE > meanRow (const mat::MatrixRow< T_FEATURE > &aimatrixrowt_instances)
Obtiene un vector con la media de una matriz por columnas.
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE >
void sumFeacturesSQ (T_FEATURE_SUM *aoarrayt_sumFeacturesSQ, T_FEATURE *aiarrayt_meanFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Gets the sum of the difference of the instances with the mean and the result square.
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE , typename FUNCTIONFREQ >
void sumFeacturesFreqSQ (T_FEATURE_SUM *aoarrayt_sumFeacturesSQ, T_FEATURE *aiarrayt_meanFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const FUNCTIONFREQ func_freq)
Gets the sum of the difference of the instances with the mean and the result square. For instances frequently.
template<typename T_FEATURE >
void varTodesvstd (T_FEATURE *aioarrayt_varTodesvstd)
Obtain the standard deviation given the variance.
template<typename INPUT_ITERATOR , typename T_FEATURE >
void minFeatures (T_FEATURE *aoarrayt_minFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Obtain the minimum attributes of the instances.
template<typename INPUT_ITERATOR , typename T_FEATURE >
void maxFeatures (T_FEATURE *aoarrayt_maxFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Obtain the maximum attributes of the instances.
template<typename INPUT_ITERATOR >
auto matrixVarcovar (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow< decltype((*aiiterator_instfirst) ->getAttribute(0))>
Get covariance matrix, only for T_FEATURE real.
template<typename T_FEATURE >
mat::MatrixRow< T_FEATURE > getMatrixDiagonal (T_FEATURE *aiarrayt_varianceFeactures)
Get weight matrix diagonal for calculate dist induced [8] [6] [7].
template<typename INPUT_ITERATOR >
auto getMatrixMahalonobis (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow< decltype((*aiiterator_instfirst) ->getAttribute(0))>
Get weight matrix Mahalonobis for calculate dist induced [8] [6] [7].
template<typename INPUT_ITERATOR , typename T_FEATURE >
void transform (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const mat::MatrixRow< T_FEATURE > &aimatrixrow_transform)
Make a transformation to the instances.
template<typename T_IDX , typename T >
void rank (std::vector< std::pair< T_IDX, T > > &aiovectorpair_rank)
Detailed Description
Model for transforming the data structure of the instances.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
getMatrixDiagonal()
template<typename T_FEATURE > mat::MatrixRow< T_FEATURE > stats::getMatrixDiagonal (T_FEATURE * aiarrayt_varianceFeactures)
Get weight matrix diagonal for calculate dist induced [8] [6] [7].
Parameters
aiarrayt_varianceFeactures a array with variance feactures
Definition at line 842 of file stats_instances.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::initialize(), and mat::MatrixRow< T_FEATURE >::print().
getMatrixMahalonobis()
template<typename INPUT_ITERATOR > mat::MatrixRow< T_FEATURE > stats::getMatrixMahalonobis (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow<decltype((*aiiterator_instfirst)->getAttribute(0))>
Get weight matrix Mahalonobis for calculate dist induced [8] [6] [7].
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
Definition at line 904 of file stats_instances.hpp.
References mat::inverse(), and matrixVarcovar().
Referenced by main().
matrixVarcovar()
template<typename INPUT_ITERATOR > mat::MatrixRow< T_FEATURE > stats::matrixVarcovar (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> mat::MatrixRow<decltype((*aiiterator_instfirst)->getAttribute(0))>
Get covariance matrix, only for T_FEATURE real.
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
Definition at line 752 of file stats_instances.hpp.
References mat::CblasNoTrans, mat::CblasTrans, interfacesse::gemm(), meanRow(), data::toMatrixRowTrans(), and interfacesse::transy().
Referenced by getMatrixMahalonobis().
maxFeatures()
template<typename INPUT_ITERATOR , typename T_FEATURE > void stats::maxFeatures (T_FEATURE * aoarrayt_maxFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Obtain the maximum attributes of the instances.
Parameters
aoarrayt_maxFeactures an output vector with the maximum attributes
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
Definition at line 681 of file stats_instances.hpp.
References inout::containerprint(), interfacesse::copy(), data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by eac::gagr_fkcentroid(), eac::kga_fkcentroid(), main(), and eac::tgca_vkcentroid().
meanRow()
template<typename T_FEATURE , typename T_FEATURE_SUM > std::vector< T_FEATURE > stats::meanRow (const mat::MatrixRow< T_FEATURE > & aimatrixrowt_instances)
Obtiene un vector con la media de una matriz por columnas.
Get a vector with the mean of one matrix per row
Parameters
aimatrixrowt_instances a matrix with the data to average
Returns
vector with the mean by row
Definition at line 310 of file stats_instances.hpp.
References inout::containerprint(), DATATYPE_REAL, mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and interfacesse::sum().
Referenced by mat::getMatrixTransformPCA(), and matrixVarcovar().
meanVector()
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_FEATURE_NUM > void stats::meanVector (T_FEATURE * aoarrayt_mean, const T_FEATURE_NUM ait_feactureNum, const T_FEATURE_SUM * aiarrayt_feactureSum, const uintidx aiu_idxVector = 0)
￼Calculate average of a vector
For a sum of feactures, calculate the average
Parameters
aoarrayt_mean an array to store the average result
ait_feactureNum an integer with the number of feactures
aiarrayt_feactureSum an array with the sum of feactures
aiu_idxVector an identifier of the vector number, for control
Definition at line 55 of file stats_instances.hpp.
References interfacesse::axpyInv(), inout::containerprint(), and interfacesse::copya().
Referenced by clusteringop::fillEmptyPartitions(), clusteringop::getCentroids(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::incrementalUpdate(), um::indexI(), um::indexIreeval(), main(), clusteringop::meanCentroids(), um::scoreFunction(), um::scoreFunctionreeval(), um::ssbreeval(), um::VRC(), um::VRCreeval(), um::WBIndex(), and um::WBIndexreeval().
minFeatures()
template<typename INPUT_ITERATOR , typename T_FEATURE > void stats::minFeatures (T_FEATURE * aoarrayt_minFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Obtain the minimum attributes of the instances.
Parameters
aoarrayt_minFeactures an output vector with the minimum attributes
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
Definition at line 608 of file stats_instances.hpp.
References inout::containerprint(), interfacesse::copy(), data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by eac::gagr_fkcentroid(), eac::kga_fkcentroid(), main(), and eac::tgca_vkcentroid().
rank()
template<typename T_IDX , typename T > void stats::rank (std::vector< std::pair< T_IDX, T > > & aiovectorpair_rank)
Definition at line 1038 of file stats_instances.hpp.
Referenced by main().
sumFeactures()
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE > void stats::sumFeactures (T_FEATURE_SUM * aoarrayt_sumFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_FEATURE ait_initialValue)
Add the instances by attributes.
Parameters
aoarrayt_sumFeactures an output vector with the sum of the instances
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
ait_initialValue value with which the output vector is initialized
Definition at line 141 of file stats_instances.hpp.
References interfacesse::axpy(), inout::containerprint(), interfacesse::copya(), data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by um::indexI(), um::indexIreeval(), main(), um::scoreFunction(), um::scoreFunctionreeval(), um::ssbreeval(), um::VRC(), um::VRCreeval(), um::WBIndex(), and um::WBIndexreeval().
sumFeacturesFreq()
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE , typename FUNCTIONFREQ > uintidx stats::sumFeacturesFreq (T_FEATURE_SUM * aoarrayt_sumFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_FEATURE ait_initialValue, const FUNCTIONFREQ func_freq)
Add the instances with frequency by attributes.
Parameters
aoarrayt_sumFeactures an output vector with the sum of the instances
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
ait_initialValue value with which the output vector is initialized
func_freq a function that gets the frequency of the instance that is adding up
Definition at line 221 of file stats_instances.hpp.
References interfacesse::axpy(), inout::containerprint(), interfacesse::copya(), DATATYPE_CENTROIDS_ROUND, data::Instance< T_FEATURE >::getFeatures(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by main().
sumFeacturesFreqSQ()
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE , typename FUNCTIONFREQ > void stats::sumFeacturesFreqSQ (T_FEATURE_SUM * aoarrayt_sumFeacturesSQ, T_FEATURE * aiarrayt_meanFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const FUNCTIONFREQ func_freq)
Gets the sum of the difference of the instances with the mean and the result square. For instances frequently.
Parameters
aoarrayt_sumFeacturesSQ an output vector with the sum
aiarrayt_meanFeactures an input vector with the mean of the instances
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
func_freq a function that gets the frequency of the instance that is adding up
Definition at line 464 of file stats_instances.hpp.
References inout::containerprint(), interfacesse::copya(), and data::Instance< T_FEATURE >::getFeatures().
Referenced by main().
sumFeacturesSQ()
template<typename INPUT_ITERATOR , typename T_FEATURE_SUM , typename T_FEATURE > void stats::sumFeacturesSQ (T_FEATURE_SUM * aoarrayt_sumFeacturesSQ, T_FEATURE * aiarrayt_meanFeactures, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Gets the sum of the difference of the instances with the mean and the result square.
Parameters
aoarrayt_sumFeacturesSQ an output vector with the sum
aiarrayt_meanFeactures an input vector with the mean of the instances
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
Definition at line 388 of file stats_instances.hpp.
References inout::containerprint(), interfacesse::copya(), and data::Instance< T_FEATURE >::getFeatures().
Referenced by main().
transform()
template<typename INPUT_ITERATOR , typename T_FEATURE > void stats::transform (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const mat::MatrixRow< T_FEATURE > & aimatrixrow_transform)
Make a transformation to the instances.
void transform (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const mat::MatrixRow<T_FEATURE> &aimatrixrow_transform)
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aimatrixrow_transform a transformation matrix
Definition at line 967 of file stats_instances.hpp.
References interfacesse::copy(), interfacesse::gemv(), and data::Instance< T_FEATURE >::getNumDimensions().
Referenced by varTodesvstd().
varTodesvstd()
template<typename T_FEATURE > void stats::varTodesvstd (T_FEATURE * aioarrayt_varTodesvstd)
Obtain the standard deviation given the variance.
Parameters
aioarrayt_varTodesvstd an input and output vector with the variances of the attributes of the instances
Definition at line 536 of file stats_instances.hpp.
References inout::containerprint(), DATATYPE_REAL, and transform().
Referenced by main().