Library Evolutionary Algorithms for Clustering (LEAC): gabinaryop Namespace Reference
gabinaryop Namespace Reference
Genetic binary operators.
Functions
template<typename T_BITSIZE , typename T_REAL , typename FUNCTION >
void initializeGenes (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarray_chrom, const FUNCTION function)
initialize genes where function evaluate to 1
template<typename T_BITSIZE >
void onePointDistCrossover (mat::BitMatrix< T_BITSIZE > &aobitmatrix_child1, mat::BitMatrix< T_BITSIZE > &aobitmatrix_child2, mat::BitMatrix< T_BITSIZE > &aibitmatrix_parent1, mat::BitMatrix< T_BITSIZE > &aibitmatrix_parent2)
template<typename T_BITSIZE , typename T_REAL >
void onePointCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarray_chromChild1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarray_chromChild2, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarray_chromParent1, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarray_chromParent2)
template<typename T_BITSIZE , typename T_REAL >
void onePointDistCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarraychrom_child1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarraychrom_child2, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarraychrom_parent1, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarraychrom_parent2)
One point distance crossover.
template<typename T_BITSIZE , typename T_REAL >
void uniformCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarraychrom_child1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aobitarraychrom_child2, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarraychrom_parent1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aibitarraychrom_parent2, const T_REAL airt_probCrossover)
Uniform crossover.
template<typename T_BITSIZE , typename T_CLUSTERIDX >
void bitMutation (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aiobitcrispmatrix_chrom)
template<typename T_BITSIZE , typename T_REAL >
void bitMutation (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aiobitarray_chrom)
Change one bit.
template<typename T_BITSIZE , typename T_REAL >
void eachBitArrayMutation (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > &aiobitarray_chrom, const T_REAL airt_probMutation)
Toggle bits.
Detailed Description
Genetic binary operators.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
bitMutation() [1/2]
template<typename T_BITSIZE , typename T_CLUSTERIDX > void gabinaryop::bitMutation (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aiobitcrispmatrix_chrom)
Definition at line 560 of file ga_binary_operator.hpp.
References mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::getMember(), mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumRows(), prob::getRandUnlike(), gmt19937_eng, mat::BitMatrix< T_BITSIZE >::print(), and mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember().
Referenced by eac::clustering_genetic(), eac::gaclustering_fkcrispmatrix(), and eac::gaclustering_vktreebinary().
bitMutation() [2/2]
template<typename T_BITSIZE , typename T_REAL > void gabinaryop::bitMutation (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aiobitarray_chrom) inline
Change one bit.
Consists of randomly choosing an element of a change the value 1 by 0 or 0 by 1.
Parameters
aiobitarray_chrom a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
for (auto&& liter_iChrom :lvectorchrom_population) {
  if ( uniformdis_real01(gmt19937_eng)
       <  aiinpcga_inParamGACasillas.getProbMutation() )
    {
      gabinaryop::bitArrayMutation(*liter_iChrom);
    }
}
Note
Use by [10]
Definition at line 649 of file ga_binary_operator.hpp.
References gmt19937_eng, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), mat::BitArray< T_BITSIZE >::size(), and ds::BitContainer< T_BITSIZE >::toggleBit().
eachBitArrayMutation()
template<typename T_BITSIZE , typename T_REAL > void gabinaryop::eachBitArrayMutation (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aiobitarray_chrom, const T_REAL airt_probMutation)
Toggle bits.
Each bit of each offspring chromosome mutates with a predefined probability (mutation rate airt_probMutation).
Parameters
aiobitarray_chrom a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
airt_probMutation a real number with mutation rate
for (auto lchrombitarray_iter: lvectorchrom_setO) {
   gabinaryop::eachBitArrayMutation
    (*lchrombitarray_iter,
     aiinpkkunchevabezdek_inParamGA.getProbMutation()
    );
}
Note
Use by [27]
Definition at line 710 of file ga_binary_operator.hpp.
References gmt19937_eng, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), mat::BitArray< T_BITSIZE >::size(), and ds::BitContainer< T_BITSIZE >::toggleBit().
Referenced by eac::gaprototypes_fkmedoid().
initializeGenes()
template<typename T_BITSIZE , typename T_REAL , typename FUNCTION > void gabinaryop::initializeGenes (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarray_chrom, const FUNCTION function)
initialize genes where function evaluate to 1
Parameters
aobitarray_chrom OUT a gaencode::ChromosomeBitArray
function IN evalute in {0,1} where value is 1 set gene to 1 other 0
for (auto lchrombitarray_iter: lvectorchrom_population) {
    gabinaryop::initializeGenes
      (*lchrombitarray_iter,
       [&]()
       {
         return (uniformdis_real01(gmt19937_eng) <= aiinpkkunchevabezdek_inParamGA.getPini());
       }
       );
 }
Definition at line 65 of file ga_binary_operator.hpp.
References ds::BitContainer< T_BITSIZE >::initialize(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), ds::BitContainer< T_BITSIZE >::setBit(), and mat::BitArray< T_BITSIZE >::size().
Referenced by eac::clustering_genetic(), eac::gaclustering_vktreebinary(), and eac::gaprototypes_fkmedoid().
onePointCrossover()
template<typename T_BITSIZE , typename T_REAL > void gabinaryop::onePointCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarray_chromChild1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarray_chromChild2, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarray_chromParent1, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarray_chromParent2)
Definition at line 257 of file ga_binary_operator.hpp.
References ds::BitContainer< T_BITSIZE >::copyAligned(), gmt19937_eng, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), and mat::BitArray< T_BITSIZE >::size().
Referenced by eac::gaclustering_vktreebinary().
onePointDistCrossover() [1/2]
template<typename T_BITSIZE > void gabinaryop::onePointDistCrossover (mat::BitMatrix< T_BITSIZE > & aobitmatrix_child1, mat::BitMatrix< T_BITSIZE > & aobitmatrix_child2, mat::BitMatrix< T_BITSIZE > & aibitmatrix_parent1, mat::BitMatrix< T_BITSIZE > & aibitmatrix_parent2)
Definition at line 143 of file ga_binary_operator.hpp.
References mat::BitMatrix< T_BITSIZE >::copyAligned(), mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumRows(), prob::getRandPairUnlikeInOrd(), gmt19937_eng, and mat::BitMatrix< T_BITSIZE >::print().
Referenced by eac::clustering_genetic(), and eac::gaclustering_fkcrispmatrix().
onePointDistCrossover() [2/2]
template<typename T_BITSIZE , typename T_REAL > void gabinaryop::onePointDistCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarraychrom_child1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarraychrom_child2, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarraychrom_parent1, const gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarraychrom_parent2)
One point distance crossover.
Parameters
aobitarraychrom_child1 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aobitarraychrom_child2 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aibitarraychrom_parent1 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aibitarraychrom_parent2 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
Note
Use by [38]
Definition at line 344 of file ga_binary_operator.hpp.
References ds::BitContainer< T_BITSIZE >::copyAligned(), prob::getRandPairUnlikeInOrd(), gmt19937_eng, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), and mat::BitArray< T_BITSIZE >::size().
uniformCrossover()
template<typename T_BITSIZE , typename T_REAL > void gabinaryop::uniformCrossover (gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarraychrom_child1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aobitarraychrom_child2, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarraychrom_parent1, gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > & aibitarraychrom_parent2, const T_REAL airt_probCrossover)
Uniform crossover.
The parent chromosomes swap their i-th bits with a certain probability, and i goes from 1 to n length chromosome.
Parameters
aobitarraychrom_child1 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aobitarraychrom_child2 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aibitarraychrom_parent1 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
aibitarraychrom_parent2 a gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>
airt_probCrossover a real number probability swap bits
gaiterator::crossoverRandSelect
  (lvectorchrom_matingPool.begin(),
   lvectorchrom_matingPool.end(),
   lvectorchrom_setO.begin(),
   lvectorchrom_setO.end(),
   [&](gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>* aichrom_parent1,
       gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>* aichrom_parent2,
       gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>* aochrom_child1,
       gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>* aochrom_child2
       )
   {
     gabinaryop::uniformCrossover
       (*lchrom_child1,
         *lchrom_child2,
         *aichrom_parent1,
         *aichrom_parent2,
        aiinpkkunchevabezdek_inParamGA.getProbCrossover()
        );
     aochrom_child1->setObjetiveFunc(std::numeric_limits<double>::max());
     aochrom_child2->setObjetiveFunc(std::numeric_limits<double>::max());
   }
   );
Note
Use by [27]
Definition at line 480 of file ga_binary_operator.hpp.
References ds::BitContainer< T_BITSIZE >::getBit(), gmt19937_eng, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), mat::BitArray< T_BITSIZE >::size(), and ds::BitContainer< T_BITSIZE >::toggleBit().
Referenced by eac::gaprototypes_fkmedoid().