Library Evolutionary Algorithms for Clustering (LEAC): eac Namespace Reference
eac Namespace Reference
Evolutionary Algorithms for Clustering.
Functions
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR >
void iterateGLAAux (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aochrom_cbga, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const int aii_numIteration, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
uintidx getCrossSetSizeAux (const int aii_opSelectMethod, const uintidx aist_populationSize)
Cross size.
uintidx getSurvivorsAux (int aii_opSelectMethod, uintidx aist_populationSize)
Get survivors.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR >
void changeOptimalityAux (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > &aochrom_cbga, gaencode::OptimalityCBGA aiooptimalitycbga_a, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
Change optimality.
template<typename T_FEATURE , typename T_REAL , typename T_INSTANCE_FREQUENCY , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > cbga_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, const inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY > &aiinParam_CBGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
CBGA [17].
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > cga_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamWithoutPcPmVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
CGA [19].
template<typename T_REAL , typename T_BITSIZE , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > clustering_genetic (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstBi, const T_REAL aitr_w, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamSubClusterBinVk, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist, const COMMON_IDOMAIN aii_numrunalg, const runtime::ExecutionTime aiet_executionTime)
template<typename T_BITSIZE , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR >
std::tuple< gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL >, mat::MatrixRow< T_FEATURE >, std::vector< T_INSTANCES_CLUSTER_K >, partition::PartitionDisjSets< T_CLUSTERIDX > > clustering_vksubclusterbinary (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamSubClusterBinVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > feca_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamFEAC, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
EAC, EAC I, EAC II, EAC III, EAC IV and FEAC.
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromosomeCrispMatrix< T_BITSIZE, T_CLUSTERIDX, T_REAL > gaclustering_fkcrispmatrix (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamWithoutPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > gaclustering_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinpcgaprobfixedk_inParamGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
std::pair< gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL >, std::vector< uintidx > > gaclustering_vktreebinary (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamGenWOChgVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
GA Clustering [10].
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_FEATURE, T_REAL > gagr_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, const inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamProbAdaptive, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL > gaprototypes_fkmedoid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamGAPrototypes, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_FEATURE, T_REAL > gas_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
GAS [32].
template<typename T_INSTANCEIDX , typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K >
gaencode::ChromFixedLength< T_INSTANCEIDX, T_REAL > gca_fkmedoid (inout::OutParamGAMedoid< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamGCA, const mat::MatrixTriang< T_REAL > &aimatrixtriagrt_dissimilarity)
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
mat::MatrixRow< T_FEATURE > gcuk_vkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamPcPmVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
GCUK [5].
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > gga_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamGGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
GGA [1].
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > gka_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
template<typename T_INSTANCEIDX , typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K >
gaencode::ChromFixedLength< T_INSTANCEIDX, T_REAL > hka_fkmedoid (inout::OutParamGAMedoid< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamHKA, mat::MatrixTriang< T_REAL > &aimatrixtriagrt_dissimilarity)
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K >
igka_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamPmFk, std::vector< data::Instance< T_FEATURE > * > &aivectorptinst_instances, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
IGKA [29] and FGKA [28].
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromFixedLength< T_FEATURE, T_REAL > kga_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
KGA [4].
template<typename CONTAINER_ITERINST , typename T_CLUSTERIDX , typename FUNCTION_GETATTRIBUTE >
auto tgca_getKSegments (const CONTAINER_ITERINST aiiterator_instfirst, const CONTAINER_ITERINST aiiterator_instlast, partition::PartitionDisjSets< T_CLUSTERIDX > &aipartitionDisjSets_clusters, FUNCTION_GETATTRIBUTE function_getAttribute) -> mat::MatrixRow< decltype(function_getAttribute(*aiiterator_instfirst))>
tgca_getKSegments [18]
template<typename T_METRIC , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
gaencode::ChromVariableLength< T_FEATURE, T_METRIC > tgca_vkcentroid (inout::OutParamGAC< T_METRIC, T_CLUSTERIDX > &aoop_outParamGAC, inout::InParamTGCA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > &aiinp_inParamTGCA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > &aifunc2p_dist)
TGCA [18].
Detailed Description
Evolutionary Algorithms for Clustering.
Implementation of evolutionary algorithms used to solve the clustering problem
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
cbga_fkcentroid()
template<typename T_FEATURE , typename T_REAL , typename T_INSTANCE_FREQUENCY , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, _INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > eac::cbga_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, const inout::InParamCBGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K, T_INSTANCE_FREQUENCY > & aiinParam_CBGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
CBGA [17].
Implementation of the CBGA algorithm based on [17].
Returns
A partition of a data set, encoded on a chromosome where each gene is the coordinate of a centroid or a codebook.
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinParam_CBGA a inout::InParamGAClusteringPcPmFk parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 477 of file cbga_fkcentroid.hpp.
References COMMON_COUT_PRECISION, gaclusteringop::crossPNNnew(), um::distortion(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), getCrossSetSizeAux(), prob::getElitistPairCross(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), data::Instance< T_FEATURE >::getNumDimensions(), getSurvivorsAux(), runtime::getTime(), gmt19937_eng, iterateGLAAux(), inout::li_i, measuare_undefObjetiveFunc, gaencode::OPT_NONE, OUTPARAMCLUSTERING_FITNESS_NaN, runtime::plot_funtionHist(), clusteringop::randomInitialize(), clusteringop::reassignCluster(), RUNTIMEFUNCTION_NOT_STORAGE, runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), interfacesse::sum(), and um::sumDistInstCentInK().
Referenced by main().
cga_vklabel()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > eac::cga_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamWithoutPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamWithoutPcPmVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
CGA [19].
Implementation of CGA algorithm based on [19].
Returns
A partition of a data set, encoded on a chromosome where each gene is the index of a cluster to which the instance belongs.
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamWithoutPcPmVk a inout::InParamWithoutPcPmVk parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 67 of file cga_vklabel.hpp.
References COMMON_COUT_PRECISION, gaclusteringop::crossoverCGA(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), dist::getMatrixDissimilarity(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), ds::getPartitionLinkedNumInst(), runtime::getTime(), gmt19937_eng, gagenericop::initializeGenes(), INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, inout::li_i, prob::linearNormalization(), prob::makeDistRouletteWheel(), measuare_lowerValueSilhouette, gaclusteringop::MO1(), gaclusteringop::MO2(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::silhouette(), runtime::start(), STATISTICAL_ALL_MEASURES, and runtime::stop().
Referenced by main().
changeOptimalityAux()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR > void eac::changeOptimalityAux (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aochrom_cbga, gaencode::OptimalityCBGA aiooptimalitycbga_a, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Change optimality.
Does a local search depending on the status of the chromosome
Parameters
aochrom_cbga a chromosome of type gaencode::ChromosomeCBGA
aiooptimalitycbga_a gaencode::OptimalityCBGA
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distance
Definition at line 175 of file cbga_fkcentroid.hpp.
References GENETICOPCLUSTER_MAX_GLA, iterateGLAAux(), gaencode::OPT_BOTH, gaencode::OPT_CB, gaencode::OPT_NONE, gaencode::OPT_PA, OPTIMALITY_CBGA_STRING, and clusteringop::reassignCluster().
Referenced by iterateGLAAux().
clustering_genetic()
template<typename T_REAL , typename T_BITSIZE , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL> eac::clustering_genetic (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstBi, const T_REAL aitr_w, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamSubClusterBinVk, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist, const COMMON_IDOMAIN aii_numrunalg, const runtime::ExecutionTime aiet_executionTime)
Definition at line 72 of file clustering_vksubclusterbinary.hpp.
References gabinaryop::bitMutation(), clusteringop::bkinCiToMemberShip(), COMMON_COUT_PRECISION, inout::containerprint(), um::Dinter(), um::Dintra(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), clusteringop::getClusters(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), mat::MatrixBase< T_FEATURE >::getNumRows(), prob::getWithoutRepeatsSet(), gmt19937_eng, gabinaryop::initializeGenes(), inout::li_i, prob::makeDistRouletteWheel(), gabinaryop::onePointDistCrossover(), runtime::plot_funtionHist(), mat::MatrixRow< T_FEATURE >::print(), RUNTIMEFUNCTION_NOT_STORAGE, runtime::RuntimeFunctionValue< T_VALUE >::setValue(), and STATISTICAL_ALL_MEASURES.
Referenced by clustering_vksubclusterbinary().
clustering_vksubclusterbinary()
template<typename T_BITSIZE , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR > std::tuple<gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL>, mat::MatrixRow<T_FEATURE>, std::vector<T_INSTANCES_CLUSTER_K>, partition::PartitionDisjSets<T_CLUSTERIDX> > eac::clustering_vksubclusterbinary (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamSubClusterBinaryVk< T_REAL, T_BITSIZE, T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamSubClusterBinVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 937 of file clustering_vksubclusterbinary.hpp.
References um::avgRadiusClusterK(), clustering_genetic(), COMMON_IDOMAIN, inout::containerprint(), um::D2(), clusteringop::getCentroids(), clusteringop::getClusters(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), partition::PartitionDisjSets< T_CLUSTERIDX >::getNumCluster(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), um::minDistCjCjp(), graph::nearestNeighbor(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), partition::PartitionDisjSets< T_CLUSTERIDX >::print(), runtime::start(), and runtime::stop().
Referenced by main().
feca_vklabel()
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > eac::feca_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamFEAC< T_FEATURE, T_REAL, T_CLUSTERIDX, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamFEAC, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
EAC, EAC I, EAC II, EAC III, EAC IV and FEAC.
Implementation of the EAC, EAC I, EAC II, EAC III, EAC IV and FEAC algorithm based on [21] and [2].
Returns
A partition of a data set, encoded on a chromosome with the membership labels of each instance and the centroids of the clusters.
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamFEAC a inout::InParamFEAC parameters required by the algorithm
aiiterator_instfirst an input iterator to the initial positions of the sequence of instances
aiiterator_instlast an input iterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 81 of file feac_vklabel.hpp.
References COMMON_COUT_PRECISION, runtime::elapsedTime(), gaencode::FEAC_OPERATOR_MO1, gaencode::FEAC_OPERATOR_MO2, runtime::functionhiststat_evaluateAll(), sm::getConfusionMatrix(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, gaclusteringop::kmeansfeac(), inout::li_i, prob::linearNormalization(), prob::makeDistRouletteWheel(), gaclusteringop::MO1(), gaclusteringop::MO2(), runtime::plot_funtionHist(), clusteringop::randomInitialize(), RUNTIMEFUNCTION_NOT_STORAGE, runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::simplifiedSilhouette(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and interfacesse::sum().
Referenced by main().
gaclustering_fkcrispmatrix()
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromosomeCrispMatrix<T_BITSIZE,T_CLUSTERIDX,T_REAL> eac::gaclustering_fkcrispmatrix (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamWithoutPcPmFk< T_CLUSTERIDX, T_BITSIZE, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamWithoutPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 69 of file gaclustering_fkcrispmatrix.hpp.
References gabinaryop::bitMutation(), COMMON_COUT_PRECISION, COMMON_VERBOSE_COUT_PRECISION, runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), sm::getConfusionMatrix(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getMisclassified(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), clusteringop::getPartition(), runtime::getTime(), um::j1(), inout::li_i, gabinaryop::onePointDistCrossover(), runtime::plot_funtionHist(), clusteringop::randomInitialize(), RUNTIMEFUNCTION_NOT_STORAGE, runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and data::toMatrixRow().
Referenced by main().
gaclustering_fklabel()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL> eac::gaclustering_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinpcgaprobfixedk_inParamGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 67 of file gaclustering_fklabel.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), COMMON_COUT_PRECISION, runtime::elapsedTime(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, gagenericop::initializeGenes(), gaintegerop::isNotValid(), inout::li_i, prob::makeDistRouletteWheel(), gaintegerop::mutation(), gagenericop::onePointCrossover(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSE(), runtime::start(), STATISTICAL_ALL_MEASURES, and runtime::stop().
Referenced by main().
gaclustering_vktreebinary()
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > std::pair< gaencode::ChromosomeBitArray< T_BITSIZE, T_REAL >, std::vector< uintidx > > eac::gaclustering_vktreebinary (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamGenWOChgVk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamGenWOChgVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
GA Clustering [10].
Implementation of GA algorithm based on [10].
Returns
A partition of a data set, encoded on a chromosome with n 1 binary genes and a minimum spanning Tree (MST) where each gene with value 0 means that this edge remains and 1 means that this edge is eliminated. The number of elements with value 1 represents the value of k 1.
Parameters
aoop_outParamGAC a inout::OutParamGAC
aiinp_inParamGenWOChgVk a inparam::InParamGenWOChgVk
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist a dist::Dist<T_REAL,T_FEATURE>
Definition at line 70 of file gaclustering_vktreebinary.hpp.
References gabinaryop::bitMutation(), COMMON_COUT_PRECISION, COMMON_IDOMAIN, graph::component(), DATATYPE_REAL, runtime::elapsedTime(), graph::fromPiToGraph(), runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaselect::getIdxRouletteWheel(), dist::getMatrixDissimilarity(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::increaseDomainUpperBound(), gabinaryop::initializeGenes(), INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, inout::li_i, prob::makeDistRouletteWheel(), measuare_undefVRC, gabinaryop::onePointCrossover(), runtime::plot_funtionHist(), graph::prim(), gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), mat::MatrixRow< T_FEATURE >::print(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), inout::vectorlistprint(), and um::VRC().
Referenced by main().
gagr_fkcentroid()
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromFixedLength<T_FEATURE,T_REAL> eac::gagr_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, const inout::InParamAdaptivePcPmFk< T_CLUSTERIDX, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamProbAdaptive, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 70 of file gagr_fkcentroid.hpp.
References prob::adaptiveProb(), gaclusteringop::biDirectionHMutation(), COMMON_COUT_PRECISION, runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gagenericop::GAGRdist(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), runtime::getTime(), gmt19937_eng, garealop::heuristicCrossover(), inout::li_i, prob::makeDistRouletteWheel(), gafuncobj::makeGAFuncObjSSE(), stats::maxFeatures(), stats::minFeatures(), gagenericop::pathCrossover(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), clusteringop::randomInitialize(), gaclusteringop::rearrangedCluster(), clusteringop::reassignCluster(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and clusteringop::updateCentroids().
Referenced by main().
gaprototypes_fkmedoid()
template<typename T_BITSIZE , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromosomeBitArray<T_BITSIZE,T_REAL> eac::gaprototypes_fkmedoid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamGAPrototypesFk< T_BITSIZE, T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamGAPrototypes, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 69 of file gaprototypes_fkmedoid.hpp.
References COMMON_COUT_PRECISION, gabinaryop::eachBitArrayMutation(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), data::Instance< T_FEATURE >::getNumDimensions(), clusteringop::getPartition(), runtime::getTime(), gmt19937_eng, clusteringop::initialize(), gabinaryop::initializeGenes(), um::j1(), inout::li_i, gaencode::ChromosomeBitArray< T_BITSIZE, T_METRIC >::print(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), data::toMatrixRow(), and gabinaryop::uniformCrossover().
Referenced by main().
gas_fkcentroid()
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromFixedLength< T_FEATURE, T_REAL > eac::gas_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
GAS [32].
Implementation of GAS algorithm based on [32].
Returns
A partition of a data set, encoded on a chromosome where each gene is the coordinate of a centroid. Base to following equation:
where , represents the medoid of cluster
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamPcPmFk a inout::InParamPcPmFk parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 70 of file gas_fkcentroid.hpp.
References COMMON_COUT_PRECISION, runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, inout::li_i, prob::makeDistRouletteWheel(), gagenericop::onePointCrossover(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), clusteringop::randomInitialize(), garealop::randomMutation(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSE(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and clusteringop::updateCentroids().
Referenced by main().
gca_fkmedoid()
template<typename T_INSTANCEIDX , typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > gaencode::ChromFixedLength<T_INSTANCEIDX,T_REAL> eac::gca_fkmedoid (inout::OutParamGAMedoid< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamGCA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamGCA, const mat::MatrixTriang< T_REAL > & aimatrixtriagrt_dissimilarity)
Definition at line 66 of file gca_fkmedoid.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), COMMON_COUT_PRECISION, interfacesse::copy(), runtime::elapsedTime(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), mat::MatrixTriang< T_FEATURE >::getNumRows(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), prob::getRandPairUnlike(), runtime::getTime(), prob::getWithoutRepeatsSet(), gmt19937_eng, inout::li_i, prob::makeDistRouletteWheel(), gaintegerop::mutationD_PM(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), gaintegerop::recombinationD_MX(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSEMedoid(), runtime::start(), STATISTICAL_ALL_MEASURES, and runtime::stop().
Referenced by main().
gcuk_vkcentroid()
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > mat::MatrixRow< T_FEATURE > eac::gcuk_vkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPcPmVk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamPcPmVk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
GCUK [5].
Implementation of the GCUK algorithm based on [5]. Which automatically finds K cluster using the DaviesBouldin index.
Returns
A partition of a data set, encoded on a chromosome where each gene is the coordinate of a centroid. Base to following equation:
where , represents the centroid of cluster
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamPcPmVk a inout::InParamPcPmVk parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 72 of file gcuk_vkcentroid.hpp.
References COMMON_COUT_PRECISION, um::dbindex(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), mat::MatrixWithRowNull< T_GENE >::getMatrix(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_GENE >::getNumRows(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, inout::li_i, prob::makeDistRouletteWheel(), partition::makePartition(), measuare_undefDBindex, gaclusteringop::onePointCrossover(), runtime::plot_funtionHist(), gaencode::ChromosomeMatrixWithRowNull< T_GENE, T_METRIC >::print(), clusteringop::randomInitialize(), gaclusteringop::randomMutation(), RUNTIMEFUNCTION_NOT_STORAGE, runtime::RuntimeFunctionValue< T_VALUE >::setValue(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and clusteringop::updateCentroids().
Referenced by main().
getCrossSetSizeAux()
uintidx eac::getCrossSetSizeAux (const int aii_opSelectMethod, const uintidx aist_populationSize)
Cross size.
Calculate the amount of chromosomes to crossover
Returns
an integer number with the number of individuals to cross
Parameters
aii_opSelectMethod type of selected method: GACLUSTERING_CBGA_SELECMETH_ROULETTE, GACLUSTERING_CBGA_SELECMETH_ELITIST1, GACLUSTERING_CBGA_SELECMETH_ZIGZAG or GACLUSTERING_CBGA_SELECMETH_ELITIST2
aist_populationSize an integer with the size of the population
Definition at line 92 of file cbga_fkcentroid.hpp.
References GACLUSTERING_CBGA_SELECMETH_ELITIST1, GACLUSTERING_CBGA_SELECMETH_ELITIST2, GACLUSTERING_CBGA_SELECMETH_ROULETTE, and GACLUSTERING_CBGA_SELECMETH_ZIGZAG.
Referenced by cbga_fkcentroid().
getSurvivorsAux()
uintidx eac::getSurvivorsAux (int aii_opSelectMethod, uintidx aist_populationSize)
Get survivors.
Calculate the number of selected individuals in an elitist manner
Parameters
aii_opSelectMethod type of selected method
aist_populationSize an integer with the size of the population
Definition at line 129 of file cbga_fkcentroid.hpp.
References GACLUSTERING_CBGA_SELECMETH_ELITIST1, GACLUSTERING_CBGA_SELECMETH_ELITIST2, GACLUSTERING_CBGA_SELECMETH_ROULETTE, and GACLUSTERING_CBGA_SELECMETH_ZIGZAG.
Referenced by cbga_fkcentroid().
gga_vklabel()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > gaencode::ChromosomeGGA< T_CLUSTERIDX, T_REAL > eac::gga_vklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamGGA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamGGA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
GGA [1].
Implementation of the GGA algorithm based on [1]. Which automatically finds K cluster using the Silhouette and DaviesBouldin index.
Returns
A partition of a data set, encoded on a chromosome where each gene is the index of a cluster to which the instance belongs.
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamGGA a inout::InParamGGA parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 73 of file gga_vklabel.hpp.
References assert_msg, um::avgRadiusClusterK(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::begin(), COMMON_COUT_PRECISION, inout::containerprint(), interfacesse::copya(), mat::MatrixRow< T_FEATURE >::copyRow(), um::dbindex(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::decrementGroupSecSize(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::deleteGroupNull(), runtime::elapsedTime(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::end(), runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getElementSize(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), dist::getMatrixDissimilarity(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::getNumClusterK(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), ds::getPartitionLinkedNumInst(), prob::getRandPairUnlike(), prob::getRandUnlike(), mat::MatrixRow< T_FEATURE >::getRow(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::getString(), runtime::getTime(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::getVectorNumInstClusterK(), gmt19937_eng, mat::MatrixRow< T_FEATURE >::initialize(), gagenericop::initializeGenes(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::initializeGroupSec(), INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::isValid(), gaintegerop::labelKeep(), inout::li_i, prob::linearNormalization(), prob::makeDistRouletteWheel(), measuare_lowerValueSilhouette, measuare_undefDBindex, gaclusteringop::mergeCrossover(), gaclusteringop::mergeMutation(), runtime::plot_funtionHist(), gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::print(), clusteringop::reassignCluster(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeGGA< T_CLUSTERIDX, T_METRIC >::setElementSize(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::silhouette(), gaclusteringop::splittingMutation(), runtime::start(), STATISTICAL_ALL_MEASURES, and runtime::stop().
Referenced by main().
gka_fklabel()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename INPUT_ITERATOR > gaencode::ChromFixedLength<T_CLUSTERIDX,T_REAL> eac::gka_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 67 of file gka_fklabel.hpp.
References COMMON_COUT_PRECISION, runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gmt19937_eng, gagenericop::initializeGenes(), inout::li_i, RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSE(), runtime::start(), and STATISTICAL_ALL_MEASURES.
Referenced by main().
hka_fkmedoid()
template<typename T_INSTANCEIDX , typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > gaencode::ChromFixedLength<T_INSTANCEIDX,T_REAL> eac::hka_fkmedoid (inout::OutParamGAMedoid< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamHKA< T_CLUSTERIDX, T_INSTANCEIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamHKA, mat::MatrixTriang< T_REAL > & aimatrixtriagrt_dissimilarity)
Definition at line 65 of file hka_fkmedoid.hpp.
References gaencode::ChromFixedLength< T_GENE, T_METRIC >::begin(), COMMON_COUT_PRECISION, interfacesse::copy(), runtime::elapsedTime(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::end(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), mat::MatrixTriang< T_FEATURE >::getNumRows(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), prob::getWithoutRepeatsSet(), gmt19937_eng, inout::li_i, gaintegerop::mutationD_PM(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), gaintegerop::recombinationD_MX(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSEMedoid(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), gaselect::tournament(), and clusteringop::updateMedoids().
Referenced by main().
igka_fklabel()
template<typename T_CLUSTERIDX , typename T_REAL , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K > gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > eac::igka_fklabel (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamPmFk, std::vector< data::Instance< T_FEATURE > * > & aivectorptinst_instances, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
IGKA [29] and FGKA [28].
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamPmFk a inout::InParamPmFk parameters required by the algorithm
aivectorptinst_instances a std::vector<data::Instance<T_FEATURE>* >
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 80 of file igka_fklabel.hpp.
References interfacesse::axpy(), COMMON_COUT_PRECISION, nearest::dist(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), clusteringop::getCentroids(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), runtime::getTime(), gmt19937_eng, gagenericop::initializeGenes(), clusteringop::kmeansoperator(), inout::li_i, prob::makeDistRouletteWheel(), clusteringop::meanCentroids(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::print(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeFGKA< T_CLUSTERIDX, T_METRIC >::setNumClusterK(), gaencode::ChromFixedLength< T_CLUSTERIDX, T_METRIC >::setStringSize(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSE(), runtime::start(), STATISTICAL_ALL_MEASURES, gaencode::ChromFixedLength< T_GENE, T_METRIC >::stcgetStringSize(), and runtime::stop().
Referenced by main().
iterateGLAAux()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_REAL , typename INPUT_ITERATOR > void eac::iterateGLAAux (gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL > & aochrom_cbga, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const int aii_numIteration, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Definition at line 283 of file cbga_fkcentroid.hpp.
References changeOptimalityAux(), clusteringop::fillEmptyPartitions(), clusteringop::meanCentroids(), gaencode::OPT_BOTH, gaencode::OPT_CB, gaencode::OPT_NONE, gaencode::OPT_PA, OPTIMALITY_CBGA_STRING, and clusteringop::reassignCluster().
Referenced by cbga_fkcentroid(), and changeOptimalityAux().
kga_fkcentroid()
template<typename T_FEATURE , typename T_REAL , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromFixedLength< T_FEATURE, T_REAL > eac::kga_fkcentroid (inout::OutParamGAC< T_REAL, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamPcPmFk< T_CLUSTERIDX, T_REAL, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamPcPmFk, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
KGA [4].
Implementation of the KGA algorithm based on [4].
Returns
A partition of a data set, encoded on a chromosome where each gene is the coordinate of a centroid. Base to following equation:
where , represents the centroid of cluster
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamPcPmFk a inout::InParamPcPmFk parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 72 of file kga_fkcentroid.hpp.
References gaclusteringop::biDirectionHMutation(), COMMON_COUT_PRECISION, runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::getString(), runtime::getTime(), gaencode::ChromosomeBase< T_METRIC >::getValidString(), gmt19937_eng, inout::li_i, prob::makeDistRouletteWheel(), stats::maxFeatures(), stats::minFeatures(), gagenericop::onePointCrossover(), runtime::plot_funtionHist(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), clusteringop::randomInitialize(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), gaencode::ChromFixedLength< T_GENE, T_METRIC >::setStringSize(), gaencode::ChromosomeBase< T_METRIC >::setValidString(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), um::SSE(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), and clusteringop::updateCentroids().
Referenced by main().
tgca_getKSegments()
template<typename CONTAINER_ITERINST , typename T_CLUSTERIDX , typename FUNCTION_GETATTRIBUTE > auto eac::tgca_getKSegments (const CONTAINER_ITERINST aiiterator_instfirst, const CONTAINER_ITERINST aiiterator_instlast, partition::PartitionDisjSets< T_CLUSTERIDX > & aipartitionDisjSets_clusters, FUNCTION_GETATTRIBUTE function_getAttribute) -> mat::MatrixRow<decltype(function_getAttribute(*aiiterator_instfirst))>
tgca_getKSegments [18]
The attribute with maximum range is partitioned into ki segments by hierarchical agglomerative clustering algorithm. Then initial values of cluster centers are produced through uniformly random selection in every segment.
Returns
the coordinate of a centroid.
Parameters
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aipartitionDisjSets_clusters a partition::PartitionDisjSets of the attribute with maximum range maximum ki segments is partitioned into by hierarchical agglomerative clustering algorithm.
function_getAttribute a function to obtain the attributes of an instance
Definition at line 72 of file tgca_vkcentroid.hpp.
Referenced by tgca_vkcentroid().
tgca_vkcentroid()
template<typename T_METRIC , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > gaencode::ChromVariableLength< T_FEATURE, T_METRIC > eac::tgca_vkcentroid (inout::OutParamGAC< T_METRIC, T_CLUSTERIDX > & aoop_outParamGAC, inout::InParamTGCA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K > & aiinp_inParamTGCA, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_METRIC, T_FEATURE > & aifunc2p_dist)
TGCA [18].
Implementation of the TGCA algorithm based on [18]. Which automatically finds K cluster using the Variance Ratio Criterion (VRC).
Returns
A partition of a data set, encoded on a chromosome where each gene is the coordinate of a centroid. Base to following equation:
where , represents the medoid of cluster
Parameters
aoop_outParamGAC a inout::OutParamGAC with the output parameters of the algorithm
aiinp_inParamTGCA a inout::InParamTGCA parameters required by the algorithm
aiiterator_instfirst an InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 176 of file tgca_vkcentroid.hpp.
References gaclusteringop::biDirectionMutation(), COMMON_COUT_PRECISION, COMMON_IDOMAIN, inout::containerprint(), mat::MatrixRow< T_FEATURE >::copyRow(), runtime::elapsedTime(), runtime::functionhiststat_evaluateAll(), data::Instance< T_FEATURE >::getAttribute(), clusteringop::getCentroids(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), runtime::ListRuntimeFunction< T_INTEGERDOMAIN >::getHeaderFuntions(), gaselect::getIdxRouletteWheel(), data::Instance< T_FEATURE >::getNumDimensions(), gaencode::ChromosomeBase< T_METRIC >::getObjetiveFunc(), mat::MatrixRow< T_FEATURE >::getRow(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getString(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::getStringSize(), runtime::getTime(), prob::getWithoutRepeatsSet(), gmt19937_eng, INPARAMCLUSTERING_DEFAULT_CLUSTERK_UNDEFINED, inout::li_i, prob::makeDistRouletteWheel(), partition::makePartition(), stats::maxFeatures(), measuare_undefObjetiveFunc, measuare_undefVRC, stats::minFeatures(), NEARESTCENTROID_UNKNOWN, gaclusteringop::newChromosome(), gagenericop::onePointCrossover(), vectorutils::partition(), runtime::plot_funtionHist(), clusteringop::pointerToDisjSets(), gaencode::ChromVariableLength< T_GENE, T_METRIC >::print(), mat::MatrixRow< T_FEATURE >::print(), clusteringop::reassignCluster(), RUNTIMEFUNCTION_NOT_STORAGE, gaencode::ChromosomeBase< T_METRIC >::setFitness(), gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc(), runtime::RuntimeFunctionValue< T_VALUE >::setValue(), clusteringop::slink(), clusteringop::sortLambda(), runtime::start(), STATISTICAL_ALL_MEASURES, runtime::stop(), tgca_getKSegments(), and um::VRC().
Referenced by main().