Library Evolutionary Algorithms for Clustering (LEAC): gaselect Namespace Reference
gaselect Namespace Reference
Chromosome selection method in genetic algorithms.
Functions
template<typename T_PROBABILITY , typename T_INTIDX >
T_INTIDX getIdxRouletteWheel (const std::vector< T_PROBABILITY > &aivectorrt_probDist, const T_INTIDX aiuintidx_begin)
Selection a random index in [IdxBegin,n].
template<typename INPUT_ITERATOR , typename FITNESSOPERATION >
INPUT_ITERATOR tournament (const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const uintidx aiuintidx_orderTournament, const FITNESSOPERATION fitness_func)
Detailed Description
Chromosome selection method in genetic algorithms.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
getIdxRouletteWheel()
template<typename T_PROBABILITY , typename T_INTIDX > T_INTIDX gaselect::getIdxRouletteWheel (const std::vector< T_PROBABILITY > & aivectorrt_probDist, const T_INTIDX aiuintidx_begin)
Selection a random index in [IdxBegin,n].
Selection a which is proportional to its probability dstribution by aivectorrt_probDist, utilizes for roulette wheel selection method
Parameters
aivectorrt_probDist a acumulate probability dstribution in [0,1]
aiuintidx_begin a unsigned integer index where begin index to select
//COPY POPULATION TO MATING POOL FOR ROULETTE WHEEL--------------------------
for (auto&& lchrom_iter: lvectorchrom_matingPool) {
   uintidx luiidx_chrom =
   gaselect::getIdxRouletteWheel
   (lvectorT_probDistRouletteWheel,
    uintidx(0)
   );
   lchrom_iter = lvectorchrom_population.at(luiidx_chrom);
}
Definition at line 63 of file ga_selection.hpp.
References gmt19937_eng.
Referenced by eac::cga_vklabel(), eac::clustering_genetic(), eac::feca_vklabel(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), prob::getIdxPairUnlikeRoulette(), prob::getIdxVectorRoulette(), eac::gga_vklabel(), eac::igka_fklabel(), eac::kga_fkcentroid(), gaclusteringop::MO1(), gaclusteringop::MO2(), gaintegerop::mutationgka(), and eac::tgca_vkcentroid().
tournament()
template<typename INPUT_ITERATOR , typename FITNESSOPERATION > INPUT_ITERATOR gaselect::tournament (const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const uintidx aiuintidx_orderTournament, const FITNESSOPERATION fitness_func)
Definition at line 145 of file ga_selection.hpp.
References gmt19937_eng, and inout::li_i.
Referenced by eac::hka_fkmedoid().