Library Evolutionary Algorithms for Clustering (LEAC): mat Namespace Reference
mat Namespace Reference
Matrix module and associated operations.
Classes
class BitArray
Bit array.
class BitMatrix
Bit matrix.
class CrispMatrix
Bit crisp matrix.
class MatrixBase
MatrixBase.
class MatrixResizableRow
MatrixResizableRow [17].
class MatrixRow
Matrix store items for row.
class MatrixTriang
MatrixTriang.
class MatrixWithRowNull
MatrixWithRowNull.
Typedefs
typedef enum mat::TRANSPOSE TRANSPOSE
Enumerations
enum TRANSPOSE { CblasNoTrans =111, CblasTrans =112, CblasConjTrans =113, CblasConjNoTrans =114 }
Functions
template<typename T_NUMBITON , typename T_BITSIZE >
void getRowsNumBitOn (std::vector< T_NUMBITON > &aovectort_numNumBitOn, BitMatrix< T_BITSIZE > &aibmatrix_w)
template<typename T_C , typename T_BITSIZE , typename T_B >
void mulRowsIColumns0N (T_C *aoarrayT_rowC, uintidx aiuintidx_idxBegin, uintidx aiuintidx_idxEnd, mat::BitArray< T_BITSIZE > &aibarray_rowA, MatrixRow< T_B > &aimatrixrowt_B)
mulRowsIColumns0N:
template<typename T_C , typename T_BITSIZE , typename T_B >
void bitgemm (MatrixRow< T_C > &aomatrixrowt_C, mat::BitMatrix< T_BITSIZE > &aibitmatrixT_A, MatrixRow< T_B > &aimatrixrowt_B)
bitgemm multiply a matrix of bits by another of real or integers
template<class T >
void r8mat_identity (int n, T a[])
template<class T >
void r8mat_diag_get_vector (int n, T a[], T v[])
template<class T >
T r8mat_is_eigen_right (int n, int k, T a[], T x[], T lambda[])
template<class T >
T r8mat_norm_fro (int m, int n, T a[])
template<class T >
void jacobi_eigenvalue (int n, T a[], int it_max, T v[], T d[], int &it_num, int &rot_num)
float lange (char aic_norm, mat::MatrixRow< float > &aimatrixt_a)
Calculates the norm of a matrix for float.
double lange (char aic_norm, mat::MatrixRow< double > &aimatrixt_a)
Calculates the norm of a matrix for double.
std::tuple< std::vector< float >, mat::MatrixRow< float > > syevd (const mat::MatrixRow< float > &aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
std::tuple< std::vector< double >, mat::MatrixRow< double > > syevd (const mat::MatrixRow< double > &aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
int inverse (mat::MatrixRow< double > &aiomatrix_a)
template<class T >
T lange (const char aic_norm, const mat::MatrixRow< T > &aimatrixt_a)
template<class T >
int getrf (mat::MatrixRow< T > &aiomatrix_a, uintidx *aovectorui_p)
template<class T >
std::tuple< std::vector< T >, mat::MatrixRow< T > > syevd (const mat::MatrixRow< T > &aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
template<class T >
int inverse (mat::MatrixRow< T > &aiomatrix_a)
Compute the inverse of a matrix.
template<class T_FEATURE >
MatrixRow< T_FEATURE > getIdentity (const uintidx aiui_dimension)
template<class T_FEATURE >
MatrixRow< T_FEATURE > getTranspose (MatrixRow< T_FEATURE > &aimatrix_B)
template<class T_FEATURE , class T_IDX >
MatrixRow< T_FEATURE > keepRows (const MatrixRow< T_FEATURE > &aimatrixT_b, std::vector< T_IDX > &aovectorT_idxRow)
template<class T_FEATURE >
int LUPdecompose (mat::MatrixRow< T_FEATURE > &aiomatrixrt_a, uintidx *aovectorui_p)
template<class T_FEATURE >
int LUPinverse (mat::MatrixRow< T_FEATURE > &aiomatrixrt_lu, uintidx *aivectorui_p)
template<class T_FEATURE >
mat::MatrixRow< T_FEATURE > matrixread_get (const std::string &aistr_matrix, const bool aib_homogeneousCoord=false)
template<typename T >
MatrixRow< T > translation (const std::vector< T > &aivector_translation)
template<typename T >
MatrixRow< T > scale (const std::vector< T > &aivector_scale)
template<typename T >
void point (MatrixRow< T > &aimatrixt_trans, T *aiarrayt_point, long int aili_idxCoordX, long int aili_idxCoordY, long int aili_idxCoordZ, FILE *aifile_outCoord)
template<typename T >
void point (MatrixRow< T > &aimatrixt_trans, T *aiarrayt_point, const char *aiastr_label, long int aili_idxCoordX, long int aili_idxCoordY, long int aili_idxCoordZ, FILE *aifile_outCoord)
template<typename INPUT_ITERATOR >
auto getMatrixTransformPCA (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> MatrixRow< decltype((*aiiterator_instfirst) ->getAttribute(0))>
Detailed Description
Matrix module and associated operations.
Implementation of the data type Matrix and operations, uses OpenBLAS when compiling with this option, otherwise functions that are not based in the Interface to Streaming SIMD Extensions (SSE).
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Typedef Documentation
TRANSPOSE
typedef enum mat::TRANSPOSE mat::TRANSPOSE
Enumeration Type Documentation
TRANSPOSE
enum mat::TRANSPOSE
Enumerator
CblasNoTrans
CblasTrans
CblasConjTrans
CblasConjNoTrans
Definition at line 25 of file common_interfacelapack.hpp.
Function Documentation
bitgemm()
template<typename T_C , typename T_BITSIZE , typename T_B > void mat::bitgemm (MatrixRow< T_C > & aomatrixrowt_C, mat::BitMatrix< T_BITSIZE > & aibitmatrixT_A, MatrixRow< T_B > & aimatrixrowt_B)
bitgemm multiply a matrix of bits by another of real or integers
Parameters
aomatrixrowt_C a The resulting matrix mat::MatrixRow<T_C>
aibitmatrixT_A a matrix of bits mat::BitMatrix
aimatrixrowt_B a matrix of integers or real MatrixRow<T_B>
Definition at line 91 of file bitmatrix_matrix_operator.hpp.
References mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::BitMatrix< T_BITSIZE >::getNumRows(), mat::BitMatrix< T_BITSIZE >::getRow(), mat::MatrixRow< T_FEATURE >::getRow(), mulRowsIColumns0N(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by clusteringop::getCentroids().
getIdentity()
template<class T_FEATURE > MatrixRow<T_FEATURE> mat::getIdentity (const uintidx aiui_dimension)
Definition at line 538 of file matrix.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::initialize(), inout::li_i, and mat::MatrixRow< T_FEATURE >::print().
Referenced by main().
getMatrixTransformPCA()
template<typename INPUT_ITERATOR > auto mat::getMatrixTransformPCA (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast) -> MatrixRow<decltype((*aiiterator_instfirst)->getAttribute(0))>
Definition at line 230 of file transformation.hpp.
References interfacesse::dot(), interfacesse::gemm(), getTranspose(), stats::meanRow(), interfacesse::scal(), scale(), syevd(), data::toMatrixRowTrans(), translation(), and interfacesse::transy().
Referenced by main().
getrf()
template<class T > int mat::getrf (mat::MatrixRow< T > & aiomatrix_a, uintidx * aovectorui_p)
Definition at line 144 of file matop_withoutopenblas.hpp.
References LUPdecompose().
getRowsNumBitOn()
template<typename T_NUMBITON , typename T_BITSIZE > void mat::getRowsNumBitOn (std::vector< T_NUMBITON > & aovectort_numNumBitOn, BitMatrix< T_BITSIZE > & aibmatrix_w)
Definition at line 551 of file bit_matrix.hpp.
References inout::containerprint(), and inout::li_i.
Referenced by clusteringop::getCentroids().
getTranspose()
template<class T_FEATURE > MatrixRow<T_FEATURE> mat::getTranspose (MatrixRow< T_FEATURE > & aimatrix_B)
Definition at line 578 of file matrix.hpp.
References interfacesse::copy(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), inout::li_i, mat::MatrixRow< T_FEATURE >::print(), and mat::MatrixRow< T_FEATURE >::toArray().
Referenced by getMatrixTransformPCA(), and syevd().
inverse() [1/2]
template<class T > int mat::inverse (mat::MatrixRow< T > & aiomatrix_a)
Compute the inverse of a matrix.
Compute the inverse of a matrix using the LU factorization
Parameters
aiomatrix_a a mat::MatrixRow to invest
Definition at line 232 of file matop_withoutopenblas.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), LUPdecompose(), and LUPinverse().
inverse() [2/2]
int mat::inverse (mat::MatrixRow< double > & aiomatrix_a)
Definition at line 262 of file matop_openblaslapacke.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::print(), and mat::MatrixRow< T_FEATURE >::toArray().
Referenced by stats::getMatrixMahalonobis().
jacobi_eigenvalue()
template<class T > void mat::jacobi_eigenvalue (int n, T a[], int it_max, T v[], T d[], int & it_num, int & rot_num)
Definition at line 298 of file jacobi_eigenvalue.hpp.
References inout::a, inout::c, inout::d, inout::l, inout::q, r8mat_diag_get_vector(), r8mat_identity(), and inout::v.
Referenced by syevd().
keepRows()
template<class T_FEATURE , class T_IDX > MatrixRow<T_FEATURE> mat::keepRows (const MatrixRow< T_FEATURE > & aimatrixT_b, std::vector< T_IDX > & aovectorT_idxRow)
Definition at line 634 of file matrix.hpp.
References mat::MatrixRow< T_FEATURE >::copyRow(), and mat::MatrixBase< T_FEATURE >::getNumColumns().
lange() [1/3]
float mat::lange (char aic_norm, mat::MatrixRow< float > & aimatrixt_a)
Calculates the norm of a matrix for float.
Return the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absoute value of a float matrix A
Parameters
aimatrixt_a a mat::MatrixRow to calculate the norm
aic_norm specifies the type of norm: 'M', '1', 'I' or 'F' max(abs(A(i,j))), NORM = 'M' or 'm' norm1(A), NORM = '1', 'O' or 'o' normI(A), NORM = 'I' or 'i' normF(A), NORM = 'F', 'f', 'E' or 'e' where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares).
Note that max(abs(A(i,j))) is not a consistent matrix norm.
Definition at line 51 of file matop_openblaslapacke.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::toArray().
lange() [2/3]
template<class T > T mat::lange (const char aic_norm, const mat::MatrixRow< T > & aimatrixt_a)
Definition at line 54 of file matop_withoutopenblas.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumElems(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and mat::MatrixRow< T_FEATURE >::toArray().
lange() [3/3]
float mat::lange (char aic_norm, mat::MatrixRow< double > & aimatrixt_a)
Calculates the norm of a matrix for double.
Return the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absoute value of a float matrix A
Parameters
aimatrixt_a a mat::MatrixRow to calculate the norm
aic_norm specifies the type of norm: 'M', '1', 'I' or 'F' max(abs(A(i,j))), NORM = 'M' or 'm' norm1(A), NORM = '1', 'O' or 'o' normI(A), NORM = 'I' or 'i' normF(A), NORM = 'F', 'f', 'E' or 'e' where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares).
Note that max(abs(A(i,j))) is not a consistent matrix norm.
Definition at line 89 of file matop_openblaslapacke.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::toArray().
LUPdecompose()
template<class T_FEATURE > int mat::LUPdecompose (mat::MatrixRow< T_FEATURE > & aiomatrixrt_a, uintidx * aovectorui_p)
Definition at line 46 of file matrix_inverse_lup.hpp.
References inout::containerprint(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by getrf(), and inverse().
LUPinverse()
template<class T_FEATURE > int mat::LUPinverse (mat::MatrixRow< T_FEATURE > & aiomatrixrt_lu, uintidx * aivectorui_p)
Definition at line 146 of file matrix_inverse_lup.hpp.
References inout::containerprint(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by inverse().
matrixread_get()
template<class T_FEATURE > mat::MatrixRow<T_FEATURE> mat::matrixread_get (const std::string & aistr_matrix, const bool aib_homogeneousCoord = false)
Definition at line 40 of file matrix_read.hpp.
References inout::LineSplit::getItem(), mat::MatrixRow< T_FEATURE >::getRow(), MATRIX_WITHROWNULL_CHAR, and inout::LineSplit::split().
mulRowsIColumns0N()
template<typename T_C , typename T_BITSIZE , typename T_B > void mat::mulRowsIColumns0N (T_C * aoarrayT_rowC, uintidx aiuintidx_idxBegin, uintidx aiuintidx_idxEnd, mat::BitArray< T_BITSIZE > & aibarray_rowA, MatrixRow< T_B > & aimatrixrowt_B)
mulRowsIColumns0N:
Parameters
aoarrayT_rowC a array of type T_C
aiuintidx_idxBegin a uintidx
aiuintidx_idxEnd a uintidx
aibarray_rowA a mat::BitArray<T_BITSIZE>
aimatrixrowt_B a MatrixRow<T_B>
Definition at line 49 of file bitmatrix_matrix_operator.hpp.
References interfacesse::axpy(), interfacesse::copya(), ds::BitContainer< T_BITSIZE >::getBit(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixRow< T_FEATURE >::getRow(), and inout::li_i.
Referenced by bitgemm().
point() [1/2]
template<typename T > void mat::point (MatrixRow< T > & aimatrixt_trans, T * aiarrayt_point, long int aili_idxCoordX, long int aili_idxCoordY, long int aili_idxCoordZ, FILE * aifile_outCoord)
Definition at line 136 of file transformation.hpp.
References interfacesse::dot(), mat::MatrixBase< T_FEATURE >::getNumColumns(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by main().
point() [2/2]
template<typename T > void mat::point (MatrixRow< T > & aimatrixt_trans, T * aiarrayt_point, const char * aiastr_label, long int aili_idxCoordX, long int aili_idxCoordY, long int aili_idxCoordZ, FILE * aifile_outCoord)
Definition at line 180 of file transformation.hpp.
References interfacesse::dot(), mat::MatrixBase< T_FEATURE >::getNumColumns(), and mat::MatrixRow< T_FEATURE >::getRow().
r8mat_diag_get_vector()
template<class T > void mat::r8mat_diag_get_vector (int n, T a[], T v[])
Definition at line 87 of file jacobi_eigenvalue.hpp.
References inout::a, and inout::v.
Referenced by jacobi_eigenvalue().
r8mat_identity()
template<class T > void mat::r8mat_identity (int n, T a[])
Definition at line 27 of file jacobi_eigenvalue.hpp.
References inout::a.
Referenced by jacobi_eigenvalue().
r8mat_is_eigen_right()
template<class T > T mat::r8mat_is_eigen_right (int n, int k, T a[], T x[], T lambda[])
Definition at line 135 of file jacobi_eigenvalue.hpp.
References inout::a, inout::c, inout::l, and r8mat_norm_fro().
r8mat_norm_fro()
template<class T > T mat::r8mat_norm_fro (int m, int n, T a[])
Definition at line 228 of file jacobi_eigenvalue.hpp.
References inout::a.
Referenced by r8mat_is_eigen_right().
scale()
template<typename T > MatrixRow<T> mat::scale (const std::vector< T > & aivector_scale)
Definition at line 88 of file transformation.hpp.
References mat::MatrixRow< T_FEATURE >::initialize().
Referenced by getMatrixTransformPCA().
syevd() [1/3]
std::tuple< std::vector< float >, mat::MatrixRow< float > > mat::syevd (const mat::MatrixRow< float > & aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
syevd computes all eigenvalues and eigenvectors of a float symmetric matrix A. If eigenvectors are desired, it uses a divide and conquer algorithm.
Parameters
aimatrixt_symatrix a mat::MatrixRow with the data
Definition at line 117 of file matop_openblaslapacke.hpp.
References inout::containerprint(), mat::MatrixBase< T_FEATURE >::getNumColumns(), and mat::MatrixBase< T_FEATURE >::getNumRows().
Referenced by getMatrixTransformPCA().
syevd() [2/3]
template<class T > std::tuple< std::vector< T >, mat::MatrixRow< T > > mat::syevd (const mat::MatrixRow< T > & aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
syevd computes all eigenvalues and eigenvectors of a T symmetric matrix A. If eigenvectors are desired, it uses a divide and conquer algorithm.
Parameters
aimatrixt_symatrix a mat::MatrixRow with the data
Definition at line 159 of file matop_withoutopenblas.hpp.
References inout::containerprint(), mat::MatrixBase< T_FEATURE >::getNumRows(), getTranspose(), jacobi_eigenvalue(), and mat::MatrixRow< T_FEATURE >::toArray().
syevd() [3/3]
std::tuple< std::vector< double >, mat::MatrixRow< float > > mat::syevd (const mat::MatrixRow< double > & aimatrixt_symatrix)
syevd computes all eigenvalues and eigenvectors
syevd computes all eigenvalues and eigenvectors of a double symmetric matrix A. If eigenvectors are desired, it uses a divide and conquer algorithm.
Parameters
aimatrixt_symatrix a mat::MatrixRow with the data
Definition at line 187 of file matop_openblaslapacke.hpp.
References inout::containerprint(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::print().
translation()
template<typename T > MatrixRow<T> mat::translation (const std::vector< T > & aivector_translation)
Definition at line 37 of file transformation.hpp.
References mat::MatrixRow< T_FEATURE >::initialize().
Referenced by getMatrixTransformPCA().