Library Evolutionary Algorithms for Clustering (LEAC): gaintegerop Namespace Reference
gaintegerop Namespace Reference
Genetic integer operators.
Functions
template<typename T_INTEGER , typename T_METRIC >
void labelKeep (gaencode::ChromosomeString< T_INTEGER, T_METRIC > &aochrom_relabel, std::vector< uintidx > &aivectorcidx_clustersKeep)
Label keep.
template<typename T_INTEGER , typename T_METRIC >
void oneChangelabel (gaencode::ChromosomeString< T_INTEGER, T_METRIC > &aochrom_relabel, T_INTEGER aigene_Cs, T_INTEGER aigene_Cj)
One change label.
template<typename T_REAL >
void recombinationD_MX (gaencode::ChromosomeString< uintidx, T_REAL > &aochrom_child1, gaencode::ChromosomeString< uintidx, T_REAL > &aochrom_child2, const gaencode::ChromosomeString< uintidx, T_REAL > &aichrom_parent1, const gaencode::ChromosomeString< uintidx, T_REAL > &aichrom_parent2, const uintidx aiui_maximumValueToMutate, const T_REAL airt_mixMutationProb)
recombination D_MX
template<typename T_INTEGER , typename T_METRIC >
void mutationD_PM (gaencode::ChromosomeString< T_INTEGER, T_METRIC > &aochrom_offspring, const uintidx aiui_maximumValueToMutate)
Mutate a integer gene.
template<typename T_INTEGER , typename T_METRIC , typename FUNCTION >
std::pair< uintidx, T_INTEGER > mutation (gaencode::ChromosomeString< T_INTEGER, T_METRIC > &aochrom_offspring, FUNCTION function)
Mutate a integer gene.
template<typename T_INTEGER , typename T_METRIC >
bool isNotValid (gaencode::ChromosomeString< T_INTEGER, T_METRIC > &aichrom_chromosome, const T_INTEGER aiit_lowerRangeGenes, const T_INTEGER aiit_upperRangeGenes)
Check if not valid string.
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR >
void mutationgka (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > &aiochrom_mutate, const T_REAL airt_probMutation, mat::MatrixRow< T_FEATURE > &aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist)
mutation GKA
Detailed Description
Genetic integer operators.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
isNotValid()
template<typename T_INTEGER , typename T_METRIC > bool gaintegerop::isNotValid (gaencode::ChromosomeString< T_INTEGER, T_METRIC > & aichrom_chromosome, const T_INTEGER aiit_lowerRangeGenes, const T_INTEGER aiit_upperRangeGenes)
Check if not valid string.
Return true if the string has integers in the range aiit_lowerRangeGenes to aiit_upperRangeGenes otherwise false
Parameters
aichrom_chromosome a gaencode::ChromosomeString<T_INTEGER,T_METRIC>
aiit_lowerRangeGenes a integer lower value gene
aiit_upperRangeGenes a integer upper value gene
Definition at line 548 of file ga_integer_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), and gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize().
Referenced by eac::gaclustering_fklabel().
labelKeep()
template<typename T_INTEGER , typename T_METRIC > void gaintegerop::labelKeep (gaencode::ChromosomeString< T_INTEGER, T_METRIC > & aochrom_relabel, std::vector< uintidx > & aivectorcidx_clustersKeep)
Label keep.
Parameters
aochrom_relabel a gaencode::ChromosomeString<T_INTEGER,T_METRIC>
aivectorcidx_clustersKeep a std::vector<uintidx> with label to keep
Definition at line 58 of file ga_integer_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by eac::gga_vklabel(), gaclusteringop::kmeansfeac(), gaclusteringop::mergeCrossover(), and gaclusteringop::MO1().
mutation()
template<typename T_INTEGER , typename T_METRIC , typename FUNCTION > std::pair< uintidx, T_INTEGER > gaintegerop::mutation (gaencode::ChromosomeString< T_INTEGER, T_METRIC > & aochrom_offspring, FUNCTION function)
Mutate a integer gene.
Parameters
aochrom_offspring a gaencode::ChromosomeString<T_INTEGER,T_METRIC>
function a function evaluate a gene
Definition at line 490 of file ga_integer_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::getGene(), gmt19937_eng, gaencode::ChromosomeBase< T_METRIC >::print(), and gaencode::ChromosomeString< T_GENE, T_METRIC >::setGene().
Referenced by eac::gaclustering_fklabel().
mutationD_PM()
template<typename T_INTEGER , typename T_METRIC > void gaintegerop::mutationD_PM (gaencode::ChromosomeString< T_INTEGER, T_METRIC > & aochrom_offspring, const uintidx aiui_maximumValueToMutate)
Mutate a integer gene.
One element in a child string C is selected randomly with a predetermined probability, Pm.point, and, upon success, replaced by a copy of an element indicated randomly in the complementary subset to produce C' [30]
Parameters
aochrom_offspring a gaencode::ChromosomeString<T_INTEGER,T_METRIC>
aiui_maximumValueToMutate a unsigned integer specifies the the maximum value to change from [0, aiui_maximumValueToMutate-1]
Definition at line 417 of file ga_integer_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::begin(), gaencode::ChromosomeString< T_GENE, T_METRIC >::end(), prob::getRandSetUnlike(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, gaencode::ChromosomeBase< T_METRIC >::print(), and gaencode::ChromosomeString< T_GENE, T_METRIC >::setGene().
Referenced by eac::gca_fkmedoid(), and eac::hka_fkmedoid().
mutationgka()
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL , typename INPUT_ITERATOR > void gaintegerop::mutationgka (gaencode::ChromFixedLength< T_CLUSTERIDX, T_REAL > & aiochrom_mutate, const T_REAL airt_probMutation, mat::MatrixRow< T_FEATURE > & aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
mutation GKA
mutation GKA based on [26]
Parameters
aiochrom_mutate a gaencode::ChromFixedLength to mutate
airt_probMutation a real number
aomatrixt_centroids a mat::MatrixRow space to work and store the centroids associated with the chromosome
aomatrixt_sumInstancesCluster a mat::MatrixRow space to work and store the sum of instances per cluster
aovectort_numInstancesInClusterK a std::vector space to work to store the number of instances per cluster
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 587 of file ga_integer_operator.hpp.
References clusteringop::getCentroids(), prob::getDistGKA(), gaselect::getIdxRouletteWheel(), mat::MatrixBase< T_FEATURE >::getNumColumns(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), and gmt19937_eng.
oneChangelabel()
template<typename T_INTEGER , typename T_METRIC > void gaintegerop::oneChangelabel (gaencode::ChromosomeString< T_INTEGER, T_METRIC > & aochrom_relabel, T_INTEGER aigene_Cs, T_INTEGER aigene_Cj)
One change label.
Parameters
aochrom_relabel a gaencode::ChromosomeString<T_INTEGER,T_METRIC>
aigene_Cs a integer number
aigene_Cj a integer number
Definition at line 130 of file ga_integer_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), and gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize().
Referenced by gaclusteringop::MO1().
recombinationD_MX()
template<typename T_REAL > void gaintegerop::recombinationD_MX (gaencode::ChromosomeString< uintidx, T_REAL > & aochrom_child1, gaencode::ChromosomeString< uintidx, T_REAL > & aochrom_child2, const gaencode::ChromosomeString< uintidx, T_REAL > & aichrom_parent1, const gaencode::ChromosomeString< uintidx, T_REAL > & aichrom_parent2, const uintidx aiui_maximumValueToMutate, const T_REAL airt_mixMutationProb)
recombination D_MX
In general, many recombination operators, including D_MX, when applied to two parent strings (P_1, P_2), produce two child strings (C_1, C_2) D_MX P_1, P_2 -—> C_1, C_2 [30]
Parameters
aochrom_child1 a gaencode::ChromosomeString<uintidx,T_REAL>
aochrom_child2 a gaencode::ChromosomeString<uintidx,T_REAL>
aichrom_parent1 a gaencode::ChromosomeString<uintidx,T_REAL>
aichrom_parent2 a gaencode::ChromosomeString<uintidx,T_REAL>
aiui_maximumValueToMutate a numeber with numero of instances
airt_mixMutationProb a real number mutation probability mix
Definition at line 190 of file ga_integer_operator.hpp.
References inout::containerprint(), interfacesse::copy(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, and gaencode::ChromosomeBase< T_METRIC >::print().
Referenced by eac::gca_fkmedoid(), and eac::hka_fkmedoid().