Library Evolutionary Algorithms for Clustering (LEAC): vectorutils Namespace Reference
vectorutils Namespace Reference
Vector utils.
Functions
template<typename INPUT_ITERATOR , typename T_SIZE >
std::vector< INPUT_ITERATOR > partition (INPUT_ITERATOR aiiterator_first, INPUT_ITERATOR aiiterator_last, const T_SIZE aist_numPartitions)
template<class T >
std::vector< T > keepItems (const std::vector< T > &aivector_b, std::vector< uintidx > &aivectorcidx_items)
std::vector< std::string > foundStrings (const std::vector< std::string > &aivectorstr_stringsToSearch, const std::string &aistr_stringToFound)
Detailed Description
Vector utils.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
foundStrings()
std::vector<std::string> vectorutils::foundStrings (const std::vector< std::string > & aivectorstr_stringsToSearch, const std::string & aistr_stringToFound)
Definition at line 154 of file vector_utils.hpp.
Referenced by inout::if().
keepItems()
template<class T > std::vector<T> vectorutils::keepItems (const std::vector< T > & aivector_b, std::vector< uintidx > & aivectorcidx_items)
Definition at line 83 of file vector_utils.hpp.
Referenced by gaclusteringop::kmeansfeac().
partition()
template<typename INPUT_ITERATOR , typename T_SIZE > std::vector<INPUT_ITERATOR> vectorutils::partition (INPUT_ITERATOR aiiterator_first, INPUT_ITERATOR aiiterator_last, const T_SIZE aist_numPartitions)
Definition at line 42 of file vector_utils.hpp.
Referenced by eac::tgca_vkcentroid().