Library Evolutionary Algorithms for Clustering (LEAC): ds Namespace Reference
ds Namespace Reference
Data structure.
Classes
class BitContainer
Bit container.
class DisjSets
Disjoint-set.
class IteratorPartitionLinked
An iterator for a PartitionLinked.
class PartitionLinked
Data structure to define the instances that belong to a cluster consecutively.
class PartitionLinkedNumInst
A data structure for managing an instance partition with the number of instances per cluster.
class PartitionLinkedStats
Partition with an array of membership.
Functions
template<typename T_CLUSTERIDX >
PartitionLinked< T_CLUSTERIDX > getPartitionlinked (partition::Partition< T_CLUSTERIDX > &aipartition_clusters)
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename FUNCINSTFREQUENCY >
auto getPartitionLinkedNumInst (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency) -> PartitionLinkedNumInst< T_CLUSTERIDX, decltype(func_instfrequency(*aiiterator_instfirst))>
Detailed Description
Data structure.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
getPartitionlinked()
template<typename T_CLUSTERIDX > PartitionLinked<T_CLUSTERIDX> ds::getPartitionlinked (partition::Partition< T_CLUSTERIDX > & aipartition_clusters)
Definition at line 407 of file partition_linked.hpp.
Referenced by gaclusteringop::crossoverCGA().
getPartitionLinkedNumInst()
template<typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename FUNCINSTFREQUENCY > auto ds::getPartitionLinkedNumInst (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, const FUNCINSTFREQUENCY func_instfrequency) -> PartitionLinkedNumInst<T_CLUSTERIDX,decltype(func_instfrequency(*aiiterator_instfirst))>
Definition at line 217 of file partition_linked_numinst.hpp.
References partition::Partition< T_CLUSTERIDX >::begin(), partition::Partition< T_CLUSTERIDX >::getNumCluster(), and partition::Partition< T_CLUSTERIDX >::next().
Referenced by eac::cga_vklabel(), eac::gga_vklabel(), and main().