Library Evolutionary Algorithms for Clustering (LEAC): dist Namespace Reference
dist Namespace Reference
Module for definition of distance between objects or instances.
Classes
struct Dist
Generic dist.
struct Euclidean
Euclidean distance.
struct EuclideanSquared
Euclidean distance sqrt.
struct Induced
Dist induced for real number [8] [6] [7].
struct InducedSquareRoot
Dist induced sqrt for real number [8] [6] [7].
Functions
double kernelEuclidean (const double *aiarrayd_p, const double *aiarrayd_q, const uintidx uintidx_length)
Gets the Euclidean distance of two double n-dimensional points with SSE.
double kernelEuclideanSquared (const double *aiarrayd_p, const double *aiarrayd_q, const uintidx uintidx_length)
Gets the square Euclidean distance of two double n-dimensional points with SSE.
float kernelEuclidean (const float *aiarrayd_p, const float *aiarrayd_q, const uintidx uintidx_length)
Gets the Euclidean distance of two float n-dimensional points with SSE.
float kernelEuclideanSquared (const float *aiarrayf_p, const float *aiarrayf_q, const uintidx uintidx_length)
Gets the square Euclidean distance of two float n-dimensional points with SSE.
double kernelEuclidean (const int *aiarrayi_p, const int *aiarrayi_q, const uintidx uintidx_length)
Kernel euclidean.
double kernelEuclideanSquared (const int *aiarrayi_p, const int *aiarrayi_q, uintidx uintidx_length)
Gets the square Euclidean distance of two int n-dimensional points with SSE.
double kernelEuclidean (const short *aiarrays_p, const short *aiarrays_q, const uintidx uintidx_length)
Gets the Euclidean distance of two short integer n-dimensional points with SSE.
double kernelEuclideanSquared (const short *aiarrays_p, const short *aiarrays_q, const uintidx uintidx_length)
Gets the square Euclidean distance of two short integer n-dimensional points with SSE.
template<typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR >
mat::MatrixTriang< T_DIST > getMatrixDissimilarity (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Triangular distance matrix.
template<typename T_FEATURE >
T_FEATURE kernelEuclidean (const T_FEATURE *aiad_p, const T_FEATURE *aiad_q, const uintidx aiuintidx_length)
Kernel euclidean distance for T_FEATURE.
template<typename T_FEATURE >
T_FEATURE kernelEuclideanSquared (const T_FEATURE *aiad_p, const T_FEATURE *aiad_q, const uintidx aiuintidx_length)
Kernel euclidean distance for T_FEATURE.
Detailed Description
Module for definition of distance between objects or instances.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
getMatrixDissimilarity()
template<typename T_FEATURE , typename T_DIST , typename INPUT_ITERATOR > mat::MatrixTriang< T_DIST > dist::getMatrixDissimilarity (INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Triangular distance matrix.
Returns the triangular distance matrix using a specified distance measure.
Parameters
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast a InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 42 of file dist_matrix_dissimilarity.hpp.
References mat::MatrixTriang< T_FEATURE >::print().
Referenced by eac::cga_vklabel(), eac::gaclustering_vktreebinary(), eac::gga_vklabel(), and main().
kernelEuclidean() [1/5]
template<typename T_FEATURE > T_FEATURE dist::kernelEuclidean (const T_FEATURE * aiad_p, const T_FEATURE * aiad_q, const uintidx aiuintidx_length)
Kernel euclidean distance for T_FEATURE.
Parameters
aiad_p an array of T_FEATURE
aiad_q an array of T_FEATURE
aiuintidx_length length of the array
Definition at line 36 of file dist_template.hpp.
kernelEuclidean() [2/5]
double dist::kernelEuclidean (const double * aiarrayd_p, const double * aiarrayd_q, const uintidx uintidx_length) inline
Gets the Euclidean distance of two double n-dimensional points with SSE.
Parameters
aiarrayd_p a double array
aiarrayd_q a double array
uintidx_length a length of the array
Definition at line 43 of file dist_kernel_64bits.hpp.
Referenced by dist::Euclidean< T_DIST, T_FEATURE >::operator()().
kernelEuclidean() [3/5]
float dist::kernelEuclidean (const float * aiarrayd_p, const float * aiarrayd_q, const uintidx uintidx_length) inline
Gets the Euclidean distance of two float n-dimensional points with SSE.
Parameters
aiarrayd_p a float array
aiarrayd_q a float array
uintidx_length length of the array
Definition at line 94 of file dist_kernel_64bits.hpp.
kernelEuclidean() [4/5]
double dist::kernelEuclidean (const int * aiarrayi_p, const int * aiarrayi_q, const uintidx uintidx_length) inline
Kernel euclidean.
Gets the distance of two n-dimensional points with SSE for int
Parameters
aiarrayi_p a int array
aiarrayi_q a int array
uintidx_length length of the array
Definition at line 147 of file dist_kernel_64bits.hpp.
kernelEuclidean() [5/5]
double dist::kernelEuclidean (const short * aiarrays_p, const short * aiarrays_q, const uintidx uintidx_length) inline
Gets the Euclidean distance of two short integer n-dimensional points with SSE.
Parameters
aiarrays_p a short int array
aiarrays_q a short int array
uintidx_length length of the array
Definition at line 198 of file dist_kernel_64bits.hpp.
kernelEuclideanSquared() [1/5]
template<typename T_FEATURE > T_FEATURE dist::kernelEuclideanSquared (const T_FEATURE * aiad_p, const T_FEATURE * aiad_q, const uintidx aiuintidx_length)
Kernel euclidean distance for T_FEATURE.
Parameters
aiad_p an array of T_FEATURE
aiad_q an array of T_FEATURE
aiuintidx_length length of the array
Definition at line 60 of file dist_template.hpp.
kernelEuclideanSquared() [2/5]
double dist::kernelEuclideanSquared (const double * aiarrayd_p, const double * aiarrayd_q, const uintidx uintidx_length) inline
Gets the square Euclidean distance of two double n-dimensional points with SSE.
Parameters
aiarrayd_p a double array
aiarrayd_q a double array
uintidx_length length of the array
Definition at line 68 of file dist_kernel_64bits.hpp.
Referenced by dist::EuclideanSquared< T_DIST, T_FEATURE >::operator()().
kernelEuclideanSquared() [3/5]
float dist::kernelEuclideanSquared (const float * aiarrayf_p, const float * aiarrayf_q, const uintidx uintidx_length) inline
Gets the square Euclidean distance of two float n-dimensional points with SSE.
Parameters
aiarrayf_p a float array
aiarrayf_q a float array
uintidx_length length of the array
Definition at line 121 of file dist_kernel_64bits.hpp.
kernelEuclideanSquared() [4/5]
double dist::kernelEuclideanSquared (const int * aiarrayi_p, const int * aiarrayi_q, uintidx uintidx_length) inline
Gets the square Euclidean distance of two int n-dimensional points with SSE.
Parameters
aiarrayi_p a int array
aiarrayi_q a int array
uintidx_length length of the array
Definition at line 173 of file dist_kernel_64bits.hpp.
kernelEuclideanSquared() [5/5]
double dist::kernelEuclideanSquared (const short * aiarrays_p, const short * aiarrays_q, const uintidx uintidx_length) inline
Gets the square Euclidean distance of two short integer n-dimensional points with SSE.
Parameters
aiarrays_p a short int array
aiarrays_q a short int array
uintidx_length length of the array
Definition at line 224 of file dist_kernel_64bits.hpp.