Library Evolutionary Algorithms for Clustering (LEAC): inout Namespace Reference
inout Namespace Reference
Module for input and output parameters.
Classes
class InParamAdaptivePcPm
Input parameter for EA with adaptive probabilities of crossover and mutation [11].
class InParamAdaptivePcPmFk
Input parameter for EA with adaptive probabilities of crossover and mutation [11].
class InParamAlgorithmo
Input parameter for define propertys of the algorithmos.
class InParamCBGA
Input parameter for CBGA [17].
class InParamClustering
Input parameter for clustering algorithm.
class InParamClusteringMaxIter
Input parameter for algorithm with iteration maximum.
class InParamDBSCAN
Input parameter for DBSCAN algorithm [Est].
class InParamFCM
Input parameter for FCM algorithm clustering [8].
class InParamFEAC
Input parameter Fast Evolutionary Algorithm for Clustering F-EAC [2].
class InParamFk
Input parameter for algorithms with Fixed K.
class InParamGAClustering
Input parameter for genetic algorithm.
class InParamGAPrototypesFk
Input parameter for GA-Prototypes algorithm [27].
class InParamGCA
Input parameter for GCA algorithm k-medoid clustering [30].
class InParamGenWOChgVk
Input parameter Document clustering into an unknown number of clusters using a genetic algorithm [10].
class InParamGGA
Input parameter for GGA algorithm [1].
class InParamHKA
Input parameter for HKA a hybrid algorithm for k-medoid clustering [37].
class InParamIsoData
Input parameter for IsoData algorithm.
class InParamKmeans
Input parameter for traditional algorithm clustering [31].
class InParamPAM
Input parameter for Medoids PAM algorithm [25].
class InParamPCA
Input parameter for PCA Algorithmo.
class InParamPCAtransmatrix
Input parameter for PCA transformation matrix.
class InParamPcPm
Input parameter for GA with probability crossover (Pc) and mutation (Pm)
class InParamPcPmFk
Input parameter for GA with probability Pc, Pm and Fixed K.
class InParamPcPmVk
Input parameter for GA with probability Pc, Pm and Variable K.
class InParamPlotClustering
Input parameter for plot clustering.
class InParamPm
Input parameter for GA with only probability mutation (Pm)
class InParamPmFk
Input parameter for GKA with only probability mutation (Pm) and Fixed K [26].
class InParamReadInst
Input parameter for read instances.
class InParamReadInstFreq
Input parameter for read instances with frequency.
class InParamSlink
Input parameter for traditional algorithm clustering [31].
class InParamStdVar
Input parameter for standardization of variables Algorithmo.
class InParamSubClusterBinaryVk
Input parameter for CLUSTERING algorithm A genetic approach to the automatic clustering problem[38].
class InParamTGCA
Input parameter for TGCA a two-stage genetic algorithm [18].
class InParamVk
class InParamWithoutPcPmFk
Input parameter for GA without probability crossover (Pc) and mutation (Pm)[7].
class InParamWithoutPcPmVk
Input parameter for GA without probability crossover (Pc) and mutation (Pm)[19].
class LineSplit
Used for processing files to read.
class OutFileName
class OutParamAlgorithm
Output parameters for genetic algorithm.
class OutParamClustering
Output parameters for a generic clustering algorithm.
class OutParamClusteringMetric
Output parameters for a generic clustering algorithm.
class OutParamDBSCAN
Output parameter for DBSCAN Algorithmo [Est].
class OutParamGAC
Output Output parameters of the evolutionary algorithm.
class OutParamGAMedoid
class OutParamKmeans
Output parameter for Kmeans Algorithmo [31].
Enumerations
enum InParam_algTypeOut {
LABEL, CENTROIDS, CRISPPARTITION, MEDOIDS,
DENSITY_BASED, HIERARCHICAL, OTHER
}
enum ParamPCAmatrix { COVARIANCE, CORRELATION, COVARIANCE, CORRELATION }
enum ParamPCAmethod { EIGEN, SVD, EIGEN, SVD }
enum ParamPCAmatrix { COVARIANCE, CORRELATION, COVARIANCE, CORRELATION }
enum ParamPCAmethod { EIGEN, SVD, EIGEN, SVD }
enum EnumFormatInstanceFile { INPARAM_FORMATINSTANCEFILE_UCI =0, INPARAM_FORMATINSTANCEFILE_KEEL =1 }
enum OutParamNameObjectiveFunc {
SED =0, SSE =1, Distortion =2, J1 =3,
CSmeasure =4, DunnIndex =5, SDunnIndex =6, Silhouette =7,
SSilhouette =8, DBindex =9, VRC =10, WBIndex =11,
SSB =12, ScoreFunction =13, RandIndex =14, Purity =15,
Fmeasure =16, JaccardIndex =17, precision =18, recall =19,
Misclassified =20, Pairs_a =21, Pairs_b =22, Pairs_c =23,
Pairs_d =24, Jm =25, IndexI_cFuzzy =26, IndexI =27,
XieBeniIndex =28, XieBeniIndex_crisp =29, Entropy =30, PartitionCoefficient =31,
IntraInterClust =32, NotUse =33
}
Functions
template<typename INPUT_ITERATOR >
void containerprint (INPUT_ITERATOR iterator_first, INPUT_ITERATOR iterator_last, std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
template<typename INPUT_ITERATOR , typename FUNCGETVALUE >
void containerprint (INPUT_ITERATOR iterator_first, INPUT_ITERATOR iterator_last, FUNCGETVALUE func_getValue, std::ostream &os=std::cout, const char *aipc_label="", const char aic_delimCoef=',')
template<typename T >
void maplistprint (const std::map< T, std::list< T > > &aimaplistadj_g, std::ostream &out=std::cout, const char *aipc_label="", const char aic_delimCoef=',', const char aic_delimRow=';')
Prints graph of a map structure with list of adjacencies.
template<typename T >
void vectorlistprint (const std::vector< std::list< T > > &aivectorlist_g, std::ostream &out=std::cout, const char *aipc_label="", const char aic_delimList=';')
void barprogress_update (int ai_numberOfRun, int ai_totalRuns)
std::string fileutils_subName (const std::string aistr_name, const std::string aistr_nameSub)
bool fileutils_isdir (const char *aiptstr_dirname)
std::vector< std::string > fileutils_listdir (const char *aiptstr_dirname)
aoipc_inParamClustering setNumInstances (luintidx_read)
liss_stringstream str (optarg)
aoipc_inParamClustering setClassInstanceColumn (luintidx_read)
aoipc_inParamClustering setClusterInstanceColumn (luintidx_read)
aoipc_inParamClustering setIDInstanceColumn (luintidx_read)
aoipc_inParamClustering setInstanceFrequencyColumn (luintidx_read)
if (optind< argc)
if (lptstr_fileInstance==NULL)
if (fileutils_isdir(lptstr_fileInstance))
if (lptstr_fileInstanceTest !=NULL)
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
std::pair< uintidx, uintidx > readNumInstances (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiipri_inParamReadInst, const bool aib_fileTest=false)
Read the number of instances or objects.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
std::pair< std::vector< std::string >, std::string > instancesReadDimName (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiipri_inParamReadInst, const bool aib_fileTest=false)
Read the name of the dimensions of instances and class.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
std::vector< data::Instance< T_FEATURE > * > instancesRead (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiipri_inParamReadInst, const bool aib_fileTest=false)
Read the instances or objects.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
std::vector< data::Instance< T_FEATURE > * > instancesReadWithClass (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiipri_inParamReadInst, const bool aib_fileTest=false)
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY >
std::vector< data::Instance< T_FEATURE > * > instancesReadWithFreq (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > &aiipri_inParamReadInst, const bool aib_fileTest=false)
Read the instances or objects with frequency.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY >
std::vector< data::Instance< T_FEATURE > * > instancesReadWithFreqClass (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > &aiipri_inParamReadInst, const bool aib_fileTest=false)
Read the instances or objects with frequency.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
std::pair< std::vector< data::Instance< T_FEATURE > * >, std::vector< data::Instance< T_FEATURE > * > > dataSetRead (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > &aiipri_inParamReadInst)
Read a data set.
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY >
std::pair< std::vector< data::Instance< T_FEATURE > * >, std::vector< data::Instance< T_FEATURE > * > > dataSetReadWithFreq (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > &aiipri_inParamReadInstWithFreq)
Variables
const char * las_optTokensYesNo [] = {"no", "yes", (char *) NULL }
uintidx li_i
std::cout<< "\nUsage: "<< argv0<< " [OPTION]\n"<< "\tAbout groups of instances for a set K as well as statistics\n"<< "\tof the algorithm used\n\n";std::cout<< " -i, --instances=FILE or DIRECTORY\n"<< " file or directory containing data of instances\n"<< " to be clustered\n";std::cout<< " -x, --select-instances[=PREFIX]\n"<< " if instances is directory search files with\n"<< " prefix for training (eg. iris-10-1tra.dat,\n"<< " iris-10-2tra.dat,... PREFIX=tra.dat)\n";std::cout<< " -t, --test[=FILE or PREFIX] if instances is directory search files with\n"<< " prefix for test (eg. iris-10-1tst.dat,\n"<< " iris-10-2tst.dat,... PREFIX=tst.dat),\n"<< " in other case only name file\n";std::cout<< " -b --format-file[=NAME] ";li_i=0;while(larray_opFormatFile[li_i+1] !=NULL) { std::cout<< larray_opFormatFile[li_i]<< ",";++li_i;} std::cout<< " or "<< larray_opFormatFile[li_i]<< ", by default "<< larray_opFormatFile[aoipc_inParamClustering.getFormatInstanceFile()]<< '\n';std::cout<< " -h, --with-header[=yes/no] file contains names of instances or a header,\n"<< " by default is "<< las_optTokensYesNo[aoipc_inParamClustering.getHaveHeaderFileInstance()]<< '\n';std::cout<< " -u, --number-instances[=NUMBER]\n"<< " the number of instances the file contains\n"<< " instances, if not specified file is obtained\n";std::cout<< " -a, --select-attributes[=ARG]\n"<< " select the attributes to be processed for\n"<< " example, \"1-2,4\" by default all. Also\n"<< " used to specify the number of dimensions\n"<< " of the instances, unless specified file is\n"<< " obtained instances\n";std::cout<< " -d, --delimit-attributes=[ARG]\n"<< " separated file by default \""<< INPARAM_FILE_SEPARATOR_DEFAULT<< "\"\n";std::cout<< " -c, --class-column[=NUMBER] input file of instances has a class assigned\n"<< " in the column [NUMBER=undefined]\n";std::cout<< " -e, --cluster-column[=NUMBER]\n"<< " input file of instances has a cluster assigned\n"<< " in the column [NUMBER=undefined]\n";std::cout<< " -l, --idinstances-column[=NUMBER]\n"<< " the input file instance is assigned a column\n"<< " instance identifier [NUMBER=undefined]\n";std::cout<< " -f, --freq-instances-column[=NUMBER]\n"<< " the input file instance is assigned a column\n"<< " frequency instances [NUMBER=undefined]\n";std::cout<< " -r, --number-runs[=NUMBER] number of runs or repetitions of the algorithm\n"<< " (by default [NUMBER=1])\n";std::cout<< " -R, --runtime-filename=[FILE]\n"<< " out file of times run\n";std::cout<< "\nParticular options of the algorithm "<< aoipc_inParamClustering.getAlgorithmoName()<< '\n'<< " based on "<< aoipc_inParamClustering.getAlgorithmoAuthor()<< '\n';std::cout<< "\n";std::cout<< " -v, --verbose[=NUMBER] explain what is being done (compiled with\n"<< " VERBOSE=yes)\n";std::cout<< " -q, --bar-progress progress bar printing, default is not\n";std::cout<< " -?, --help help";std::cout<< std::endl;exit(-1);} { const char *larray_opFormatFile[]=INPARAMCLUSTERING_FORMATINSTANCEFILE;int li_opt;char *lps_optsubValue;int li_idxSubOpt;char *lptstr_fileInstance=NULL;char *lptstr_fileSelectInstances=NULL;char *lptstr_fileInstanceTest=NULL;static struct option long_options[]={ {"instances", required_argument, 0, 'i'}, {"select-instances", required_argument, 0, 'x'}, {"test", required_argument, 0, 't'}, {"format-file", required_argument, 0, 'b'}, {"with-header", required_argument, 0, 'h'}, {"number-instances", required_argument, 0, 'u'}, {"select-attributes", required_argument, 0, 'a'}, {"delimit-attributes", required_argument, 0, 'd'}, {"class-column", required_argument, 0, 'c'}, {"cluster-column", required_argument, 0, 'e'}, {"idinstance-column", required_argument, 0, 'l'}, {"freq-instance-column", required_argument, 0, 'f'}, {"distance", required_argument, 0, 'n'}, {"number-runs", required_argument, 0, 'r'}, {"random-seed", required_argument, 0, 'z'}, {"max-execution-time", required_argument, 0, 'w'}, {"centroids-outfile", required_argument, 0, 'C'}, {"centroids-format", required_argument, 0, 0}, {"membership-outfile", required_argument, 0, 'M'}, {"partitionstable-outfile", required_argument, 0, 'T'}, {"table-format", required_argument, 0, 0}, {"print-mulline", required_argument, 0, 0}, {"runtime-filename", required_argument, 0, 'R'}, {"gnuplot", required_argument, 0, 'P'}, {"verbose", no_argument, 0, 'v'}, {"bar-progress", no_argument, 0, 'q'}, {"plot-styles", required_argument, 0, 'y'}, {"help", no_argument, 0, '?'}, {0, 0, 0, 0} };int option_index=0;using namespace std;istringstream liss_stringstream;uintidx luintidx_read;std::string ls_read;while(1) { li_opt=getopt_long(argc, argv, "i:x:t:b:h:u:a:d:c:e:l:f:r:R:n:z:w:C:M:T:G:P:y:v:q?", long_options, &option_index);if(li_opt==-1) break;switch(li_opt) { case 0:break;case 'i':lptstr_fileInstance=optarg;break;case 'x':lptstr_fileSelectInstances=optarg;break;case 't':lptstr_fileInstanceTest=optarg;break;case 'b':if((li_idxSubOpt=getsubopt_getsubopt(&optarg, larray_opFormatFile, &lps_optsubValue)) !=-1) { switch(li_idxSubOpt) { case 0:aoipc_inParamClustering.setFormatInstanceFile(INPARAM_FORMATINSTANCEFILE_UCI);break;case 1:aoipc_inParamClustering.setFormatInstanceFile(INPARAM_FORMATINSTANCEFILE_KEEL);aoipc_inParamClustering.setSeparateAttributes(INPARAMCLUSTERING_KEEL_FILE_SEPARATOR);aoipc_inParamClustering.setHaveHeaderFileInstance(false);break;default:break;} } else { aoipc_inParamClustering.errorArgument(argv[0], long_options[option_index].name, larray_opFormatFile);} break;case 'h':aoipc_inParamClustering.setHaveHeaderFileInstance(aoipc_inParamClustering.isYesNo(optarg, argv[0], long_options[option_index].name));break;case 'u':liss_stringstream.clear();liss_stringstream.str(optarg);liss_stringstream > luintidx_read
break
case a
case d
case c
case e
case l
case f
case r
case R
case q
case v
case __pad0__
case aoipc_inParamClustering
default __pad1__
else
const char * garray_nameObjetiveFunc []
Detailed Description
Module for input and output parameters.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Author
Hermes Robles Berumen
Date
2015-2017
Copyright
GPLv3 license
Enumeration Type Documentation
EnumFormatInstanceFile
enum inout::EnumFormatInstanceFile
Enumerator
INPARAM_FORMATINSTANCEFILE_UCI
INPARAM_FORMATINSTANCEFILE_KEEL
Definition at line 33 of file inparam_readinst.hpp.
InParam_algTypeOut
enum inout::InParam_algTypeOut
Enumerator
LABEL
CENTROIDS
CRISPPARTITION
MEDOIDS
DENSITY_BASED
HIERARCHICAL
OTHER
Definition at line 30 of file inparam.hpp.
OutParamNameObjectiveFunc
enum inout::OutParamNameObjectiveFunc
Enumerator
SED
SSE
Distortion
J1
CSmeasure
DunnIndex
SDunnIndex
Silhouette
SSilhouette
DBindex
VRC
WBIndex
SSB
ScoreFunction
RandIndex
Purity
Fmeasure
JaccardIndex
precision
recall
Misclassified
Pairs_a
Pairs_b
Pairs_c
Pairs_d
Jm
IndexI_cFuzzy
IndexI
XieBeniIndex
XieBeniIndex_crisp
Entropy
PartitionCoefficient
IntraInterClust
NotUse
Definition at line 87 of file outparam_clustering.hpp.
ParamPCAmatrix [1/2]
enum inout::ParamPCAmatrix
Enumerator
COVARIANCE
CORRELATION
COVARIANCE
CORRELATION
Definition at line 32 of file inparam_pca.hpp.
ParamPCAmatrix [2/2]
enum inout::ParamPCAmatrix
Enumerator
COVARIANCE
CORRELATION
COVARIANCE
CORRELATION
Definition at line 32 of file inparam_pcatransmatrix.hpp.
ParamPCAmethod [1/2]
enum inout::ParamPCAmethod
Enumerator
EIGEN
SVD
EIGEN
SVD
Definition at line 33 of file inparam_pca.hpp.
ParamPCAmethod [2/2]
enum inout::ParamPCAmethod
Enumerator
EIGEN
SVD
EIGEN
SVD
Definition at line 33 of file inparam_pcatransmatrix.hpp.
Function Documentation
barprogress_update()
void inout::barprogress_update (int ai_numberOfRun, int ai_totalRuns)
Definition at line 28 of file bar_progress.hpp.
References BARPROGRESS_SIZE, and li_i.
Referenced by main().
containerprint() [1/2]
template<typename INPUT_ITERATOR > void inout::containerprint (INPUT_ITERATOR iterator_first, INPUT_ITERATOR iterator_last, std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',')
Definition at line 50 of file container_out.hpp.
Referenced by um::avgRadiusClusterK(), gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::checkChangedCodeVectors(), eac::clustering_genetic(), eac::clustering_vksubclusterbinary(), gaclusteringop::crossoverCGA(), um::D2(), um::diameterClusterK(), clusteringop::getCentroids(), prob::getDistGKA(), ds::BitContainer< T_BITSIZE >::getIdxWithBitOn(), mat::getRowsNumBitOn(), prob::getWithoutRepeatsSet(), eac::gga_vklabel(), gaclusteringop::kmeansfeac(), clusteringop::kmeansoperator(), prob::linearNormalization(), mat::LUPdecompose(), mat::LUPinverse(), prob::makeDistRouletteWheel(), stats::maxFeatures(), um::maxRadiusClusterK(), stats::meanRow(), stats::meanVector(), mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K >::mergeTwoRow(), stats::minFeatures(), clusteringop::nearestRepresentative(), sm::partialRandIndex(), gagenericop::pathCrossover(), partition::PartitionLabelVector< T_CLUSTERIDX >::print(), partition::PartitionLabel< T_CLUSTERIDX >::print(), ds::PartitionLinkedNumInst< T_CLUSTERIDX, T_INSTANCES_CLUSTER_K >::print(), gaencode::ChromosomeFEAC< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::print(), ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM >::print(), clusteringop::randomInitialize(), clusteringop::reassignCluster(), gaintegerop::recombinationD_MX(), clusteringop::setUpCuster(), um::silhouette(), um::simplifiedSilhouette(), clusteringop::slink(), um::sumDistInstCentInK(), stats::sumFeactures(), stats::sumFeacturesFreq(), stats::sumFeacturesFreqSQ(), stats::sumFeacturesSQ(), mat::syevd(), eac::tgca_vkcentroid(), clusteringop::updateClusterCj(), clusteringop::updateMedoids(), and stats::varTodesvstd().
containerprint() [2/2]
template<typename INPUT_ITERATOR , typename FUNCGETVALUE > void inout::containerprint (INPUT_ITERATOR iterator_first, INPUT_ITERATOR iterator_last, FUNCGETVALUE func_getValue, std::ostream & os = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',')
Definition at line 81 of file container_out.hpp.
dataSetRead()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > std::pair< std::vector< data::Instance< T_FEATURE > * >, std::vector< data::Instance< T_FEATURE > * > > inout::dataSetRead (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiipri_inParamReadInst)
Read a data set.
Parameters
aiipri_inParamReadInst a inout::InParamReadInst with the necessary parameters to read a data set file
Returns
a pair of vectors, the first with the training instances and the second with the test instances
Definition at line 922 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstanceTest(), clusteringop::initialize(), instancesRead(), and instancesReadWithClass().
Referenced by main().
dataSetReadWithFreq()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY > std::pair< std::vector<data::Instance<T_FEATURE>* >, std::vector<data::Instance<T_FEATURE>* > > inout::dataSetReadWithFreq (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > & aiipri_inParamReadInstWithFreq)
Definition at line 1006 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getNumFilesInstanceTest(), clusteringop::initialize(), instancesReadWithFreq(), and instancesReadWithFreqClass().
Referenced by main().
fileutils_isdir()
bool inout::fileutils_isdir (const char * aiptstr_dirname)
Definition at line 61 of file file_utils.hpp.
fileutils_listdir()
std::vector<std::string> inout::fileutils_listdir (const char * aiptstr_dirname)
Definition at line 73 of file file_utils.hpp.
Referenced by if().
fileutils_subName()
std::string inout::fileutils_subName (const std::string aistr_name, const std::string aistr_nameSub)
Definition at line 37 of file file_utils.hpp.
if() [1/4]
inout::if ()
Definition at line 4695 of file inparamclustering_getparameter.hpp.
References aoipc_inParamClustering.
if() [2/4]
inout::if (lptstr_fileInstance = = NULL)
Definition at line 4703 of file inparamclustering_getparameter.hpp.
References aoipc_inParamClustering.
if() [3/4]
inout::if (fileutils_isdir(lptstr_fileInstance))
Definition at line 4710 of file inparamclustering_getparameter.hpp.
References aoipc_inParamClustering, fileutils_listdir(), and vectorutils::foundStrings().
if() [4/4]
inout::if (lptstr_fileInstanceTest ! = NULL)
Definition at line 4758 of file inparamclustering_getparameter.hpp.
References aoipc_inParamClustering.
instancesRead()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > std::vector< data::Instance< T_FEATURE > * > inout::instancesRead (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Read the instances or objects.
Parameters
aiipri_inParamReadInst a inout::InParamReadInst with the necessary parameters to read a data set file
aib_fileTest a bool to specify if the data set is a test
Definition at line 284 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), data::Instance< T_FEATURE >::readFeature(), readNumInstances(), and data::Instance< T_FEATURE >::setNumDimensions().
Referenced by dataSetRead(), and main().
instancesReadDimName()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > std::pair< std::vector< std::string >, std::string > inout::instancesReadDimName (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Read the name of the dimensions of instances and class.
Parameters
aiipri_inParamReadInst a inout::InParamReadInst with the necessary parameters to read a data set file
aib_fileTest a bool to specify if the data set is a test
Definition at line 167 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getFormatInstanceFile(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::LineSplit::getItem(), inout::LineSplit::getNumSelectColumns(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::LineSplit::getSelectColumns(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), inout::LineSplit::getVectorString(), INPARAM_FORMATINSTANCEFILE_KEEL, INPARAM_FORMATINSTANCEFILE_UCI, inout::LineSplit::setSeparator(), and inout::LineSplit::split().
Referenced by main().
instancesReadWithClass()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > std::vector<data::Instance<T_FEATURE>* > inout::instancesReadWithClass (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Definition at line 413 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClusterInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), data::Instance< T_FEATURE >::readFeature(), readNumInstances(), and data::Instance< T_FEATURE >::setNumDimensions().
Referenced by dataSetRead(), and main().
instancesReadWithFreq()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY > std::vector< data::Instance< T_FEATURE > * > inout::instancesReadWithFreq (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Read the instances or objects with frequency.
Parameters
aiipri_inParamReadInst a inout::InParamReadInstFreq with the necessary parameters to read a data set file
aib_fileTest a bool to specify if the data set is a test
Definition at line 597 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getInstanceFrequencyColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), data::Instance< T_FEATURE >::readFeature(), readNumInstances(), and data::Instance< T_FEATURE >::setNumDimensions().
Referenced by dataSetReadWithFreq().
instancesReadWithFreqClass()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY > std::vector< data::Instance< T_FEATURE > * > inout::instancesReadWithFreqClass (inout::InParamReadInstFreq< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX, T_INSTANCE_FREQUENCY > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Read the instances or objects with frequency.
Parameters
aiipri_inParamReadInst a inout::InParamReadInstFreq with the necessary parameters to read a data set file
aib_fileTest a bool to specify if the data set is a test
Definition at line 748 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClassInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getClusterInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getIDInstanceColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getInstanceFrequencyColumn(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes(), data::Instance< T_FEATURE >::readFeature(), readNumInstances(), and data::Instance< T_FEATURE >::setNumDimensions().
Referenced by dataSetReadWithFreq().
maplistprint()
template<typename T > void inout::maplistprint (const std::map< T, std::list< T > > & aimaplistadj_g, std::ostream & out = std::cout, const char * aipc_label = "", const char aic_delimCoef = ',', const char aic_delimRow = ';')
Prints graph of a map structure with list of adjacencies.
Parameters
aimaplistadj_g a map de list
out a std::ostream
aipc_label a label of graph
aic_delimCoef a separtor item separator
aic_delimRow a separtor item separator
Definition at line 122 of file container_out.hpp.
readNumInstances()
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > std::pair< uintidx, uintidx > inout::readNumInstances (inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX > & aiipri_inParamReadInst, const bool aib_fileTest = false)
Read the number of instances or objects.
Parameters
aiipri_inParamReadInst a inout::InParamReadInst with the necessary parameters to read a data set file
aib_fileTest a bool to specify if the data set is a test
Definition at line 61 of file instances_read.hpp.
References inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getCurrentFileInstanceTest(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getHaveHeaderFileInstance(), inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSelectAttributes(), and inout::InParamReadInst< T_FEATURE, T_INSTANCES_CLUSTER_K, T_CLUSTERIDX >::getSeparateAttributes().
Referenced by instancesRead(), instancesReadWithClass(), instancesReadWithFreq(), and instancesReadWithFreqClass().
setClassInstanceColumn()
aoipc_inParamClustering inout::setClassInstanceColumn (luintidx_read)
setClusterInstanceColumn()
aoipc_inParamClustering inout::setClusterInstanceColumn (luintidx_read)
setIDInstanceColumn()
aoipc_inParamClustering inout::setIDInstanceColumn (luintidx_read)
setInstanceFrequencyColumn()
aoipc_inParamClustering inout::setInstanceFrequencyColumn (luintidx_read)
setNumInstances()
aoipc_inParamClustering inout::setNumInstances (luintidx_read)
str()
liss_stringstream inout::str (optarg)
Referenced by inout::LineSplit::split().
vectorlistprint()
template<typename T > void inout::vectorlistprint (const std::vector< std::list< T > > & aivectorlist_g, std::ostream & out = std::cout, const char * aipc_label = "", const char aic_delimList = ';')
Definition at line 143 of file container_out.hpp.
Referenced by eac::gaclustering_vktreebinary(), main(), graph::nearestNeighbor(), and graph::prim().
Variable Documentation
__pad0__
case inout::__pad0__
Definition at line 4686 of file inparamclustering_getparameter.hpp.
__pad1__
default inout::__pad1__
Definition at line 4690 of file inparamclustering_getparameter.hpp.
a
case inout::a
Definition at line 4548 of file inparamclustering_getparameter.hpp.
Referenced by utils::closeenough(), gnuplot_plot_slope(), mat::jacobi_eigenvalue(), mat::r8mat_diag_get_vector(), mat::r8mat_identity(), mat::r8mat_is_eigen_right(), and mat::r8mat_norm_fro().
aoipc_inParamClustering
default inout::aoipc_inParamClustering
Definition at line 4686 of file inparamclustering_getparameter.hpp.
Referenced by if().
break
inout::break
Definition at line 4546 of file inparamclustering_getparameter.hpp.
c
case inout::c
Definition at line 4554 of file inparamclustering_getparameter.hpp.
Referenced by __strchrnul(), mat::jacobi_eigenvalue(), and mat::r8mat_is_eigen_right().
d
case inout::d
Definition at line 4551 of file inparamclustering_getparameter.hpp.
Referenced by interfacesse::axpyInv(), gnuplot_plot_x(), gnuplot_write_x_csv(), mat::jacobi_eigenvalue(), and interfacesse::scalInv().
e
case inout::e
Definition at line 4560 of file inparamclustering_getparameter.hpp.
Referenced by prob::adaptiveProb().
else
inout::else
Initial value:
{
      aoipc_inParamClustering.setFileInstance(lptstr_fileInstance)
Definition at line 4756 of file inparamclustering_getparameter.hpp.
f
case inout::f
Definition at line 4573 of file inparamclustering_getparameter.hpp.
Referenced by interfacesse::axpyInv(), utils::RunOnce::RunOnce(), and interfacesse::scalInv().
garray_nameObjetiveFunc
const char* inout::garray_nameObjetiveFunc[]
Definition at line 44 of file outparam_clustering.hpp.
Referenced by inout::OutParamClustering< T_METRIC, T_MEMBERCLUSTER_IDX >::getNameUsedObjetiveFunc(), inout::OutParamClusteringMetric< T_METRIC >::getNumObjetiveFunc(), inout::OutParamClustering< T_METRIC, T_MEMBERCLUSTER_IDX >::print(), and inout::OutParamClusteringMetric< T_METRIC >::print().
l
case inout::l
Definition at line 4566 of file inparamclustering_getparameter.hpp.
Referenced by mat::jacobi_eigenvalue(), and mat::r8mat_is_eigen_right().
las_optTokensYesNo
const char* inout::las_optTokensYesNo[] = {"no", "yes", (char *) NULL }
Definition at line 501 of file inparamclustering_getparameter.hpp.
Referenced by inout::InParamAlgorithmo::isYesNo().
li_i
uintidx inout::li_i
Definition at line 503 of file inparamclustering_getparameter.hpp.
Referenced by mat::MatrixWithRowNull< T_GENE >::addRow(), barprogress_update(), eac::cbga_fkcentroid(), eac::cga_vklabel(), eac::clustering_genetic(), mat::MatrixRow< T_METRIC >::cpyLoweToUpper(), mat::MatrixRow< T_METRIC >::cpyUpper(), inout::InParamAlgorithmo::errorArgument(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gagr_fkcentroid(), eac::gaprototypes_fkmedoid(), eac::gas_fkcentroid(), eac::gca_fkmedoid(), eac::gcuk_vkcentroid(), interfacesse::gemm(), partition::PartitionFuzzy< T_U, T_CLUSTERIDX >::getClusterIdx(), mat::getIdentity(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getIdxMaximum(), mat::MatrixRow< T_METRIC >::getMaximumElemIJ(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::getMisclassified(), mat::getRowsNumBitOn(), sm::getSensitivity(), sm::getStrSenSpe(), mat::getTranspose(), eac::gga_vklabel(), eac::gka_fklabel(), eac::hka_fkmedoid(), eac::igka_fklabel(), mat::MatrixWithRowNull< T_GENE >::keepRows(), eac::kga_fkcentroid(), main(), prob::makeDistRouletteWheel(), mat::MatrixTriang< T_DIST >::MatrixTriang(), mat::MatrixWithRowNull< T_GENE >::MatrixWithRowNull(), mat::mulRowsIColumns0N(), mat::MatrixTriang< T_DIST >::operator=(), mat::MatrixWithRowNull< T_GENE >::operator=(), sm::partialRandIndex(), graph::AlgorithmsDFS::print(), graph::AlgorithmsDFSAdjMatrix< T_BITSIZE >::print(), inout::LineSplit::split(), sm::PartitionMatrix< T_INSTANCES_CLUSTER_K >::sumPartitionTable(), eac::tgca_vkcentroid(), gaselect::tournament(), mat::MatrixTriang< T_DIST >::~MatrixTriang(), and mat::MatrixWithRowNull< T_GENE >::~MatrixWithRowNull().
luintidx_read
liss_stringstream inout::luintidx_read
Definition at line 4544 of file inparamclustering_getparameter.hpp.
q
case inout::q
Definition at line 4674 of file inparamclustering_getparameter.hpp.
Referenced by mat::jacobi_eigenvalue().
r
case inout::r
Definition at line 4598 of file inparamclustering_getparameter.hpp.
R
case inout::R
Definition at line 4601 of file inparamclustering_getparameter.hpp.
v
case inout::v
Definition at line 4683 of file inparamclustering_getparameter.hpp.
Referenced by mat::jacobi_eigenvalue(), and mat::r8mat_diag_get_vector().