Library Evolutionary Algorithms for Clustering (LEAC): garealop Namespace Reference
garealop Namespace Reference
Genetic real operators.
Functions
template<typename T_GENE , typename T_METRIC >
void heuristicCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentY)
Heuristic crossover [11].
template<typename T_GENE , typename T_METRIC >
void averageCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentY, const T_METRIC airt_lambda)
Heuristic crossover [11].
template<typename T_GENE , typename T_METRIC >
void BLXalphaCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > &aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > &aichrom_parentY, const T_METRIC airt_alpha)
BLXalphaCrossover.
template<typename T_GENE , typename T_REAL >
void randomMutation (gaencode::ChromFixedLength< T_GENE, T_REAL > &aiochromfixlen_toMutate)
randomMutation [32]
template<typename T_GENE , typename T_REAL >
void muhlenbeinMutation (gaencode::ChromosomeString< T_GENE, T_REAL > &aiochromstr_toMutate, T_GENE aifeact_ai, T_GENE aifeact_bi)
Muhlenbein mutation.
Detailed Description
Genetic real operators.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
averageCrossover()
template<typename T_GENE , typename T_METRIC > void void garealop::averageCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentY, const T_METRIC airt_lambda)
Heuristic crossover [11].
if is better than in term of the fitness with mutation probability.
Parameters
aochrom_childX a gaencode::ChromosomeString
aochrom_childY a gaencode::ChromosomeString
aichrom_parentX a gaencode::ChromosomeString
aichrom_parentY a gaencode::ChromosomeString
airt_lambda a real number
Definition at line 169 of file ga_real_operator.hpp.
References interfacesse::aysxpy(), interfacesse::copy(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gaencode::ChromosomeBase< T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
BLXalphaCrossover()
template<typename T_GENE , typename T_METRIC > void void garealop::BLXalphaCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentY, const T_METRIC airt_alpha)
BLXalphaCrossover.
Parameters
aochrom_childX a gaencode::ChromosomeString<T_GENE,T_METRIC>
aochrom_childY a gaencode::ChromosomeString<T_GENE,T_METRIC>
aichrom_parentX a gaencode::ChromosomeString<T_GENE,T_METRIC>
aichrom_parentY a gaencode::ChromosomeString<T_GENE,T_METRIC>
airt_alpha a real number
Definition at line 265 of file ga_real_operator.hpp.
References gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, gaencode::ChromosomeBase< T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
heuristicCrossover()
template<typename T_GENE , typename T_METRIC > void void garealop::heuristicCrossover (gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childX, gaencode::ChromosomeString< T_GENE, T_METRIC > & aochrom_childY, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentX, const gaencode::ChromosomeString< T_GENE, T_METRIC > & aichrom_parentY)
Heuristic crossover [11].
if is better than in term of the fitness and where , is a uniform distribution on interval with mutation probability
Parameters
aochrom_childX a gaencode::ChromosomeString
aochrom_childY a gaencode::ChromosomeString
aichrom_parentX a gaencode::ChromosomeString
aichrom_parentY a gaencode::ChromosomeString
Definition at line 50 of file ga_real_operator.hpp.
References interfacesse::aysxpy(), interfacesse::copy(), gaencode::ChromosomeBase< T_METRIC >::getFitness(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), gmt19937_eng, gaencode::ChromosomeBase< T_METRIC >::print(), gaencode::ChromosomeBase< T_METRIC >::setFitness(), and gaencode::ChromosomeBase< T_METRIC >::setObjetiveFunc().
Referenced by eac::gagr_fkcentroid().
muhlenbeinMutation()
template<typename T_GENE , typename T_REAL > void garealop::muhlenbeinMutation (gaencode::ChromosomeString< T_GENE, T_REAL > & aiochromstr_toMutate, T_GENE aifeact_ai, T_GENE aifeact_bi)
Muhlenbein mutation.
Parameters
aiochromstr_toMutate a gaencode::ChromosomeString
aifeact_ai lower range limit
aifeact_bi upper range limit
Definition at line 436 of file ga_real_operator.hpp.
References gaencode::ChromosomeString< T_GENE, T_METRIC >::getString(), gaencode::ChromosomeString< T_GENE, T_METRIC >::getStringSize(), and gmt19937_eng.
randomMutation()
template<typename T_GENE , typename T_REAL > void garealop::randomMutation (gaencode::ChromFixedLength< T_GENE, T_REAL > & aiochromfixlen_toMutate)
randomMutation [32]
Only one gene will be mutated. A number in the range [0,1] is generated with uniform distribution. If the value at that position is , then after mutation it becomes
Parameters
aiochromfixlen_toMutate a gaencode::ChromFixedLength
The ‘+’ or ‘−’ sign occurs with equal probability.
Parameters
aiochromfixlen_toMutate a gaencode::ChromFixedLength chromosome to mutate
Definition at line 355 of file ga_real_operator.hpp.
References DATATYPE_REAL, gaencode::ChromFixedLength< T_GENE, T_METRIC >::getGene(), gmt19937_eng, gaencode::ChromFixedLength< T_GENE, T_METRIC >::print(), and gaencode::ChromFixedLength< T_GENE, T_METRIC >::setGene().
Referenced by eac::gas_fkcentroid().