Library Evolutionary Algorithms for Clustering (LEAC): clusteringop Namespace Reference
clusteringop Namespace Reference
Clustering operators.
Functions
template<typename T_CENTROIDS , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX >
void meanCentroids (T_CLUSTERIDX &aocidx_numClusterNull, mat::MatrixBase< T_CENTROIDS > &aomatrixt_meanCentroids, mat::MatrixBase< T_FEATURE_SUM > &aimatrixtrowt_sumInstancesClusterK, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstClusterK)
template<typename T_FEATURE , typename INPUT_ITERATOR_IDX , typename INPUT_ITERATOR >
void initialize (mat::MatrixBase< T_FEATURE > &aomatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, INPUT_ITERATOR_IDX aiiterator_idxInstanceRandFirst)
template<typename T_FEATURE , typename INPUT_ITERATOR >
void randomInitialize (mat::MatrixBase< T_FEATURE > &aomatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
void randomInitialize (mat::MatrixBase< T_FEATURE > &aomatrixt_centroids, T_CLUSTERIDX *aoarraycidx_memberShip, std::vector< T_INSTANCES_CLUSTER_K > &aovectorit_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Initialize the centroids and labels by selecting random instances.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR >
uintidx reassignCluster (T_CLUSTERIDX *aioarraycidx_memberShip, const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Change each instance to the nearest cluster.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR >
void setUpCuster (T_CLUSTERIDX *aioarraycidx_memberShip, const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Set up cluster index.
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR >
T_CLUSTERIDX getCentroids (mat::MatrixRow< T_FEATURE > &aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstancesInClusterK, partition::Partition< T_CLUSTERIDX > &aipartition_clusters, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
template<typename T_BITSIZE , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL >
std::tuple< mat::MatrixRow< T_FEATURE >, partition::PartitionDisjSets< T_CLUSTERIDX >, std::vector< T_INSTANCES_CLUSTER_K > > getClusters (const mat::BitArray< T_BITSIZE > &aibirarray_clusterSeedIdx, const mat::MatrixRow< T_FEATURE > &aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > &aivectort_numInstBi, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_dist, const T_CLUSTERIDX aiit_datatypeClusterIdx)
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_DIST >
void updateCentroids (T_CLUSTERIDX &aocidx_numClusterNull, mat::MatrixRow< T_FEATURE > &aiomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR >
void updateClusterCj (mat::MatrixRow< T_FEATURE > &aiomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aiomatrixt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectorit_numInstClusterK, T_CLUSTERIDX *aioarraycidx_memberShip, T_CLUSTERIDX aicidx_Cj, std::vector< T_CLUSTERIDX > &aivectorcidx_clustersNew, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_DIST , typename INPUT_ITERATOR >
T_CLUSTERIDX kmeansoperator (T_CLUSTERIDX *aioarraycidx_memberShip, mat::MatrixRow< T_FEATURE > &aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
K-Means Operator [26].
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR >
std::pair< bool, T_DIST > reassignCluster (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aoipartlinkstats_partition, const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Change each instance to the nearest cluster.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR >
void reassignCluster (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aoipartlinkstats_partition, const mat::MatrixBase< T_FEATURE > &aimatrixt_centroids, T_CLUSTERIDX *aiarraycidx_newIndex, uintidx aiui_countNewIndex, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Reassign cluster.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR >
void joinPartition (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aoipartlinkstats_partition, const T_CLUSTERIDX aicidx_partitionFrom, const T_CLUSTERIDX aicidx_partitionTo, const INPUT_ITERATOR aiiterator_instfirst)
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR >
void fillEmptyPartitions (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aiopartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > &aiomatrixresizerow_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Fill empty partitions.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR >
void removeEmptyPartitions (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aoipartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > &aomatrixresizerow_centroids, const INPUT_ITERATOR aiiterator_instfirst, const T_CLUSTERIDX aicidx_numclusterKTopMin)
Remove empty partitions.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR >
void pnnFast (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > &aoipartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > &aiomatrixresizerow_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numclusterKToReduce, const dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
template<typename T_BITSIZE , typename T_CLUSTERIDX >
void randomInitialize (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aiocrispmatrix_partition)
template<typename T_BITSIZE , typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename FUNCTION_INSTCLASS >
void initializeOptimal (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aiocrispmatrix_partition, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, FUNCTION_INSTCLASS function_instClass)
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_BITSIZE , typename T_CLUSTERIDX >
T_CLUSTERIDX getCentroids (mat::MatrixRow< T_FEATURE > &aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > &aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > &aovectort_numInstancesInClusterK, mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aicrispmatrix_partition, mat::MatrixRow< T_FEATURE > &aimatrixt_instances)
Calculate centroids.
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_BITSIZE , typename T_DIST >
void getPartition (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > &aobcrispmatrix_partition, mat::MatrixRow< T_FEATURE > &aimatrixt_instances, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, dist::Dist< T_DIST, T_FEATURE > &aifunc2p_dist)
Get partition.
template<typename T_REAL >
void randomInitialize (mat::MatrixRow< T_REAL > &aomatrixt_fuzzyPartition)
Initializes randomly a fuzzy partition.
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_REAL >
mat::MatrixRow< T_REAL > fuzzyPartition (const mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_REAL airt_m, const dist::Dist< T_REAL, T_FEATURE > &aifunc2p_distSquare)
Get a fuzzy c-partitions based on [8] [6].
template<typename T_REAL , typename T_FEATURE >
bool getCentroids (mat::MatrixRow< T_FEATURE > &aomatrixt_centroids, mat::MatrixRow< T_REAL > &aimatrixt_fuzzyPartition, mat::MatrixRow< T_FEATURE > &aimatrixt_instances, T_REAL ait_m, mat::MatrixRow< T_REAL > &aimatrixrowt_work)
template<typename T_REAL , typename T_FEATURE >
void reassignCluster (mat::MatrixRow< T_REAL > &aomatrixt_fuzzyPartition, mat::MatrixRow< T_FEATURE > &aimatrixt_instances, mat::MatrixRow< T_FEATURE > &aimatrixt_centroids, T_REAL ait_m, dist::Dist< T_REAL, T_FEATURE > &aifunc2p_squaredDist)
template<typename T_REAL >
std::vector< std::pair< uintidx, T_REAL > > sortLambda (const uintidx *aiarrayiu_pi, const T_REAL *aiarrayrt_lambda, const uintidx aiui_numObj)
template<typename T_REAL >
ds::DisjSets pointerToDisjSets (const std::vector< std::pair< uintidx, T_REAL > > &aivector_pairIdxLambda, const uintidx *aiarrayiu_pi, const uintidx aiui_numClusterK)
template<typename T_REAL , typename INPUT_ITERATOR , typename FUNCTION_DISTANCE >
void slink (uintidx *aoarrayiu_pi, T_REAL *aoarrayrt_lambda, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, FUNCTION_DISTANCE function_distance)
template<typename T_CLUSTERIDX >
std::vector< T_CLUSTERIDX > bkinCiToMemberShip (const partition::PartitionDisjSets< T_CLUSTERIDX > &aimembclassdisjsets_Bi, const partition::PartitionDisjSets< T_CLUSTERIDX > &aimembclassdisjsets_BkinCi)
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX >
std::tuple< T_DIST, ds::PartitionLinked< T_CLUSTERIDX > > nearestRepresentative (T_INSTANCEIDX *aioarrayui_idxMedoids, T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > &aimattriag_dissimilarity)
nearestRepresentative
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX >
std::pair< T_DIST, T_INSTANCEIDX > nearestRepresentative (T_CLUSTERIDX *aoarraycidx_memberShip, const T_INSTANCEIDX *aioarrayui_idxMedoids, const T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > &aimattriag_dissimilarity)
nearestRepresentative [25]
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX >
T_DIST computeTotalCostSwap (const T_INSTANCEIDX aiuiidx_medoidRand, const T_CLUSTERIDX *aiarraycidx_memberShip, T_INSTANCEIDX *aoarrayuiidx_medoids, const T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > &aimattriag_dissimilarity)
computeTotalCostSwap
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX >
T_DIST computeCostInstanceClusterJ (T_INSTANCEIDX aiuintidx_medoids, T_CLUSTERIDX aicidx_Cj, ds::PartitionLinked< T_CLUSTERIDX > &aipartlink_partition, mat::MatrixTriang< T_DIST > &aimattriag_dissimilarity)
computeCostInstanceClusterJ
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX >
T_DIST updateMedoids (T_INSTANCEIDX *aioarrayui_idxMedoids, const T_CLUSTERIDX aicidx_numKMedoids, const T_INSTANCEIDX aiu_nearestNeighborsP, mat::MatrixTriang< T_DIST > &aimattriag_dissimilarity)
Update medoids, local search heuristic [37].
Detailed Description
Clustering operators.
Version
1.0
Date
2015-2017
Copyright
GPLv3 license
Function Documentation
bkinCiToMemberShip()
template<typename T_CLUSTERIDX > std::vector<T_CLUSTERIDX> clusteringop::bkinCiToMemberShip (const partition::PartitionDisjSets< T_CLUSTERIDX > & aimembclassdisjsets_Bi, const partition::PartitionDisjSets< T_CLUSTERIDX > & aimembclassdisjsets_BkinCi)
Definition at line 36 of file clustering_operator_label.hpp.
Referenced by eac::clustering_genetic(), and main().
computeCostInstanceClusterJ()
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX > T_DIST clusteringop::computeCostInstanceClusterJ (T_INSTANCEIDX aiuintidx_medoids, T_CLUSTERIDX aicidx_Cj, ds::PartitionLinked< T_CLUSTERIDX > & aipartlink_partition, mat::MatrixTriang< T_DIST > & aimattriag_dissimilarity)
computeCostInstanceClusterJ
calculates the cost or sum of Euclidean distances from the most representative to all the objects belonging to the cluster j
Parameters
aiuintidx_medoids an index of a medoid to investigate the cost
aicidx_Cj an integer with the cluster index j
aipartlink_partition a partition::Partition of objects in clusters
aimattriag_dissimilarity a distance matrix
Definition at line 319 of file clustering_operator_medoids.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), and ds::IteratorPartitionLinked< T_CLUSTERIDX >::next().
Referenced by updateMedoids().
computeTotalCostSwap()
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX > T_DIST clusteringop::computeTotalCostSwap (const T_INSTANCEIDX aiuiidx_medoidRand, const T_CLUSTERIDX * aiarraycidx_memberShip, T_INSTANCEIDX * aoarrayuiidx_medoids, const T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > & aimattriag_dissimilarity)
computeTotalCostSwap
calculates the cost of changing a randomly selected medoid to a defined one
Parameters
aiuiidx_medoidRand an index of a randomly selected medoid to investigate if the cost improves
aiarraycidx_memberShip an aioarraycidx_memberShip an array of indexes belonging to previously assigned or UNKNOWN_CLUSTER_IDX
aoarrayuiidx_medoids an array of output with the indexes of the representative objects
aicidx_numKMedoids cluster number
aimattriag_dissimilarity a distance matrix
Definition at line 221 of file clustering_operator_medoids.hpp.
References mat::MatrixTriang< T_FEATURE >::getNumRows(), and nearest::medoidsNN().
fillEmptyPartitions()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR > void clusteringop::fillEmptyPartitions (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aiopartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > & aiomatrixresizerow_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Fill empty partitions.
For each empty partition adds a new centroid
Parameters
aiopartlinkstats_partition a ds::PartitionLinkedStats to fill empty clusters
aiomatrixresizerow_centroids a mat::MatrixResizableRow with the centroids of each cluster
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1760 of file clustering_operator_centroids.hpp.
References interfacesse::copy(), data::Instance< T_FEATURE >::getFeatures(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getFrequency(), data::Instance< T_FEATURE >::getNumDimensions(), and stats::meanVector().
Referenced by eac::iterateGLAAux().
fuzzyPartition()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_REAL > mat::MatrixRow< T_REAL > clusteringop::fuzzyPartition (const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, T_REAL airt_m, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist)
Get a fuzzy c-partitions based on [8] [6].
Parameters
aimatrixt_centroids a mat::MatrixRow with centroids of the clusters
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast an InputIterator to the final positions of the sequence of instances
airt_m a real number with the weighting exponent
aifunc2p_dist an object of type dist::Dist square distance of preference
Definition at line 109 of file clustering_operator_fuzzy.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
Referenced by main().
getCentroids() [1/3]
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_BITSIZE , typename T_CLUSTERIDX > T_CLUSTERIDX clusteringop::getCentroids (mat::MatrixRow< T_FEATURE > & aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstancesInClusterK, mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aicrispmatrix_partition, mat::MatrixRow< T_FEATURE > & aimatrixt_instances)
Calculate centroids.
Calculate centroids from the Crisp Matrix partition. Returns the sum of instances and number of instances per cluster. Also the number and null clusters
Parameters
aomatrixt_centroids an output mat::MatrixRow with centroids
aomatrixt_sumInstancesCluster a mat::MatrixRow with the sum of instances per cluster
aovectort_numInstancesInClusterK a std::vector with the number of instances per cluster
aicrispmatrix_partition an input mat::CrispMatrix partition of instances in clusters
aimatrixt_instances an input mat::MatrixRow with the instances
Definition at line 202 of file clustering_operator_crispmatrix.hpp.
References mat::bitgemm(), interfacesse::copya(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::getRowsNumBitOn(), mat::MatrixRow< T_FEATURE >::initialize(), meanCentroids(), and mat::MatrixRow< T_FEATURE >::print().
getCentroids() [2/3]
template<typename T_REAL , typename T_FEATURE > bool clusteringop::getCentroids (mat::MatrixRow< T_FEATURE > & aomatrixt_centroids, mat::MatrixRow< T_REAL > & aimatrixt_fuzzyPartition, mat::MatrixRow< T_FEATURE > & aimatrixt_instances, T_REAL ait_m, mat::MatrixRow< T_REAL > & aimatrixrowt_work)
Definition at line 226 of file clustering_operator_fuzzy.hpp.
References mat::CblasNoTrans, interfacesse::gemm(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumElems(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), mat::MatrixRow< T_FEATURE >::print(), interfacesse::scal(), interfacesse::sum(), and mat::MatrixRow< T_FEATURE >::toArray().
getCentroids() [3/3]
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > T_CLUSTERIDX clusteringop::getCentroids (mat::MatrixRow< T_FEATURE > & aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstancesInClusterK, partition::Partition< T_CLUSTERIDX > & aipartition_clusters, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Definition at line 608 of file clustering_operator_centroids.hpp.
References interfacesse::axpy(), partition::Partition< T_CLUSTERIDX >::begin(), inout::containerprint(), interfacesse::copya(), partition::Partition< T_CLUSTERIDX >::getNumCluster(), mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), mat::MatrixRow< T_FEATURE >::initialize(), stats::meanVector(), partition::Partition< T_CLUSTERIDX >::next(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by eac::clustering_vksubclusterbinary(), gaclusteringop::crossoverCGA(), eac::gaclustering_fkcrispmatrix(), eac::gaclustering_fklabel(), eac::gaclustering_vktreebinary(), eac::gga_vklabel(), eac::gka_fklabel(), eac::igka_fklabel(), gaencode::ChromosomeIGKA< T_CLUSTERIDX, T_METRIC, T_FEATURE, T_FEATURE_SUM, T_INSTANCES_CLUSTER_K >::initialize(), kmeansoperator(), main(), gaclusteringop::MO1(), gaintegerop::mutationgka(), and eac::tgca_vkcentroid().
getClusters()
template<typename T_BITSIZE , typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_REAL > std::tuple<mat::MatrixRow<T_FEATURE>, partition::PartitionDisjSets<T_CLUSTERIDX>, std::vector<T_INSTANCES_CLUSTER_K> > clusteringop::getClusters (const mat::BitArray< T_BITSIZE > & aibirarray_clusterSeedIdx, const mat::MatrixRow< T_FEATURE > & aimatrixrowt_Vi, const std::vector< T_INSTANCES_CLUSTER_K > & aivectort_numInstBi, const dist::Dist< T_REAL, T_FEATURE > & aifunc2p_dist, const T_CLUSTERIDX aiit_datatypeClusterIdx)
Definition at line 750 of file clustering_operator_centroids.hpp.
References interfacesse::axpy(), ds::BitContainer< T_BITSIZE >::getBit(), ds::BitContainer< T_BITSIZE >::getNumBitOn(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), nearest::NN(), mat::BitArray< T_BITSIZE >::print(), mat::MatrixRow< T_FEATURE >::print(), interfacesse::scal(), interfacesse::scalInv(), and mat::BitArray< T_BITSIZE >::size().
Referenced by eac::clustering_genetic(), eac::clustering_vksubclusterbinary(), and main().
getPartition()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_BITSIZE , typename T_DIST > void clusteringop::getPartition (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aobcrispmatrix_partition, mat::MatrixRow< T_FEATURE > & aimatrixt_instances, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Get partition.
Calculate a partition crisp matrix partition with the nearest neighbor rule.
Parameters
aobcrispmatrix_partition an output mat::CrispMatrix partition of instances in clusters.
aimatrixt_instances an input mat::MatrixRow with the instances
aimatrixt_centroids an input mat::MatrixRow with centroids
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 292 of file clustering_operator_crispmatrix.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixRow< T_FEATURE >::getRow(), nearest::NN(), mat::BitMatrix< T_BITSIZE >::print(), and mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX >::setMember().
Referenced by eac::gaclustering_fkcrispmatrix(), and eac::gaprototypes_fkmedoid().
initialize()
template<typename T_FEATURE , typename INPUT_ITERATOR_IDX , typename INPUT_ITERATOR > void clusteringop::initialize (mat::MatrixBase< T_FEATURE > & aomatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, INPUT_ITERATOR_IDX aiiterator_idxInstanceRandFirst)
Definition at line 136 of file clustering_operator_centroids.hpp.
References interfacesse::copy(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), and mat::MatrixBase< T_FEATURE >::print().
Referenced by inout::dataSetRead(), inout::dataSetReadWithFreq(), eac::gaprototypes_fkmedoid(), and main().
initializeOptimal()
template<typename T_BITSIZE , typename T_CLUSTERIDX , typename INPUT_ITERATOR , typename FUNCTION_INSTCLASS > void clusteringop::initializeOptimal (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aiocrispmatrix_partition, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, FUNCTION_INSTCLASS function_instClass)
Definition at line 127 of file clustering_operator_crispmatrix.hpp.
References mat::BitMatrix< T_BITSIZE >::initialize(), mat::BitMatrix< T_BITSIZE >::print(), and mat::BitMatrix< T_BITSIZE >::setBit().
joinPartition()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR > void clusteringop::joinPartition (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aoipartlinkstats_partition, const T_CLUSTERIDX aicidx_partitionFrom, const T_CLUSTERIDX aicidx_partitionTo, const INPUT_ITERATOR aiiterator_instfirst)
Definition at line 1649 of file clustering_operator_centroids.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), data::Instance< T_FEATURE >::getFeatures(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::getFrequency(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::next(), data::InstanceFreq< T_FEATURE, T_INSTANCE_FREQUENCY >::print(), and UINTIDX_NIL.
Referenced by pnnFast(), and removeEmptyPartitions().
kmeansoperator()
template<typename T_CLUSTERIDX , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_DIST , typename INPUT_ITERATOR > T_CLUSTERIDX clusteringop::kmeansoperator (T_CLUSTERIDX * aioarraycidx_memberShip, mat::MatrixRow< T_FEATURE > & aomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
K-Means Operator [26].
For the given partition in an array of labels, it performs an update using the k-means algorithm. Returns the membership tags, centroids, sum of instances and number of instances in each cluster.
Parameters
aioarraycidx_memberShip an array with the labels belong to the cluster
aomatrixt_centroids a mat::MatrixRow with the centroids of each cluster
aomatrixt_sumInstancesCluster a mat::MatrixRow<T_FEATURE_SUM>
aovectort_numInstancesInClusterK a std::vector<T_INSTANCES_CLUSTER_K>
aiiterator_instfirst a InputIterator to the initial positions of the sequence of instances
aiiterator_instlast a InputIterator to the final positions of the sequence of instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1283 of file clustering_operator_centroids.hpp.
References inout::containerprint(), getCentroids(), mat::MatrixBase< T_FEATURE >::getNumRows(), and reassignCluster().
Referenced by eac::igka_fklabel().
meanCentroids()
template<typename T_CENTROIDS , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX > void clusteringop::meanCentroids (T_CLUSTERIDX & aocidx_numClusterNull, mat::MatrixBase< T_CENTROIDS > & aomatrixt_meanCentroids, mat::MatrixBase< T_FEATURE_SUM > & aimatrixtrowt_sumInstancesClusterK, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstClusterK)
Definition at line 66 of file clustering_operator_centroids.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), stats::meanVector(), and mat::MatrixBase< T_FEATURE >::print().
Referenced by getCentroids(), eac::igka_fklabel(), eac::iterateGLAAux(), gaencode::ChromosomeCBGA< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM, T_REAL >::optimalCodebook(), updateCentroids(), and updateClusterCj().
nearestRepresentative() [1/2]
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX > std::tuple< T_DIST, ds::PartitionLinked< T_CLUSTERIDX > > clusteringop::nearestRepresentative (T_INSTANCEIDX * aioarrayui_idxMedoids, T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > & aimattriag_dissimilarity)
nearestRepresentative
Assign each instance to a closer group and calculate the sum of the distances of each Medoid mj with its instances
Parameters
aioarrayui_idxMedoids an array with the indexes of the representative objects initially
aicidx_numKMedoids cluster number
aimattriag_dissimilarity a distance matrix
Definition at line 47 of file clustering_operator_medoids.hpp.
References mat::MatrixTriang< T_FEATURE >::getNumRows(), and nearest::medoidsNN().
Referenced by updateMedoids().
nearestRepresentative() [2/2]
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX > std::pair< T_DIST, T_INSTANCEIDX > clusteringop::nearestRepresentative (T_CLUSTERIDX * aoarraycidx_memberShip, const T_INSTANCEIDX * aioarrayui_idxMedoids, const T_CLUSTERIDX aicidx_numKMedoids, const mat::MatrixTriang< T_DIST > & aimattriag_dissimilarity)
nearestRepresentative [25]
Assign each instance to a closer group and calculate the sum of the distances of each Medoid mj with its instances
Parameters
aoarraycidx_memberShip an array of out with the labels belong to the cluster
aioarrayui_idxMedoids an array of input with the indexes of the representative objects
aicidx_numKMedoids cluster number
aimattriag_dissimilarity a distance matrix
Definition at line 131 of file clustering_operator_medoids.hpp.
References inout::containerprint(), mat::MatrixTriang< T_FEATURE >::getNumRows(), and nearest::medoidsNN().
pnnFast()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR > void clusteringop::pnnFast (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aoipartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > & aiomatrixresizerow_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const T_CLUSTERIDX aicidx_numclusterKToReduce, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 2044 of file clustering_operator_centroids.hpp.
References nearest::deleteNearestCentroid(), nearest::findAllPairCentroidsClosest(), nearest::findNearestCentroids(), joinPartition(), nearest::markRecalculationNearest(), nearest::recalculateDistNearestCentroids(), and removeEmptyPartitions().
Referenced by gaclusteringop::crossPNNnew().
pointerToDisjSets()
template<typename T_REAL > ds::DisjSets clusteringop::pointerToDisjSets (const std::vector< std::pair< uintidx, T_REAL > > & aivector_pairIdxLambda, const uintidx * aiarrayiu_pi, const uintidx aiui_numClusterK)
Definition at line 99 of file clustering_operator_hierarchical.hpp.
References ds::DisjSets::getNumSet(), ds::DisjSets::merge(), ds::DisjSets::print(), and ds::DisjSets::size().
Referenced by eac::tgca_vkcentroid().
randomInitialize() [1/4]
template<typename T_REAL > void clusteringop::randomInitialize (mat::MatrixRow< T_REAL > & aomatrixt_fuzzyPartition)
Initializes randomly a fuzzy partition.
Parameters
aomatrixt_fuzzyPartition a random fuzzy partition
Definition at line 42 of file clustering_operator_fuzzy.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), gmt19937_eng, and mat::MatrixRow< T_FEATURE >::print().
randomInitialize() [2/4]
template<typename T_BITSIZE , typename T_CLUSTERIDX > void clusteringop::randomInitialize (mat::CrispMatrix< T_BITSIZE, T_CLUSTERIDX > & aiocrispmatrix_partition)
Definition at line 49 of file clustering_operator_crispmatrix.hpp.
References mat::BitMatrix< T_BITSIZE >::getNumColumns(), mat::BitMatrix< T_BITSIZE >::getNumRows(), gmt19937_eng, mat::BitMatrix< T_BITSIZE >::initialize(), mat::BitMatrix< T_BITSIZE >::print(), and mat::BitMatrix< T_BITSIZE >::setBit().
randomInitialize() [3/4]
template<typename T_FEATURE , typename INPUT_ITERATOR > void clusteringop::randomInitialize (mat::MatrixBase< T_FEATURE > & aomatrixt_centroids, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Definition at line 205 of file clustering_operator_centroids.hpp.
References interfacesse::copy(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), prob::getWithoutRepeatsSet(), gmt19937_eng, and mat::MatrixBase< T_FEATURE >::print().
Referenced by eac::cbga_fkcentroid(), eac::feca_vklabel(), eac::gaclustering_fkcrispmatrix(), eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gcuk_vkcentroid(), and eac::kga_fkcentroid().
randomInitialize() [4/4]
template<typename T_FEATURE , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename INPUT_ITERATOR > void clusteringop::randomInitialize (mat::MatrixBase< T_FEATURE > & aomatrixt_centroids, T_CLUSTERIDX * aoarraycidx_memberShip, std::vector< T_INSTANCES_CLUSTER_K > & aovectorit_numInstClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast)
Initialize the centroids and labels by selecting random instances.
Parameters
aomatrixt_centroids a mat::MatrixBase with the centroids of each cluster
aoarraycidx_memberShip a T_CLUSTERIDX
aovectorit_numInstClusterK a std::vector
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
Definition at line 298 of file clustering_operator_centroids.hpp.
References inout::containerprint(), interfacesse::copy(), interfacesse::copya(), data::Instance< T_FEATURE >::getFeatures(), data::Instance< T_FEATURE >::getNumDimensions(), mat::MatrixBase< T_FEATURE >::getNumRows(), mat::MatrixBase< T_FEATURE >::getRow(), prob::getWithoutRepeatsSet(), gmt19937_eng, NEARESTCENTROID_UNKNOWN, and mat::MatrixBase< T_FEATURE >::print().
reassignCluster() [1/4]
template<typename T_REAL , typename T_FEATURE > void clusteringop::reassignCluster (mat::MatrixRow< T_REAL > & aomatrixt_fuzzyPartition, mat::MatrixRow< T_FEATURE > & aimatrixt_instances, mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, T_REAL ait_m, dist::Dist< T_REAL, T_FEATURE > & aifunc2p_squaredDist)
Definition at line 409 of file clustering_operator_fuzzy.hpp.
References mat::MatrixBase< T_FEATURE >::getNumColumns(), mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixRow< T_FEATURE >::getRow().
reassignCluster() [2/4]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR > uintidx clusteringop::reassignCluster (T_CLUSTERIDX * aioarraycidx_memberShip, const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Change each instance to the nearest cluster.
Each data instance of the container is assigned to the cluster with the nearest neighbor rule
Parameters
aioarraycidx_memberShip an array of indexes belonging to previously assigned or UNKNOWN_CLUSTER_IDX. Also returns how many cluster changed
aimatrixt_centroids a mat::MatrixRow with the centroids of each cluster
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 421 of file clustering_operator_centroids.hpp.
References inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), and nearest::NN().
Referenced by eac::cbga_fkcentroid(), eac::changeOptimalityAux(), eac::gagr_fkcentroid(), eac::gga_vklabel(), eac::iterateGLAAux(), kmeansoperator(), and eac::tgca_vkcentroid().
reassignCluster() [3/4]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR > std::pair< bool, T_DIST > clusteringop::reassignCluster (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aoipartlinkstats_partition, const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Change each instance to the nearest cluster.
Parameters
aoipartlinkstats_partition a ds::PartitionLinkedStats for specifying cluster membership
aimatrixt_centroids a mat::MatrixBase with the centroids of each cluster
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1378 of file clustering_operator_centroids.hpp.
References nearest::NN().
reassignCluster() [4/4]
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename T_DIST , typename INPUT_ITERATOR > void clusteringop::reassignCluster (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aoipartlinkstats_partition, const mat::MatrixBase< T_FEATURE > & aimatrixt_centroids, T_CLUSTERIDX * aiarraycidx_newIndex, uintidx aiui_countNewIndex, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Reassign cluster.
Reassign cluster based on a local search. Returns if the partition is valid and the distance distortion metric
Parameters
aoipartlinkstats_partition a ds::PartitionLinkedStats for specifying cluster membership
aimatrixt_centroids a mat::MatrixBase with the centroids of each cluster
aiarraycidx_newIndex an array with the new indexes
aiui_countNewIndex number of new indices
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 1506 of file clustering_operator_centroids.hpp.
References mat::MatrixBase< T_FEATURE >::getNumRows(), and mat::MatrixBase< T_FEATURE >::getRow().
removeEmptyPartitions()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_INSTANCE_FREQUENCY , typename T_INSTANCES_CLUSTER_K , typename T_FEATURE_SUM , typename INPUT_ITERATOR > void clusteringop::removeEmptyPartitions (ds::PartitionLinkedStats< T_FEATURE, T_CLUSTERIDX, T_INSTANCE_FREQUENCY, T_INSTANCES_CLUSTER_K, T_FEATURE_SUM > & aoipartlinkstats_partition, mat::MatrixResizableRow< T_FEATURE, T_INSTANCES_CLUSTER_K > & aomatrixresizerow_centroids, const INPUT_ITERATOR aiiterator_instfirst, const T_CLUSTERIDX aicidx_numclusterKTopMin)
Remove empty partitions.
Parameters
aoipartlinkstats_partition a ds::PartitionLinkedStats to join, this also specifies membership in the cluster
aomatrixresizerow_centroids a mat::MatrixResizableRow with the centroids of each cluster
aiiterator_instfirst a input iterator of the instances
aicidx_numclusterKTopMin a minimum number of clusters to maintain
Definition at line 1949 of file clustering_operator_centroids.hpp.
References joinPartition().
Referenced by pnnFast().
setUpCuster()
template<typename T_FEATURE , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR > void clusteringop::setUpCuster (T_CLUSTERIDX * aioarraycidx_memberShip, const mat::MatrixRow< T_FEATURE > & aimatrixt_centroids, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Set up cluster index.
Assigns the instances of the container with an unknown cluster using the nearest neighbor rule
Parameters
aioarraycidx_memberShip an array of indexes only with the seed instances as the clustering center. The other instances with UNKNOWN_CLUSTER_IDX
aimatrixt_centroids a mat::MatrixRow with the centroids of each cluster
aiiterator_instfirst a input iterator of the instances
aiiterator_instlast a const input iterator of the instances
aifunc2p_dist an object of type dist::Dist to calculate distances
Definition at line 511 of file clustering_operator_centroids.hpp.
References inout::containerprint(), data::Instance< T_FEATURE >::getFeatures(), NEARESTCENTROID_UNKNOWN, and nearest::NN().
Referenced by gaclusteringop::crossoverCGA(), and gaclusteringop::MO1().
slink()
template<typename T_REAL , typename INPUT_ITERATOR , typename FUNCTION_DISTANCE > void clusteringop::slink (uintidx * aoarrayiu_pi, T_REAL * aoarrayrt_lambda, const INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, FUNCTION_DISTANCE function_distance)
Definition at line 205 of file clustering_operator_hierarchical.hpp.
References inout::containerprint().
Referenced by eac::tgca_vkcentroid().
sortLambda()
template<typename T_REAL > std::vector<std::pair<uintidx,T_REAL> > clusteringop::sortLambda (const uintidx * aiarrayiu_pi, const T_REAL * aiarrayrt_lambda, const uintidx aiui_numObj)
Definition at line 38 of file clustering_operator_hierarchical.hpp.
Referenced by eac::tgca_vkcentroid().
updateCentroids()
template<typename INPUT_ITERATOR , typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_DIST > void clusteringop::updateCentroids (T_CLUSTERIDX & aocidx_numClusterNull, mat::MatrixRow< T_FEATURE > & aiomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aomatrixt_sumInstancesCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectort_numInstancesInClusterK, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, const dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 1040 of file clustering_operator_centroids.hpp.
References interfacesse::axpy(), mat::MatrixRow< T_FEATURE >::getRow(), meanCentroids(), and nearest::NN().
Referenced by eac::gagr_fkcentroid(), eac::gas_fkcentroid(), eac::gcuk_vkcentroid(), and eac::kga_fkcentroid().
updateClusterCj()
template<typename T_FEATURE , typename T_FEATURE_SUM , typename T_INSTANCES_CLUSTER_K , typename T_CLUSTERIDX , typename T_DIST , typename INPUT_ITERATOR > void clusteringop::updateClusterCj (mat::MatrixRow< T_FEATURE > & aiomatrixt_centroids, mat::MatrixRow< T_FEATURE_SUM > & aiomatrixt_sumInstCluster, std::vector< T_INSTANCES_CLUSTER_K > & aovectorit_numInstClusterK, T_CLUSTERIDX * aioarraycidx_memberShip, T_CLUSTERIDX aicidx_Cj, std::vector< T_CLUSTERIDX > & aivectorcidx_clustersNew, INPUT_ITERATOR aiiterator_instfirst, const INPUT_ITERATOR aiiterator_instlast, dist::Dist< T_DIST, T_FEATURE > & aifunc2p_dist)
Definition at line 1134 of file clustering_operator_centroids.hpp.
References interfacesse::axpy(), inout::containerprint(), mat::MatrixRow< T_FEATURE >::getRow(), mat::MatrixRow< T_FEATURE >::initialize(), meanCentroids(), nearest::NN(), and mat::MatrixRow< T_FEATURE >::print().
Referenced by gaclusteringop::MO2().
updateMedoids()
template<typename T_INSTANCEIDX , typename T_DIST , typename T_CLUSTERIDX > T_DIST clusteringop::updateMedoids (T_INSTANCEIDX * aiui_idxInstMedoids, const T_CLUSTERIDX aicidx_numKMedoids, const T_INSTANCEIDX aiu_nearestNeighborsP, mat::MatrixTriang< T_DIST > & aimattriag_dissimilarity)
Update medoids, local search heuristic [37].
For each cluster finds the most representative object
Assign each object in to the cluster with the closest medoid
For each cluster , repeat until the medoid does not change
Choose a subset in Cj the corresponds to and its nearest neighbors of .
Calulate the new medoid
if is different from replace with the new medoid
Repat step 1 and 2 until medoids do not change
Parameters
aioarrayui_idxMedoids an array with the indexes of the representative objects initially
aicidx_numKMedoids cluster number
aiu_nearestNeighborsP size of subset P of search neighbors
aimattriag_dissimilarity a distance matrix
Definition at line 389 of file clustering_operator_medoids.hpp.
References ds::IteratorPartitionLinked< T_CLUSTERIDX >::begin(), computeCostInstanceClusterJ(), inout::containerprint(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::end(), mat::MatrixTriang< T_FEATURE >::getNumRows(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::getValue(), nearestRepresentative(), ds::IteratorPartitionLinked< T_CLUSTERIDX >::next(), um::SSEMedoid(), and UINTIDX_NIL.
Referenced by eac::hka_fkmedoid().