Library Evolutionary Algorithms for Clustering (LEAC): dist::Induced< T_DIST, T_FEATURE > Struct Template Reference
dist::Induced< T_DIST, T_FEATURE > Struct Template Reference
Dist induced for real number [8] [6] [7].
#include <dist_euclidean.hpp>
Public Member Functions
Induced ()
Induced (const mat::MatrixRow< T_DIST > &aimatrix_weight)
virtual ~Induced ()
T_DIST operator() (const T_FEATURE *aiarrayT_p, const T_FEATURE *aiarrayT_q, const uintidx uintidx_length) const
Public Member Functions inherited from dist::Dist< T_DIST, T_FEATURE >
virtual ~Dist ()
Public Attributes
mat::MatrixRow< T_DIST > _matrix_weight
T_DIST * _arrayt_xt
T_DIST * _arrayt_x
Detailed Description
template<class T_DIST, class T_FEATURE>
struct dist::Induced< T_DIST, T_FEATURE >
Dist induced for real number [8] [6] [7].
Definition at line 79 of file dist_euclidean.hpp.
Constructor & Destructor Documentation
Induced() [1/2]
template<class T_DIST , class T_FEATURE > dist::Induced< T_DIST, T_FEATURE >::Induced () inline
Definition at line 80 of file dist_euclidean.hpp.
Induced() [2/2]
template<class T_DIST , class T_FEATURE > dist::Induced< T_DIST, T_FEATURE >::Induced (const mat::MatrixRow< T_DIST > & aimatrix_weight) inline
Definition at line 85 of file dist_euclidean.hpp.
~Induced()
template<class T_DIST , class T_FEATURE > virtual dist::Induced< T_DIST, T_FEATURE >::~Induced () inline virtual
Definition at line 92 of file dist_euclidean.hpp.
References dist::Induced< T_DIST, T_FEATURE >::_arrayt_x, and dist::Induced< T_DIST, T_FEATURE >::_arrayt_xt.
Member Function Documentation
operator()()
template<class T_DIST , class T_FEATURE > T_DIST dist::Induced< T_DIST, T_FEATURE >::operator() (const T_FEATURE * aiarrayT_p, const T_FEATURE * aiarrayT_q, const uintidx uintidx_length) const inline virtual
Implements dist::Dist< T_DIST, T_FEATURE >.
Reimplemented in dist::InducedSquareRoot< T_DIST, T_FEATURE >.
Definition at line 100 of file dist_euclidean.hpp.
References dist::Induced< T_DIST, T_FEATURE >::_arrayt_x, dist::Induced< T_DIST, T_FEATURE >::_arrayt_xt, dist::Induced< T_DIST, T_FEATURE >::_matrix_weight, interfacesse::axpy(), interfacesse::copy(), interfacesse::dot(), and interfacesse::gemv().
Member Data Documentation
_arrayt_x
template<class T_DIST , class T_FEATURE > T_DIST* dist::Induced< T_DIST, T_FEATURE >::_arrayt_x
Definition at line 138 of file dist_euclidean.hpp.
Referenced by dist::Induced< T_DIST, T_FEATURE >::operator()(), and dist::Induced< T_DIST, T_FEATURE >::~Induced().
_arrayt_xt
template<class T_DIST , class T_FEATURE > T_DIST* dist::Induced< T_DIST, T_FEATURE >::_arrayt_xt
Definition at line 137 of file dist_euclidean.hpp.
Referenced by dist::Induced< T_DIST, T_FEATURE >::operator()(), and dist::Induced< T_DIST, T_FEATURE >::~Induced().
_matrix_weight
template<class T_DIST , class T_FEATURE > mat::MatrixRow<T_DIST> dist::Induced< T_DIST, T_FEATURE >::_matrix_weight
Definition at line 136 of file dist_euclidean.hpp.
Referenced by dist::Induced< T_DIST, T_FEATURE >::operator()().
The documentation for this struct was generated from the following file:
include/dist_euclidean.hpp